### ISSUE TITLE
v3.0.0 prerelease available

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1001]
Getting close to wrapping v3.0.0. 
- [Release Notes](https://github.com/tj/commander.js/releases/tag/v3.0.0-0)
- [CHANGELOG](https://github.com/tj/commander.js/blob/release/3.0.0/CHANGELOG.md)
- [README](https://github.com/tj/commander.js/blob/release/3.0.0/Readme.md)
- [Milestone](https://github.com/tj/commander.js/milestone/3?closed=1)
- [Code](https://github.com/tj/commander.js/tree/release/3.0.0)

There have been 28 releases since 2.0.0 which was published by tj back in 2013. The last 16 of them published by @abetomo. 

I'm intending to have another read through the CHANGELOG, and add some examples for the new features and breaking changes. I think the release notes for a major version are more important than usual.

When ready, I suggest we publish a prerelease as `commander@next` from the `release/3.0.0` branch and give it a couple of weeks for feedback? I'll go through all the affected issues adding a comment when the prerelease is available.

Edit: available now, install instructions below: https://github.com/tj/commander.js/issues/1001#issuecomment-515651225

**Comment by shadowspawn** [comment]
I have expanded the changelog a little with more examples of the new features. I had wondered about covering breaking changes explicitly in a separate section, but will only add that for issues we get feedback about.

**Comment by shadowspawn** [comment]
I think we are ready for prerelease, but let me know if I missed anything. Version number is 3.0.0-0 on the `release/3.0.0` branch.

I have not published many prereleases, so a tip that you specify the tag on the publish like so (to avoid it being tagged as latest):

```
npm publish --tag next
```

I'll leave publish from `release/3.0.0` branch to you @abetomo, but happy to do it if you like.

**Comment by abetomo** [comment]
Thank you.
Published in the 'next' tag.

**Comment by shadowspawn** [comment]
Readers can try the prerelease with:
```
npm install commander@next
```
or from the github branch if you prefer:
```
npm install tj/commander.js#release/3.0.0
```

See the changelog for details:
https://github.com/tj/commander.js/blob/release/3.0.0/CHANGELOG.md

Open issues or add comment here for any problems you encounter.

**Comment by usmonster** [comment]
> I had wondered about covering breaking changes explicitly in a separate section, but will only add that for issues we get feedback about.

I think separate section for breaking changes isn't necessary, but maybe you could prefix the relevant bullet points with *[BC BREAK]*, or *BREAKING CHANGE:* or similar, if it doesn't make it harder to read?

Another small nit, which you can take or leave: can you please link the issue references to the pull requests? Though the references on [the Releases" page](https://github.com/tj/commander.js/releases) do autolink, they appear as normal text when browsing the changelog markdown file directly.

It would also be nice to eventually follow an explicit convention, such as https://keepachangelog.com and/or https://www.conventionalcommits.org (which would allow automatic, readable changelog generation based on the merge commit messages).

Thanks again for all the work you put into making this release happen!

**Comment by shadowspawn** [comment]
Thanks for the feedback. Added manual links.

**Comment by shadowspawn** [comment]
(Added a GitHub release too, to hopefully notify anyone watching repo for Releases. 📣  )

**Comment by shadowspawn** [comment]
Couple of minor followups on conventions:
- I use convention from https://keepachangelog.com  in other projects I maintain, so familiar with that
- I have been keeping an eye out for how other projects mark breaking patterns, and currently like **Breaking** prefix to change description when does not require further explanation

**Comment by shadowspawn** [comment]
I have bumped version number to 3.0.0 on branch ready for release and merge to master.
Not tagged yet, and release date still to go in changelog.

I left a 3.0.0-0 title in changelog with just the date and a placeholder note. (I think it looks ok.)

**Comment by shadowspawn** [comment]
@abetomo 
How about I tag and merge to master and develop branches tomorrow (Thursday)?
I'll leave npm publish to you?

I'll update Releases page in GitHub at same time as I merge. In the weekend after both npm and GitHub updated, I'll go through the resolved issues adding comments and closing.

**Comment by abetomo** [comment]
Leave it to me.

**Comment by shadowspawn** [comment]
Tagged and pushed on master. Adding Release Notes now.

**Comment by shadowspawn** [comment]
Release Notes are done. Branches merged. Chinese README updated too.

I'm done until after npm release, when I am looking forward to updating quite a few open issues!

**Comment by abetomo** [comment]
Was it okay to release it in v3.0.0?
May I run `npm publish`?

**Comment by shadowspawn** [comment]
Yes please. 👍 Thanks.

**Comment by abetomo** [comment]
3.0.0 released!

**Comment by shadowspawn** [comment]
Woop woop! 🚀 🎆

**Comment by shadowspawn** [comment]
On a related note, I was wondering if and how long we should officially support 2.x for security updates (if any).

My current thinking is support 2.x for at least a month until we have more feedback about how easily people can move from v2 to v3.
