### ISSUE TITLE
Support subclassing Command

### ISSUE THREAD

**Issue by ngocdaothanh** [tj/commander.js#1002]
Currently, the return type of the methods in class `Command` is `Command`:

```js
public command(name: string, desc?: string, opts?: commander.CommandOptions): Command;
```

I cannot extend `Command` to add more methods, like this:

```js
class MyCommandWithUtilities extends Command {
  public util1(): this {
     // ...
     return this;
  }
}

const cmd = new MyCommandWithUtilities();
cmd
  .command('foo')
  .util1()  // Syntax error, because `command` returns `Command`, not `MyCommandWithUtilities`
  .option(...);
```

So, please change the return type of the methods in `Command` to `this`.

```js
public command(name: string, desc?: string, opts?: commander.CommandOptions): this;
```

It seems that simply changing the definitions in index.d.ts is not enough. The main source code must also be changed.

See:
https://github.com/microsoft/TypeScript/pull/4910

**Comment by ngocdaothanh** [comment]
```
public command(name: string, desc?: string, opts?: commander.CommandOptions): this;
```

It's not that simple, because the current design is to return a new `Command` instance, unless `desc` is specified; the return type is `Command | this`.

So to support subclassing, we need to change the design of `command`.

**Comment by shadowspawn** [comment]
Yes, for action handler based subcommands (no description), `.command` returns a new object representing the new command. (That might be doable using a factory method to create the new object, but definitely more complicated than just changing the TypeScript definition for `.command`.)

**Comment by ngocdaothanh** [comment]
Workaround: use a wrapper.

Example (TypeScript):

```
export class MyCommand {
  private readonly cmd: commander.Command;

  constructor(cmd?: commander.Command) {
    this.cmd = cmd ? cmd : new commander.Command();
  }

  public command(name: string): MyCommand {
    const cmd = this.cmd.command(name);
    return new MyCommand(cmd);
  }

  public description(desc: string): this {
    this.cmd.description(desc);
    return this;
  }

  public util1(): this {
     // ...
     return this;
  }

  ...
}
```

**Comment by shadowspawn** [comment]
See #1191 for work in progress which resolves this issue.
