### ISSUE TITLE
Howto:  option with int value and default ? 

### ISSUE THREAD

**Issue by m67hoff** [tj/commander.js#1007]
Hi, I try to create an option with integer value and default value.  However all my tries were  unsuccessful:

`.option('--port <int>', 'port', 33001)`
-> works for `run_connect` (no optional port number) and set port to 33001, but fails with `run_connect --port 22` , since port is a string

`.option('--port <int>', 'port', parseInt, 33001)`
-> fails since 33001 is taken as second argument for parseInt 

`.option('--port <int>', 'port', parseInt, 10, 33001)`
-> works for `run_connect  --port 22`, but with no port specified it sets the default port to 10 (also shows 10 in help as default)

`.option('--port <int>', 'port', parseFloat, 33001)`
-> my current workaround works for `run_connect --port 22` , but the network request fails with non int ports:   `run_connect --port 22.5`    (the middle between ssh and telnet)  ;-)   

Any hint for me ?

**Comment by shadowspawn** [comment]
There is a `parseInt ` example in the README. See under: https://github.com/tj/commander.js#custom-option-processing

See if that helps.

(The reason passing `parseInt` directly does not work is that it takes two parameters which are different than the two parameters passed to the custom callback function.)

**Comment by m67hoff** [comment]
Hi thanks,

ok I thought there is an easier possibility, but for int you really need to "cast"  parseInt to a function that accepts only one parameter, otherwise the default is "misunderstood" as parseInt second radix parameter.

So works:
```
function myParseInt(value) {
  return parseInt(value);
}

program
  .option('--port <int>', 'port', myParseInt, 33001)

if (program.port) {
  config.ssh.port = program.port
}
```javascript
but its the same result as (seems parseInt also "strip" the non integer decimals)

 ```javascript
program
  .option('--port <int>', 'port', parseFloat, 33001)

if (program.port) {
  config.ssh.port = Math.floor(program.port)
}
```
