### ISSUE TITLE
Update Chinese README for #1010 (.name and .usage)

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1014]
I updated the README in #1010 which has been merged to the develop branch.

I made the format changes in #1013 for the Chinese README but just copied the english text for the new section in the help.

A Pull Request, or just a translation of that section, is welcome.

**Comment by shadowspawn** [comment]
<pre>
### .usage and .name

 These allow you to customise the usage description in the first line of the help. The name is otherwise
 deduced from the (full) program arguments. Given:

 ```js
 program
   .name("my-command")
   .usage("[global options] command")
 ```

 The help will start with:

 ```Text
 Usage: my-command [global options] command
 ```
</pre>

**Comment by oGsLP** [comment]
```
### .usage 和 .name

 这两个选项让你可以自定义在帮助信息第一行中显示的命令使用描述(description)，并且描述是从（完整的）命令参数中推导出来的。例如：

 ```js
 program
     .name("my-command")
     .usage("[global options] command")
     ```

 帮助信息会以此开头：

 ```Text
 Usage: my-command [global options] command
     ```
```

**Comment by shadowspawn** [comment]
Thanks @oGsLP ! I'll get add this to my Pull Request.

**Comment by shadowspawn** [comment]
(The translation has been added to develop branch for next release.)
