### ISSUE TITLE
Have in-house support in-order to recommend matching commands

### ISSUE THREAD

**Issue by jamesgeorge007** [tj/commander.js#1015]
[yargs](https://github.com/yargs/yargs) comes shipped with a `recommendCommands()` method as part of the public API. It would be great if commander.js would have it as well :clap: 

```ts
program
  .name('sample')
  .usage('<command>)
  .version(version)
  .recommendCommands();

program
  .command('init')
  .action(() => {});

program
  .command('create');
  .action(() => {});
```

`sample creat`
```bash
Unknown command creat.
Did you mean create?
```

**Comment by jamesgeorge007** [comment]
@shadowspawn I would love to submit a PR if you could throw light on the implementation strategy :+1:

**Comment by jamesgeorge007** [comment]
@shadowspawn @oGsLP thoughts :thinking:

**Comment by oGsLP** [comment]
Only for me, I think it's not necessary. People can realize it by 
```js
program.command("*").action(cmd => {
  suggestCommand(cmd);
});
```
And we can find a npm package named `didyoumean` to customzie `suggestCommand(cmd)` easily.

I'm not familiar with yargs, it seems that it doesn't have an api to match regex cmd like '*' so it has `recommendCommands()` to handle this. But commander do.

**Comment by shadowspawn** [comment]
I do not think it likely I would accept a PR for this currently, as we still have some improvements to make in whether Commander warns about unrecognised commands in the first place. (So not "in-house support".)

I am interested in how to add possible matches, and currently that would be in own code or in an add-on package. Also interested in how popular an idea this is, so feel free to leave this issue open even if you decide not to investigate yourself.

My limited knowledge (not researched) is most computer programs use the Levenshtein distance algorithm. I was casually looking at didyoumean and didyoumean2 in weekend. (Using these as examples rather than recommendations.)

(Both roll-your-own solutions and didyoumean also suggested by @oGsLP, thanks for comment )

**Comment by shadowspawn** [comment]
I came across an implementation in comments:  https://github.com/tj/commander.js/issues/432#issuecomment-175785162

**Comment by jamesgeorge007** [comment]
@shadowspawn what about documenting how to achieve it with [didyoumean](https://www.npmjs.com/package/didyoumean).
I would happily submit a PR :+1:

**Comment by shadowspawn** [comment]
Same feedback as building it in, I do not think it likely I would accept a PR for this currently. If the code is not huge, you could simply add it as a comment here though.

**Comment by jamesgeorge007** [comment]
A typical implementaion would be:-
```js
const suggestCommands = cmd => {
  const availableCommands = program.commands.map(c => c._name);

  const suggestion = didYouMean(cmd, availableCommands);
  if (suggestion) {
    console.log(`  ` + chalk.red(`Did you mean ${chalk.yellow(suggestion)}?`));
  }
};

program.arguments('<command>').action(cmd => {
  program.outputHelp();
  console.log(`  ` + chalk.red(`\n  Unknown command ${chalk.yellow(cmd)}.`));
  console.log();
  suggestCommands(cmd);
});
```

**Comment by shadowspawn** [comment]
I have opened a PR to use didYouMean in the README as the example for an unrecognised command #1176

**Comment by jamesgeorge007** [comment]
https://github.com/tj/commander.js/pull/1176/files#r376756601

**Comment by jamesgeorge007** [comment]
> https://github.com/tj/commander.js/pull/1176/files#r376756601

#1181 did made sense in this regard.

**Comment by jamesgeorge007** [comment]
> https://github.com/tj/commander.js/pull/1176/files#r376756601

#1181 does made sense in this regard.

**Comment by jamesgeorge007** [comment]
> https://github.com/tj/commander.js/pull/1176/files#r376756601

#1181 does makes sense in this regard.

**Comment by shadowspawn** [comment]
You could add the `require` to https://github.com/tj/commander.js/issues/1015#issuecomment-536262298

**Comment by jamesgeorge007** [comment]
Ig it would make much sense for a dedicated section to be introduced within `README` containing the instructions for command suggestion implementation.

**Comment by shadowspawn** [comment]
I do not wish to put a dedicated section in the README for this.

I have considered adding a separate page and examples for such code, and possibly links to modules which implement add-ons to Commander and the like. There has not been compelling enough information so far, but this is one such example.

**Comment by jamesgeorge007** [comment]
Sounds good :+1:

**Comment by jamesgeorge007** [comment]
But the present state with #1176 is essentially causing trouble.

**Comment by shadowspawn** [comment]
This issue didn't get any upvotes in six months. I am happy to leave it up to authors for now to roll their own suggestions.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
