### ISSUE TITLE
Type definitions for CommanderStatic missing `rawArgs`

### ISSUE THREAD

**Issue by bschlenk** [tj/commander.js#1019]
The `CommanderStatic` type, or probably the `Command` that it inherits from (defined [here](https://github.com/tj/commander.js/blob/fea94a9feccdc234fead2d74c9bcdc72e598186d/typings/index.d.ts#L28)) should include a `rawArgs` property that is defined as `string[]`. Is there a reason this was omitted from `Command`? If not, I'm open to submitting a pull request.

**Comment by shadowspawn** [comment]
Thanks, I will look into it. The TypeScript definition does deliberately leave out some properties and methods that never got promoted to fully public and supported.

**Comment by shadowspawn** [comment]
Ok to add if you would find it useful, in `Command` along with

```
args: string[];
```

**Comment by shadowspawn** [comment]
Closing as not planning to act on this report myself, but PR still welcome.

Thank you  for your contributions.
