### ISSUE TITLE
help command not respecting executableFile option

### ISSUE THREAD

**Issue by Piccirello** [tj/commander.js#1025]
Using commander v3.0.0, I have a command that specifies the `executableFile` option:

```javascript
program
  .name("testapp")
  .version("1.0.0")
  .command("list <type>", "List available configuration", { executableFile: 'cli/list' })
```

The `list` command in `cli/list.js` specifies its name and some subcommands (only one listed for brevity):

```javascript
program
  .name("list")
  .description("List available configuration")
  .command("secrets", "Print all available secret types", { executableFile: 'list-secrets' })
```

Calling `testapp list --help` works as expected, but `testapp help list` throws an error. It appears `help` is trying to load `cli-list.js` rather than the file specified by `executableFile`.

```javacript
$ testapp list --help
Usage: list [options] [command]

List available configuration

Options:
  -h, --help       output usage information

Commands:
  secrets          Print all available secret types
  help [cmd]       display help for [cmd]
```
```javacript
$ testapp help list
error: cli-list(1) does not exist, try --help
```

**Comment by shadowspawn** [comment]
Thanks for the clear report and reproduce detail.

There is a Pull Request (thanks to @nazieb) which has been accepted onto the develop branch which should fix this: https://github.com/tj/commander.js/pull/1018

We have some other PR close to ready, but I think we might ship a v3.0.1 and not wait. It is great that people are using the new configuration option. I'll fix the TypeScript omission and then we could ship soon @abetomo ?

**Comment by Piccirello** [comment]
Excellent! Thanks for the heads up @shadowspawn, and for the fix @nazieb.
