### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [tj/commander.js#1031]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

**Comment by shadowspawn** [comment]
I am dubious about adding a specific service name at the top level of the `package.json` for a 2 week old project. Good luck, but no thanks at this stage.

**Comment by shadowspawn** [comment]
> On another note, work is being done to standardize fields like this for donations, so there's that to look forward to in the future.

I came across two discussions today, one of which I see you commented on:
- https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md
- https://github.com/npm/cli/pull/187

And also somewhat related:
- https://blog.npmjs.org/post/187382017885

I'm interested in seeing what comes of these.

**Comment by lastmjs** [comment]
Yes, I'm especially excited for what npm is about to do
