### ISSUE TITLE
not executable. try chmod or run with root

### ISSUE THREAD

**Issue by lxfriday** [tj/commander.js#1041]
![image](https://user-images.githubusercontent.com/20264467/64664371-8e9c7a00-d481-11e9-94c9-517d8a2c2a96.png)
I have 2 files to  exec, but when I install my cli from npm, I cannot exec It

```bash
woodpecker inject
# should exec woodpecker-inject
# but error
```

![image](https://user-images.githubusercontent.com/20264467/64664395-ac69df00-d481-11e9-8646-d3190043d356.png)

**Comment by lxfriday** [comment]
This is the entry file
![image](https://user-images.githubusercontent.com/20264467/64664761-b8a26c00-d482-11e9-98c6-42073870f88e.png)

**Comment by shadowspawn** [comment]
(Including the actual code and error message as text is better for reporting issues than pictures, so it can be searched, and I can copy-and-paste it to reproduce the problem too.)

**Comment by shadowspawn** [comment]
The first approach is to make your subcommand a real executable. Your `woodpecker-inject` file needs to have the first line say how it is executed, which for a javascript file is usually:

```
#!/usr/bin/env node
```

And the subcommand file needs be executable:

```
chmod a+x woodpecker-inject
# or
chmod 755 woodpecker-inject
```

then you can check it is executable by trying to run it directly on command line like:

```
./woodpecker-inject
```

The second approach for a javascript file is you could add `.js` to the filename, and Commander will automatically launch it using node.

**Comment by lxfriday** [comment]
Thank you very much, your second approach solved my problem. And I have another way to fix this.

I add `woodpecker-inject` file into `package.json`  `bin` field, when I install my cli  globally, npm will automaticly make it executable.

**Comment by lxfriday** [comment]
Add the original problem,

```bash
error: /home/xxx/.nvm/versions/node/v10.16.0/lib/node_modules/@namespace/woodpecker/bin/woodpecker-inject(1) not executable. try chmod or run with root
```
files
```
- bin
 - woodpecker.js
 - woodpecker-inject
```

`woodpecker-inject` is a javascript file. I added `#!/usr/bin/env node` at first line. But when installed, the file is not executable.

**Comment by shadowspawn** [comment]
Thanks @lxfriday
