### ISSUE TITLE
Node option max_old_space_size example

### ISSUE THREAD

**Issue by ArtemDordovskyi** [tj/commander.js#1046]
Could you please add an example how to use --max_old_space_size=4096 with command 'start'?
```
program
  .command('start')
  .description('start server')
  .option('-p', '--port', 'Start server with different port')

program.parse(process.argv)
```

**Comment by shadowspawn** [comment]
You set the node flags for the whole javascript program.

You have two options, specify it on the command line when you run your source file like:

```
node --max_old_space_size=4096 index.js
```

Or on Linux and Mac you can specify flags in the "hashbang" line for when the program is executed directly, like say:

```
#!/usr/bin/env node --max_old_space_size=4096
console.log(process.execArgv);
```

And then when run:
```
$ chmod a+x my-program
$ ./my-program
[ '--max_old_space_size=4096' ]
```

**Comment by ArtemDordovskyi** [comment]
Can I always run with this option my command ```start``` or I always should add it custom?

**Comment by ArtemDordovskyi** [comment]
Thank you. That is what I want.
