### ISSUE TITLE
'--domain' option may cause problem

### ISSUE THREAD

**Issue by ohsc** [tj/commander.js#105]
Command object inherit from EventEmitter directly. However EventEmitter have a issue that [it assume .domain as a Domain instance](https://github.com/joyent/node/issues/3922). And this issue is still opening.

Maybe commander.js could do something to prevent user from using 'domain'.

**Comment by vanesyan** [comment]
We can migrate to another event emitter, rather than standard one.

**Comment by shadowspawn** [comment]
The `domain` issue in particular is fixed in node 10.

**Comment by shadowspawn** [comment]
Closing this as covered by #183 and #933
