### ISSUE TITLE
Optionally pass options as an object

### ISSUE THREAD

**Issue by saivan** [tj/commander.js#1055]
Now that we can destructure arguments to options, perhaps it would be useful to 
have the ability to pass options as an object to the handler. So we could do

```js
program.command('hello <arg1> <arg2>')
  .option('-c, --specialSetup <optionA>')
  .passAsObject()
  .action( async options => {
    const { arg1, arg2, specialSetup } = options
    ...
  })
```

The benefit here is, say I had some special setup function, I don't need to rely on the order of my arguments. Etc:

```js
program.command('hello <arg1> <arg2>')
  .option('-c, --specialSetup <optionA>')
  .passAsObject()
  .action( doSetup( async options => {
    const { arg1, arg2 } = options
    ...
  }))
```

So I could reuse doSetup all over my code, without needing to worry about the order that commands get passed in. I know that you can accomplish what I'm trying to achieve in other ways such as looking for option flags. But this seems like strictly more flexibility.

Not sure about the effect on code complexity though.

**Comment by shadowspawn** [comment]
This has not scored any likes or comments in a month. I don't think it is something we are likely to do based on current information.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
