### ISSUE TITLE
Prevent input/output mixing in Node.js console?

### ISSUE THREAD

**Issue by Bluscream** [tj/commander.js#1057]
Can i do https://stackoverflow.com/questions/31359231/prevent-input-output-mixing-in-node-js-console with commander.js?

![](https://i.stack.imgur.com/2Gbp0.png)

**Comment by shadowspawn** [comment]
Commander does not prompt for input or do any cursor manipulation, so it isn't going to help you do that. It might work with whatever else you do.

**Comment by Bluscream** [comment]
Thanks

**Comment by hello-sunbaixin** [comment]
you can try Inquirer
