### ISSUE TITLE
Command insensitive

### ISSUE THREAD

**Issue by AparnaaKS** [tj/commander.js#1065]
Can you make the commands to be case insensitive? The commands are case sensitive right now.

**Comment by shadowspawn** [comment]
No, there is not support for case insensitive. You might be able to achieve that by preprocessing the arguments before you call parse?

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
