### ISSUE TITLE
v4.0.0 prerelease available

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1067]
Release Notes here: https://github.com/tj/commander.js/releases/tag/v4.0.0-0

You can try the prerelease with:

    npm install commander@next

or from the github branch if you prefer:

    npm install tj/commander.js#develop

Open an issue or add a comment here for any problems you encounter.

**Comment by shadowspawn** [comment]
Added .requiredOption to prerelease: https://github.com/tj/commander.js/releases/tag/v4.0.0-1

**Comment by qoomon** [comment]
What about async await support for actions?

**Comment by shadowspawn** [comment]
@qoomon 
No async changes in 4.0.0. The open issue you can subscribe to is #806

**Comment by shadowspawn** [comment]
@abetomo 
Shall we release this weekend? I'll get develop into good state ready for release, which will be mostly just consolidating the release notes.

**Comment by abetomo** [comment]
@shadowspawn Release on the weekend!

**Comment by shadowspawn** [comment]
Published v4.0.0, and removed `next` tag.
