### ISSUE TITLE
support for values which start with a hyphen

### ISSUE THREAD

**Issue by stephenmathieson** [tj/commander.js#107]
unable to use values which begin with a hyphen:

```
$ node lib/cli --option=-value
error: unknown option `-value'
```

**Comment by SteveEmmerich** [comment]
Hello, I am sorry to reopen this issue but I cannot find the duplicate with the answer to this question. Could you please reference the ticket number or revisit the answer?

**Comment by tj** [comment]
ah sorry it's #61, need some maintainers here though :(
