### ISSUE TITLE
2.20.1 Not Backward Compatible

### ISSUE THREAD

**Issue by terrancesnyder** [tj/commander.js#1073]
https://github.com/tj/commander.js/blob/master/index.js#L100

// new Set();

Is not compatible. This hit us with pm2 where pm2 includes commander, and pm2 runs on node 0.10.x however it includes updated commander which is now using new Set() which is not supported under 0.10.x. We can not upgrade. Please ensure semantic versioning and move Set() to a different version.

**Comment by shadowspawn** [comment]
Thanks for report. I'll do some investigation.

**Comment by shadowspawn** [comment]
`Set` goes back to Node 0.12.18 but not to 0.10.48 according to:
- <https://node.green>

Node v0.12.0 (Stable) was released 2015-02-06
- <https://nodejs.org/en/blog/release/v0.12.0/>

Commander v2.0.0 was released on Jul 19, 2013, so Commander 2.x started before node 0.12 and so reasonable that 2.x.y should not break in this way despite the age.

The fix I made was not essential. I suggest we reverse the change I made in 2.x, if you agree @abetomo ? (I'm happy to do it, but likely to be a couple of days before I have time.)

**Comment by abetomo** [comment]
Fixed.
Could you try using v2.20.3?

**Comment by shadowspawn** [comment]
Release a new version, and no further activity in a month. Closing this as resolved.

Thanks @abetomo for quick action on this one.

People will probably upgrade from Command 2.x to 4.x now, but if anyone hits same issue with 3 we could make the same change there. 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
