### ISSUE TITLE
sub-commands without their own command are not passed any options or arguments

### ISSUE THREAD

**Issue by leroy0211** [tj/commander.js#1077]
When you have a primary command like `pm`, and you want to create sub-commands like `pm-search`, the arguments (and options) are not passed to the subcommand. Either this functionality doesn't work, or it's not documented. Some of the test fixtures suggest this should be possible. I want to separate the commands, even if there are no real sub-commands.

This example will demonstrate what I try to achieve

```js
# pm
program.command('search <value>', 'This will search for stuff');
```

```js
# pm-search
console.log(`Searching for ${value}`) 
// I want to use the argument of the search command in here (and possible options too)
```
I've tried to create a sub `program.command('<value>')` without any name, but that didn't worked. The file is being executed, so that's not the problem.

**Comment by leroy0211** [comment]
Oh I figured it out myself. 

by creating just a `program.action` with optional options, you can pass the arguments to a sub-command. 

```
# pm-search
const program = require('commander');

program.option('--foo', 'enable foo')
    .action(function(value, {foo}) {
        console.log(`Searched for ${value} and ${foo}`);
    });

program.parse(process.argv);
```

This should be added to the documentation!

**Comment by shadowspawn** [comment]
In `pm-search` you can specify that you are expecting an argument on what is locally the top-level command with `.arguments()`.
- https://github.com/tj/commander.js#specify-the-argument-syntax

```js
#!/usr/bin/env node
// pm-search

const program = require('commander');

program
  .option('--foo', 'enable foo')
  .arguments('<value>')
  .action(function(value, {foo}) {
    console.log(`Searched for ${value} and ${foo}`);
  });

program.parse(process.argv);

if (program.args.length === 0) {
  console.log('Please supply a value to search for');
}
```

**Comment by leroy0211** [comment]
Ah ok, It wasn't that clear to me in the documentation. Maybe some reference to "specify the argument syntax" from the "Action handler (sub)commands" section, because that was my starting point in searching the documentation about this use-case.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
