### ISSUE TITLE
Global options not displayed in sub-command help

### ISSUE THREAD

**Issue by jjs105** [tj/commander.js#1078]
I may be missing something but is there any way to include the global options information in the sub-command help.

Test Code:
```
program
  .description('Test program/command.')
  .option('-g, --global', 'a global option')
  .version(VERSION);

program
  .command('sub')
  .description('Sub-command!')
  .option('-l, --local', 'a sub-command local option')
  .action(() => {});

program.parse(process.argv);
```

Program Help Output:
```
$> node test.js -h
Usage: test [options] [command]

Test program/command.

Options:
  -g, --global   a global option
  -V, --version  output the version number
  -h, --help     output usage information

Commands:
  sub [options]  Sub-command!
```

Sub-Command Help Output:
```
$> node test.js sub -h
Usage: test sub [options]

Sub-command!

Options:
  -l, --local  a sub-command local option
  -h, --help   output usage information
```

What I would want/expect:
<pre>
$> node test.js sub -h
Usage: test sub [options]

Sub-command!

Options:
  <b>-g, --global   a global option
  -V, --version  output the version number</b>
  -l, --local  a sub-command local option
  -h, --help   output usage information
</pre>

**Comment by shadowspawn** [comment]
You didn't miss anything, there is not a way to include the global options information in the sub-command help.

**Comment by shadowspawn** [comment]
Related: #905

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity or likes in a few months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Opened poll on possible enhancements to global options: #1551

**Comment by shadowspawn** [comment]
Added `showGlobalOptions` in Commander 9.5.0.
