### ISSUE TITLE
Example provided for Options in README no longer valid?

### ISSUE THREAD

**Issue by mkiddTempus** [tj/commander.js#1079]
Based on the README [here](https://github.com/tj/commander.js#options), the opts outputted should include the other options as well but they are outputted within `program.opts` with `undefined`. Has this changed to only outputting the defined values from the command?

**Comment by shadowspawn** [comment]
Are you asking about:
```
console.log(program.opts());
```
producing
```
{ debug: true, small: undefined, pizzaType: undefined }
```

I used the otherwise undocumented `.opts()` method in that example. That routine makes an object with a key and value for each option which has been added to the command with `.option`. I do not think the behaviour has changed recently.

What are you seeing and what were you expecting?

**Comment by mkiddTempus** [comment]
This code: 
```
const cli = async () => {
  try {
    const program = new commander.Command();
    program.version('0.0.1');
    program
      .option('-a, --assume', 'assumed')
      .option('-g, --global', 'global')
      .option('-o, --ordertype <order>', 'Order or order type');

    program.parse(process.argv);
    console.log('args/opts from commander');
    console.log(`program.opts(): ${JSON.stringify(program.opts())}`);
    console.log(`program.args: ${program.args}`);
  } catch (error) {
    console.log(error);
  }

```

Has this output:
```
args/opts from commander
program.opts(): {"version":"0.0.1"}
program.args: 
```
I would have expected the same output you posted but it didn't occur. Curious if the feature changed behavior and the README was not updated.

**Comment by shadowspawn** [comment]
`JSON.stringify` omits the undefined values.

```js
const example = { value: true, missing: undefined };

console.log(example);
console.log(JSON.stringify(example));
```

```
$ node index.js 
{ value: true, missing: undefined }
{"value":true}
```

**Comment by shadowspawn** [comment]
Closing this as resolved.
