### ISSUE TITLE
Enhancement: Mandatory options

### ISSUE THREAD

**Issue by ace130-github** [tj/commander.js#1086]
I would like to mark certain options as mandatory.
When such an option (along with a value, if so defined) is not present then the program would print the help to the console and exit (just like when you specify an option with a mandatory parameter by angle brackets).

I would like to use this feature e.g. to pass credentials to a program that can't work without them, eg
`importToDatabase.js -u <username> -p <password> -d <databaseUrl>`

**Comment by shadowspawn** [comment]
Thanks for the example. You are in luck! See #1071 for more details.

This is available now in a prerelease: https://github.com/tj/commander.js/releases/tag/v4.0.0-1

We are planning to release v4 this weekend.

**Comment by shadowspawn** [comment]
v4.0.0 has been released.

**Comment by ace130-github** [comment]
Thanks a lot, this is good news! And sorry for not searching through the existing issues carefully enough.
