### ISSUE TITLE
Should 'command:*' and command('*') be removed from README?

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1090]
We have two examples of using command+* in the README but perhaps not a good pattern to encourage. I wonder whether we should remove them and suggest or provide better alternatives.

1) 
```
// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```

This works nicely in some cases, but is not a general solution:
- an action handler on the program _also_ listens for `command:*`
- it is called for every command for which there is not an action handler, which includes all git-style executable commands. Not just for unknown commands. (#809)

It might be an ok pattern for a subset of cases and could expand comments so clearer not a general pattern.

See also: #1088

2)
```
program
  .command('*')
  .action(function(env){
    console.log('deploying "%s"', env);
  });
```

This example predates the ability to add arguments to the program using `.arguments()`, which might make for a tidier example, and more consistent with (sub)command action handlers.

Somewhat related is a request for allowing an action based command as default command #742

**Comment by shadowspawn** [comment]
I would like to do further investigation and work around 'command:*' actions and handling, but this issue isn't likely to prompt that work. Closing to reduce issue noise.

**Comment by Yalhu** [comment]
I want to add a listener(do some checking, like version) on every command created.

**Comment by shadowspawn** [comment]
There is not a hook called before actions. The related open issue is: #1197

1) `command:*` is sent when the command name does not match a subcommand, and is a bit like the newer default command.

2) 'command:init' will be sent when the subcommand `init` is used. Depending on whether you define the listener before or after the subcommand, your listener will be called before or after the subcommand.

If that does not help, then open a new issue so some visibility on question and answer instead of hidden away here. 😄
