### ISSUE TITLE
Multiple required options

### ISSUE THREAD

**Issue by dylanirlbeck** [tj/commander.js#1093]
Is there a way to implement more than one required option? Maybe I'm not reading the docs correctly, but when I try to do this:

```js
program
         .requiredOption(...)
         .requiredOption(...)
         .option(...)
```

only the first `requiredOption` gets enforced. 

If there isn't a way using commander.js, is there a recommended workaround?

Thanks!

**Comment by shadowspawn** [comment]
They will all be enforced, but you only get an error message for one at a time. Does that explain what you are seeing?

```js
const program = require('commander');

program
   .requiredOption('-a, alpha', 'first required option')
   .requiredOption('-b, beta', 'second required option');

program.parse(process.argv);
```

```
$ node index.js
error: required option '-a, alpha' not specified
$ node index.js -a
error: required option '-b, beta' not specified
```

**Comment by dylanirlbeck** [comment]
@shadowspawn, that is exactly what I'm seeing! My apologies for not giving a more detailed output message. Thanks so much!
