### ISSUE TITLE
Help doesn't work when using subcommands

### ISSUE THREAD

**Issue by andzdroid** [tj/commander.js#110]
Very simple test program:

```
var program = require('commander');
program
  .version('0.0.1')
  .command('test', 'test command')
  .parse(process.argv);
```

Save it as bla.js.

If we run `node bla -h`, we get this error:

```
bla--h(1) does not exist
```

Similar results if we use `--help`.

`-V` and `--version` work fine though.

I'm okay with it not working, since we can use `bla help [cmd]`, but the help message lists -h and --help as options, and there is no way to turn that off.

**Comment by fingerpich** [comment]
this works for me

```js
var program = require('commander');
program
  .version('0.0.1');

program
  .command('test [name]')
  .description('test command')
  .action((name, cmd) => {
    ...
  });

program
  .parse(process.argv);
```
