### ISSUE TITLE
How to disable '--no-foo' (negatable boolean and flag|value) features

### ISSUE THREAD

**Issue by snowman** [tj/commander.js#1100]
I write an program which wrap around git command, in which runs `git diff --no-index` command.

```javascript
const program = require('commander');

program
  .version('0.0.7')
  .usage('[options] [<commit>] [--] [<path>...]')
  .option('--cached', 'show diff of staging files')
  .option('--no-index', 'compare two paths on the filesystem')
  .parse(process.argv);

const options = ['--patience'];
if (program.cached) {
  options.push('--cached');
}
if (!program.index) {        // instead of using `program.noIndex"
  options.push('--no-index')
}
```

**Comment by shadowspawn** [comment]
There is not a way to disable the negatable boolean feature. Your program looks as expected.

The negatable feature looks for an option name with a leading `no-` and does not trigger if the option is named differently. So you can get the code to have `noIndex` but only by using a matching command line option. (I am not suggesting you would want to do this, just mentioning the possibility.) For example:

```
  .option('--noIndex', 'compare two paths on the filesystem')
```

```
if (program.noIndex) {
  options.push('--no-index')
}
```
