### ISSUE TITLE
access options directly via key

### ISSUE THREAD

**Issue by goodmanpersonguy** [tj/commander.js#1110]
I created a new Typescript project for a little CLI. I want to create multiple commands, so on startup I pass the `program` object to those commands via loop

**app.ts**

```ts
const commands: Command[] = [new AddCommand()];

async function bootstrap() {
	const program: Program = new Program();
	program.version(version);

	for (let i = 0; i < commands.length; i++) {
		commands[i].load(program);
	}

	program.parse(process.argv);
}
bootstrap();
```

Each command implements a helper interface

**command.ts**

```ts
export interface Command {
	load(program: Program): void;
}
```

Finally I have a command that should access an option by key. This option determines if the code should use the current working Directory

```ts
export class AddCommand implements Command {
	load(program: Program): void {
		program
			.command(`add [directory]`)
			.alias('a')
			.option('-c, --current', 'Use the current working directory')
			.action(async (directory: string, options: any) => {
				console.log(program.c); // undefined
				console.log(program.current); // undefined
				console.log(options.c); // undefined
				console.log(options.current); // undefined
				console.log(program.options.c); // undefined
				console.log(program.options.current); // undefined
				console.log(options.parent.args[0]); // ./src
				console.log(process.argv[3]); // ./src
			});
	}
}
```

As you can see I have to access the options via array index. How can I access the `current` option directly?

What I call in the terminal:

`npm run dev a ./src -c`

I created a minimal repository for reproduction

https://github.com/goodmanpersonguy/commander-cli

Thanks in advance

**Comment by shadowspawn** [comment]
In the action handler in `add.command.ts` the `current` option value is available as `options.current`.

Thanks for the repo for reproduction. Using your repo:

```
% npm run build 
...
% node dist/app.js add --current                                                                                 master
undefined
undefined
undefined
true               // i.e. options.current
undefined
undefined
undefined
--current
```

What command are you running when you see undefined for `options.current`?

**Comment by shadowspawn** [comment]
Just saw the command you are running in your message, sorry, missed that first time through.

**Comment by shadowspawn** [comment]
When you run a command with options through npm (and nodemon) multiple commands are looking at the options and may decide they are intended for them. Notice that the `-c` does not appear in the logging from npm, it was npm that ate the `-c`.

```
% npm run dev a ./src -c                                                                                         master

> commander-cli@0.0.1 dev /Users/john/Documents/Sandpits/commander/issues/1110/commander-cli
> nodemon --exec ts-node src/app.ts "a" "./src"

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/app.ts a ./src`
undefined
undefined
undefined
undefined
undefined
undefined
./src
./src
[nodemon] clean exit 
```

**Comment by shadowspawn** [comment]
A standard approach supported by Commander itself too is to stop looking for options are seeing `--`:

```
% npm run -- dev a ./src -c                                                                                      master

> commander-cli@0.0.1 dev /Users/john/Documents/Sandpits/commander/issues/1110/commander-cli
> nodemon --exec ts-node src/app.ts "a" "./src" "-c"

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/app.ts a ./src -c`
undefined
undefined
undefined
true
undefined
undefined
./src
./src
[nodemon] clean exit - waiting for changes before restart
```

**Comment by shadowspawn** [comment]
https://docs.npmjs.com/cli/run-script

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:
>
>    npm run test -- --grep="pattern"

**Comment by goodmanpersonguy** [comment]
yes, running `npm run -- dev a ./src -c` worked for me :)
