### ISSUE TITLE
Call git subcommand from another command

### ISSUE THREAD

**Issue by evanstachowiak** [tj/commander.js#1111]
Apologies if this has been asked before, but I haven't found quite the answer I'm looking for.

I've seen this issue: https://github.com/tj/commander.js/issues/643, but my use-case is slightly different.

I am using git-style subcommands, each subcommand with its own file. Using this app structure, is there any way to call another command within node? Or is it necessary to just call the command using the cli with`spawnSync` or equivalent?

For example, I have two top-level commands with subcommands (each within their own files):
  `app-cli topcommand1 subcommand1`
  `app-cli topcommand2 subcommand1`

I would like to call `app-cli topcommand1 subcommand1` from within `app-cli topcommand2 subcommand1`.

**Comment by shadowspawn** [comment]
As you say, call the command using the cli withspawnSync or equivalent. (Unless you export a javascript module from the subcommand, but I expect you mean without changing implementation!)

A shortcut is that you can probably call the subcommand directly, and not go through the hierarchy, if you are comfortable using knowledge of the implementation. So could call the leaf command `app-cli-topcommand1-subcommand1` directly from `app-cli topcommand2 subcommand1`.

**Comment by evanstachowiak** [comment]
Actually, I would be perfectly fine changing the implementation. That's what I was wondering about, what would be exported and what's the signature to call the exported module?

**Comment by evanstachowiak** [comment]
Or do you think calling spawnSync would be better practice?

**Comment by shadowspawn** [comment]
Nothing clever, I was just meaning plain javascript export. Signature up to you. 

For example, if you shift the implementation for topcommand2 subcommand1 into a separate file:

```
// topcommand2-subcommand1-lib.js
function doWork() {
  console.log('doing the work for topcommand2 subcommand1');
}

exports.doWork = doWork;
```

Then you can call it from the implementation of topcommand1 subcommand1.

```
// topcommand1-subcommand1.js
const tc2 = require('./topcommand2-subcommand1-lib')

console.log('running subcommand1');
tc2.doWork();
```

**Comment by evanstachowiak** [comment]
thanks for the speedy responses @shadowspawn !

A couple more questions if you don't mind.
  1. I had already been considering your solution above, so I ended up going with that. In this case, I assume you also recommend unit testing the individual subcommands by running `spawnSync`?
  2. When using git subcommands, `process.argv` gets processed in the subcommands and no longer represents what was passed in to the original command. Is there anyway to reference the original `process.argv` in subcommands?

**Comment by shadowspawn** [comment]
1. How you unit test is very much dependent on what you are trying to test. I don't have a recommendation.

2. There isn't a built-in way of accessing the parent command/process arguments, either in Commander or in Node. See #563 for some discussion, where I suggested using `process.env` as a possibility.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity recently. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
