### ISSUE TITLE
async action fearure

### ISSUE THREAD

**Issue by blendsdk** [tj/commander.js#1128]
Hi guys,

Any news on  the [async pull request](https://github.com/tj/commander.js/pull/1118)?

**Comment by shadowspawn** [comment]
The PR isn't ready for merging and publishing yet. I made the code available for feedback before doing the README et al.

Now that it has some likes and a review (thanks) I can proceed with more confidence that it is likely to be useful. We are planning a minor release in early January and it might make that.

**Comment by shadowspawn** [comment]
Subscribe to #806 or #1118 for updates.
