### ISSUE TITLE
Pass arguments to executable sub-commands

### ISSUE THREAD

**Issue by gitoutthere** [tj/commander.js#1137]
I am implementing pass parameters by json file allowing users to provide -i and path to a json file which has options and their values. I have 10 sub-commands and I want this parameters from json file to be passed to sub-command file to be utilised.

I have currently achieved this by putting content of input file in process.env.inputFIle and within each sub-command file I unpack this var and shove it inside process.argv

funApp.js
```
program.version('2.1')
.command('add' [parameters], ' adding stuff')
.command('update' [parameters], ' update stuff')
.command('remove' [parameters], ' remove stuff')
[... etc]
.option('-i, --input <value>',' json param file')
[...]
program.on('option:input', function(inputFile) {
  const fileData = JSON.parse(fs.readFileSync(inputFile,'utf8'))
// Somehow pass these args to the funApp-add.js as args?!
})
```
That way my CLI could be `funApp add -i params.json --overrideArg value --newArg value`

**Comment by shadowspawn** [comment]
The open issue is: #563

I had the same idea as you, passing context using environment variables: https://github.com/tj/commander.js/issues/563#issuecomment-520112985

You could perhaps treat environment variables as a first class source of options, like:
https://github.com/tj/commander.js/issues/1135#issuecomment-570016609

**Comment by gitoutthere** [comment]
Thank you for the prompt reply. Funny enough, I reviewed all those links before I posted mine. I am not fan of using env var as default value on .options since I would have less control (if env is not set and other issues)

I tried to insert the file arguments into rawArgs and other vars I thought relevant, I was hoping they get passed into subcommand as argv same way CLI options values gets passed to sub-commands.

Perhaps I can ask my question differently, can I manipulate the arguments before it is passed to the sub-command file? In my above example, can do manipulate values of --overrideArg and --newArg before they are passed to FunApp-add.js as argv?

**Comment by shadowspawn** [comment]
Good question. There is not currently support for modifying arguments before (for) passing to subcommands.

**Comment by evg656e** [comment]
I ran into the somewhat similar problem.

The use case is to have common options (e.g. verbosity level, config path etc.) for the subcommands. I found some workarounds, e.g. to create option setter function and call this function for each subcommand, or to use `.on('option:` handler and store common options in global variable, but all of these is quite messy.

I would like that options set before first command to be pass through somehow:
```javascript
program
  // common options for all subcommands
  .option('-v, --verbose', 'show more info')
  .option('-c, --config <path>', 'path to config file')
  // subcommands
  .command('encode <path>')
  .option('-p, --preset <name>', 'preset name') // command specific options
  .action((path, opts, commonOpts) => {
    // const { preset } = opts;
    // const { verbose, config } = commonOpts;
  });
````

**Comment by shadowspawn** [comment]
@evg656e 
If you are using an action handler with your command, you can access the global options on the program object, or from within an action handler on `.parent` on the passed command.

```
const commander = require('commander');

const program = new commander.Command();

program
  // common options for all subcommands
  .option('-v, --verbose', 'show more info')
  .option('-c, --config <path>', 'path to config file')
  // subcommands
  .command('encode <path>')
  .option('-p, --preset <name>', 'preset name') // command specific options
  .action((path, cmd) => {
    const { preset } = cmd;
    console.log(program.verbose, program.config);
    console.log(cmd.parent.verbose, cmd.parent.config);
  });

program.parse(process.argv);
```

```
% node index.js --verbose --config ccc encode --preset ppp bar
true ccc
true ccc
```

**Comment by evg656e** [comment]
Thanks, that what i've been looking for.

**Comment by shadowspawn** [comment]
Closing in favour of #563

**Comment by Ramonng-required** [comment]
> Good question. There is not currently support for modifying arguments before (for) passing to subcommands.





https://openjs.space/questions/tips-for-providing-arguments-in-javascript
