### ISSUE TITLE
Help subcommand doesn't call process.exit()

### ISSUE THREAD

**Issue by matthewp** [tj/commander.js#114]
./command help sub-command should show the subcommand help and then exit, but it continues executing the parent program.

**Comment by abetomo** [comment]
@matthewp Does the same problem still occur now?

**Comment by matthewp** [comment]
No idea, this is from a long time ago. 😀 Feel free to close.

**Comment by abetomo** [comment]
Closing due to possible answer suggested and no response registered. Feel free to comment and we can re-open in case this issue persisted.
