### ISSUE TITLE
how to use Git-style executable (sub)commands?

### ISSUE THREAD

**Issue by zhishaofei3** [tj/commander.js#1140]
how to use Git-style executable (sub)commands?
Can you give me a example?

**Comment by shadowspawn** [comment]
There is a functional partial program in examples with some explanation:
- https://github.com/tj/commander.js/blob/master/examples/pm
- https://github.com/tj/commander.js/blob/master/examples/pm-install
- https://github.com/tj/commander.js/blob/master/examples/pm-publish.js

And there are some undocumented fixtures used in the tests:
- https://github.com/tj/commander.js/tree/master/tests/fixtures

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
