### ISSUE TITLE
Subcommands unusable with npm link

### ISSUE THREAD

**Issue by dignifiedquire** [tj/commander.js#115]
I've tried to use the git-style subcommand feature in combination with `npm link` and `npm link module`. The main entry point  works. So for example

``` bash
$ testacular help
```

works fine.
But when I try

``` bash
$ testacular help start
execvp(): No such file or directory

  testacular-start(1) does not exist

```

it throws. The problem seems to be that it looks in the `bin` folder where the main entry point is linked to.

PS. If I run `bin/testacular help start` from within the project folder everything is fine.

**Comment by sahlouls** [comment]
Hi,
Still not clear, nor documented how test git-styled commands with seprate files (npm link) and how to publish them properly ?
Help required.
Thanks
