### ISSUE TITLE
Option callback is not called if optional value is not defined

### ISSUE THREAD

**Issue by kirbysayshi** [tj/commander.js#116]
Hopefully the title isn't too confusing :)

I have an option

```
.option('-c, --chart [columns]', 'Add columns', splitOrDefault, false)
```
- If `--chart` is not present, I would want the value to be `false`. 
- If it is present, but `[columns]` are not, I want to default it to something like `['col1', 'col2']`.
- If something like `--chart col1,col2,col3` is passed, I want those values to take precedence. 

Unfortunately, the option value callback (`splitOrDefault` above) is not called if the value is `undefined`, and thus I cannot check for `--chart` being defined but not `[columns]`, and it's just defaulted to false.

Given [line 332](https://github.com/visionmedia/commander.js/blob/master/index.js#L332), I get that this callback behavior is intended, but wanted to discuss before submitting a PR.

I may be asking for too much from commander, or there might be a simpler way... is this possible?

**Comment by abetomo** [comment]
Closing due to possible answer suggested and no response registered. Feel free to comment and we can re-open in case this issue persisted.

**Comment by shadowspawn** [comment]
Options with optional arguments and a default value were broken before Commander 9. This will be possible with proposed changes in #1652
