### ISSUE TITLE
requiredOption doesn't work for option named 'action'

### ISSUE THREAD

**Issue by andrui** [tj/commander.js#1160]
STR:
```
const program = require('commander');

program
  .requiredOption('-a, --action <action>', 'service action');

program.parse(process.argv);
```
AR:
No "required option" error

**Comment by shadowspawn** [comment]
The reason for the lack of error is that `program.action` is a function and clashes with using `program.action` as an option value. From Commander 4.1, you can avoid option name clashes by disabling the old behaviour using `.storeOptionsAsProperties(false)`;

https://github.com/tj/commander.js#avoiding-option-name-clashes

```
const program = require('commander');

program
  . storeOptionsAsProperties(false);

program
  .requiredOption('-a, --action <action>', 'service action');

program.parse(process.argv)
```

```
% node .
error: required option '-a, --action <action>' not specified
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Opened a PR to add a warning for option name clashes: #1275
