### ISSUE TITLE
v5.0.0 pre-release available (code complete)

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1163]
Release Notes: 
- https://github.com/tj/commander.js/releases/tag/v5.0.0-0
- https://github.com/tj/commander.js/releases/tag/v5.0.0-1
- https://github.com/tj/commander.js/releases/tag/v5.0.0-2
- https://github.com/tj/commander.js/releases/tag/v5.0.0-3
- https://github.com/tj/commander.js/releases/tag/v5.0.0-4
- https://github.com/tj/commander.js/blob/develop/CHANGELOG.md

README: https://github.com/tj/commander.js/blob/develop/Readme.md

You can try the prerelease with:
```
npm install commander@next
```

Open an issue or add a comment here for any problems you encounter.

**Comment by OEMarshall** [comment]
I wasn't able to access `commander@next` using yarn, so I did this instead. 
```
yarn add https://github.com/tj/commander.js.git#develop
```

**Comment by shadowspawn** [comment]
No further code changes are planned for the Commander v5.0.0 release.

**Comment by shadowspawn** [comment]
`develop` branch has version number updated, CHANGELOG updated, ready for copy-up to master and release as soon as suits you @abetomo

(Exciting! 🎉 )

**Comment by abetomo** [comment]
I appreciate your fantastic job.
5.0.0 has been released.

**Comment by shadowspawn** [comment]
Commander v5.0.0 has been released.
https://github.com/tj/commander.js/releases/tag/v5.0.0
