### ISSUE TITLE
How to pass a value to the default command without using a flag or subcommand?

### ISSUE THREAD

**Issue by siowyisheng** [tj/commander.js#1173]
My program is:
```
prog
```

I want to be able to do:
```
prog my_file.txt
```
The program will figure it out that it's an argument because of the `.txt` extension.

I can see that I can pass it as an option or use a subcommand like:
```
prog -f my_file.txt
prog run my_file.txt
```
But I want my behavior above. Is that possible with commander.js?

**Comment by siowyisheng** [comment]
My bad, seems like I can use 
```
program.parse(process.argv).args
```
to get and check the argument.

Closing.

**Comment by shadowspawn** [comment]
You can declare arguments to the program with `.arguments()` like:

```
program.arguments('[filename]');
```

https://github.com/tj/commander.js#specify-the-argument-syntax
