### ISSUE TITLE
NPM arg passing issue with command style syntax

### ISSUE THREAD

**Issue by quetzalsly** [tj/commander.js#1182]
I am having some issues with 5.0.0:

1. The `-v` does not work, only `--version` works like this:
```
program
  .version('1.0.0')
  .description('Test');
```

2. The commands syntax does not seem to work with the npm argument passing system:
```
"scripts": {
    "program": "cross-env NODE_ENV=production node ./src/program/main.js",
    "test:program": "npm run program -- test"
  },

program.command('test')
  .description('Test')
  .action(async function()
  {
    await something();
  });

await program.parseAsync(process.argv);
```

Before I used commands, I used `--arg` style and `test:program` passed it along like `-- --arg` and it all worked fine.

**Comment by shadowspawn** [comment]
1) Big `-V` not small `-v`? As seen in the help:

```
  -V, --version  output the version number
```

2) Quite a lot of programs involved in the processing there, but don't think Commander is the problem. 

What are you typing on command line, and what is not working?

For debugging, putting in a line to log the arguments early in the program is often helpful to narrow down what is reaching the node program. i.e.

```
console.log(process.argv);
```

**Comment by quetzalsly** [comment]
1. Solved thanks :) why not small v though? other programs use small v don't they?
2. Here is the console log at start of main:
```
[
  'E:\\Node\\node.exe',
  'E:\\Program\\program\\src\\program\\main.js',
  'test'
]
```

Log shows something weird here:
```
unsafe-perm in lifecycle true
Returned: code: 1  signal: null
npm\node_modules\npm-lifecycle\index.js:332:16
```

The thing is it was working perfectly with the `--arg`, what could possibly be causing the issue with using commands instead of the standard way? Would really love to solve this somehow :(

**Comment by shadowspawn** [comment]
1) Some programs do use `-v` for version, but many use `-V` and leave `-v` for verbose or other purposes.

- http://www.catb.org/~esr/writings/taoup/html/ch10s05.html
- https://unix.stackexchange.com/a/108141

2) So `test` is getting passed into the program, which is good (and reassuring since was working previously with `--arg`). 

What happens when you call your program directly?

```
node ./src/program/main.js test
```

**Comment by quetzalsly** [comment]
Thanks, I understand about the `V` now. I deleted `node_modules` and reinstalled it and everything suddenly started working... I think the issue was `npm` all along. Thanks for your help anyway! really loving the library.
