### ISSUE TITLE
Decouple arguments description from command description

### ISSUE THREAD

**Issue by sergiz** [tj/commander.js#1192]
https://github.com/tj/commander.js/blob/516a14c659d3db4650020f0eee1669957cd8918e/index.js#L1398-L1416

Hello.

Is there a special reason why we cannot only describe command arguments without the command itself?

**Comment by shadowspawn** [comment]
I think no special reason. That code matches the way they are specified, where the description is an expected parameter and the `argsDescription` is an optional parameter. 

```
   * @param {string} str
   * @param {Object} [argsDescription]
...
  description(str, argsDescription)
```

(The `argsDescription` parameter is currently undocumented.)

**Comment by sergiz** [comment]
I see, but the current implementation makes it impossible to avoid adding command description, when you only want to describe arguments.

For example, when you have a self explanatory command, but want to provide some additional description for the arguments.

My proposal is to change that, so this._argsDescription will be displayed regardless of the this._description. Optionally the description() method could also be adjusted, os if the first argument (str) is an object then it would swap the arguments (so you don't need to explicitly make str null or ''.

**Comment by sergiz** [comment]
I see, but the current implementation makes it impossible to avoid adding command description, when you only want to describe arguments.

For example, when you have a self explanatory command, but want to provide some additional description for the arguments.

My proposal is to change that, so this._argsDescription will be displayed regardless of the this._description. Optionally the description() method could also be adjusted, so if the first argument (str) is an object then it would swap the arguments (so you don't need to explicitly make str null or ''.

**Comment by shadowspawn** [comment]
Given the arguments descriptions are not currently documented, I don't this this issue will affect many people. No further activity in a month. Closing.

> My proposal is to change that, so this._argsDescription will be displayed regardless of the this._description. 

PR for this is welcome if someone does want to fix it.

> Optionally the description() method could also be adjusted, so if the first argument (str) is an object then it would swap the arguments (so you don't need to explicitly make str null or ''.

No, I do not want to complicate the method signature for a rare case.
Feel free to open a new issue if it comes up again, with new information and renewed interest.

Thank you  for your contributions.

**Comment by shadowspawn** [comment]
In Commander 7, you can pass an empty string for the command description and supply an arguments description to add just arguments description.
