### ISSUE TITLE
5.x readme is missing .action() validation explanation

### ISSUE THREAD

**Issue by sergiz** [tj/commander.js#1193]
https://github.com/tj/commander.js/blob/d5186ba4b9b64a72cd685fccbb9ec5d0ec0c430d/Readme.md#L393

This line has been modified in the develop branch and no longer explains that .action() method needs to be used in order for arguments/options to be validated.

**Comment by shadowspawn** [comment]
That was deliberate, as the options are now validated whether or not there is an action handler.
