### ISSUE TITLE
Possible to handle piped stream

### ISSUE THREAD

**Issue by ReinsBrain** [tj/commander.js#1202]
Loving linux so i'd like my command to handle piped data - any thoughts on that?

**Comment by shadowspawn** [comment]
A common pattern is to use `-` as a placeholder for a filename when you expect a filename but want to allow piped `stdin`/`stdout` too. Commander has some support in the option parsing for single dashes for this reason.

e.g.
```
tar cf - * | ( cd /target; tar xfp -)
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by TheFirstJeffreyLee** [comment]
@shadowspawn Can you show us an example of this, I am new to scripting and making CLI tools so this isn't very intuitive to me. Either that or I missed some documentation

**Comment by shadowspawn** [comment]
Piped data? I have not done that myself. 

(My comment was just about using `-` as a placeholder in the arguments.)

**Comment by TheFirstJeffreyLee** [comment]
I see yea, yea I was looking to see if this package would support taking in a continuous stream of data and then having my command process it. Is that possible or no?

**Comment by shadowspawn** [comment]
Commander does not provide tools for working with a continuous stream of data.

I was just looking for clues about reading from stdin, and some examples here:
- https://stackoverflow.com/questions/30441025/read-all-text-from-stdin-to-a-string

**Comment by TheFirstJeffreyLee** [comment]
Ah I see, okay thanks for the quick response.
