### ISSUE TITLE
Commander.js signal handling kills process and means sub-commands cant handle signals

### ISSUE THREAD

**Issue by pgebheim** [tj/commander.js#1210]
https://github.com/tj/commander.js/blob/8e1cdf5405b1e67359ca7613ff3c6ed81714b181/index.js#L785

In order to get around this, a non-executable command that needs to watch for SIGINT needs to deregister all SIGINT handlers manually in order to capture it itself.

This is a very odd set of behavior.

**Comment by shadowspawn** [comment]
That behaviour got added so that a spawned subcommand would be terminated when the "program" was terminated: #411 #632

I am not sure from your description what your setup is. Do you have a program with a SIGINT handler that calls `.parse()` and spawns a long running subcommand?

Would not adding a listener (handler) if there is one already work for your use case?

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by alexnix** [comment]
Hi,

Having an issue that might be related, so I am asking it here: i am starting WebpackDevServer from within a command.
WebpackDevServer will initiate graceful shutdown on the first Cmd+C then wait for some file watches to be closed and finish when this is done, or on a second Cmd+c. Detailed [here](https://github.com/webpack/webpack-dev-server/issues/1479#issuecomment-927113703).

Issue is, in my setup, when i press cmd+c the terminal immediately changes as if the command stopped immediately, but then not only it prints additional message from webpack (the one about graceful stopping) but also, the terminal is left in a state where non asci characters (such as up/down arrows) are printed as ^[OA^[OB.

Wondering if this behaviour could be related to what is described in this issue.

Have to mention that if i send SIGINT from `htop` or `kill` it works correctly, tho.

**Comment by shadowspawn** [comment]
Commander only listens for the signals when it is running a subcommand as a stand-alone executable. If you aren't using a subcommand implemented as a stand-alone executable when the problem occurs, then your problem is not related to this issue.

**Comment by alexnix** [comment]
My command implemented using the `.action((args) => {})` syntax. I suppose guess then it is not the case. Thanks for the clarification.
