### ISSUE TITLE
Prevent/override automatic help generation

### ISSUE THREAD

**Issue by b3nk3** [tj/commander.js#1215]
I am successfully utilising the custom help, as per README.md however, I would like to prevent the output of the automatically generated help. 

Is there a way to do this?

**Comment by shadowspawn** [comment]
So do you want the help option support (e.g. for `--help`), but don't want the automatically generated help displayed as part of the processing?

There is not currently explicit support for that.

I have a tentative idea for the future which would allow this, feedback welcome:
https://github.com/tj/commander.js/issues/1023#issuecomment-574451728

**Comment by b3nk3** [comment]
Yes, precisely that.

I like the idea of the separation you have outlined. 

I would also include an option, as a boolean, to toggle auto generated help?

Happy to work on this with you, just need to get an understanding of how the whole thing works :)

**Comment by shadowspawn** [comment]
You can override the help by defining your own option using the same flags. This isn't a complete solution as the autogenerated help would show both, but this might not affect you since you are displaying custom help anyway!

e.g.

```
const { Command } = require('commander');
program = new Command();

program
  .storeOptionsAsProperties(false)
  .option('-h, --help', 'show my custom help')
  .parse(process.argv);

const options = program.opts();
if (options.help) {
  console.log('show my custom help');
}
```

```
$ node index.js -h
show my custom help
```

**Comment by b3nk3** [comment]
This is helpful and enough for my use case. Still happy to help, if you need  hand.

**Comment by shadowspawn** [comment]
Thanks. I am planning to go through the issues and collect the help related issues before making any changes, to look for the more popular or common issues that come up. I'll post here when I do.

**Comment by shadowspawn** [comment]
(Collected help issues in #1225.)

**Comment by shadowspawn** [comment]
No additional likes on this issue in particular, closing in favour of #1225 with collected issues.

Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Commander v6.1 allows allows disabling the built-in help option: #1325
