### ISSUE TITLE
No command provided is run twice in @5

### ISSUE THREAD

**Issue by Lakitna** [tj/commander.js#1216]
I've encountered a small issue in @next, though I'm not 100% sure it's due to @next or if this is pre-existing behaviour.

The new behaviour where it will output the help when no command is provided is very useful :) but it seems to do it twice. Normally you won't notice because of `process.exit(1)`. But I'm stubbing it for unit testing so `expect(process.exit).to.have.been.calledOnce;` is failing right now.

Relevant tests: https://gist.github.com/Lakitna/4d3eff25f79528ec06dbba84529e1c12

Note that the first test fails due to commander running `outputHelp and exit(1)` twice. The second one passes because my custom `outputHelp and exit(1)` is run only once.

**Comment by shadowspawn** [comment]
You can't just stub out `exit` and let the code carry on, or you will encounter the sorts of problems you are seeing. The code was not written to call `exit` and _also_ fall out gracefully.

This was actually part of the motivation for adding `.exitOverride()`, as I encountered the same issue myself when expanding the test coverage.

Have a look at Commander's own tests for possible approaches, for example:

https://github.com/tj/commander.js/blob/master/tests/command.help.test.js

**Comment by Lakitna** [comment]
The example you've provided assumes you have control over `program` before `program.parse(process.argv)`. This makes a lot of sense when testing commander itself but is an issue for me atm.

I'm trying to test the file that implements commander in my codebase. The final line of that file is `program.parse(...)`. In other words: I can't use `.exitOverride()` before I invoke `program.parse(...)`.

I could move the actual implementation of commander to another file that exports `program` and have the `bin/cli.js` file only do the import & `program.parse()` but that feels a bit iffy to me.

Actually, now that I think about it... What I'm doing is already iffy. I'm literally testing unmodified behaviour of a dependency. I'll simplify the test to only test if `process.exit(1)` has been called and not care about how many times or if it outputs help. This way I'll catch `isDefault` things without retesting commander.

Thanks for your help!
