### ISSUE TITLE
Commander v5.0.0 has been released

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1217]
If you are upgrading then be aware this is a major version change, and you may encounter some breaking changes in areas where we could not preserve backwards compatibility.

Lots of improvements and fixes: https://github.com/tj/commander.js/releases/tag/v5.0.0

Let us know if we can offer better advice in the release notes, or if you encounter issues.

**Comment by sanex3339** [comment]
After upgrading to 5.0.0 if I use `--help` in tests it completely stopped my tests after that.

**Comment by shadowspawn** [comment]
Open a new issue please @sanex3339 . What version did you upgrade from? Is it a public repo so I can try it?

**Comment by sanex3339** [comment]
https://github.com/tj/commander.js/issues/1218

**Comment by shadowspawn** [comment]
Solved the `--help` mystery in #1218. The bug was in Commander v4!

**Comment by ayroblu** [comment]
I setup a typescript project with this and the types didn't show up for me (unresolved module), not sure if I need to do something special 🤷

**Comment by shadowspawn** [comment]
@ayroblu Was this working in previous versions of Commander? Please open a new issue and supply some more details.

**Comment by ayroblu** [comment]
I don't need to fight for this right now, for my basic cli app it doesn't really matter. Just flagging it, cause typescript typing can be weird to setup.
FWIW, I created a new project with all the all the latest stuff
