### ISSUE TITLE
Command action removes last parameter value

### ISSUE THREAD

**Issue by krazyjakee** [tj/commander.js#1219]
```javascript
program
  .command("a <b> <c> <d>")
  .action((a, b, c, d) => {
    // a, b & c are string values as expected
    // d is the Command class object
  })
  .parse(process.argv);
```

The workaround is to add an extra, unused argument until this is fixed.

```javascript
program
  .command("a <b> <c> <d> [x]")
  .action((a, b, c, d) => {
    // a, b, c & d are string values as expected
  })
  .parse(process.argv);
```

**Comment by shadowspawn** [comment]
Quick reply, the name `cmd` is the command object (not a string) and is the last parameter after the arguments. Alternatively you can call it `options` which is mostly what it is used for. You want:
```
.action((a, b, c, cmd)
```

**Comment by krazyjakee** [comment]
@shadowspawn I've updated the original post to fix my wording. Ignoring that cmd is missing from the action callback arguments, this is very much a bug.

**Comment by shadowspawn** [comment]
The command name is not passed to the action handler, just the arguments for the command.

```
  .command("a-name <b-arg> <c-arg> <d-arg> [x]")
  .action((b, c, d, x) => {
```

**Comment by krazyjakee** [comment]
@shadowspawn with your example

```javascript
program
  .command("a-name <b-arg> <c-arg> <d-arg> [x]")
  .action((b, c, d, x) => {
    console.log(b, c, d, x);
  })
  .parse(process.argv);
```

`node index.js a b c d e` prints `a b c d`

a being the command name is indeed being printed, this likely explains the loss of `e`.

**Comment by shadowspawn** [comment]
Missed this first time due to haste, but you are calling `parse` on the new subcommand instead of on the program.

Try changing parse call to:
```
program
  .parse(process.argv);
```

**Comment by shadowspawn** [comment]
Related issue: #1209

**Comment by krazyjakee** [comment]
Thanks, this solves the issue.

I'm wanting to create multiple subcommands with their own actions but I can't really see the best way to do it, or how to do it at all in the readme.

```javascript
.command("add [id] [file]")
.command("update [id] [file]")
```

If an action follows that, the subcommand gets passed in and I can work with it, but obviously the bug in this issue exists.

**Comment by shadowspawn** [comment]
You want to hang on to the new high level subcommand in a variable, and then add its own commands to that.

Have a look at `brew` in  https://github.com/tj/commander.js/blob/master/examples/nestedCommands.js

(I started with the coverage of the new nested commands fairly minimal in the README to see how things go, whether it is an advanced usage or a common case.)

**Comment by shadowspawn** [comment]
Wanting for possible confusion, typo in example: I just noticed a `tea` command gets added twice! The second one is meant to be coffee...

**Comment by krazyjakee** [comment]
@shadowspawn thanks for the help! 💯
