### ISSUE TITLE
Can I immitate this command with Commander.js?

### ISSUE THREAD

**Issue by ffMathy** [tj/commander.js#1223]
Look at https://docs.docker.com/compose/reference/overview/

More specifically:

> Usage:
>   docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
>   docker-compose -h|--help
> 
> Options:
>   -f, --file FILE             Specify an alternate compose file
>                               (default: docker-compose.yml)
>   -p, --project-name NAME     Specify an alternate project name
>                               (default: directory name)
>   --verbose                   Show more output
>   --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
>   --no-ansi                   Do not print ANSI control characters
>   -v, --version               Print version and exit
>   -H, --host HOST             Daemon socket to connect to
> 
>   --tls                       Use TLS; implied by --tlsverify
>   --tlscacert CA_PATH         Trust certs signed only by this CA
>   --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
>   --tlskey TLS_KEY_PATH       Path to TLS key file
>   --tlsverify                 Use TLS and verify the remote
>   --skip-hostname-check       Don't check the daemon's hostname against the
>                               name specified in the client certificate
>   --project-directory PATH    Specify an alternate working directory
>                               (default: the path of the Compose file)
>   --compatibility             If set, Compose will attempt to convert deploy
>                               keys in v3 files to their non-Swarm equivalent
> 
> Commands:
>   build              Build or rebuild services
>   bundle             Generate a Docker bundle from the Compose file
>   config             Validate and view the Compose file
>   create             Create services
>   down               Stop and remove containers, networks, images, and volumes
>   events             Receive real time events from containers
>   exec               Execute a command in a running container
>   help               Get help on a command
>   images             List images
>   kill               Kill containers
>   logs               View output from containers
>   pause              Pause services
>   port               Print the public port for a port binding
>   ps                 List containers
>   pull               Pull service images
>   push               Push service images
>   restart            Restart services
>   rm                 Remove stopped containers
>   run                Run a one-off command
>   scale              Set number of containers for a service
>   start              Start services
>   stop               Stop services
>   top                Display the running processes
>   unpause            Unpause services
>   up                 Create and start containers
>   version            Show the Docker-Compose version information

Can I immitate that form of command structure with Commander.js? If not, what is the closest I can get to it?

**Comment by shadowspawn** [comment]
Global options. Commands. Yes.

Was there something in particular you were interested in?

There is not support for automatically tying together options, like "Use TLS; implied by --tlsverify", but you can of course handle that in code yourself.

**Comment by ffMathy** [comment]
What about the syntax for those options?

**Comment by shadowspawn** [comment]
Short flags. Long flags. Boolean flags. Options with a value. Default values. Yes.

Was there something in particular you were interested in?

There is not build-in support for validating an option comes from a subset of values (`--log-level`), but can be added yourself with a few lines of code.

**Comment by shadowspawn** [comment]
(Asked same question on yargs: https://github.com/yargs/yargs/issues/1593 )

**Comment by shadowspawn** [comment]
Can reopen if there is further interest, but this question is currently so broad that not worthwhile keeping open to help others.
