### ISSUE TITLE
program with async action never ends in v 5.0.0

### ISSUE THREAD

**Issue by davojan** [tj/commander.js#1224]
```typescript
#!/usr/bin/env node

import { program } from 'commander'

program
  .name('sync-accounts')
  .arguments('[authIds...]')
  .option('-A, --all', 'synchronize all accounts')
  .action(async (authIds, commandObj) => {
    return Promise.resolve()
  })
  .parseAsync()
  .then(() => /*process.exit(0)*/)
  .catch(err => {
    console.error('command failed', err)
    //process.exit(1)
  })
```

When I call: ``node cli.js 1234``, action works as expected, but command never finishes without commented ``process.exit``

**Comment by shadowspawn** [comment]
I was not able to reproduce your problem with this example, the program terminated normally. Perhaps you have some other dangling promise in your real program?

(I also need to change the import to a require to work with node 12 with default behaviour.)

**Comment by davojan** [comment]
@shadowspawn I'm sorry, you are right, this is definitely dangling promise in my program.
The import works fine with my typescript setup, not sure about pure js though.
Thanks for your time!
