### ISSUE TITLE
Is it right that Commander exits with exit code 1 on default command that prints help?

### ISSUE THREAD

**Issue by prokopsimek** [tj/commander.js#1228]
Upgrading Commander to v5 causes exit code 1 on default command that prints help.

Previous v4 behavior:
```
$ bin/run --help
       ## prints HELP message
$ echo $?
0
$ bin/run
       ## prints HELP message
$ echo $?
0  ## EXIT CODE 0
```

v5 behavior:
```
$ bin/run --help
       ## prints HELP message
$ echo $?
0
$ bin/run
       ## prints HELP message
$ echo $?
1  ## EXIT CODE 1
```

See changes: https://github.com/DXHeroes/dx-scanner/pull/275

The previous implementation of `outputHelp();` exited with code `0` and v5 exits by default with exit code `1`.

Now it causes CI failures.

Src how to get exit code of command: https://www.cyberciti.biz/faq/bash-get-exit-code-of-command/

**Comment by shadowspawn** [comment]
Short version: yes, as intended.

Long version

In Commander v5, the help is displayed if the subcommand is "missing" on the command line, and exits with exit code 1. This case isn't treated like a "default command", but more as a helpful error message.

The exit status for this case is a common behaviour:

```
$ npm
... # help displayed
$ echo $?
1

$ git
... # help displayed
$ echo $?
1
```

You were previously calling `.outputHelp()` yourself when you were using Commander v4, it was not being called by Commander itself:

```
    if (!process.argv.slice(2).length) {		
       cmder.outputHelp();		
     }
```

`outputHelp()` still displays the help and does not exit the program in Commander v5, that has not changed.

**Comment by prokopsimek** [comment]
@shadowspawn Ok, thank you. 👍 🙂
