### ISSUE TITLE
usage and description display order

### ISSUE THREAD

**Issue by tdjastrzebski** [tj/commander.js#1234]
Although it makes perfect sense to display **usage** and then **description** on command help, it may make more sense to display **description** first and then **usage** on program help. Otherwise default help output looks like:
```
Usage: MyProgram MyCommand

MyProgram is a super demo program (description)

Options:
--version
--myoption, -m   demo option
```
Desired order:
```
MyProgram is a super demo program (description)

Usage: MyProgram MyCommand

Options:
--version
--myoption, -m   demo option
```

**Comment by shadowspawn** [comment]
I do not think we are likely to make this change on its own. I have collected help related issues into #1225, and added this. One way of achieving what you suggest might be with a "prefix/banner" which has come up a few times.

**Comment by shadowspawn** [comment]
No further activity in a month. Added to #1225. Closing as (partially) covered by that collection.

Thank you  for your contributions.
