### ISSUE TITLE
Prompting user input

### ISSUE THREAD

**Issue by ianengelbrecht** [tj/commander.js#1238]
It seems co and co-prompt are the packages of choice for user input, using generators and yield to get that input. They both seem outdated though with widespread use of async/await. Is there a recommended async/await package for use with commander now?

**Comment by shadowspawn** [comment]
I have personally used Inquirer, but I don't have a recommended package as such.

**Comment by shadowspawn** [comment]
No further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
