### ISSUE TITLE
How to catch exceptions in subcommands?

### ISSUE THREAD

**Issue by kaysonwu** [tj/commander.js#1239]
I don't seem to have a way to catch the exception of the child process. It mainly comes from errors in `Promise`.

**Comment by shadowspawn** [comment]
The default behaviour is to call `process.exit()` when the child process terminates. Have a look at `.exitOverride()` to do more. It happens asynchronously, so not easy to handle:

- https://github.com/tj/commander.js#override-exit-handling

**Comment by kaysonwu** [comment]
`exitOverride` No effect. Through the `process.on('unhandledRejection')` event in the subcommand, you can catch the error from the Promise. 

Usually this kind of error is known, just for a more friendly prompt, so if it can be captured and handled in the main command, that would be great!

**Comment by kaysonwu** [comment]
I tried private properties and methods and there is no good solution, close it first
