### ISSUE TITLE
CommandError ignores program.name() 

### ISSUE THREAD

**Issue by sseaman** [tj/commander.js#1240]
If you set the name of your app via program.name() it is not used when an error occurs due to line 86 (https://github.com/tj/commander.js/blob/master/index.js#L86) which sets the name to this.constructor.name

**Comment by shadowspawn** [comment]
That line is setting the name of the custom error class, and is not related to the program name. See for example the same code pattern in:

https://javascript.info/custom-errors

```
class MyError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
  }
}
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
