### ISSUE TITLE
Overriding exit handling still messages to console

### ISSUE THREAD

**Issue by sseaman** [tj/commander.js#1241]
If you override the exit handling via program.exitOverride() you still get console messages due to all the console.log()s starting at line https://github.com/tj/commander.js/blob/master/index.js#L1097.

**Comment by shadowspawn** [comment]
Yes, `.exitOverride()` allows you to override just the `exit` part of the handling, and does not give you full control over the error handling.

There isn't currently support for suppressing or customising the error related console messages.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Adding support for overriding messages to console in #1387
