### ISSUE TITLE
How do I get a list of all parsed arguments?

### ISSUE THREAD

**Issue by raineorshine** [tj/commander.js#1244]
How do I get an array or object of all parsed arguments? I want to print them out with their values for debugging.

I searched for "all arguments" and "all options" in existing issues and did not see an answer.

```js
const program = require('commander')
program
  .option('--foo <x>', 'Do something')
  .option('--bar <y>', 'Do something else')
  ...

program.parse(process.argv)
```

`program` itself has a lot of extra properties that I do not want to print out. All of the examples suggest accessing individual properties with `program.foo`, but I have dozens of `options` passed in, and do not want to explicitly reference each one to print them out.

```sh
mycli --foo one --bar two
```

How do I get the following without referencing each argument by name:

```js
{
  foo: 'one',
  bar: 'two',
}
```

**Comment by shadowspawn** [comment]
Use `program.opts()`, which returns an object with the options and their values.

(It isn't currently covered explicitly in the README, but appears in a few examples.)

**Comment by raineorshine** [comment]
Thank you!
