### ISSUE TITLE
[feature] type safety for program options in TypeScript

### ISSUE THREAD

**Issue by trusktr** [tj/commander.js#1245]
At the moment, any properties on `program` after calling `program.parse(process.argv)` are typed as `any`, leaving much to be desired for TypeScript users.

I'm not sure what the solution would be, but it'd be nice to have more type information when handling options after they've been parsed.

As an example, imagine one option accepts a JSON string that must have certain properties, and when handling the parsed object in TypeScript we'd see the types for all the properties in the object.

**Comment by shadowspawn** [comment]
I am not sure how it could be integrated into Commander, but you can do it yourself:

```
interface MyOptions {
    size?: "small" | "big";
    type?: string;
}

const opts: MyOptions = program.opts();
```

**Comment by shadowspawn** [comment]
No further activity in a few months.  It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by Snaptags** [comment]
Nice workaround, thanks for pointing this out!
