### ISSUE TITLE
Possible inconsistency in reported unknown option

### ISSUE THREAD

**Issue by gkarlos** [tj/commander.js#1246]
When the value of a registered option is prefix to an unknown option, the error message seems to trim the value from the passed option. Example:

```js
const { program } = require('commander');
program.option('-s, --silent', "Hide all output")
```
Invoking with `npm start -- -stuff` outputs `error: unknown option '-tuff'`

Is this the indented behavior or a bug? 

I suppose the relevant code is this : https://github.com/tj/commander.js/blob/ebc8b41c9c713ab059a10547d11dfe2ab5f71855/index.js#L1028-L1042

**Comment by shadowspawn** [comment]
Not a bug as such. Commander sees the valid short flag, and tries to interpret the remaining text as further flags which does not work. Complaining about `-tuff` is more a side affect of where the parsing got up to than a carefully considered error message. Here is a program where that is a valid incantation:

```
const { program } = require('commander');
program.option('-s, --silent <value>', "Hide all output")
program.parse();
console.log(program.opts());
```

```
% node index.js -stuff
{ silent: 'tuff' }
```

(Before Commander v5 this would have been expanded to `-s -t -u -f -f` and complained about the unrecognised `-t`.)

**Comment by gkarlos** [comment]
I see. I think an error message about `-stuff` as a whole is what i would expect. But that would require more sophisticated parsing i guess.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. A better error message would be nice, but perhaps the situation is rare enough and an error is reported, that may not be worth the complications to the parsing code.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

Thank you  for your contributions.
