### ISSUE TITLE
No warning when incorrect options are passed with changed parameters order

### ISSUE THREAD

**Issue by GoalSmashers** [tj/commander.js#125]
Let's take the following code (assume file is named demo.js).

```
#!/usr/bin/env node

var commands = require('commander');

commands
  .option('-t, --test <value>', 'Just testing')
  .parse(process.argv);
```

Let's try to run it:
`./demo.js --test 5` - no errors
`./demo.js --test 5 demo.js` - no errors
`./demo.js --test 5 --test2 demo.js` - unknown option '--test2'
`./demo.js demo.js --test 5 --test2` - no errors

Apparently extra arguments where added at the beginning suppress errors.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
