### ISSUE TITLE
Handling of "--version" program option is buggy

### ISSUE THREAD

**Issue by khitrenovich** [tj/commander.js#1252]
Program option `-v`/`--version` is not supported in reliable way.

Consider the following sample program:
```
const app = require('commander');

app
  .option('-v, --version [id]', 'version identifier to use (optional)')
  .action((options) => {
    console.log(options.version);
  });

app.parse(process.argv);
```

This will be the output - 
```
~/work/commander-test > node app.js --version 42
42
~/work/commander-test > node app.js 
[Function: version]
~/work/commander-test > 
```

Note that `options.version` is always defined, even if not provided, defaulting to a function (my guess that it is https://github.com/tj/commander.js/tree/v5.0.0#version-option). 

Side effect of the above is that I cannot mark `-v` option as required - it does not error out, since it is always implicitly defined.

**Comment by shadowspawn** [comment]
Clashing option names with properties on the Command object is a problem, with collected issues in #933

The good news is there is a solution now! See `.storeOptionsAsProperties(false)` and the section in the README:

https://github.com/tj/commander.js#avoiding-option-name-clashes

**Comment by khitrenovich** [comment]
Thank you, this solves the problem for me!

**Comment by shadowspawn** [comment]
Opened a PR to add a warning for option name clashes: #1275
