### ISSUE TITLE
Cannot take options with more than one value

### ISSUE THREAD

**Issue by radio-miskovice** [tj/commander.js#1254]
I have a situation when the app is supposed to filter some data based on date (mandatory) and time (optional).

My desired option definition would be:

`program.option( '-a, --all-after <date> [time]', 'Copy all items dated after <date> and after <time> if specified (defaults to 23:59)')`

Currently I can have only one value. I can hack this, but having two values, one mandatory and the other one optional, would be more useful. This is not the same as array of repeatable values, as each value has different meaning and maximum is two.

**Comment by shadowspawn** [comment]
Related older issues: #175 #674

**Comment by shadowspawn** [comment]
The suggested syntax does fit in with the command-arguments which is a plus, as sometimes working out how to express the intent is the hard part! However, specifying default values and custom parsing and storing the values are all complications. None of these are offered for command-arguments.

Some other packages allow specifying how many arguments should be consumed as option-arguments, which is similar but different:
- https://docs.python.org/2.7/library/argparse.html#nargs

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
