### ISSUE TITLE
Help vs Version short flags

### ISSUE THREAD

**Issue by gavinr** [tj/commander.js#1258]
- the [default short flag for help is `-h`](https://github.com/tj/commander.js/blob/64053252cbd5b5434afb7ec3f12c46ad2a352d8a/index.js#L125) (lower-case)
- the [default short flag for version is `-V`](https://github.com/tj/commander.js/blob/64053252cbd5b5434afb7ec3f12c46ad2a352d8a/index.js#L1187) (upper case)

Is there a reason these are not consistently both upper- or both lower-case?

**Comment by shadowspawn** [comment]
Lowercase `-v` is quite used for verbose or other application flags, so some applications choose to use `-V` for version to leave it available. `-h` is the most common short flag for help.

Related: #509 https://github.com/tj/commander.js/issues/1182#issuecomment-583796433

Verbose: https://www.tldp.org/LDP/abs/html/standard-options.html

**Comment by gavinr** [comment]
👍 thank you for the explanation!
