### ISSUE TITLE
Option flag doesn't works when running commander from script using NPM

### ISSUE THREAD

**Issue by shahafa** [tj/commander.js#1262]
Hi,

I'm following the pizza example in the documentation

**index.js**
```
const { program } = require('commander');

program
  .option('-d, --debug', 'output extra debugging')
  .option('-s, --small', 'small pizza size')
  .option('-p, --pizza-type <type>', 'flavour of pizza');

program.parse(process.argv);

if (program.debug) console.log(program.opts());
console.log('pizza details:');
if (program.small) console.log('- small pizza size');
if (program.pizzaType) console.log(`- ${program.pizzaType}`);
```

**package.json**
```
{
  "name": "test",
  "scripts": {
    "start": "node index.js",
  },
  "dependencies": {
    "commander": "^5.1.0"
  }
}
```

when I'm running `yarn start -p cheese` everything works as expected and the console prints
```
pizza details:
- cheese
```

however when I'm running `npm run start -p cheese` the pizza type flag is missing, the console prints
```
pizza details:
```

**Comment by shadowspawn** [comment]
Short version: try `npm run start -- -p cheese`

Long version

npm is still looking for options and gobbles the `-p` so it does not get passed along to node and your program. Like Commander, npm supports the convention to stop looking for options after seeing a `--` in the arguments.

https://docs.npmjs.com/cli/run-script

A good debugging check when you have commands chained together like this is to dump out the arguments that reached your program:

```js
console.log(process.argv);
```

**Comment by shahafa** [comment]
Thanks, @shadowspawn!
