### ISSUE TITLE
RequiredOption is undefined, when no value is passed to the command

### ISSUE THREAD

**Issue by benwinding** [tj/commander.js#1265]
I'm getting an issue where a `requiredOption` is undefined, when no value is passed to the command.

### Code
``` js
program
  .command('build')
  .requiredOption('-c, --config', 'Configuration Name')
  .action(async function (env, options) {
// options is undefined
  });
```
### Args
``` sh
$ ./mycommander build -c
```
### Result
options is undefined
![image](https://user-images.githubusercontent.com/11782590/82826638-acfdb500-9eec-11ea-9c4f-6a9c88271cda.png)

### Expected
I would expect `requiredOption` to be an option that enforces a value, not just the flag to be present

**Also related:** #230

Ps: Love the library, it's pretty nice to work with :+1:

**Comment by shadowspawn** [comment]
1) Your build command does declare any arguments, so the first parameter passed to the action handler will be the options.

```js
program
   .command('build')
   // ...
   .action(async function (options)
```

From the README (https://github.com/tj/commander.js#action-handler-subcommands):

> The action handler gets passed a parameter for each argument you declared, and one additional argument which is the command object itself. This command argument has the values for the command-specific options added as properties.

2) From its description, it sounds like your option expect a value. This might just be a typo in your example, but in case it causes confusion:

```js
.requiredOption('-c, --config <name>', 'Configuration Name')
```

**Comment by benwinding** [comment]
Ahh I see now, works as expected.

Thanks @shadowspawn!
