### ISSUE TITLE
Question: Is it possible to have a splash screen?

### ISSUE THREAD

**Issue by Thanzex** [tj/commander.js#1272]
Hi there! I've been trying to make a nice ASCII art splash screen for my CLI. I'd like it to be displayed when the program is called without arguments or commands and to be displayed before the help information.

I've tried with a hidden default command, but then it's name shows up in the usage and the help is relative to the command.
Is there any clean way to do it?

**Comment by shadowspawn** [comment]
It is easy to display a banner for no arguments by checking arguments before calling Commander, but not currently clean support for including the banner in normal help. Currently being discussed.

Related: 
- https://github.com/tj/commander.js/issues/1225#issuecomment-602005009
- https://github.com/tj/commander.js/pull/1267

**Comment by shadowspawn** [comment]
To give an example for my comment:

> It is easy to display a banner for no arguments by checking arguments before calling Commander

```
const { program } = require('commander');

// Configure program
program
   .option('-d,--debug');

// Test for no arguments before calling parse
if (process.argv.length <= 2) {
    console.log('ASCII ART');
    program.help(); // exits
}

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
Closing this as answered and/or covered by #1225

**Comment by shadowspawn** [comment]
See `.addHelpText()` in Commander 7.0.0.
