### ISSUE TITLE
program property undefined

### ISSUE THREAD

**Issue by KyleMit** [tj/commander.js#1273]
According to the docs, I should be able to access commander via `program` like this:

```js
const { program } = require('commander');
```

However that destructuring leaves the program variable undefined because it can't be found on `require('commander')`

### Steps to reproduce:

```bash
npm init -y
npm install commander --save
```

**File**: `test.js`

```js
const { program } = require('commander');
console.log(program)
```

```bash
node test.js
```

Has there been a change in the API?

![node test.js](https://user-images.githubusercontent.com/4307307/83557676-0f077d00-a4e0-11ea-8d1c-45240e56ad41.png)

![require('commander') watch](https://user-images.githubusercontent.com/4307307/83557404-96a0bc00-a4df-11ea-9ebf-9b27bd500025.png)

```bash
node -v  # v12.9.0
npm list # commander@4.1.1
```

**Comment by shadowspawn** [comment]
The program property got added in Commander v5: https://github.com/tj/commander.js/releases/tag/v5.0.0

But you have 4.1.1 installed for some reason. Try:
```
npm install commander@latest
```

I am guessing you accidentally ran your test steps in an existing package which already had an older version of Commander installed.

**Comment by KyleMit** [comment]
oh, thank you... this was installed in a brand new project, but realized I had [**`prefer-offline=true`**](https://docs.npmjs.com/misc/config#prefer-offline) set in my `.npmrc`.  While I'm new to commander, I must've used a library that used 4.1.1 so it considered that as my `@latest` build.  When I took away prefer offline, 5.1.0 lists as the latest build.  

Thanks for your time 👍
