### ISSUE TITLE
Variable action parameters makes really hard to create a generic action handler.

### ISSUE THREAD

**Issue by mshima** [tj/commander.js#1277]
When implementing a program with options and actions that are created at runtime, its really hard to create generic action handlers.

See:
https://github.com/jhipster/generator-jhipster/blob/b24652dc0382ebc3219da0c13add9b65b3d2a1dc/cli/cli.js#L95-L134

Would be really nice to have an option to receive a object like `{args, options, unknown, command}` instead of an array.

Would be nice to add options as an object `{name, description, defaultValue}` instead of `name, description, defaultValue` too.

**Comment by shadowspawn** [comment]
> Would be nice to add options as an object {name, description, defaultValue} instead of name, description, defaultValue too.

Comment heard, but add a separate issue if you would like some visibility and opportunity for community interest on that. Off topic for the title of this issue. 🙂

**Comment by shadowspawn** [comment]
Related past issue: #1055

**Comment by shadowspawn** [comment]
With current behaviour, I had a go at repackaging the action parameters for more generic processing:

```js
const { program } = require('commander');

program
  .arguments('<name>')
  .option('-e,--example')
  .action((...everything) => {
    const last = everything.pop();
    let extraArgs;
    let cmd;
    if (Array.isArray(last)) {
      extraArgs = last;
      cmd = everything.pop();
    } else {
      cmd = last;
    }
    const options = cmd.opts();
    const args = everything;

    console.log('args: ', args);
    console.log('options: ', options);
    console.log('extraArgs: ', extraArgs);
  });

program.parse();
```

```
$ node index.js -e foo  
args:  [ 'foo' ]
options:  { example: true }
extraArgs:  undefined
$ node index.js -e foo bar
args:  [ 'foo' ]
options:  { example: true }
extraArgs:  [ 'bar' ]
```

**Comment by mshima** [comment]
Looks much better but I have to deal with unknown args too.
```
const { program } = require('commander');

program
  .allowUnknownOption(true)
  .arguments('[first]')
  .arguments('[name...]')
  .option('-e,--example')
  .action((...everything) => {
    const last = everything.pop();
    let extraArgs = [];
    let cmd;
    if (Array.isArray(last)) {
      extraArgs = last || [];
      cmd = everything.pop();
    } else {
      cmd = last;
    }

    // move unknown options back to extraArgs
    const splitUnknown = argsToSplit => {
      const args = [];
      const unknown = [];
      argsToSplit.find((item, index) => {
        if (item === undefined) {
          return;
        }
        if (item.startsWith('-')) {
          unknown.push(...argsToSplit.slice(index))
          args.push(...argsToSplit.slice(0, index));
          return true;
        } else {
          args.push(item);
        }
      });
      return [args, unknown];
    }
    const options = cmd.opts();
    let variadicArg = everything.pop();

    const splitted = splitUnknown(everything);
    const args = splitted[0];
    extraArgs.push(...splitted[1]);

    if (variadicArg) {
      if (Array.isArray(variadicArg)) {
        const splittedVariadic = splitUnknown(variadicArg);
        args.push(splittedVariadic[0]);
        extraArgs.push(...splittedVariadic[1]);
      } else {
        args.push(variadicArg);
      }
    }

    console.log('args: ', args);
    console.log('options: ', options);
    console.log('extraArgs: ', extraArgs);
  });

program.parse();
```

**Comment by shadowspawn** [comment]
You can get access to the command (and options) in the listener by using a function and not just an arrow function: https://nodejs.org/api/events.html#events_passing_arguments_and_this_to_listeners

The listener gets passed the args split into "operands" and "unknown". (There are only operands unless you `allowUnknownOption`.) 

For example:

```js
const { program } = require('commander');

program
  .command('sub')
  .allowUnknownOption()
  .arguments('<name>')
  .option('-e,--example')
  .action(() => { })
  .on('command:sub', function (operands, unknown) {
    const cmd = this;
    const opts = cmd.opts();
    console.log('operands: ', operands);
    console.log('unknown: ', unknown);
    console.log('opts: ', opts);
  });

program.parse();
```

```bash
$ node demo.js sub alpha -e beta --unknown gamma
operands:  [ 'alpha', 'beta' ]
unknown:  [ '--unknown', 'gamma' ]
opts:  { example: true }
```

**Comment by mshima** [comment]
> The listener gets passed the args split into "operands" and "unknown". (There are only operands unless you `allowUnknownOption`.)

This approach doesn't applies arguments processing including variadic arguments to operands and can't return a promise.

There 3 approaches for unknown options:
1 - No operand (unknown included) processing (listener approach)
2 - No unknown processing
3 - Unknown as argument guessing (action approach)

I want the approach 2, that puts arguments in place (variadic included) but keep unknown untouched.

The example I posted uses plugin options, but the details is not right yet so I am falling back to old options processing.
Once the plugin options details are resolved I will remove allowUnknownOption.
So I will go with https://github.com/tj/commander.js/issues/1277#issuecomment-641954431 implementation.

This unknown discussion is related to https://github.com/tj/commander.js/issues/1278 and probably should be discussed there.

This feature request is to avoid having to implement https://github.com/tj/commander.js/issues/1277#issuecomment-641872980 workaround

By passing an object to action should allow passing something like `{ arguments, options, unknown, operands, guessedArguments }` and give a great flexibility for those who are migrating to commander.

**Comment by shadowspawn** [comment]
The parsing becomes ambiguous as soon as there are unknown options. Does the unknown option take an argument, or not? In general, the parser does not know. Before Commander v5 it was assumed all unknown options took an argument, and that led to some bad parsing. The approach Commander v5 takes is not to disturb the argument order when there are unknowns so that the remaining arguments are still in the original order and can be passed to whatever further processing is going to be done.

Running the example code from your comment:

```shell
$ node example.js --unknown first second third               
args:  [ [ 'first', 'second', 'third' ] ]
options:  { example: undefined }
extraArgs:  [ '--unknown' ]
```

How do you know that it should not be:

```
args:  [ [ 'second', 'third' ] ]
options:  { example: undefined }
extraArgs:  [ '--unknown', 'first' ]

```

If you tighten the usage on the command line you could remove some ambiguity. For example, you could require all options to specify their values in the same argument. e.g. `--unknown=4` or `-p80`.)

**Comment by mshima** [comment]
> Running the example code from your comment:
> 
> ```shell
> $ node example.js --unknown first second third               
> args:  [ [ 'first', 'second', 'third' ] ]
> options:  { example: undefined }
> extraArgs:  [ '--unknown' ]
> ```

Considering:
```
program
  .allowUnknownOption(true)
  .arguments('<arg>')
  .arguments('<files...>')
  ...
```

I need
```shell
$ node first *.txt example.js --unknown second third
args:  [ 'first', [ 'a.txt', 'b.txt' ] ]
options:  { example: undefined }
extraArgs:  [ '--unknown', 'second', 'third' ]
```

Action gives me:
```shell
$ node first *.txt example.js --unknown second third
args:  [ 'first', ['a.txt', 'b.txt', '--unknown', 'second', 'third' ] ]
options:  { example: undefined }
extraArgs:  [ ]
```

Event gives me:
```shell
$ node first *.txt example.js --unknown second third
args:  [ 'first', 'a.txt', 'b.txt' ]
options:  { example: undefined }
extraArgs:  [ '--unknown', 'second', 'third' ]
```

**Comment by shadowspawn** [comment]
(I think you missed `example.js` in your example output.)

**Comment by shadowspawn** [comment]
Thanks for the example output. Helpful contrasting the action handler and listener and what you want.

I think the treatment of the unknown arguments you want is a bit too specific to add to Commander.

I'm happy to leave this issue open though to see whether it generates further interest or insights.

**Comment by shadowspawn** [comment]
I missed describing one other fairly direct approach for a generic action handler, with easy access to args and opts. The action handler is called with `this` set to the command. (This does not offer any assistance with unknowns.)

```js
const { program } = require('commander');

function common() {
  console.log('args: %o', this.args);
  console.log('opts: %o', this.opts());
}

program.command('zero')
  .option('-z, --zero')
  .action(common);

program.command('one')
  .option('-o, --one')
  .arguments('<file>')
  .action(common);

program.command('two')
  .option('-t, --two')
  .arguments('<source> <dest>')
  .action(common);

program.parse();
```

```
% node named.js zero -z 1 2 3
args: [ '1', '2', '3', [length]: 3 ]
opts: { zero: true }
% node named.js one -o 1 2 3 
args: [ '1', '2', '3', [length]: 3 ]
opts: { one: true }
% node named.js two -t 1 2 3 
args: [ '1', '2', '3', [length]: 3 ]
opts: { two: true }
```

**Comment by mshima** [comment]
@shadowspawn thanks.
The most problematic is indeed unknown, I am moving away from it.
One suggestion is to set every possible handling to the Command.
```
args:  [ 'first', ['a.txt', 'b.txt', '--unknown', 'second', 'third' ] ]
options:  { example: undefined }
confirmedArgs:  [ 'first', [ 'a.txt', 'b.txt' ] ]
extraArgs:  [ '--unknown', 'second', 'third' ]
```
Since unknown args is really complicated and not used often, I am closing this.
