### ISSUE TITLE
Typing "help [command]" causes exiting without any error

### ISSUE THREAD

**Issue by ltccss** [tj/commander.js#1279]
Even though I set "program.exitOverride()" in the script,

version:5.1.0

**Comment by shadowspawn** [comment]
Can you show us some code?

**Comment by ltccss** [comment]
here is the code →.→  @shadowspawn 

`const { program } = require('commander');

program
    .command('make.test')
    .description('for test')
    .action(() => {
        console.log("test");
    });

    let fs = require('fs')
    let tips = ">>>"
    console.log("type 'help' to get more info\n");

    program.exitOverride();

    async function loopFunc()
    {
        while (true)
        {
            process.stdout.write(tips);
            process.stdin.pause();

            const buf = Buffer.allocUnsafe(10000);
            let buffSize = fs.readSync(process.stdin.fd, buf, 0, 10000, 0);
            process.stdin.end();

            let inputText = buf.toString('utf8', 0, buffSize).trim();
            if (inputText == "exit")
            {
                break;
            }
            // console.log(inputText);
            let params = inputText.split(' ');

            try
            {
                await program.parseAsync(params, { from: 'user' });
            }
            catch (err)
            {
                if (err.code != "commander.help" && err.code != "commander.missingArgument")
                {
                    console.log(err);
                    break;
                }
                
            }
        }
    }
    loopFunc();


`

**Comment by shadowspawn** [comment]
Thanks for example. A quick potential fix (I have not run code to confirm): try shifting the `program.exitOverride();` to before calling `program.command`.

When you call `help [command]` then it is the subcommand that display the help.

The effects of calling `exitOverride()` are passed on to commands that are added _after_ it is set. 

(I have been wondering if I need to document the "inherited" behaviours so there are some clues in the documentation.)

**Comment by ltccss** [comment]
I've tried putting "program.exitOverride()" before "program.command...", but seemingly it does nothing... :(

**Comment by shadowspawn** [comment]
I got an error when I tried running that code:

```
Error: ENXIO: no such device or address, read
```

and quite a lot going on with the async too, so will simplify down program to focus on the exit/help issue.

**Comment by shadowspawn** [comment]
Simplified program:

```js
const { program } = require('commander');

program.exitOverride();

program
  .command('make.test')
  .description('for test')
  .action(() => {
    console.log("test");
  });

try {
  program.parse();
} catch (err) {
  console.log(`Caught error code: ${err.code}`);
}
```

```shell
$ node index.js --help        
Usage: index [options] [command]

Options:
  -h, --help      display help for command

Commands:
  make.test       for test
  help [command]  display help for command
Caught error code: commander.helpDisplayed

$ node index.js help make.test
Usage: index make.test [options]

for test

Options:
  -h, --help  display help for command
Caught error code: commander.helpDisplayed

$ node index.js               
Usage: index [options] [command]

Options:
  -h, --help      display help for command

Commands:
  make.test       for test
  help [command]  display help for command
Caught error code: commander.help
```

Note that there are two different codes.

**Comment by shadowspawn** [comment]
Also, much safer to create a new command each time through the loop. Otherwise left-over state from a previous parse could affect the results.

**Comment by ltccss** [comment]
After some more tests, I finally found your guest is right, the "program.exitOverride()" should be put ahead, and at the same time,  the catch part should also be changed as 
```js
catch (err)
{
    console.log(`Caught error code: ${err.code}`);
    // both commander.help and commander.helpDisplayed need to be considered
    if (err.code != "commander.help" && err.code != "commander.missingArgument" && err.code != "commander.helpDisplayed")
    {
        console.log(err);
        break;
    }
    
}
```
LOL

**Comment by shadowspawn** [comment]
Glad you worked it out, thanks for confirming.
