### ISSUE TITLE
Make Commander localization capable

### ISSUE THREAD

**Issue by mkxml** [tj/commander.js#128]
We could add the option of getting the users language to localize commander, for example we could use the process.env.LANG to set the language for the commander default text.

Today some Node.JS apps use this approach on top of commander, so everything is shown in the users language except for the commander strings.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Anyone following this issue is likely to be interested in #1801
