### ISSUE TITLE
Add esm

### ISSUE THREAD

**Issue by xiaoxiangmoe** [tj/commander.js#1284]
https://nodejs.org/api/esm.html#esm_conditional_exports

Add support for esm. 

If you think this proposal is reasonable, I'll create a PR for this.

**Comment by shadowspawn** [comment]
What is the problem you want to solve? The ability to "import" Commander from code written as ES module?

While I am interested in the esm progress and how Commander might support esm, I don't think we would make it a default behaviour yet as the Node 14 version of the linked page lists this as "Stability: 1 - Experimental".

> Stability: 1 - Experimental. The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release. Use of the feature is not recommended in production environments.

Related: #950

**Comment by xiaoxiangmoe** [comment]
In the current situation
```js
import { program } from 'commander';
```
This will report an error in mjs.

```js
import commander from 'commander';
const {program} = commander; // Here commander and program are the same object
```
But this will perform well.

Should we encourage everyone to use default import in mjs?

**Comment by shadowspawn** [comment]
Yes, for now. The "default export" can be used in the same way as can be done with require:

```
// const commander = require('commander'); // cjs
import commander from 'commander';

const globalProgram = commander.program;
const myProgram = new commander.Command();
```

Side note 1: the exported global `program` is currently mainly for style, as it is the same as the default export.

Side note 2: I had actually been wondering about this style for the README for cjs, but decided the destructuring assignment was more widely used. e.g. `const { program } = require...`

**Comment by shadowspawn** [comment]
I noticed instructions for esm and cjs here, I'll keep an eye out for more: https://github.com/uuidjs/uuid

**Comment by shadowspawn** [comment]
Opened PR to add to README: #1298

**Comment by shadowspawn** [comment]
README update released with Commander v6.0.0 : https://github.com/tj/commander.js/releases/tag/v6.0.0

I am interested in supporting esm more directly in future, when the support is stable.

**Comment by shadowspawn** [comment]
I came across a related PR and comments about the conditional pattern: https://github.com/tapjs/node-tap/pull/668#discussion_r414982540

**Comment by shadowspawn** [comment]
I was reading about esm again today and getting keen on adding a wrapper, when came across this reminder that using an experimental feature can have downsides. In this case end users getting a warning that (a dependent package) using experimental feature, until the warning gets removed:
https://github.com/nodejs/modules/issues/485#issuecomment-587246376

**Comment by shadowspawn** [comment]
I have opened #1440 to add named imports for esm by using a deep import. I read up on conditional imports again and still want to wait for them to be stable before including in Commander.
