### ISSUE TITLE
为什么我本地测试的结果--no-foo会覆盖事先定义的--foo

### ISSUE THREAD

**Issue by dandan-xu** [tj/commander.js#1287]
直接copy文档上的例子。本地测试结果如下：
--no-cheese和--cheese（有默认值），如果后定义--cheese，打印program.cheese，那么结果是默认值。如果后定义--no-cheese，打印program.cheese，那么结果是true
如果只设置了--cheese(无默认值)，执行node index pizza-options打印program.cheese，结果是undefined

**Comment by shadowspawn** [comment]
What is your code, and what are you trying?

```
const { program } = require('commander');

program
  .option('--cheese <flavour>', 'cheese flavour', 'mozzarella')
  .option('--no-cheese', 'plain with no cheese');
  
program.parse();

console.log(program.cheese);
```

``` 
% node index.js 
mozzarella
% node index.js --cheese blue
blue
% node index.js --no-cheese  
false
% node index.js --cheese blue --no-cheese
false
% node index.js --no-cheese --cheese=blue
blue
```

**Comment by dandan-xu** [comment]
sorry，I just now found the cause of the error。
my project's commander package version is 2.20.0 and resulting in incorrect default values。
when i update it，the result is corret。
Thank you for answering my childish question

**Comment by shadowspawn** [comment]
Glad you worked it out. Thanks for explaining.

There were good improvements to `--no` in #795, released in Commander v3.
