### ISSUE TITLE
Is there a way to integrate "commander" with "plop"?

### ISSUE THREAD

**Issue by flaviolsousa** [tj/commander.js#1288]
I really like the "commander" ... but it would be amazing to integrate it with "plop" ( https://www.npmjs.com/package/plop )

When we just type "cli", displays the help ... it would be interesting to display a "plop" of the available options.

Any tip?

**Comment by shadowspawn** [comment]
I don't know `plop`, but from reading the README it looks like it can be integrated into another program:

- https://github.com/plopjs/plop#wrapping-plop
- https://github.com/plopjs/plop#further-customization

**Comment by shadowspawn** [comment]
If you were thinking of using plop to generate your program, rather than your program generating some files using plop, a previous issue is: #920

**Comment by flaviolsousa** [comment]
Thank you... I will try:
https://github.com/plopjs/plop#wrapping-plop

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
