### ISSUE TITLE
List remain options

### ISSUE THREAD

**Issue by aurium** [tj/commander.js#129]
For some programs a file name or a list of files (or URLs, or packages) may be placed without parameter name on the end of the argv. Will be useful to catch it with commander.

Examples:

```
wget -c -O filename http://somewhere.abc/bigfile
youtube-dl -t http://youtbeurl1 http://youtbeurl2 http://youtbeurl3
```

**Comment by cades** [comment]
+1

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
