### ISSUE TITLE
Commander extensions & middlware

### ISSUE THREAD

**Issue by ad-m** [tj/commander.js#1292]
I see Commander as a full-fledged CLI framework.

In my Commander experience, the extension mechanism is missing to introduce the ability to pass specific information to the executed command, or to perform some additional operation before specifying the parameter to modify the context.

In this regard, it is worth noting the "toolbox" mechanism from Gluegun:

> Extensions are additional functionality that you can monkeypatch onto the `toolbox` object. They look something like this:
> 
> ```js
> // extensions/sayhello.js
> module.exports = toolbox => {
>   const { print } = toolbox
> 
>   toolbox.sayhello = () => {
>     print.info('Hello from an extension!')
>   }
> }
> ```
> 
> When you have this extension, you can access it in any command file, like this:
> 
> ```js
> // ...
> run: async toolbox => {
>   const { sayhello } = toolbox
> 
>   sayhello()
> 
>   // or
> 
>   toolbox.sayhello()
> }
> ```

In the same are there is plugins from `structured-cli`:

https://github.com/ggoodman/structured-cli/blob/94542bc0cdd15d93c0415bf637f4a103f78822e9/lib/index.js#L85-L110

Example plugin: 
https://github.com/hyperonecom/h1-cli/blob/master/bin/_plugins/outputFormat/index.js

For example, in the case of developing an API service, it can be used to verify that the user is correctly authenticated before executing the command. As well as for consistent output formatting.

**Comment by shadowspawn** [comment]
Related to the `structured-cli` plugin/middleware and with links to some older issues: #1197

**Comment by ad-m** [comment]
@shadowspawn , thank you for pointing that issue. I use different terms for that idea. Let's continue that discussion in #1197.
