### ISSUE TITLE
Usage Information is not getting populated correctly for stand-alone executables for subcommands

### ISSUE THREAD

**Issue by Naitik333** [tj/commander.js#1310]
Usage Information is not getting populated correctly for stand-alone executables for subcommands. 
for e.g. let's say I have "here" as the main command with node file "here.js" and "xyz" as a subcommand with its own executable file "here-xyz.js" than if we do help for subcommand than in help output usage is not getting populated correctly -
```
here xyz --help
Usage:  [options] [command]
```
also if we have more commands defined inside "xyz" than for them as well help is not getting populated correctly 
```
here xyz upload --help
Usage: here-xyz upload [options] [id]
```

**Comment by shadowspawn** [comment]
What are you referring to when you say "not getting populated correctly"? The name of the command in the usage line?

The help for the subcommand is generated by the subcommand. It is a stand-alone program and run using node as it has `.js` suffix. So I would expect to see the same results by calling:

```
here xyz --help
node here-xyz --help
```

```
here xyz upload --help
node here-xyz upload --help
```

You can customise the name displayed in the help by using the `.name()` routine.

**Comment by Naitik333** [comment]
> What are you referring to when you say "not getting populated correctly"? The name of the command in the usage line?
> 
> The help for the subcommand is generated by the subcommand. It is a stand-alone program and run using node as it has `.js` suffix. So I would expect to see the same results by calling:
> 
> ```
> here xyz --help
> node here-xyz --help
> ```
> 
> ```
> here xyz upload --help
> node here-xyz upload --help
> ```
> 
> You can customise the name displayed in the help by using the `.name()` routine.

Thanks for the quick reply. Yes, I am saying about the command name. I agree it's subcommand and internally it will work with node here-xyz --help. but as an end-user of CLI, I don't know about the internal mechanism and I want the correct usage command. so it should be 
`Usage: here xyz [options] [command]`
`Usage: here xyz upload [options] [id]`

I will check what can be done using .name() routine, Thanks for this info. I feel this will be kind of workaround fix and by default the library should populate the help correctly for subcommands as well.

**Comment by shadowspawn** [comment]
A reasonable expectation, especially these days. Commander has changed the `usage` for action-based subcommands to include the full command path, and `git` on which the stand-alone subcommands were modelled has gotten more integrated.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
