### ISSUE TITLE
Dynamically call a sub command - not working for top level

### ISSUE THREAD

**Issue by brettswift** [tj/commander.js#1317]
### Premise

In a git style cli: 

instead of a user doing: 
1. git -h 
   * get output
2. git  pull <opts>

I wanted a user to be prompted and select the sub command. 

### Subcommand solution

I have this working with inquirer but anything would work really. 

Flow:

1. The top command's action looks for a subcommand being requested via `cmd.args.length`.   
2. if empty, prompt, and return the string name of the function to a variable (`selectedSubCommandString`). 
3. `const foundCommand = this.command.commands.find((cmd) => cmd._name === selectedSubCommandString);`
4.  Be sneaky and call the hidden method directly: `foundCommand._actionHandler(fakeArgs)`

### Problem
This seems to work when your command is 2nd level and subcommand is 3rd level. (ie `git remote` would prompt for `rm` etc.)  However, when you try to do this when your command is the top level program, and your subcommands are 2nd level, it errors saying: 

`foundCommand._actionHandler is not a function`

I'm not super happy about calling a private function in the first place.   I'm wondering if there is/could be a more built in way of doing this that would also work at the top level?

Example code: 

```typescript


    const subCommandChoices = [
      { name: 'report', message: 'report', value: 'service' },
      { name: 'service', message: 'service', value: 'service' },
      { name: 'feedback', message: 'feedback', value: 'feedback' },
    ];

 private async callSubCommandDynamically(subCommandChoices: inquirer.ChoiceOptions[]) {
    const subCommand = await promptForSubCommand("Select:", subCommandChoices);
    const foundCommand = this.command.commands.find((cmd) => cmd._name === subCommand);

    if (foundCommand) {
      // all commands must support prompting for their options in this scenario. Passing in blank args to satisfy the commander API.
      const fakeArgs = [''];
      foundCommand._actionHandler(fakeArgs);
    }
    return subCommand;
  }
```

**Comment by shadowspawn** [comment]
Are the subcommands of the top level command implemented using action handlers, or stand-alone commands?

(There isn't much difference between the top-level command and the subcommands in contents.)

**Comment by jdmarshall** [comment]
I can't recall what problems I ran into, but I ended up having to exec a child process to get things to work. I don't think commander is designed to be reentrant.

**Comment by shadowspawn** [comment]
The `async` is a bit of a complication. A high level approach might be to call the parsing from the top with the additional argument from prompting, then Commander is working normally and you aren't trying to hook into the internal dispatching. The safest way of doing this is with a new copy of the top level command, as some state is left behind by parsing.

e.g. assuming one level of subcommands

```
    if (foundCommand) {
      const fakeArgs = [foundCommand.name()];
      await makeProgram().parseAsync(fakeArgs, from: "user");
    }

```

**Comment by shadowspawn** [comment]
No replies or further activity in a month.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
