### ISSUE TITLE
Breaking change related to short options in 6.0.0?

### ISSUE THREAD

**Issue by martinlevesque** [tj/commander.js#1318]
Hey,

Previously the following:

```
commander
    .command('logs')
    .option("-n <nb-lines>", "Number of lines")
    .description('Print logs')
    .action(async function(opts) {
      ....

```

The option n was populated in **opts.N** (note the capital letter), but now it is no more available opts.N but is now available in **opts.n**. Is it a bug or the correct new behaviour?

**Comment by shadowspawn** [comment]
Correct new behaviour. See #1249 #1256 

(I didn't call out this change specifically in the release notes, partly because I wasn't sure how many people were using short options.)

**Comment by martinlevesque** [comment]
Sounds good thanks. I think it's better with lower case with the new version, would have been better to have a breaking change line in the release note I think, thanks anyway.

**Comment by shadowspawn** [comment]
Add breaking note to CHANGELOG and Release Notes
