### ISSUE TITLE
Dynamic loading commands problem

### ISSUE THREAD

**Issue by eps90** [tj/commander.js#132]
Hi. In my application I tried to use commander for choosing script to run by reading list files in `commands` directory, so I created a loop which reads contents of that directory and in each iteration it performs `program.command` (where `var program = require('commander')`). Here's the loop:

``` javascript
var app_commands = this.loadCommands();
    for (var i = 0; i < app_commands.length; i++) {
        var app = app_commands[i];
        if(typeof app != 'undefined') {
            program
                .command(app.command)
                .description(app.description)
                .action(function() {
                    Console.info("Executing "+app.class_name);
                    var application_class = require(app.path);
                    var application = new application_class();
                    application.run()
                });
        }
    }
```

Well, after running application with `--help` option, it showsscripts correctly:

```
$ node app.js --help
Usage: app.js [options] [command]

  Commands:

    tester                 Blablablabla
    parser                Parse sth
```

Problem is that when I run `node app parser` it runs correct script (performs method `run()` on class `Parser`. But when I do `node app tester` it _also_ runs `Parser.run()`! I even did debugging - I put breakpoint inside `action` callback, but it runs only once - when `parser` command is passed. While being inside that callback, when I inspect `app.command` it has `parser` value. Am I doing something wrong? Should it be built in the other way? Thanks.

**Comment by abadraja** [comment]
Can you please show src of loadCommands() function?
