### ISSUE TITLE
Conveniency about parameter "argsDescription" in program.description()

### ISSUE THREAD

**Issue by ltccss** [tj/commander.js#1321]
In my case, some arguments of a command are not necessary to describe,  but currently I have to write all descriptions of them to avoid the null reference error.

I think it may be more pleasant to make a null check for "argsDescription[arg.name]" here?
https://github.com/tj/commander.js/blob/1b5ede83cee2b5bc7edbcdebde81f273095ebd8c/index.js#L1551

**Comment by shadowspawn** [comment]
Reasonable suggestion.

(This is the second ever issue opened for the undocumented `argsDescription` parameter to `.description()`!)

**Comment by shadowspawn** [comment]
Released in Commander v6.1
https://github.com/tj/commander.js/releases/tag/v6.1.0
