### ISSUE TITLE
Sets the optional parameters of the option

### ISSUE THREAD

**Issue by AloneScar** [tj/commander.js#1328]
Set the default value. The required parameter should be changed to [Type]

**Comment by shadowspawn** [comment]
The example works fine with a required value of `<type>`?

```js
program
  .option('-c, --cheese <type>', 'add the specified type of cheese', 'blue');
```

https://github.com/tj/commander.js/blob/master/examples/options-defaults.js

**Comment by AloneScar** [comment]
But I used the 
```javascript
.option('-c, --cheese <type>', 'add the specified type of cheese', 'blue');
```
return error

When I change `<type>` to `[type]`, it works

**Comment by AloneScar** [comment]
I'm sorry That I didn't fully understand the role of <type>

There is nothing wrong with this program. It may be that my requirements are related to the optional parameters that cause unnecessary errors

I think when I use this option I can pass no arguments and use the default values

Excuse me. Have a nice day

**Comment by shadowspawn** [comment]
This option has a required value: `-c, --cheese <type>`. If the option is used then you must supply the value.

```
example
example -c blue
example -cblue
example --cheese blue
example --cheese=blue
example --cheese   <-- error, value not specified
```

This option has an optional value, it can be used just as a boolean flag or with a value: `-c, --cheese [type]`

```
example
example --cheese
example --cheese blue
```

**Comment by shadowspawn** [comment]
Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
