### ISSUE TITLE
Is there a way to run command as detach mode?

### ISSUE THREAD

**Issue by fdorantesm** [tj/commander.js#1335]
I'm looking how to create a http server as detached process with command but i didn't find if it's possible or not.

Regards.

**Comment by shadowspawn** [comment]
The simple answer is do it yourself with calls to `child_process.spawn` et al.

(Commander subcommands implemented as external executables are run as a separate process, but it is an attached process, and does not sound like a match for what you have in mind.)

**Comment by aemonge** [comment]
Hey @fdorantesm , I had the same issue/request you needed, so I went ahead and implemented it in a forked repository.

@shadowspawn I did found the subcommand issue a bit tough, but I think I've been able to include it and was able to implement the feature. Please go ahead a start a discussion with me to query about my implementation, i really hope it can be merged and it provides value to other users.

Thanks both in advance, you can see my pull request > https://github.com/tj/commander.js/pull/1340

**Comment by fdorantesm** [comment]
> Hey @fdorantesm , I had the same issue/request you needed, so I went ahead and implemented it in a forked repository.
> 
> @shadowspawn I did found the subcommand issue a bit tough, but I think I've been able to include it and was able to implement the feature. Please go ahead a start a discussion with me to query about my implementation, i really hope it can be merged and it provides value to other users.
> 
> Thanks both in advance, you can see my pull request > #1340

Nice. I solved using `spawn`method of `process-child. I'm starting an express app.

**Comment by fdorantesm** [comment]
> The simple answer is to do it yourself with calls to `child_process.spawn` et al.
> 
> (Commander subcommands are implemented as external executables are run as a separate process, but it is an attached process, and does not sound like a match for what you have in mind.)

Indeed, thanks.
