### ISSUE TITLE
Type a one character option followed by any character, that part becomes the argument.

### ISSUE THREAD

**Issue by ivgtr** [tj/commander.js#1341]
A single character option defined in `.option()` is used as an argument if a sloppy character is added after the option.

### sample  
``` javascript
program
  .option('-s --size [size]', 'size')
  .parse(process.argv)

console.log(program.size)
```
```
$ node ./src -sabcd
```

The result I want is an error, but it actually has `abcd` as an argument in `program.size`.
An option with more than two characters returns the desired `error: unknown option -sabcd`.

I would like to know if this is a bug or a specification.
If it's a spec, I want to know how to make this pattern an error.

Sorry for my bad English.

**Comment by shadowspawn** [comment]
That is unfortunate in this case, but effectively by design. It is because the value can come straight after the short flag:

```
node ./src -s BIG
node ./src -sBIG
node ./src --size BIG
node ./src --size=BIG
```

When you have two dashes like `--sabcd` then you get an error because it is an unrecognised long option.

**Comment by shadowspawn** [comment]
> If it's a spec, I want to know how to make this pattern an error.

There is not support for making this an error in Commander.

**Comment by ivgtr** [comment]
It's a shame..., but I could see the clue to the solution.
Thanks for the help, @shadowspawn
