### ISSUE TITLE
Flag option with implicit negate alternative.

### ISSUE THREAD

**Issue by mshima** [tj/commander.js#1343]
We currently have a mix of commander.js with meow for unknown options.
I am trying to disable allowUnknownOption.
One challenge is that commander does not allow --no to flags without adding the negate flag.

Why do we need need negate?
Our documentation and usability requires it.
When the application is executed for the first time (ex `--foo`) we save the option, and then when it is executed for the second time (ex `--no-foo`), we allow that option to be changed.

Adding negate option to every flag is a workaround, but that brings others problem:
- Our help is already too big without the negate value.
- We don't provide descriptions for the negate option and we don't have plans to provide.

It would be great if commander added 1 of the following:
- Something like program.alwaysAllowNegate(true)
This would always allow a flag to have negate value.
- ~Add an option to hide the option help, eg hide when staring with '!':~
```
this.option('cheese', 'with cheese').option('no-cheese', '!with cheese')
```
- ~Hide empty negate flag help if the flag is added.~
```
this.option('cheese', 'with cheese').option('no-cheese')
```
- ~Add implicit negate when the option starts or ends with !.~
```
this.option('cheese!', 'with cheese')
```

**Comment by shadowspawn** [comment]
Nice description of your problem.

An open issue to allow hiding options is #1106 and a PR with a possible approach is #1331.

**Comment by mshima** [comment]
@shadowspawn after a failed attempt, we actually need negate option by default.
Reason:
- Execute `foo` command with `bar` option not settled.
- At some point it can consolidate to `bar: false` value.
- We regenerate command args becoming [`--no-bar`].
- Then we fork with child_process.fork('foo', ['--no-bar'].
- Fails with unknown `--no-bar` option.

**Comment by shadowspawn** [comment]
I do not understand your failed attempt. Were you only adding either `--bar` or `--no-bar`, depending on the saved state? (I would expect you need to add both since either could be specified on the command line independent of the saved state.)

**Comment by shadowspawn** [comment]
I do not know if this covers your use cases, but as an example this custom class automatically adds a hidden negative option when boolean options are added. It uses new features coming in Commander v7 (code available now on the `release/7.x` branch).

```js
const { Command, Option } = require('commander');

class MyCommand extends Command {
  createCommand(name) {
    return new MyCommand(name);
  }

  addOption(option) {
    const result = super.addOption(option);
    // Add a hidden `--no` option for boolean options
    if (option.long && !option.required && !option.negate && !option.optional) {
      super.addOption(new Option(option.long.replace(/^--/, '--no-')).hideHelp());
    }
    return result;
  }
}

const program = new MyCommand();

program
  .option('-c, --cat')
  .option('-p, --port <number>')
  .action((cmd) => console.log(cmd.opts()));
  
program.command('sub')
  .option('-d, --dog')
  .action((cmd) => console.log(cmd.opts()));

program.parse();
```

```
% node index.js --help
Usage: index [options] [command]

Options:
  -c, --cat            
  -p, --port <number>  
  -h, --help           display help for command

Commands:
  sub [options]
% node index.js --cat 
{ cat: true, port: undefined }
% node index.js --port 80
{ cat: undefined, port: '80' }
% node index.js --no-port   
error: unknown option '--no-port'
% node index.js --no-cat 
{ cat: false, port: undefined }
% node index.js sub     
{ dog: undefined }
% node index.js sub --dog
{ dog: true }
% node index.js sub --no-dog
{ dog: false }
```

**Comment by shadowspawn** [comment]
For interest, Minimist and Yargs both have support for `--no` for their zero-config parsing of boolean options. (Not sure if they support `--no` for declared options which can take a value.)

- https://github.com/substack/minimist/issues/54
- https://github.com/yargs/yargs/blob/master/docs/tricks.md#negating-boolean-arguments

**Comment by mshima** [comment]
> I do not know if this covers your use cases, but as an example this custom class automatically adds a hidden negative option when boolean options are added. It uses new features coming in Commander v7 (code available now on the `release/7.x` branch).

@shadowspawn thanks, it should work with the negate behaviour change for default value.
That's enough for me, fell free to close.

The problem I can think about this approach is that the negate option is not implicit, it's hidden.
So it can conflict with an explicit negate option.
This is just an example since we can test a pre-existing option.
```
const { Command, Option } = require('commander');

class MyCommand extends Command {
  createCommand(name) {
    return new MyCommand(name);
  }

  addOption(option) {
    const result = super.addOption(option);
    // Add a hidden `--no` option for boolean options
    if (option.long && !option.required && !option.negate && !option.optional) {
      super.addOption(new Option(option.long.replace(/^--/, '--no-')).hideHelp());
    }
    return result;
  }
}

const program = new MyCommand();

program
  .option('-C, --no-cat', 'without cat', () => 'no cat')
  .option('-c, --cat')
  .option('-p, --port <number>')
  .action((cmd) => console.log(cmd.opts()));
  
program.command('sub')
  .option('-d, --dog')
  .action((cmd) => console.log(cmd.opts()));

program.parse();
```

```
% node test.js --no-cat
{ cat: false, port: undefined, opt: undefined }
```

**Comment by shadowspawn** [comment]
> The problem I can think about this approach is that the negate option is not implicit, it's hidden.
> So it can conflict with an explicit negate option.

Good point. I was assuming using this _instead_ of explicit `--no` options. This is a custom approach, not a general solution.

**Comment by mshima** [comment]
We don't use explicit negate option, so it won't be a problem for us.
I will drop unknown options again once v7 is released.

I rebased the allowNegateOption commit https://github.com/mshima/commander.js/commit/9e832e5fd5f43a03fd7fc78de4e6a0c2f88d9b29.

**Comment by mshima** [comment]
@shadowspawn any timeline for commander 7?

**Comment by shadowspawn** [comment]
Yes, Commander 7 release planned for January 2021. Major releases about six months apart. We like to make a prerelease available over a month in advance, and could do a prerelease soon if useful.

https://github.com/tj/commander.js/milestone/8

**Comment by mshima** [comment]
@shadowspawn thanks.

**Comment by shadowspawn** [comment]
This is somewhat implied by the title of this issue and some discussion in the PR, but to be explicit, the proposed

```js
program.alwaysAllowNegate(true);
```

would allow negation of all boolean options. It would not automatically allow negation of options with option-values as the caller is not expecting a boolean value in these cases.

**Comment by shadowspawn** [comment]
For interest, the PR also added the ability for an option to add negation support without requiring separate options for the positive and negated options. This could be considered a separate enhancement. (Because it parallels what can be achieved with existing support, it probably wouldn't be considered on its own.)

**Comment by shadowspawn** [comment]
@mshima 
Commander 7.0.0 has shipped.

**Comment by shadowspawn** [comment]
A single option which supports negation is a future possibility (rather than the existing separate positive and negative options), but it isn't likely to get acted on based on this report.

Feel free to open a new issue if this idea comes up again, with new information and renewed interest.
 
Thank you for your contributions.
