### ISSUE TITLE
Implied Options

### ISSUE THREAD

**Issue by brannonh** [tj/commander.js#1358]
I just started using Commander.js yesterday, and I am very happy with it. That being said, I noticed there is no way to mark that a boolean option implies another boolean option. My thought process is that if such a boolean option is provided to the program, the _implied_ option(s) would _also_ be set to `true`.

Having this available would allow for less verification code within the program itself. You could always check a single option, rather than checking multiple options.

As an example, here's a(n edited) snippet of my current code:

```javascript
program
  .option('-d, --dump', 'dump data on error and end of execution')
  .option('-t, --trace', 'log everything (implies -d)');
```

Currently, I would either have to check for both options or check for `-t` and set `-d`. With an implied option, I could do something like this (rough example):

```javascript
program
  .option('-d, --dump', 'dump data on error and end of execution')
  .option('-t, --trace', 'log everything')
  .implies('trace', 'dump');
```

The automated help would also automatically add something like `(implies -d)` to the description for the `trace` option.

I would think that a negatable boolean option would take precedence over the implication (i.e., `program -t --no-dump` would result in `trace` being `true` and `dump` being `false`).

Anyways, that's all. I think this would be a nice addition to Commander.js' current functionality. If it's possible now and I just missed it, please let me know. Otherwise, I'm also always open to feedback. Thanks!

**Comment by shadowspawn** [comment]
Thanks. Another other sort of configuration sometimes offered is mutually exclusive options. 

I see these as fairly low value as only a few lines of code to do the exact custom logic required. Happy to leave issue open though, and see if it is popular. 👍

**Comment by brannonh** [comment]
Thanks for the feedback. I understand that completely. I guess the value would be higher in cases where the custom logic is required in multiple places. In that case adding/removing a flag implication would require updating the custom logic in all of those places, which always opens the door for missing one.

**Comment by shadowspawn** [comment]
Related: #1391 #1408

**Comment by shadowspawn** [comment]
For potential interest to people following this issue, there is a PR open for similar-but-different `conflicts`. See #1678

**Comment by shadowspawn** [comment]
I am experimenting with calling signature `Option.implies(optionBag)` that specifies the implied options and their values, like:

```js
program
  .addOption(new Option('--quiet').implies({ logLevel: 'off' }))
  .addOption(new Option('--log-level <level>').choices(['info', 'warning', 'error', 'off']).default('info'));
```

**Comment by shadowspawn** [comment]
Commander v9.3.0 adds `Options.implies()`
