### ISSUE TITLE
Add Option/Command from hash?

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1359]
Are authors interested in a factory method to construct commands or options from a hash of the properties? This would be an alternative approach rather than a replacement for the current chaining interface. The use case is adding options and commands from meta information supplied from elsewhere.

e.g.

```
const my = readOption();
const myOption = Option.fromHash({ flags: my.flags, description: my.description, mandatory: my.mandatory, hidden: my.hidden });
program.addOption(myOption)
```

**Comment by shadowspawn** [comment]
Related:
- https://github.com/tj/commander.js/issues/1277#issuecomment-641849117

**Comment by mshima** [comment]
I don't think this is required anymore with addOption been exposed:
```
const my = readOption();
program.addOption(
  new Option(my.flags, my.description)
    .makeOptionMandatory(!!my.mandatory)
    .hideHelp(!!my.hidden));
```

But would be nice to expose every option:
```
const my = readOption();
program.addOption(
  new Option(my.long, my.description)
    .short(my.short)
    .required(!!my.required)
    .optional(!!my.optional));
```

**Comment by shadowspawn** [comment]
> But would be nice to expose every config

I did wonder about adding chaining setters for the lower level properties, but chose to start by keeping the existing Option constructor taking the flags parameter, and have the flags and flags related properties consistent when set this way. 

The properties are public.

**Comment by shadowspawn** [comment]
This issue didn't get much interest. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
