### ISSUE TITLE
How to create shell/repl?

### ISSUE THREAD

**Issue by Zearin** [tj/commander.js#136]
(Sorry for the n00b question, but I’m under time constraints on a project. ☺)

I _really_ dig the way commander.js makes it possible to write command line programs!  The only thing I’m wondering is: 

How can I use commander.js to make a “shell” (repl)?

**Comment by KaKi87** [comment]
Hello,

I got the same question, but it seems that Commander only handles arguments, but not commands, which is understandable since it's meant to be used with a single file i.e. a single command.

So, how to handle that part ?

Thanks

**Comment by shadowspawn** [comment]
Commander supports subcommands, which would be used to parse what you treat as commands in the REPL.

**Comment by KaKi87** [comment]
Oh, I didn't think of it that way, thank you very much.

**Comment by KaKi87** [comment]
One more thing : `parse` only takes an array, how to make the conversion ?
I guess I can't just use `split(' ')` as it would break things like `--foo="bar baz"`.
Thanks

**Comment by shadowspawn** [comment]
You could look at https://www.npmjs.com/package/shell-quote which has a parse command.

**Comment by KaKi87** [comment]
Thanks !

**Comment by KaKi87** [comment]
So, I finally achieved my goal.

As it turns out, I needed to put 2 `undefined` items at the beginning of the array to pass to `program.parse`.

Also, because `program.parse` doesn't return a promise nor take a callback, I needed to add an event to be fired on the `postAction` hook so the prompt wouldn't re-appear until the action is finished.

However, I got another issue : the `help` command, as well as any incorrect input from the user, will result in the script exiting.

How can I avoid that, e.g. showing the error but then letting the prompt re-appear for the user to try again ?

Thanks.

---

Here's my minimal reproducible code :

```js
import repl from 'node:repl';

import { Command } from 'commander';
import { createEmitter } from 'simpler-emitter';
import { parse } from 'shell-quote';

const
    program = new Command(),
    emitter = createEmitter();

program.hook('postAction', () => emitter.emit('idle'));

program.command('split')
    .description('Split a string into substrings and display as an array.')
    .argument('<string>', 'string to split')
    .option('--first', 'display just the first substring')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((str, options) => {
        const limit = options.first ? 1 : undefined;
        console.log(str.split(options.separator, limit));
    });
program.command('join')
    .description('Join the command-arguments into a single string')
    .argument('<strings...>', 'one or more strings')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((strings, options) => {
        console.log(strings.join(options.separator));
    });

repl.start({
    eval: (
        line,
        _,
        __,
        callback
    ) => {
        emitter.once('idle', callback);
        program.parse([undefined, undefined, ...parse(line)]);
    }
});
```

**Comment by shadowspawn** [comment]
Please open a new issue @KaKi87 

Things have changed in the 10 years since this issue was closed. :-)

**Comment by shadowspawn** [comment]
(Tip: you can use Edit on your message to get access to the raw markdown for copying.)

**Comment by KaKi87** [comment]
[Done](https://github.com/tj/commander.js/issues/1841).

> Tip: you can use Edit on your message to get access to the raw markdown for copying.

Yeah I know, another tip : you can use the *Quote reply* feature to access the raw markdown of a post you didn't authored.
