### ISSUE TITLE
Support piping

### ISSUE THREAD

**Issue by mathiasbynens** [tj/commander.js#137]
Say you want to support piping in your script, e.g.:

``` bash
echo "foo bar" | ./test.js
```

That’s currently possible using [code that looks like this](http://stackoverflow.com/a/15467539/96656):

``` js
var data = '';
function withPipe(data) {
   console.log('content was piped');
   console.log(data.trim());
}
function withoutPipe() {
   console.log('no content was piped');
}

var self = process.stdin;
self.on('readable', function() {
    var chunk = this.read();
    if (chunk === null) {
        withoutPipe();
    } else {
       data += chunk;
    }
});
self.on('end', function() {
   withPipe(data);
});
```

It would be neat if commander.js could somehow abstract all this away and make it easier to write scripts that accept piped content.

**Comment by Potherca** [comment]
I did [the same thing here](https://github.com/Dealerdirect/liquid-linter-cli/blob/master/index.js#L194). Works like a charm.

**Comment by shadowspawn** [comment]
Popular approach from @jrschumacher , thanks

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
