### ISSUE TITLE
Add method to get help option description

### ISSUE THREAD

**Issue by Melissa0x1f992** [tj/commander.js#1370]
Something like `helpDescription()`?  And maybe when someone uses `helpOption(..., 'custom description')`, subsequent calls will return the new description?

Context: I'm using `helpOption(false)` to disable the implicit help because I have a non-console help output, and I'd rather not display help redundantly on the console.  I use `helpInformation()` to get the help string in the action of my own `'-h, --help'` option.  I'd like my help description to match commander's default help option description.  My current options are just to hardcode a copy of your string, or access the `_helpDescription` field.  I've opted for the former for now, but I'd rather not have a random copy of data when the intent was to refer to the already-existing data.

**Comment by shadowspawn** [comment]
Best approach currently is a copy of the string, as you have done. 

There is a big refactor of the help in progress in #1365, but it does not provide access to the default descriptions.

Will be interesting to see if this gets upvotes, now `helpOption(false)` is possible. I don't think I would add access to the default help option description alone as this string is one of many: could also want help option flags, help command description, version option flags, version option description...

**Comment by shadowspawn** [comment]
Improving support for non-console help output in #1387

**Comment by shadowspawn** [comment]
Improved support for redirected output in Commander 7.0.0.
