### ISSUE TITLE
addHelpCommand missing from TypeScript definitions

### ISSUE THREAD

**Issue by Zamiell** [tj/commander.js#1374]
Hello,

It looks the addHelpCommand method definition is missing in the TypeScript definitions file here:
https://github.com/tj/commander.js/blob/master/typings/index.d.ts

Is this a bug?

**Comment by shadowspawn** [comment]
Short version: yes. 

Got missed in a big PR, #1149. Thanks. 👍

**Comment by shadowspawn** [comment]
Released in Commander v6.2.0

**Comment by shadowspawn** [comment]
Released in Commander v6.2.0

**Comment by Zamiell** [comment]
thanks john, appreciate your work
