### ISSUE TITLE
Lazy load options.

### ISSUE THREAD

**Issue by mshima** [tj/commander.js#1383]
Would be nice to have public apis supporting options loaded lazily.
Test case using private `_parseCommand`.
```
const { Command } = require('../');

// Test lazily loaded options.

class LazyCommand extends Command {
  createCommand(name) {
    return new LazyCommand(name);
  }

  prepareOptions(prepareOptionsCallBack) {
    this._prepareOptionsCallBack = prepareOptionsCallBack;
    return this;
  }

  _parseCommand(operands, unknown) {
    if (this._prepareOptionsCallBack) {
      this._prepareOptionsCallBack(this);
      delete this._prepareOptionsCallBack;
    }
    return super._parseCommand(operands, unknown);
  }
}

describe('with action', () => {
  test('when .parse called then prepare options is called', () => {
    const actionMock = jest.fn();
    const program = new LazyCommand();
    program.command('run').prepareOptions(() => {
      actionMock();
    });

    program.parse(['node', 'test', 'run']);
    expect(actionMock).toHaveBeenCalled();
  });

  test('when .parse called then lazily loaded option should be set', () => {
    const actionMock = jest.fn();
    const program = new LazyCommand();
    const runCommand = program.command('run').prepareOptions(self => {
      self.option('--pepper');
    }).action(actionMock);

    program.parse(['node', 'test', 'run', '--pepper']);
    expect(runCommand.pepper).toBe(true);
  });
});
```

**Comment by shadowspawn** [comment]
In the example you add option for `--foo` but from the rest of the code I think you intended that to be `--pepper`?

**Comment by shadowspawn** [comment]
Related issue: #1197

**Comment by joebnb** [comment]
i need this also,and yargs supported,like this, if input `comd build -h`,it will out put action function also,but command was disabled run action
```js
   await program
        .command('build')
        .description('build project on current dir')
        .action(async function (cmd) {
           cmd
             .option('-a,--add','some result');
             .description('add project on current dir')
        });
```

**Comment by shadowspawn** [comment]
What is a use case for lazy-loaded options?

On a related note, stand-alone executable subcommands have lazy loaded options in the sense the sub-command itself is called on demand!

**Comment by joebnb** [comment]
> What is a use case for lazy-loaded options?
> 
> On a related note, stand-alone executable subcommands have lazy loaded options in the sense the sub-command itself is called on demand!

some thing like yargs.fn(optionbuilderFn).fn(argvFn) option builder before use args(for dynamic help show),i have avoid this

**Comment by shadowspawn** [comment]
This issue has not had much support in six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
