### ISSUE TITLE
Few question regarding custom CLI logic

### ISSUE THREAD

**Issue by cupcakearmy** [tj/commander.js#1391]
Hi 👋

I have a few questions that I could not find an anwer in the readme or by googling them.

Immagine you have the following simple command.

```
program
  .command('generate')
  .option('-n, --number <numbers...>')
  .option('-a, --all')
  .action(cmd => {
    // Some stuff
  })
```

Both of the options are optional, but at least one of them is required. Is there a native way to do that?
If not, is there a way to use the built in help generator to display that info?

Thanks!! ❤️

**Comment by shadowspawn** [comment]
There is not a native way to enforce that one of `--number` and `--all` is specified.

You can include that information in the built-in help generator yourself in a variety of ways. Have a look at:
- custom help using `.on('--help')`:  https://github.com/tj/commander.js#custom-help
- `.usage()`: https://github.com/tj/commander.js#usage-and-name
- `.description()`

**Comment by cupcakearmy** [comment]
Thanks for the quick answer!
Unfortunately that will not solve the issue. Well you can't have everything 🙂
