### ISSUE TITLE
cannot use `--parent` argument

### ISSUE THREAD

**Issue by manolo** [tj/commander.js#1401]
`cmd.parent` is used internally, it should be a private name like  `cmd._parent` to allow usage of `parent` which should be a valid option, for instance in apps doing file-system operations.

**Comment by shadowspawn** [comment]
There are LOTS of properties, including `parent`. This problem has a long history: #933

However, the good news is there is a solution now! Use `.storeOptionsAsProperties(false)`, see:

https://github.com/tj/commander.js#avoiding-option-name-clashes

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Options are now stored safely by default in Commander 7.0.0.
