### ISSUE TITLE
Is there a way to group options? (one of)

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1408]
is there any way to group options together like in argparse? 
let's say I have two options: `-a` and `-b`, is there a way to group them under "one of" so that the user will get an error if he passes them both?

**Comment by shadowspawn** [comment]
No grouping support, no.

The related open issue is #1358

**Comment by shadowspawn** [comment]
I looked up the argparse support:
- https://docs.python.org/3/library/argparse.html#mutual-exclusion

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
For interest to people following this issue, there is a PR open for `'conflicts()`. See https://github.com/tj/commander.js/pull/1678
