### ISSUE TITLE
Exit status when exception is thrown

### ISSUE THREAD

**Issue by xloem** [tj/commander.js#1414]
I'm working with a script that uses commander, and noticing that the exit status seems to be 0 when an exception is thrown within an action() callback.  Is this the intended behavior?  It seems like -1 would be a better exit status.

**Comment by shadowspawn** [comment]
Commander is not altering the exception handling. The default node behaviour is exit status 1 for an uncaught exception, and that is what I see with this program:

```js
const { program } = require('commander');

program
  .action(() => {
    throw new Error('example');
  });

program.parse();
```

**Comment by xloem** [comment]
Thanks.  Must be a quirk of my script.  Sound like I'd wrap program.parse(), which is great.

**Comment by xloem** [comment]
I'm guessing it's happening because the action is async.  Nothing catches the promise rejection.

**Comment by xloem** [comment]
node 10 terminates with exit code 0 when a promise is rejected

**Comment by shadowspawn** [comment]
Ah ha! Thanks for explanation.

Are you calling `.parseAsync()` rather than `.parse()`?

**Comment by xloem** [comment]
The project was actually using version 2.  I upgraded to the latest 4, switched to parseAsync, and added a .catch that sets process.exitCode = 1 before rethrowing, for now.
