### ISSUE TITLE
How to display the full help of a command when an error occures?

### ISSUE THREAD

**Issue by electrotype** [tj/commander.js#1423]
Let's say an `option` is required but is missing. Commander then automatically displays a short "_error: required option '--myOption' not specified_" message. But what if, in addition to this message, I also want to display the _full help_ of the command? Is this possible?

And, related question: 

I do use `exitOverride()` and a big `try/catch` block. After `parseAsync()` has been called on a command with subcommands, is there a way to know what is the subcommand that was actually called? If an error occures and I could know the subcommand in my `catch` block, I guess I could display the help by myself (using `subCommand.outputHelp()`).

**Comment by shadowspawn** [comment]
Hmm, there is not direct support for either.

(Perhaps the CommanderError could include the failing command as a property.)

On a related note, the unknown command error got modified to include a reference to the help.

```
% fab unknown
error: unknown command 'unknown'. See 'fab --help'.
```

**Comment by shadowspawn** [comment]
I think you could display the appropriate help by subclassing and overriding `.command` to add a command specific `.exitOverride`. Interested, or too heavy-weight?

**Comment by electrotype** [comment]
Inspired by your suggestions:

```
command.exitOverride(err => {
  if (err.code !== 'commander.executeSubCommandAsync') {
    err.command = command;
    throw err;
  } else {
    // Async callback from spawn events, not useful to throw.
  }
});
```
I then have access to the command in my `catch` block. Works perfectly! 

Thanks.

**Comment by shadowspawn** [comment]
An answer was worked out, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Related: `.showHelpAfterError()` added in prerelease v8.0.0-2 by PR #1534
