### ISSUE TITLE
Options shared by a root command and its subCommands

### ISSUE THREAD

**Issue by electrotype** [tj/commander.js#1426]
I had an issue that took me a long time to figure out and fix. It is about an `option` that I add to _all_ the commands of my application: `-s` for "silent". When this option is set, a command will disable all outputs when running.

Since this is a global option that I add to all commands, I created a `addGlobalOptions(command)` function and I call it for every command.

The issue is that I was also calling `addGlobalOptions()` _on the root Command_! 

My program looks a bit like:
```
const commander = new Command();
addGlobalOptions(commander);
addSubCommands(commander);
```
In `addSubCommands`, each command has the global options added too, using `addGlobalOptions`.

By calling `addGlobalOptions` on the root "commander" Command, a subCommand would always receive `undefined` for the `-s` argument, even when specified by the user! By removing the global options on the root "commander" Command, `true` is received correctly.

I did not find anything in the documentation about this? What is the expected behavior when an option is shared between a root Command and one of its subCommand? Or maybe I'm doing something wrong?

**Comment by shadowspawn** [comment]
The root command parses its options from anywhere on the command line, so it consumes the option first before the subcommand. The relevant line in the README is:

> Options on the command line are not positional, and can be specified before or after other arguments.

You can add and access a common option on the root command, or add it to all your subcommands. A visible difference to the user is where in the help the option appears. Do you think of it as a "program" option on the root command, or a common option which every subcommand has locally?

There is an open issue with collected reports and research: #1229
and the related issues to your problem are: #598 #1033 #1307

**Comment by electrotype** [comment]
Thank you for the explanation.

**Comment by shadowspawn** [comment]
Pull Request opened to add `.enablePositionalOptions()` and `.passThroughOptions()`: #1427

**Comment by shadowspawn** [comment]
Opened poll on possible enhancements to global options: #1551

**Comment by shadowspawn** [comment]
Opened a draft PR for `.addCommonOption()` #1670
