### ISSUE TITLE
addCommand() -- how to?

### ISSUE THREAD

**Issue by btmurrell** [tj/commander.js#1439]
I see the discussion in #1186 that acknowledges that `addCommand` lacks doc... i am getting the error below when trying to use it.  the object I am passing to it is of type `const cmd = new Command();  cmd.command('foo'); `    Other than giving the command a name in this way ('foo'), how else would one specify a name?

```
/home/merl/dev/EDS/dev-cli/node_modules/commander/index.js:225
    if (!cmd._name) throw new Error('Command passed to .addCommand() must have a name');
                    ^

Error: Command passed to .addCommand() must have a name
    at Command.addCommand (/home/merl/dev/EDS/dev-cli/node_modules/commander/index.js:225:27)
    at Object.<anonymous> (/home/merl/dev/EDS/dev-cli/src/commands/eds.js:14:9)
```

**Comment by shadowspawn** [comment]
To give your new command a name, you can supply the name with the constructor or by calling a method:

```js
const cmd1 = new Command('foo');

const cmd2 = new Command();
cmd2.name('bar');
```

**Comment by btmurrell** [comment]
hmmmm. thanks @shadowspawn . that seems simple enough, and that worked, so I am unblocked... but there's no doc or pattern for `new Command('foo')`, and just one mention of using `cmd.name('foo')` to affect the usage info.  If I understood it more, I would put in a doc PR, but I think there's more there.  in the mean time, this issue might help others. thanks!

**Comment by Chuwiey** [comment]
I might be doing an anti pattern, but I am running into a similar `if (!cmd._name) throw new Error('Command passed to .addCommand() must have a name');` error.

In my `main.ts`:
```
import { testCommand } from './commands/test'
const { Command } = require('commander')

const program = new Command()

program
    .version('0.0.1')
    .description('Fake package manager')
program.addCommand(testCommand())
program.parse(process.argv)
```

in `commands/test.ts`:
```
export function testCommand() {
        const heat = program.command('heat')
        heat
            .command('jug')
            .action(() => {
                console.log('heat jug')
            })
        heat
            .command('pot')
            .action(() => {
                console.log('heat pot')
            })
        return heat
}
```

A console.log on install() return the correct Command structure and I can see the relevant `_name` properties. However, the `addCommand` function sees them as undefined.
