### ISSUE TITLE
(node:32144) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by mforman1** [tj/commander.js#1441]
After upgrading `commander` version from `6.2.1` to `7.0.0` I get the following error:
```
(node:32144) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

On the below line:

```
const cmd = require('commander')

 devServer: {
    contentBase: outputdir,
    open: true,
 ->   openPage: path.normalize(cmd.page),
    overlay: {
      errors: true
    },
    historyApiFallback: true
    // host: '0.0.0.0'
  },
```

Any idea on how to solve that?

**Comment by shadowspawn** [comment]
This is an educated guess as your program fragment does not show where `cmd` came from. 

Try changing `cmd.page` to `cmd.opts().page`.

 The default behaviour for storing options has changed. By default, option values are no longer stored as properties on the command. See the release notes and migration tips for more clues:

https://github.com/tj/commander.js/releases/tag/v7.0.0

**Comment by mforman1** [comment]
That was it, thank you!
