### ISSUE TITLE
Subcommands with options output the wrong help text

### ISSUE THREAD

**Issue by MGibson1** [tj/commander.js#1446]
I'm working on [bitwarden/cli](https://github.com/bitwarden/cli) and running into issues with deeply nested commands.

The CLI uses a git-style command structure and is written in Typescript and packaged using webpack. I say this because I *think* this precludes us from using standalone subcommands.

The issue I'm having is with our help text. I have been unable to output the appropriate help text for commands that are deeper than one level down **and** have either required or optional values (e.g. `option <value>` or `option [value]`).

The code below recreates this issue
``` javascript
#!/usr/bin/env node

const { Command } = require('commander');
const program = new Command();

const addOther = new Command('add <item>');
const sayThanks = new Command('thank [message]');
const order = new Command('order');

sayThanks
    .description('send a kudos')
    .addHelpText('after', 'much obliged!')
    .on('--help', () => {
        console.log('Example:');
        console.log('  thank "best pizza ever"');
    });

addOther
    .description('add an item to the pizza')
    .addHelpText('after', 'we won\'t forget them ;\)')
    .on('--help', () => {
        console.log('Examples:');
        console.log('  add anchovies');
    });

order
    .description('place the order')
    .addHelpText('after', 'I promise')
    .on('--help', () => {
        console.log('It\'ll be the best pizza you\'ve ever tasted!');
    });

program
    .description('An application for pizza ordering')
    .option('-p, --peppers', 'Add peppers')
    .option('-c, --cheese <type>', 'Add the specified type of cheese', 'marble')
    .option('-C, --no-cheese', 'You do not want any cheese')
    .addCommand(addOther)
    .addCommand(sayThanks)
    .addCommand(order);


program.parse();

const options = program.opts();
console.log('you ordered a pizza with:');
if (options.peppers) console.log('  - peppers');
const cheese = !options.cheese ? 'no' : options.cheese;
console.log('  - %s cheese', cheese);

```

* `example --help` outputs the expected auto help documentation.
* `example order --help` output the expected auto help documentation, limited to the order command's options and the custom help text defined on the order command.
* `example thank --help`, `example thank "message" --help`, `example add --help`, and `example add anchovies --help` all output help text identical to `example --help`. I expect similar behavior to `example order --help` for all of these.

The only explanation I can think of is that the command parameters are altering the handling of the help command and causing it to be early-handled by the root command.

I'd love some suggestions about how to get help text on a per-subcommand basis, regardless of the subcommand's options

**Comment by shadowspawn** [comment]
I have not tried reproducing yet, so this is a quick guess from reading the example.

Try changing:
```
const addOther = new Command('add <item>');
```

To:
```
const addOther = new Command('add');
addOther.arguments('<item>');
```

The Command constructor takes an optional command name, but not the command usage (name + arguments).

**Comment by MGibson1** [comment]
Awesome guess! :)

That fixes the issue, thank you!
