### ISSUE TITLE
using program level actions

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1451]
I have many sub-commands, but there are some actions that need to run before all sub-commands, depending on some options. It's easy to have options on the program level, but it looks like I can't have actions on the program level (I tried, but they don't run). Is there any way around it? I want to have some actions on the program level that will have access to the program level options, and will run before the sub-commands.  
if not, consider this issue as a feature request:)

**Comment by shadowspawn** [comment]
The program can have an action handler, but it isn't what you want as does not run before subcommands. Only one action handler is called. 

For some cases where the program level options are simple or independent, you may be able to use a custom event listener for the option, but this is not a general solution.

The "feature request" is probably covered by #1197

**Comment by Niryo** [comment]
ok, I thanks for the fast reply, i will close this and keep tracking the other issue
