### ISSUE TITLE
default command is being triggered even for wrong input

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1452]
is this a bug? I would expect it to print usage error. if the user doesn't supply any args, it make sense to use to default command, but if he supplies a bad arg, I would expect to see an error.
```javascript
const startCommand = createCommand('start')
startCommand
  .command('firstCoammand', {isDefault: true, hidden: true})
  .action(() => {
    console.log('hello world');
  });
startCommand
  .command('other')
  .action(() => {
    console.log('bla');
  });

//node program.js sdfsd
//output: hello world
//node program.js othet
//output: hello world even though we meant to write "other" but had a typo
```

**Comment by shadowspawn** [comment]
The default command is called unless a subcommand is specified, and it is up to the default command to do the desired error handling. In general, the default command may take command-arguments so we can't tell the difference between an intended argument and a mis-spelled subcommand.

The standard behaviour for a command is that excess command-arguments are ignored. In Commander 7 you can make excess arguments an error with `.allowExcessArguments(false)`. The error message it produces mentions the command name though, so not ideal for your example.

```sh
$ node program.js sdfsd
error: too many arguments for 'firstCoammand'. Expected 0 arguments but got 1.
```

**Comment by Niryo** [comment]
@shadowspawn thanks, I'll use `.allowExcessArguments(false)` . the error isn't perfect indeed, but at least the command will not be triggered on typo.
