### ISSUE TITLE
Event listener on command is not called  for parent commands

### ISSUE THREAD

**Issue by Kerruba** [tj/commander.js#1456]
Hello, 
I've found this issue, and wrote a test for it
```
  test('subcommand with subcommands should trigger the event', () => {
    const mockTestAction = jest.fn();
    const mockInstallAction = jest.fn();
    const program = new commander.Command();
    const subcmd1 = new commander.Command('cli1');
    subcmd1.command('install');
    subcmd1.command('update');
    subcmd1
      .on('command:install', mockInstallAction);
    const subcmd2 = new commander.Command('cli2');
    program
      .addCommand(subcmd1)
      .addCommand(subcmd2);
    program
      .on('command:cli1', mockTestAction);
    program.parse(['node', 'test', 'cli1', 'install']);
    expect(mockTestAction).toHaveBeenCalled();
    expect(mockInstallAction).toHaveBeenCalled();
  });
```
My usecase was to set certain  env variables if the subcommand `cli1` is called, others if the `cli2` instead is called
This is linked to issue https://github.com/tj/commander.js/issues/1457

**Comment by shadowspawn** [comment]
There are not events generated at the intermediate commands in the chain of subcommands. (This is partly for historical reasons, the events correspond to an action handler being called.)

**Comment by shadowspawn** [comment]
Some overlap with #1451

**Comment by shadowspawn** [comment]
Behaving as currently intended. No further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
