### ISSUE TITLE
add choices to arguments

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1458]
is it possible to have choices for arguments?
```javascript
createCommand('pickColor').arguments('<color>'); //color choices: ['red', 'blue', 'green']
```

**Comment by shadowspawn** [comment]
No, choices for command-arguments are not supported. 

(But an alternative is to make `color` an option instead of an argument.)

**Comment by Niryo** [comment]
Is it intentionally not supported or is it in the backlog? If it's in the backlog we can discuss about the api and maybe i could create a PR

**Comment by shadowspawn** [comment]
At this stage it is a new suggestion.

I see `.choices()` as just one of the things that option-arguments support that command-arguments do not: default value, custom option processing (coerce), and choices.

Do any other CLI frameworks support any of these for command-arguments?

**Comment by shadowspawn** [comment]
I had a quick look at argparse, and it configures command-arguments and option-arguments the same way:  https://docs.python.org/3/library/argparse.html#the-add-argument-method

(This is very different to how Commander currently works!)

**Comment by shadowspawn** [comment]
Previous related issue: #971

**Comment by Niryo** [comment]
My first intuition was that arguments should be treated the same as options in terms of validation and api, so it will be quite natural to have `addArguments(new Argument().choices())`, same as options, don't you think?

**Comment by shadowspawn** [comment]
I think following the option syntax may work pretty well, allowing description in a more consistent way, and defaults and coercion, and the extensible syntax to allow choices. Specifying the arguments with `.arguments()` or along with the command name in `.command()` still works fine as a shortcut for the simple cases. Using examples from the README:

```js
// arguments and description
oldProgram
  .arguments('<username> [password]')
  .description('test command', {
    username: 'user to login',
    password: 'password for user, if required'
  });
newProgram
  .description('test command')
  .argument('<username>', 'user to login')
  .argument('[password]', 'password for user, if required');

// default
cmdUsingOpt
  .option('-c, --cheese <type>', 'add the specified type of cheese', 'blue');
cmdUsingArg
  .argument('[cheese-type]', 'add the specified type of cheese', 'blue')

// coerce
cmdUsingOpt
  .option('-f, --float <number>', 'float argument', parseFloat)
cmdUsingArg
  .argument('<number>', 'float argument', parseFloat)

// choices
cmdUsingOpt
  .addOption(new Option('-d, --drink <size>', 'drink size').choices(['small', 'medium', 'large']));
cmdUsingArg
  .addArgument(new CommandArgument('<drink-size>', 'drink size').choices(['small', 'medium', 'large']));
```

**Comment by Niryo** [comment]
what is/are the correct test suite for testing the arguments? I want to duplicate all the relevant tests and make sure they are passing with the new syntax

**Comment by shadowspawn** [comment]
Be warned: I am not sure yet whether there is enough value to make what I suspect will be a lot of code changes. I have not seen many requests for the features this would add, so will be watching to see if this issue gets many 👍 . 

You may want to open a PR with some code to show and discuss, but just warning you not to expect it will be accepted.

Is there a particular area you are interested in experimenting with first? You did ask about choices, but that does need quite a lot of new syntax with what we are considering, so you may have to start elsewhere.

There are base argument tests in:
- `command.action.test.js`
- `command.variadic.test.js`

But there are related tests in lots of other files, including the help related tests and the new `.allowExcessArguments()`. Command-arguments and options are the base building blocks of the CLI.

**Comment by Niryo** [comment]
sure, I know you have the right to reject the pr:)
anyways, I think the value is not only the features themselves, the biggest value I see is making the API more concise. I am new to this lib, and it was quite un-intuitive for me to understand the difference between arguments and options, in term of API. after learning the Options api, I would expect to have the same things for arguments. also, I have a complex program with many sub-commands, and it's nice to have common arguments, just like I have common options (many commands use the same options and same arguments, like fileName argument). sadly, with the current implementation of arguments I can't have common arguments. Adding Choices and all the other sweet stuff is a nice bonus also:) 

So I think I will start by introducing the new API without adding new capabilities like choices, and later I'll them.

**Comment by shadowspawn** [comment]
`.argument()` added in #1467 #1490 #1497 for Commander v8

**Comment by shadowspawn** [comment]
The support for defaults and custom parsing with `.argument()` has landed on `release/8.x`, which makes `.choices()` a simpler addition.

**Comment by shadowspawn** [comment]
Would you like to have first go at this @Niryo ?

**Comment by Niryo** [comment]
@shadowspawn sure. i'll notice here when I am starting to work on it (until then if anyone see this and want to start working on it, you are welcome to do so)

**Comment by shadowspawn** [comment]
I have made a start on this.

**Comment by shadowspawn** [comment]
Released in Commander v8.
