### ISSUE TITLE
Command' is not assignable to type CommanderStatic.Command

### ISSUE THREAD

**Issue by QiShaoXuan** [tj/commander.js#1465]
I try to create an init command using TypeScript, as follows：

```ts
import { Command } from "commander";
export const init = ():Command => {
  const init = new Command("init");

  init
    .arguments("[name]")
    .option("--disable-lint", "disable lint", false)
    .action(async (name = "", options) => {
      //  my action
    });

  return init;
};
```

But at last return init, typescript report error:

TS2322: Type 'import("/Users/qishaoxuan/work/leo/node_modules/commander/typings/index").Command' is not assignable to type 'import("/Users/qishaoxuan/work/leo/node_modules/commander/typings/index").CommanderStatic.Command'.   The types returned by 'version(...)' are incompatible between these types.     Type 'Command' is not assignable to type 'this'.       'Command' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'Command'.

**Comment by shadowspawn** [comment]
The TypeScript definitions are a little complicated to support the legacy default export of a global command, and to work-around an issue in an older version of TypeScript. The net result is that `Command` is an interface and also a constructor. I think this is causing the error for your use case.

From experimenting, a work-around is to import this way:

```ts
import * as commander from "commander";

export const init = ():commander.Command => {
  const init = new commander.Command("init");

...

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Hopefully will fix this in Commander v8.

**Comment by shadowspawn** [comment]
In Commander v8 the TypeScript has been refactored and this is fixed. Prerelease available now.

**Comment by shadowspawn** [comment]
Released in Commander v8.
