### ISSUE TITLE
How to override options?

### ISSUE THREAD

**Issue by Githubber2021** [tj/commander.js#1468]
Hi, this is just a support question, please excuse me if this is not the right channel for this. To make it short, I am trying to find a solution to simulate the following two commands:

```
git checkout -b name
git checkout 1234567
```

Is there any way to get both into the same command?

```.command('checkout')
  .option('-b, --branch <name>')
```

I am not sure how the second option could look like. Thank you!

**Comment by shadowspawn** [comment]
You can declare command-arguments when you add the command, or by calling the `.arguments()` routine.

```js
const { program } = require('commander');

program
  .command('checkout [start-point]')
  .option('-b, --branch <name>')
  .action((startPoint, options) => {
    console.log(`Branch: ${options.branch}`);
    console.log(`Start point: ${startPoint}`);
  });

program.parse();
```

```sh
% node index.js checkout -b name
Branch: name
Start point: undefined
% node index.js checkout 123456
Branch: undefined
Start point: 123456

```

**Comment by Githubber2021** [comment]
Thank you so much!
