### ISSUE TITLE
Poll: change api for adding command arguments?

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1471]
The syntax for adding command arguments which have help descriptions is quite different from the rest of the API, and arguments and options are added quite differently although they could be similar. (Prompted by discussion about offering `.choices()` for arguments in #1458.)

A couple of questions for feedback via reactions or comments.

**Comment by shadowspawn** [comment]
Should `.argument(usage, description)` replace the use of `.description()` for supplying optional help for the command-arguments? 👍 👎

**Comment by shadowspawn** [comment]
Should `.argument()` replace the use of `.arguments()` for adding command-arguments? 👍 👎

**Comment by shadowspawn** [comment]
Not huge numbers, but unanimous positive response after a month. (Thanks for feedback.)

1. 8 👍 
2. 5 👍

**Comment by NicolasThierion** [comment]
I found I can coerce options with a function as a third parameter.
Is there any plan to allow argument corecion the same way with this new syntax ?

**Comment by shadowspawn** [comment]
Yes, planned and done. `.argument()` supports coercion (custom processing) and default value, following same pattern as `.option()`.

https://github.com/tj/commander.js/pull/1508
