### ISSUE TITLE
how run other command in my CLI?

### ISSUE THREAD

**Issue by 779102260** [tj/commander.js#1476]
i want to integrate NRM into my CLI
can  run nrm but can't interact
here is my code
```js
program
    .command('nrm [args...]')
        .action(nrm)
/**
 * nrm
 * @param {*} args
 */
async function nrm(args) {
  if (!process.env.HOME) {
    process.env.HOME = process.env.USERPROFILE
  }
  exec(`npx nrm ${args.join(' ')}`, (error, a) => {
    if (error) {
      console.log(error)
      return
    }
    console.log(a)
  })
}
```

**Comment by shadowspawn** [comment]
Do you see the same problem if you call your `nrm()` function directly without using Commander?

I think perhaps you need to set `stdio` to `inherit` for the subprocess if you want to interact. See: https://nodejs.org/api/child_process.html#child_process_options_stdio

**Comment by 779102260** [comment]
> Do you see the same problem if you call your `nrm()` function directly without using Commander?
> 
> I think perhaps you need to set `stdio` to `inherit` for the subprocess if you want to interact. See: https://nodejs.org/api/child_process.html#child_process_options_stdio

thanks!

**Comment by MaganAnkur** [comment]
@779102260 could you pls help how did you manage to run npx command.
Thanks in advance.
