### ISSUE TITLE
Required non-option arguments only checked with .action()?

### ISSUE THREAD

**Issue by kevinoid** [tj/commander.js#1493]
It appears that `commander@7.2.0` only checks `.arguments()` for the top-level command if `.action()` is given.  For example:

```js
#!/usr/bin/env node
const { Command } = require('commander');
const command = new Command();
command
  .arguments('<source>')
  .allowExcessArguments(false)
  .description('do something with a single source file')
  .action(() => {});
command.parse();
console.log('Called with arguments:', command.args);
```

Has the following behavior

    $ ./example.js
    error: missing required argument 'source'
    $ ./example.js one
    Called with arguments: [ 'one' ]
    $ ./example.js one two
    error: too many arguments. Expected 1 argument but got 2.

If `.action(() => {});` is commented out, it has the following behavior:

    $ ./example.js 
    Called with arguments: []
    $ ./example.js one
    Called with arguments: [ 'one' ]
    $ ./example.js one two
    Called with arguments: [ 'one', 'two' ]

Which was surprising to me.  If this is intentional, perhaps a comment could be added to the [Specify the argument syntax section of `Readme.md`](https://github.com/tj/commander.js/blob/master/Readme.md#specify-the-argument-syntax) to warn users?  If not, perhaps it could be fixed?

Thanks for considering,
Kevin

**Comment by shadowspawn** [comment]
Yes, the number of arguments is currently only checked if there is an action handler. More existing behaviour and implementation details than intentional. I'll think about best way forward.

(For historical interest, before Commander v5 the options were not checked either unless there was an action handler.)

**Comment by shadowspawn** [comment]
In Commander v8 the number of arguments is checked whether or not there is an action handler. Prerelease available now.

**Comment by kevinoid** [comment]
That's great.  Thanks @shadowspawn!  I gave `commander@8.0.0-0` a quick test and `example.js` from above works perfectly for me, with or without `.action(() => {})`.  Thanks again!

**Comment by shadowspawn** [comment]
Released in Commander v8.
