### ISSUE TITLE
Unable to read options as expected from command action options parameter

### ISSUE THREAD

**Issue by hak33m16** [tj/commander.js#1494]
**Versions**
commander.js: 7.2.0
node.js: 12.12.0

**Issue**
When trying to read the value of options specified on a command, I run into unexpected behavior in terms of what the options object is that's passed into the `action` closure for a new command. A minimum working example:
```
const { Command, Option } = require("commander");
const program = new Command();

let somecommand = new Command('somecommand')
    .description('An example command')
    .action((env, options) => {
        console.log(options.custom_flag) // returns 'undefined'
        console.log(options._optionValues.custom_flag) // returns 'customflagval'
        console.log(somecommand.opts().custom_flag) // returns 'customflagval'
    });

let custom_flag = new Option('-c, --custom_flag <customval>',
    'A custom string value flag')

somecommand.addOption(custom_flag)

program.addCommand(somecommand);

program.parse(process.argv);
```
(Code above is invoked with `<executable_name> somecommand --custom_flag customflagval`)

Based off of the [example provided here](https://github.com/tj/commander.js/blob/master/examples/deploy#L18), I'd expect that the first `console.log` statement would work, but that doesn't seem to be the case

As an aside, if I were to rely on the method used in the second or third `console.log`, could I expect to see any issues? I suspect that the third may be referencing internal mechanics, but I'm not sure about the second

**Comment by shadowspawn** [comment]
From the README: 

> The action handler gets passed a parameter for each command-argument you declared, and two additional parameters which are the parsed options and the command object itself.

In the example you linked, the subcommand is added with `.command('setup [env]')` so the first parameter to the action handler is the `env` parameter supplied on the command line.

In your code, your subcommand has no arguments. So renaming the parameters to match what is passed will hopefully make the observed behaviour make more sense.

```
    .action((options, cmd) => {
        console.log(options.custom_flag)
        console.log(cmd._optionValues.custom_flag)
        console.log(cmd.opts().custom_flag)
    });
```

> As an aside, if I were to rely on the method used in the second or third console.log, could I expect to see any issues? I suspect that the third may be referencing internal mechanics, but I'm not sure about the second

    console.log(options._optionValues.custom_flag)

Expect issues. By convention, properties starting with an underscore are considered private. This could break without warning in new version of Commander.

    console.log(somecommand.opts().custom_flag)

This is fine. `.opts()` is a public and documented method. It is the intended way of getting option values from a command Object.

**Comment by hak33m16** [comment]
Wow, can't believe I missed that, thanks for taking the time to go over that. I figured it might be something trivial, but I couldn't find an IRC/Slack channel to get help in. Sorry for the false alarm

**Comment by shadowspawn** [comment]
No problem, and thanks for writing a tidy working code example.
