### ISSUE TITLE
add required option

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1495]
is there any api like `addOption` for adding a required option?

**Comment by shadowspawn** [comment]
No there is not a separate API method, as you use `.addOption()` itself.

```
program
  .addOption(new Option('-r,--required <value>', 'required option').makeOptionMandatory());
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
