### ISSUE TITLE
Refactor index.js

### ISSUE THREAD

**Issue by Niryo** [tj/commander.js#1496]
Are we intentionally keeping this god `index.js` file as is, or are there plans for breaking it down to more manageable pieces? 
I am interested in contributing more stuff to this lib, and I thought that breaking up this huge file could be a good start if there are no objections...

**Comment by shadowspawn** [comment]
My main concern with splitting up the monolithic `index.js` is if there are any common client use cases that would be broken by changing to multiple files. (No?)

A minor downside is refactoring the file makes it a harder to track back through the history to find why certain lines of code and logic were introduced. But the benefits to future work outweigh this.

For interest, the file was split up in #661 in a branch to modernise the codebase for v3.

**Comment by Niryo** [comment]
About the first concern- I am not sure I can't think of a use case were client could be broken because of internal arrangement as long as the api stays the same. The api is the contract, everything else can change.

About the downside- yep, this is an annoying limitation of git, but as you said, the benefits to future work outweigh the this. 
And if you really need to track back through the history, you can still do it, nothing is lost, it just became less convenient.

For me it was super annoying to orient myself inside this huge index.js file, and a split is a no-brainer decision.

**Comment by shadowspawn** [comment]
I had a play around with refactoring, but naively splitting Help and Command introduced a circular dependency. Keeping Help and Command in the same file is still the majority of the code. Not a trivial exercise. e.g.

https://github.com/shadowspawn/commander.js/tree/feature/refactor/src

**Comment by shadowspawn** [comment]
I'll have another go at this when Pull Requests are quiet.

**Comment by Niryo** [comment]
few notes:
1. I am not sure what are the implications of cyclic dependencies here, maybe when can live with it if we can't find any workarounds. But my hunch is that we can probably find a way to structure things in such a way that remove the cyclic dependency.
2. Even if keep those classes in the same file, we will still benefit from extracting small classes, even minor ones.
3. We can also extract pure functions. currently we have many big methods that sits inside the classes themselves, and some of them can be transformed to pure functions sittings outside the classes (where it makes sense of course, not all methods should be extracted this way).

**Comment by shadowspawn** [comment]
Released in Commander v8.
