### ISSUE TITLE
Editing error

### ISSUE THREAD

**Issue by DiaxManPl** [tj/commander.js#1498]
Is there any way to edit this: 
![image](https://user-images.githubusercontent.com/63294962/113859950-c1b20700-97a5-11eb-82d5-1bbae5f83500.png)
I want to make custom "unknown option" text.

**Comment by shadowspawn** [comment]
There is not direct support for changing the error messages.

You could perhaps override `outputError` and intercept the message, or if you want additional text after the current message is displayed could catch the matching error and add the text.

https://github.com/tj/commander.js#override-exit-and-output-handling

**Comment by DiaxManPl** [comment]
Thanks. `outputError` doesn't work, but custom error handling does.

**Comment by DiaxManPl** [comment]
Oh. Custom error handling does not replace the message. It just adds custom text to the message.

**Comment by shadowspawn** [comment]
This is how I thought `outputError` could be used.

```js
const { program } = require('commander');

program.option('-p, --port <number>');

program.configureOutput({
  outputError: (str, write) => {
    if (str.startsWith('error: unknown option'))
      write('custom unknown option error\n');
    else
      write(str);
  }
});

program.parse();
```

```
$ node index.js --port
error: option '-p, --port <number>' argument missing
$ node index.js --surprise
custom unknown option error
```

**Comment by DiaxManPl** [comment]
Thanks a lot! It works!

**Comment by shadowspawn** [comment]
There is an  open issue about adding support for modifying and/or localising error messages:  #1801
