### ISSUE TITLE
Get result of the action that commander has run

### ISSUE THREAD

**Issue by RickEyre** [tj/commander.js#1503]
I'd like to get the result of the action that commander has run after running `parseAsync`.

```js
const result = await commander.parseAsync(args, { from: 'user' })
console.log(result) // result of command action that was run here
```

Is this possible?

**Comment by shadowspawn** [comment]
Commander assumes the action handler does not return a value and does not store it.

So up to you to record a result external to Commander as a side-affect of calling the action handler.

**Comment by RickEyre** [comment]
Understood. Thank you.
