### ISSUE TITLE
Show expanded help

### ISSUE THREAD

**Issue by YuriGal** [tj/commander.js#1506]
Is there a way to display short descriptions when global help command is called, e.g.
```
myprogram help

# Commands:
#  command1 <parameter>  description 1 goes here
#  command2 <parameter>  description 2 goes here   
```

  [1]: https://www.npmjs.com/package/commander
but also have ability to show expanded help when help for specific command is called:
```
myprogram help command1

# command1 is used for...
#
# ... detailed description
#
# ...

**Comment by shadowspawn** [comment]
There is not currently support for setting different descriptions for the two use cases, but there is some support for providing a custom solution yourself. You can customise `commandDescription()` and `subcommandDescription()` using `.configureHelp()` or a Help subclass.

(You can also add extra text to the specific command help with `.addHelpText()`, but that is different than what you were asking.)

Related: #898 #1291

**Comment by YuriGal** [comment]
Thanks for the prompt response and pointing me to the right direction!

**Comment by shadowspawn** [comment]
Opened a PR to add `.summary()` for a short summary to use when listing subcommands.
