### ISSUE TITLE
Equal sign separator

### ISSUE THREAD

**Issue by YuriGal** [tj/commander.js#1509]
Is there a way to create option with equal sign instead of space separating option and value, e.g.
```
.option('-p, --pizza-type=<type>', 'flavour of pizza');
```
Also, if I have several commands added - is there a way to pass unknown command? We use commander mostly to build rich help system, but there are command that just need to pass thru for the rest of the code to take care of them.

**Comment by shadowspawn** [comment]
> Is there a way to create option with equal sign instead of space separating option and value, e.g.
> .option('-p, --pizza-type=<type>', 'flavour of pizza');

That is not the format the code is expecting. If you really want this, you could modify the string before passing to Commander in a subclass of Command with an override to `.option()`.

> Also, if I have several commands added - is there a way to pass unknown command?

Not as such. But you may be able to get similar runtime by declaring that the program accepts arguments (so the unknown command is accepted as an argument).

**Comment by YuriGal** [comment]
Once again thank you for prompt help.
