### ISSUE TITLE
parse args from config file

### ISSUE THREAD

**Issue by timoxley** [tj/commander.js#151]
Can we bake something like the way mocha handles mocha.opts, straight into mocha? I often want to be able to choose from loading from config vs commandline vs overriding config with commandline args.

Perhaps:

``` js
.options('')// etc
.config('myapp.opts') 
.parse(process.argv) //etc
```

Perhaps the config file is overridable on the commandline with --config-file (though there's issues if anyone has defined this already as an option) or perhaps it can read from stdin 

e.g. 

```
$ cat /var/myconfig.opts | ./bin/myapp
```

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by jakobrosenberg** [comment]
Hi @shadowspawn. Much appreciate all your hard work around here.

Do you know if there has been any changes in regards to config files since this was posted?

**Comment by shadowspawn** [comment]
Thanks @jakobrosenberg 

I think the original poster was talking about supplying default values for options, but the subsequent conversation was more about adding new options from a control file. No changes related to config files in last year in either case.

**Comment by shadowspawn** [comment]
New open issue is #1584
