### ISSUE TITLE
Distribution options

### ISSUE THREAD

**Issue by MrMathias** [tj/commander.js#1518]
I have build a somewhat extensive CLI using commander.js, which is working out pretty great. - However I am hitting my head against the wall when it comes to distribution. 

I had hoped to use pkg, nexe, or a similar tool, to package the node project into a binary executer for distribution. This is doable in principle, but I now learn that macos' codesign tool does not accept the binaries produced with any of these packaging tools and throws a "strict validation" error. - Something about the macho file not being correctly structured.

So I am in desperate need of an alternative to single-binary distribution, or better yet, I would love to see a solid guide for packaging the commander node project into a binary, in a way that makes it sign-able by codesign..

Hope anyone have pointers or experience with this.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a month. The question is not abut Commander as such, and I don't have any insights myself.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
I came across a list of packaging tools and remembered this issue. No explicit mention of code-signing, but a good list of possibilities:
https://github.com/styfle/awesome-desktop-js#packaging
