### ISSUE TITLE
Parameter name collisions

### ISSUE THREAD

**Issue by RasterBurn** [tj/commander.js#152]
Parameter names you specify can collide with properties on the program object.

For instance, if you specify a "--password <password>" parameter, it will overwrite the `.password()` function.

**Comment by mvayngrib** [comment]
collisions aside, collapsing the command/program and passed options objects makes for a weird coding and debugging experience. To see the options passed in under the debugger, I have to do mental gymnastics to separate Command properties from the options specified for my particular command. The ugly workaround I'm using:

```js
const deployCommand = program
  .command('deploy')
  .option('-m, --models', 'deploy models')
  .action(function (cmd) {
    const opts = _.pick(cmd, deployCommand.options.map(opt => opt.name())) // <-----
    actuallyDeploy(opts)
  })
```

It would nice to be able to not have to worry about this, and be able to get all the passed options, e.g. via `program.parsed.options`, `command.parsed.options`.
