### ISSUE TITLE
Set default option value to required option value?

### ISSUE THREAD

**Issue by paul-uz** [tj/commander.js#1530]
I have some required options and optional options.

Is there a way I can set a default value of an optional option to that of a required option?

Or is there a way to define conditional options? EG 

* if option A is set, dont allow option B
* if option B is set, required option C as well

**Comment by shadowspawn** [comment]
Commander does not directly support interactions between options.

The related open issue is: #1358

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. There is still an open issue about "implied" which has been the most popular variation.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
