### ISSUE TITLE
[TypeScript typings]Accept generics value object for opts()

### ISSUE THREAD

**Issue by tyankatsu0105** [tj/commander.js#1536]
## What
In TypeScript, I want to use generics for opt methods.

```ts
type OptionValues = {
  cheese: string;
};

const options = program.opts<OptionValues>();

options.cheese
        ^^^^^^
// => (property) OptionValues.cheese: string
```

## Why

Now, interface OptionValues is record type that value is any.
https://github.com/tj/commander.js/blob/327a3ddd552f90d1dbd37f55fa7a88b9553468ae/typings/index.d.ts#L159-L161

I think generics help developers with TS if override the OptionValues type.

**Comment by shadowspawn** [comment]
Released in Commander v8.

**Comment by shadowspawn** [comment]
For some experimental strong inferred typing see: https://github.com/commander-js/extra-typings
