### ISSUE TITLE
Check if parameter was specified or is default

### ISSUE THREAD

**Issue by jakobrosenberg** [tj/commander.js#1541]
Is there a way to check whether a parameter has been manually set?

I would like to be able to prompt users for input on arguments that they haven't passed.

**Comment by shadowspawn** [comment]
Unless you include a default value in code, options which have not been specified on the command line will be undefined.

(For some special cases you can use listeners to option events, but I wouldn't start there.)

**Comment by jakobrosenberg** [comment]
I ended up putting program inside program, so now I can run program while I run program. 😎

```javascript
const createProgram = (defaults, optionsWithDefaults) => program
    .command('create [a-value]')
    .option('-a, <value>', 'this is a', defaults.a)
    .option('-b, <value>', 'this is b', defaults.b)
    ...
    .option('-z, <value>', 'this is z', defaults.z)
    .option('-d --use-defaults', 'use defaults when available')
    .action((aValue, options, command) => {

        if (!optionsWithDefaults) {
            // 1st iteration - get defaults and rerun createProgram. For 2nd run move
            // defaults to the second parameter so commanderjs doesn't receive them
            createProgram({}, options).parse(process.argv);
        } else {
            // 2nd iteration - commanderjs was created without defaults this time, so options
            // only include user specified values
            myApp.run({
                ...optionsWithDefaults,
                userSpecifiedOptions: options, // I won't prompt for these values
            });
        }
    });

createProgram(defaultsForCreate);
```

It feels a bit hackish, but gets the job done. It lets me prompt users for unspecified arguments when `--use-defaults` isn't used.

I might do `myApp.run(optionsWithDefaults.useDefaults ? optionsWithDefaults : options)` in the future.

**Comment by shadowspawn** [comment]
Some approaches suggested (including from OP), and no further activity in a month.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by cirosantilli** [comment]
A simpler approach is to leave ungiven values undefined:

```
.option('-a, <value>', 'this is a')
```

and at the end merge with:

```
options = lodash.merge({}, defaults, commander.program.opts())
```

which skips undefined values when merging.

The only problem is that it doesn't work for boolean options, which are always true or false, and I can't see how to check if they were passed without hacks.

**Comment by shadowspawn** [comment]
> Is there a way to check whether a parameter has been manually set?

There is now. The `.getOptionValueSource()` method was added in Commander v8.3 . The sources of interest are `default`, `env`, and `cli`.

**Comment by cirosantilli** [comment]
:pray:
