### ISSUE TITLE
Poll: Enhancements to global options

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1551]
Commander supports global options by declaring them on the program. This is flexible, but Commander does not offer any additional support to make them easier to use as a programmer or find them as a user. Example program with current behaviour:

```js
program
  .option('-g, --global');

program.command('sub')
  .option('-l, --local')
  .action((options, sub) => {
    console.log('subcommand options: %o', options);
    console.log('global options: %o', program.opts());
  });

program.parse();
```

```sh
$ node example.js --global sub --local
subcommand options: { local: true }
global options: { global: true }
```

```sh
$  node example.js help sub
Usage: example sub [options]

Options:
  -l, --local
  -h, --help   display help for command
```

Related: #243 #476 #905 https://github.com/tj/commander.js/pull/1024#issuecomment-568403615 #1078 #1426 #1631

What additional support would you like? (I am wondering what is most popular and useful, not planning to add everything!)

**Comment by shadowspawn** [comment]
1) An explicit way to access combined global and local options from action handler, without needing to use program variable.

This could be a parameter to `.opts()`, or a separate routine.

```js
console.log('combined options: %o', sub.opts({ includeGlobals: true }));
```

**Comment by shadowspawn** [comment]
2) Configuration so `.opts()` and the options passed to the action handler always include combined global and local options.

```js
program.includeGlobalsInOptions();
```

**Comment by shadowspawn** [comment]
3) A way to show the global options in the help for a subcommand.

```js
program.includeGlobalOptionsInHelp();
```

```sh
$  node example.js help sub
Usage: example sub [options]

Options:
  -l, --local
  -h, --help   display help for command

Global Options:
  -g, --global
```

**Comment by shadowspawn** [comment]
4) A way to add a shared option that is actually added to (all) the subcommands, rather than the program.

```js
program.sharedOption('-l, --local');
```

**Comment by binyamin** [comment]
@shadowspawn what is the time span for this poll?

**Comment by shadowspawn** [comment]
Counts at 2021-12-21.

1) An explicit way to access combined global and local options from action handler, without needing to use program variable.
    8 👍 

2) Configuration so .opts() and the options passed to the action handler always include combined global and local options.
    3 👍 

3) A way to show the global options in the help for a subcommand.
    4 👍 5 🚀 (6 people total)

4) A way to declare a common option that is actually added directly to (all) the subcommands, rather than to the program. 
    10 👍 

Thanks for the feedback.

**Comment by shadowspawn** [comment]
@binyamin
> what is the time span for this poll?

I wasn't working on global options, and two of the options have been tracking with similar numbers of votes, so I had just left the poll open!

**Comment by shadowspawn** [comment]
Opened a draft PR for `.addCommonOption()` #1670 

FYI: @rhyslbw @GerkinDev @WinterWolf98 @phi0411141 @kasperisager @zecka @mikemilano @aprat84 @ramoncarreras @DavidDudson

**Comment by shadowspawn** [comment]
Opened a draft PR for `.opts({ includeGlobals: true })` #1671

FYI: @shivanshs9 @GerkinDev @gralka @kuncevic @guillaumeLamanda @mikemilano @sureshkmit @binyamin

**Comment by shadowspawn** [comment]
Opened a PR to optionally show global options in the help: #1828
