### ISSUE TITLE
Exit without throwing an error when missing arguments?

### ISSUE THREAD

**Issue by Jakobud** [tj/commander.js#1552]
I created a simple program like this:

```
// Create cartridge
  program
    .command('doSomething <name>')
    .action(name => {
      // code here
    });
```

`node myCommand.js doSomething <name>`

When I run the command without the `name` argument, I get the typical help message in the terminal, etc.

Now, if I wrap my command in an npm script in a package.json like this:

```
...
  "doSomething": "node ./path/to/my/myCommand.js doSomething"
...
```

And I run this npm script without the argument:

```
npm run doSomething
```

I get the Commander help message, etc, but I also get an NPM error

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 doSomething: `node ./path/to/my/myCommand.js doSomething`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 doSomething script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my/.npm/_logs/2021-06-28T16_08_08_466Z-debug.log
```

So what is going on here exactly? Is this because Commander is actually ending the process with an error code because of the missing argument? And NPM is seeing this and reporting the error? Is it possible to set Commander so that it exits the process gracefully without an error?

**Comment by Jakobud** [comment]
I figured this out by wrapping the parsing in a try catch statement. Thanks,

**Comment by shadowspawn** [comment]
Just confirming: yes, Commander is exiting with a non-zero status for missing argument. And npm is noisy about error exit status!

It sounds like you are sorted, but for future readers two approaches are: if you jut want to modify the special no-arguments case test then you could test yourself before calling `.parse()`, or if you want to change the exit status for all errors use `.exitOverride()`.

**Comment by Jakobud** [comment]
What exactly does `exitOverride()` do? Is wrapping the `.parse` in a `try catch` not enough?

**Comment by shadowspawn** [comment]
Normally when Commander encounters an error during parsing, it displays an error and calls `process.exit(1)`. This is not caught by `try/catch`, so I would not expect the `try/catch` alone to change the behaviour for missing arguments.

`.exitOverride()` overrides the call to exit. The default behaviour is to throw, but for example you could call `process.exit(0)` to suppress the error exit status.

**Comment by birgersp** [comment]
Shouldn't the ["required option" section of the README](https://github.com/tj/commander.js#required-option) mention this? I tried to follow the example in the README but all I got was the exit with status 1, and no error output about the missing args. Had to come here to see how to actually get the same output as in the example.

**Comment by shadowspawn** [comment]
@birgersp 
I am not seeing any problems with `.requiredOption()`. I suggest you open a new issue with more details.

**Comment by XhmikosR** [comment]
Is there an example with combining required options and optional ones? Say for example one supports `--reporters` which would just print something but otherwise require a `file` option.

**Comment by shadowspawn** [comment]
@XhmikosR that sounds like #1408, and not related to this issue.

**Comment by birgersp** [comment]
> @birgersp I am not seeing any problems with `.requiredOption()`. I suggest you open a new issue with more details.

I think you missed my point.

[The requiredOption example](https://github.com/tj/commander.js#required-option) shows:

```
program
  .requiredOption('-c, --cheese <type>', 'pizza must have cheese');

program.parse();
```
```
$ pizza
error: required option '-c, --cheese <type>' not specified
```

But this example is false information. If you ran (exactly) this code, you don't actually get the demonstrated error message.

You just get "returned with exit code 1".

**Comment by shadowspawn** [comment]
@birgersp 
As it happens, I did correctly understand your problem. I suggest again you open a new issue so we can investigate your problem.

1) This issue and the original post are about modifying the exit status, not about a missing error message.

2) Authors do not normally need to call `.exitOverride()` and add a try/catch to get the error message out. Here I am running the example code used in the README directly from a clone of this repo. (I am on a Mac, running the example in Terminal.)

```console
$ node examples/options-required.js
error: required option '-c, --cheese <type>' not specified
```

3) There is nothing special about this error, so I would expect to see similar behaviour with all errors.

There is potential for the error message to be lost if the call to `process.exit()` causes pending standard error output to be lost. Happily this does not normally happen, so we would need to find out more about your situation: what OS, what shell. You mentioned "returned with exit code 1" which might be a clue, as I am not sure what is producing that.
