### ISSUE TITLE
Using options that start with hyphen

### ISSUE THREAD

**Issue by sunknudsen** [tj/commander.js#1556]
Hey guys,

Thanks so much for this library.

I developed a CLI to manage YouTube and PeerTube content (called [tube-manager](https://github.com/sunknudsen/tube-manager)).

I recently reached an interesting edge case when running following.

```console
$ tube-manager import -J6vK5kK3Ms
error: unknown option '-J6vK5kK3Ms'
```

I then tried running following.

```console
$ tube-manager import "-J6vK5kK3Ms"
error: unknown option '-J6vK5kK3Ms'
```

Same result… `-J6vK5kK3Ms` is a valid YouTube video ID.

Is there a way around this? If this isn’t a bug (which I guess is the case), is it possible to disable single hyphen options?

Thanks!

**Comment by sunknudsen** [comment]
Found a workaround…

```console
$ tube-manager import -- -J6vK5kK3Ms
```

That said, workaround requires being aware of `--`.

Hoping there is an alternative.

**Comment by shadowspawn** [comment]
One approach is allow unknown options. I suggest you also turn on error for excess arguments to pick up typos in option names indirectly.

```js
program
  .command("import <id>")
  .option("--config <config>")
  .allowUnknownOption()
  .allowExcessArguments(false)
  .action((id, options) => {
    console.log(`id: ${id}`);
    console.log(options);
  });
```

```sh
$ node index.js import -J6vK5kK3Ms        
id: -J6vK5kK3Ms
{}
$ node index.js import -J6vK5kK3Ms --config file
id: -J6vK5kK3Ms
{ config: 'file' }
$ node index.js import -J6vK5kK3Ms --configure oopts
error: too many arguments for 'import'. Expected 1 argument but got 3.
```

**Comment by shadowspawn** [comment]
A more radical approach is to make the problematic argument an option-argument rather than a command-argument.

```js
program
  .command("import")
  .option("--config <config>")
  .option("--id <id>")
  .action((options) => {
    console.log(options);
  });
```

```sh
$ node another.js import --id -J6vK5kK3Ms --config file
{ id: '-J6vK5kK3Ms', config: 'file' }
```

**Comment by sunknudsen** [comment]
Thanks so much for helping out @shadowspawn.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
