### ISSUE TITLE
How to have .version(VERSION, '-v, -V, --version, 'Output the version number')?

### ISSUE THREAD

**Issue by SrBrahma** [tj/commander.js#1559]
I want to have -v, -V and --version. I tried `.version(VERSION, '-v, --version', 'Output the version number')` but the --version is not recognized. How to do it?

**Comment by shadowspawn** [comment]
Commander supports a short option flag, a long option flag, or both.

To add a third option flag to show the version you could add another option, make it hidden, and handle displaying the version yourself. (To have the option show the version as soon as parsed and not proceed, put the code in an event listener for `option:optionName` and exit.)

**Comment by shadowspawn** [comment]
For example:

```js
program
   .version(VERSION)
   .addOption(new Option('-v, --secretVersion').hideHelp());

program.on('option:secretVersion', () => {
  console.log(VERSION);
  process.exit();
});
```

**Comment by SrBrahma** [comment]
Thanks for the quick reply! Will use it.

I don't know the deep working of the Commander, but I think there should be a more straight forward and smaller way to set those 3 options. I never use the -V (only -v and --version), but I will always want it since there it appears to also be a default way to check it. Maybe there could be a .version argument to set this up?
