### ISSUE TITLE
Detect option as string or number?

### ISSUE THREAD

**Issue by paul-uz** [tj/commander.js#1560]
It seems all option values are passed as strings, even if the value is `123`.

How can I parse the value to pass it as a string, or number, based on the value?

**Comment by shadowspawn** [comment]
Have a look at the custom option processing: https://github.com/tj/commander.js#custom-option-processing

In the `myParseInt` example, you could just return the argument if it is not a number, instead of throwing an error.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
