### ISSUE TITLE
Add support for required options with choices

### ISSUE THREAD

**Issue by Thomas-Smyth** [tj/commander.js#1564]
## Background: Required Options
Currently, to make an option be required one may use the `requiredOption` method.

For example:
```js
program.option('-f, --favourite-cake <name>', 'your favourite cake');
```
Would become:
```js
program.requiredOption('-f, --favourite-cake <name>', 'your favourite cake');
```

## Background: Choices
Currently, to make an option have a set of valid values one may use the snippet `.addOption(new Option(...).choices([...]))`.

For example:
```js
program.option('-f, --favourite-cake <name>', 'your favourite cake');
```
Would become:
```js
program.addOption(
  new Option(
    '-f, --favourite-cake <name>', 
    'your favourite cake'
  ).choices([
    'Chocolate Fudge Cake',
    'Victoria Sponge',
    'Carrot Cake'
  ])
);
```

## Problem
To my knowledge and as far as the documentation is aware, there's currently no way to make an option required and specify a set of valid values.

I propose a new method be added to cater for this:
```js
program.addRequiredOption(
  new Option(
    '-f, --favourite-cake <name>', 
    'your favourite cake'
  ).choices([
    'Chocolate Fudge Cake',
    'Victoria Sponge',
    'Carrot Cake'
  ])
);
```

Alternatively, a new option/method be added to the `Option`  class.

**Comment by shadowspawn** [comment]
It is not included in the README, but there is a method on Option for this: `.makeOptionMandatory()`.

```
program.addOption(
  new Option(
    '-f, --favourite-cake <name>', 
    'your favourite cake'
  ).choices([
    'Chocolate Fudge Cake',
    'Victoria Sponge',
    'Carrot Cake'
  ])
  .makeOptionMandatory()
);
```

We talk about required options, and options with a required argument. When adding the support for the higher level  ".requiredOption()", `Option` already had a property called `required` for the required-argument case. I went with "mandatory" for the terminology in Option to make it distinct.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
