### ISSUE TITLE
delegate options without parsing them

### ISSUE THREAD

**Issue by link89** [tj/commander.js#1568]
Is `commander` support to delegate the options without parsing them just like what `npm` script does?
I am using `commander` to wrap some command-line tools to make them easier to use. I am trying to find a way to delegate options to the wrapped command so that users can set options to the wrapped commands when they need them.

For example
`npm test -- --changedSince=master` 

Which just delegate the `--changedSince` option to the wrapped jest command.
It would be great if `commander` can do the same thing.

**Comment by shadowspawn** [comment]
Commander supports `--` in this way, to mark the end of the options so any further arguments are passed through as command-arguments and not interpreted as options.

And added in Commander 7,  `. passThroughOptions()` means options that come after command-arguments are treated as plain arguments and passed through as further command-arguments.

See https://github.com/tj/commander.js#parsing-configuration

**Comment by link89** [comment]
Thank you @shadowspawn How can I read options passed after `--`?

**Comment by shadowspawn** [comment]
The option processing is turned off after the `--`, so the "options" are just treated as plain command-arguments.

```js
const { program } = require('commander');

program.command('test')
  .argument('<args...>')
  .action((args) => {
    console.log(args);
  });

program.parse();
```

```
% node index.js test -- --changedSince=master     
[ '--changedSince=master' ]
```
