### ISSUE TITLE
help(cb) is deprecated 

### ISSUE THREAD

**Issue by ZhangHang12135** [tj/commander.js#1575]
I want to use chalk to process the output。
el:
program.help(() => chalk.magenta(txt));

**Comment by shadowspawn** [comment]
Did you see the example in https://github.com/tj/commander.js/blob/master/docs/deprecated.md ?

For example:

```
console.log(chalk.magenta(program.helpInformation()));
process.exit(0); // If you want to exit, like `.help()` does
```
