### ISSUE TITLE
Strange behavior with asterisk in options.

### ISSUE THREAD

**Issue by mbaldi-orangeloops** [tj/commander.js#1576]
Good day, 
I'm having a problem where I want to accept a RegEx as an option and in the case of the RegEx: `/.*/` the input that arrives at the functions eliminates the asterisk leaving only: `/./`. Is this expected behavior?
`    .option("-e, --exceptions [RegEx]", "branches to exclude, RegEx are accepted", "")`
That is how I used the option.

Thanks in advance.

**Comment by shadowspawn** [comment]
The `*` is a special character which is interpreted by some operating systems, before it reaches the application.

On Mac and Linux, if you put single speech marks around an argument then the operating system leaves it alone.

```sh
% node -e 'console.log(process.argv)' '/.*/'
[ '/usr/local/bin/node', '/.*/' ]
```

**Comment by mbaldi-orangeloops** [comment]
I see. Thank you very much! This really helped me at work
