### ISSUE TITLE
Argument default value not working?

### ISSUE THREAD

**Issue by FunctionDJ** [tj/commander.js#1577]
As far as i can tell arguments can only be accessed using `program.args`.

When i have this code
```js
program
  .argument("[foo]", "", "default value")
  .parse()

console.log(program.args)
```
And call it using `node file.js`, it logs an empty array, unless i give it an argument. Shouldn't it print `["default value"]`?

I'm using commander `8.1.0` with Node v16.

Edit: Or is it for the console output only and developers need to handle it on their own? If that's the case, that should probably be documented.

**Comment by shadowspawn** [comment]
There is a little extra work for a simple single-command program to see the default value.

`program.args` has the original command-line arguments with the options removed.

To see the default argument value, or custom processing of options, you need to use an action handler.

```js
program
  .argument("[foo]", "", "default value")
  .action((foo) => {
    console.log(`action handler has foo: ${foo}`);
  })

program.parse();

console.log(program.args);
```

```
% node index.js
action handler has foo: default value
[]
% node index.js xyz
action handler has foo: xyz
[ 'xyz' ]
```

**Comment by shadowspawn** [comment]
I forgot there is a simpler option for your case, and it is mentioned in the README too when I looked again!

> The processed argument values are passed to the action handler, and saved as `.processedArgs`.

So try `program.processedArgs`.

**Comment by FunctionDJ** [comment]
@shadowspawn That's what i was looking for. Thank you!
