### ISSUE TITLE
Allow option to set global header/banner for all commands

### ISSUE THREAD

**Issue by tlylt** [tj/commander.js#1578]
Hello,

I am hoping to add a common banner that will be displayed as the first thing in the output when running any command. Similar to tj/commander.js#578, but for general commands and not for the help command. (Is Life cycle hooks the solution to my question?)

So for example a command output could become:
```
=====
MyProgram version 1.2.3
=====
Run successfully!
```

I have searched through the issues and found out that support has been added to customize help text and make it possible to do the above for help commands, via `addHelpText()` or `configureOutput()`. Although a solution has been suggested in this comment: https://github.com/tj/commander.js/issues/1272#issuecomment-638094152, would it be possible to add this functionality as part of commander.js?

So I imagine something like:
```javascript
program.banner("Custom Banner")
```

Thanks!

**Comment by shadowspawn** [comment]
As you suggested, I think a `"preAction"` hook might be a solution for your case.

```js
program.hook("preAction", () => console.log('BEFORE'));

program.command('foo')
  .action(() => console.log('hello'));

program.parse();
```

```
% node index.js foo 
BEFORE
hello

% node index.js foo --silly   
error: unknown option '--silly'
```

**Comment by tlylt** [comment]
> As you suggested, I think a `"preAction"` hook might be a solution for your case.
> 
> ```js
> program.hook("preAction", () => console.log('BEFORE'));
> 
> program.command('foo')
>   .action(() => console.log('hello'));
> 
> program.parse();
> ```
> 
> ```
> % node index.js foo 
> BEFORE
> hello
> 
> % node index.js foo --silly   
> error: unknown option '--silly'
> ```

Thank you for the speedy reply! After playing around with it, I think it would serve my purpose just right 😄

**Comment by kdubau** [comment]
Does not show when --help used though.
