### ISSUE TITLE
how to better organize commanderjs files?

### ISSUE THREAD

**Issue by tlylt** [tj/commander.js#1581]
Hello,

I am wondering if there is any recommendation on how to organize individual commands into separate files and how to assemble them back into a main `index.js` file?
This might be subjective but I suppose that is the more common practice for larger CLI tools. The examples given in the repo seem to all be single file examples. 

Thanks!

**Comment by shadowspawn** [comment]
No recommendation from me, very subjective. :-)

High-level, you have three levels of code isolation you could consider for adding subcommands:
- `.command()` with action handler, tightly coupled implementation as subcommand inherits program settings
- `.addCommand()` with action handler, loosely coupled implementation of program and subcommand
- implementing subcommands as stand-alone executable files, separate implementation of program and subcommand

In one of my programs I decided to declare all the subcommands and Commander setup in a single file, but the action handlers just call out to routines implemented in a separate file per command. My motivation was to have the CLI in one place so I could keep the style and terminology in the help consistent.

Related: #983

**Comment by tlylt** [comment]
Hi @shadowspawn, thank you! 
I think the examples provided in the mentioned related issue are exactly what I am looking for 😃
