### ISSUE TITLE
.action callback arguments

### ISSUE THREAD

**Issue by WinterWolf98** [tj/commander.js#1582]
When the `storeOptionsAsProperties` is set as true, two command objects are passed to the `.action` callback. Is this the expected behaviour ?

Also, I would like to know the best practice to get the actual command arguments because the function signature mentioned in NPM Readme and the typescript file are different. This leaves a TS developer like me confused.

**Comment by shadowspawn** [comment]
> When the storeOptionsAsProperties is set as true, two command objects are passed to the .action callback. Is this the expected behaviour ?

Yes. This is mentioned in the Migration Tips for 7.0.0:

> If you wish to restore the old behaviour and get running quickly you can call .storeOptionsAsProperties(). To allow you to move to the new code patterns incrementally, the action handler will be passed the command twice, to match the new "options" and "command" parameters (see below).

https://github.com/tj/commander.js/releases/tag/v7.0.0

**Comment by shadowspawn** [comment]
> Also, I would like to know the best practice to get the actual command arguments because the function signature mentioned in NPM Readme and the typescript file are different. This leaves a TS developer like me confused.

Do you mean using `.action()`? What strikes you as different about the signatures?

**Comment by WinterWolf98** [comment]
Sorry my bad, I got it wrong. Thank you for the clarification.
