### ISSUE TITLE
use template literal types to call 'opts' with type safely

### ISSUE THREAD

**Issue by anatawa12** [tj/commander.js#1585]
Since typescript 4.1, [template literal types] was coming. 
This feature enables us to call the 'opts' function with type safety without specifying types, I think. Could you implement this?

[template literal types]: https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

**Comment by shadowspawn** [comment]
There is an experiment with this in #1356. 

Related: #1245

**Comment by shadowspawn** [comment]
I think this may be too complex to do with the existing API. Deducing type for `.opts()` is hard enough, but there are also the arguments passed into the action handler. They are affected by `.argument()` as well!

An alternative interface for configuration might allow type deduction and a different style of setup (e.g. #665), in situations where preference or the benefits make it attractive. 

---

I saw an interesting related statement in the Clipanion documentation:

> We won't provide domain-specific languages (DSL). Once upon a time Clipanion actually worked like this, using a "natural" language to declare commands, but over time it became clear that we were merely fighting JavaScript, losing many useful tooling integrations.

https://mael.dev/clipanion/docs/

**Comment by shadowspawn** [comment]
This issue has not had any activity in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
For some experimental strong inferred typing see: https://github.com/commander-js/extra-typings
