### ISSUE TITLE
Running a stand-alone subcommand with zx

### ISSUE THREAD

**Issue by p3k** [tj/commander.js#1592]
We are trying to combine CommanderJS and [zx](https://github.com/google/zx) in subcommand and I noticed the zx extensions are not available then:

```js
// foo.mjs (called by `zx ./foo.mjs info`)

#!/usr/bin/env zx

import { program } from "commander/esm.mjs";

program.command("info", "output information").alias("i")
```

```js
// foo-info.mjs

#!/usr/bin/env zx

console.log(typeof $);
// undefined
```

As a work-around we certainly could import the extensions again (e.g. with `import { $ } from "zx"`) but it feels a bit redundant and wrong.

Is there an option to run a stand-alone subcommand with the correct binary? Or make CommanderJS respect the shebang `#!/usr/bin/env zx`?

**Comment by shadowspawn** [comment]
If you make `foo-info.mjs` executable and remove the file extension, then the file will be executed directly and the shebang will apply. (This does not work on Windows.)

If the file has a source extension then node is used to process it.

```js
const sourceExt = ['.js', '.ts', '.tsx', '.mjs', '.cjs'];
```

```
% zx foo.mjs i
function
```

**Comment by p3k** [comment]
great, that works! thanks for the explanation, @shadowspawn 

the only downside seems to be missing syntax highlighting due to the undefined file extension for editors…

**Comment by shadowspawn** [comment]
For interest...

Commander expects by default that `argv[0]` is the utility, `argv[1]` is the script name, and `argv[2]` is the first of the user supplied arguments. 

- https://nodejs.org/dist/latest-v16.x/docs/api/process.html#process_process_argv

But when launched by `zx` there is an extra argument which is `zx` itself.

```js
// foo.mjs
console.log(process.argv);
```

```
% zx foo.mjs install
[ '/usr/local/bin/node', '/usr/local/bin/zx', 'foo.mjs', 'install' ]
```

I think if `zx` replaced the `node` argument instead of adding afterwards, Commander would work ok with the file extension.

**Comment by p3k** [comment]
> I think if `zx` replaced the `node` argument instead of adding afterwards, Commander would work ok with the file extension.

good point. maybe this is due to `zx` being an npm module run by node, anyway…?

does this mean, i could tamper with the `argv` array myself and make this work somehow?

**Comment by shadowspawn** [comment]
If you can modify `process.argv`, yes. But is it read-only in esm?

**Comment by p3k** [comment]
> If you can modify `process.argv`, yes. But is it read-only in esm?

looking good, e.g.

```js
console.log(process.argv.length) // 4
process.argv.shift();
console.log(process.argv.length) // 3
```

**Comment by p3k** [comment]
and now zx works with scripts having file extension, too! awesome.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
