### ISSUE TITLE
Whitespace in argument not parsed correctly

### ISSUE THREAD

**Issue by charmpitz** [tj/commander.js#1594]
```
new commander.Command()
    .name('download')
    .requiredOption('--start <start>', 'Start time. ex: 3 hours ago')
    .option('-p, --path [path]', 'Path where to save.', './')
    .option('--end <end>', 'End time.', 'now')
```
Calling with `download --start="3 hours ago" --path ./data` I receive `start: '3' `
Calling with `download --start 3 hours ago --path ./data` I receive `start: '3'`

What I should receive is `start: '3 hours ago'`

**Comment by shadowspawn** [comment]
> Calling with `download --start="3 hours ago" --path ./data` I receive `start: '3' `

I can not reproduce this. I suspect the arguments have gone through a shell interpreter before reaching your program, like when used with an npm run script command. Try logging out the arguments that are being used by `.parse()`.

```js
const commander = require('commander');
program = new commander.Command();

program
  .name('download')
  .requiredOption('--start <start>', 'Start time. ex: 3 hours ago')
  .option('-p, --path [path]', 'Path where to save.', './')
  .option('--end <end>', 'End time.', 'now');

program.parse();

console.log(process.argv);
console.log(program.opts());
```

```
% node index.js --start="3 hours ago" --path ./data
[
  '/usr/local/bin/node',
  '/Users/john/Documents/Sandpits/commander/issues/1594/index.js',
  '--start=3 hours ago',
  '--path',
  './data'
]
{ path: './data', end: 'now', start: '3 hours ago' }
```

**Comment by shadowspawn** [comment]
> Calling with `download --start 3 hours ago --path ./data` I receive `start: '3'`

This is expected behaviour. The `--start` option takes a single argument. The other command line arguments get processed as command arguments, and will be in `program.args`.

(You could perhaps make this work by making `--start` a variadic option, and joining together the resulting array back into a single string.)

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
