### ISSUE TITLE
Option.argumentRejected declared but not implemented.

### ISSUE THREAD

**Issue by UrielCh** [tj/commander.js#1598]
Hi in your typing file your write:

````typescript
  /**
   * Validation of option argument failed.
   * Intended for use from custom argument processing functions.
   */
  argumentRejected(messsage: string): never;
````

but `argumentRejected` do not exist anywhere.

**Comment by shadowspawn** [comment]
Oops. That routine got removed in #1392 where we switched to explicitly throwing `InvalidOptionArgumentError`. This made it easier for custom option processing to use the same error message handling as from within Option or subclasses.

**Comment by shadowspawn** [comment]
Removed in Commander v8.2.0
