### ISSUE TITLE
'npm i commander' installs version 2.17.1 instead of a higher one

### ISSUE THREAD

**Issue by kiro7shiro** [tj/commander.js#1605]
Hello,

I'm a bit confused. I run `npm i commander` in my projects folder and npm installs version '^2.17.1' . The only reason I recognized this is because the subcommands doesn't work for me. Now I see there are much higher versions already released.
Is this an intended behavior? Because I though npm would automatically install the newest release of a library. Or am I doing something wrong? 
I'm on a Ubuntu 20.04.3 LTS 64Bit, Node 16.9.1, NPM 7.17.0 system. If someone can do something with it.

EDIT: I solved this for me by appending the latest version number to the 'install' command like `npm i commander@8.2.0`. But I think somebody should have a look.

**Comment by shadowspawn** [comment]
I suspect you already had commander installed. If you already have a package installed, `npm install foo` will install the latest version compatible with the version specification in your `package.json`.

```
$ npm install commander@2.17.0
...

$ grep commander package.json 
    "commander": "^2.17.0"

$ npm install commander

+ commander@2.20.3
updated 1 package and audited 1 package in 0.937s
found 0 vulnerabilities
```

The usual way of specifying you want the latest version is:

```
npm install commander@latest
```

(For interest, this is more subtle than it looks. npm looks up the version with the `latest` "tag" and installs that version. It does not install the highest version, which might be some prerelease. Often by convention tagged with `next`.)

**Comment by kiro7shiro** [comment]
No I don't have it installed already, It was a fresh project folder and I don't have installed globaly, too. I do have several other libraries installed before 'commander.js'.  And I didn't know that I have to specifiy the latest version in the install command, too. I assumed 'npm' will always try to install the latest version by itself and inform me. If that was not possible and another version was installed. At least this is what I remember from reading the docs and my expierence with other npm packages so far. 
I double checked the tag of version 8.2.0, too. It is tagged as 'latest'.  I do understand your explanation. But I don't get my head around why.

**Comment by shadowspawn** [comment]
I am guessing some interaction with the those previous package installs. You can find out what packages have installed what packages using `npm ls` or to see just commander, `npm ls commander`. But like you I would expect latest version to be manually installed normally. 

Can you reproduce the problem? If you uninstall commander, and `npm i commander` again?

**Comment by kiro7shiro** [comment]
I'm in the office right now. I will try it later and come back to you.

**Comment by shadowspawn** [comment]
Not sure what happened, but hopefully sorted! Not likely to be a Commander issue as such.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
