### ISSUE TITLE
Headers are hard-coded in Help.formatHelp()

### ISSUE THREAD

**Issue by edukisto** [tj/commander.js#1608]
Is there a cleaner way to internationalize the headers, which are hard-coded in `Help.formatHelp()`, i. e. [Arguments](https://github.com/tj/commander.js/blob/8571a7590b3a802523a719da82a49a88da687812/lib/help.js#L323), [Commands](https://github.com/tj/commander.js/blob/8571a7590b3a802523a719da82a49a88da687812/lib/help.js#L339), [Options](https://github.com/tj/commander.js/blob/8571a7590b3a802523a719da82a49a88da687812/lib/help.js#L331), [Usage](https://github.com/tj/commander.js/blob/8571a7590b3a802523a719da82a49a88da687812/lib/help.js#L310)?

```javascript
import process from 'process';
import { Command, Help } from 'commander';

class MyHelp extends Help {
  formatHelp(cmd, helper) {
    const result = super.formatHelp(cmd, helper);
    return result.replace('Usage:', 'Verwendung:'); // Translate!
  }
}

class MyCommand extends Command {
  createHelp() {
    return Object.assign(new MyHelp(), this.configureHelp());
  }
}

const program = new MyCommand();
program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
There is not support to internationalize strings so that approach is reasonable. You can either reimplement the routine, or modify the string it returns as you did.

You can also achieve the same thing without making a subclass using `.configureHelp()`, but same idea.

Related: #128 #774

**Comment by edukisto** [comment]
`Command.configureHelp()`? Did you mean `Command.configureOutput()`?

```javascript
import process from 'process';
import { Command } from 'commander';

const program = new Command();

program.configureOutput({
  writeErr: (str) => process.stderr.write(
    str
      .replace('error:', 'ошибка:')
      // Proceed to replace other tokens from lib/command.js.
  ),

  writeOut: (str) => process.stdout.write(
    str
      .replace('Arguments:', 'Аргументы:')
      .replace('Commands:', 'Команды:')
      .replace('Options:', 'Опции:')
      .replace('Usage:', 'Использование:')
  ),
});

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
`configureOutput` works too! I did mean `configureHelp` .

```ts
import * as process from 'process';
import { Command, Help } from 'commander';

const program = new Command();

program.configureHelp({
  formatHelp: (cmd, helper) => {
    const originalHelp = new Help();
    return originalHelp.formatHelp(cmd, helper)
      .replace('Arguments:', 'Аргументы:')
      .replace('Commands:', 'Команды:')
      .replace('Options:', 'Опции:')
      .replace('Usage:', 'Использование:');
  }
});

program.parse(process.argv);
```

**Comment by edukisto** [comment]
Ah, now I see how to use `configureHelp()` to override `formatHelp()`. This is a pretty clean way.
Thank you very much!

**Comment by shadowspawn** [comment]
Anyone following this issue is likely to be interested in #1801
