### ISSUE TITLE
Listen to any command

### ISSUE THREAD

**Issue by kuncevic** [tj/commander.js#1609]
I look to the docs and found that [example](https://github.com/tj/commander.js#custom-event-listeners):

```
program.on('command:*', function (operands) {
  console.error(`error: unknown command '${operands[0]}'`);
  ...
});
```

However, it does not work unless you specify a particular command.

I can see that with [life cycle hooks](https://github.com/tj/commander.js#life-cycle-hooks) you can achieve something similar to what I was expected from the above example. 

The question is, does the above example suppose to handle any command (`command:*`)?

**Comment by shadowspawn** [comment]
The `'command:*'` dates back to the original implementation of having a default command. It is sent when there is an argument that does _not_ match one of the known subcommands. It is now only sent for backwards compatibility. As a side-affect it allowed handling unknown commands as in the example, but there is a built-in error now and also `.showSuggestionAfterError()`. (Which makes me think `'command:*'` should finally be deprecated!)

> The question is, does the above example suppose to handle any command (command:*)?

No. For that, look at a life cycle hook as you found.
