### ISSUE TITLE
Pattern to sharing common set of flags/argument for multiple commands?

### ISSUE THREAD

**Issue by AgainPsychoX** [tj/commander.js#1615]
Is there any good pattern to sharing common set of flags/argument for multiple commands?

I am creating tool to work with save files from some game, and my sub-commands (`unpack`/`pack`/`interactive`/`report`/`fix`/etc.). Almost all of them require use to specify which save file they want to work with (path, or in-game identifier, or `--latest`, or choose from cli dialog).

Currently I have code like:
```ts
program
    .command('interactive')
    .alias('repl')
    .argument('[savePath]', 'save file path (can be relative to saves directory')
    .option('-l, --latest', 'work with latest played save file')
    // ... other options specific only to the subcommand
    .description('opens save and enters interactive mode (JS REPL with save object)')
    .action(async (savePath: string, options) => {
        let inputFilePath: string | undefined;
        if (options.latest) {
            inputFilePath = await selectLatestSaveFile();
        }
        if (savePath) {
            inputFilePath = await selectSaveFileByString(savePath);
        }
        if (!inputFilePath) {
            inputFilePath = await selectSaveFilePrompt();
        }
        // ... do stuff
    })
```
but almost whole this part (argument/option definitions and handling them in `action` handler) is the same in multiple subcommands.

_It's not bug, just looking for some tips._

**Comment by shadowspawn** [comment]
There are a variety of ways of doing this, and other people may have quite different approaches to suggest. I have not done this in a real program, so my suggestions are in theory.

1) A straight-forward way of sharing the code is to have one function to add the "common" arguments and options to a command, and a second function you can call from the action handler to process the received arguments and options. (Ask if you want to see that.)

2) Your processing uses both the arguments and the options which makes it a little trickier to generalise. I might be overthinking this, but here is what I came up with for a single function setup using the relatively new life-cycle hook.

```
function addInputFileHandling(command) {
  command
    .option('-l, --latest', 'work with latest played save file')
    .argument('[savePath]', 'save file path (can be relative to saves directory')
    .hook('preAction', async (thisCommand, actionCommand) => {
      const options = actionCommand.opts();
      let inputFilePath = '';
      if (options.latest) inputFilePath = 'latest';
      if (actionCommand.processedArgs[0]) inputFilePath = actionCommand.processedArgs[0];
      if (!inputFilePath) inputFilePath = 'prompt';
      actionCommand.processedArgs[0] = inputFilePath;
    })
}

program
    .command('interactive')
    .argument('[savePath]', 'save file path (can be relative to saves directory')
    .option('-l, --latest', 'work with latest played save file')
    .action(async (savePath, options) => {
        let inputFilePath = '';
        if (options.latest) inputFilePath = 'latest';
        if (savePath) inputFilePath = savePath;
        if (!inputFilePath) inputFilePath = 'prompt';
        console.log(`action input file: ${inputFilePath}`);
        // ... do stuff
    });

const interactive2 = program
  .command('interactive-hook')
  .action(async (savePath, options) => {
    console.log(`hooked input file: ${savePath}`);
  });
addInputFileHandling(interactive2);
    
program.parseAsync().catch(() => {
  console.log('FAILED');
});
```

```
% node index.js interactive         
action input file: prompt
% node index.js interactive --latest
action input file: latest
% node index.js interactive foo     
action input file: foo

% node index.js interactive-hook    
hooked input file: prompt
% node index.js interactive-hook --latest
hooked input file: latest
% node index.js interactive-hook foo     
hooked input file: foo
```

**Comment by mig82** [comment]
Same use case here. I tried using a custom command class, but it didn't work as I expected.

**Comment by shadowspawn** [comment]
Some suggestions provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by AgainPsychoX** [comment]
Hello after some time. I was working quite a lot with `commander.js` by this time. I love the library. Now as I gained some experiences over the time, I want to share my thoughts:

One of projects I used the `commander.js` for: https://github.com/AgainPsychoX/Stellaris-Save-API
Today yet again I had opportunity to work with the library (some other project), and I yet again came back to the project above of mine, copying the patterns I ended up going back then. So here I want to share some takeaways:

---

### Command folder and files

When working on CLI tool with multiple subcommands I use `commands` folder, where I put related only to specific task:
<sub>https://github.com/AgainPsychoX/Stellaris-Save-API/blob/main/src/commands/InteractiveCommand.ts</sub>
```ts
import repl from 'repl';
import path from 'path';
import { Command } from 'commander';
import * as StellarisSaveLib from '@/index';
import { addSaveFileInputHandlingToCommand, loadSaveFileFancy, saveSaveFileFancy } from './common';

export const registerInteractiveCommand = (parent: Command) => {
	const that = parent
		.command('interactive')
		.alias('repl')
		.description('opens save and enters interactive mode (JS REPL with save object)')
		.action(async (options) => {
			const inputFilePath = options.input as string;
			// ...
		})
	;
	addSaveFileInputHandlingToCommand(that, { interactive: true });
	return that;
}

export default registerInteractiveCommand;
```

### Command mix-ins 

The pattern I ended up uses `register___Command` functions to add register the command to the program.  It can also use some "mix-ins" of sorts for the commands/program as they are getting registered. It allows to add certain common paramaters and behaviours, with DRY in mind.

<sub>https://github.com/AgainPsychoX/Stellaris-Save-API/blob/main/src/commands/common.ts</sub>
```ts
export const addSaveFileInputHandlingToCommand = (
	command: Command, 
	settings: {
		/**
		 * If true, allows using interactive prompt to select save file,
		 * if no other specifier was provided.
		 */
		interactive?: boolean,
		/**
		 * If true, error will be reported and program will exit if input file
		 * does not exist or is not accessible.
		 */
		require?: boolean, 
		/**
		 * If set as number, specifies that argument will be use as general 
		 * specifier for selecting input save file (path, name, 'latest' etc.).
		 * 
		 * If set as true, latest argument will be used.
		 */
		useArgument?: number | true
	} = {}
) => {
	settings = Object.assign({ interactive: false, require: true, useArgument: undefined }, settings);
	if (settings.useArgument) {
		command.argument('[savePath]', 'input save file path (can be relative to saves directory)'); // Arguments can be added
	}

	command
		.option('-i, --input <savePath>', 'input save file path (can be relative to save directory)')
		.option('-l, --latest', `work with latest played save file`)
		// TODO: add forcing interactive prompt for input select
		.hook('preAction', async (thisCommand) => {
			const options = thisCommand.opts();

			let providedPath = options.input;
			if (settings.useArgument) {
				if (settings.useArgument === true) {
					settings.useArgument = thisCommand.processedArgs.length - 1;
				}
				providedPath ||= thisCommand.processedArgs[settings.useArgument] as string;
			}
			// ... (cut to improve readability of the post; full version at link above)
			if (!inputFilePath && settings.require) {
				process.exitCode = 2;
				throw new MyError('input-not-specified', `Input file must be specified.`);
			}

			if (settings.useArgument) {
				thisCommand.processedArgs[settings.useArgument] = inputFilePath; // Arguments values can be set
			}
			thisCommand.setOptionValue('input', inputFilePath); // Options as well
		})
	;
}
```



### Main file

As for main file, few things to highlight:
* I don't have any command/action specific code there, those live in separate files, in `commands` directory, including the default one. If the default action is the only action, I often still put it into separate file (of course next to the main file, no point in `commands` folder for one file), as the command can be hundred lines long.
* I find simple debugging log output limiting easy to implement: Add global `-d, --debug`  option, and set your `console.debug` to `() => {}` if it's not set. That will do for simple programs.
* For larger things, like my Stellaris Save API project (below), I use simple loggers system.  The `--debug` still in fact enables `console.debug`, but aside of that there is now also `--debug-except <exceptions>` which takes comma separated list of loggers to prevent logging the debug from. I usually throw `console.debug` a lot (while `console.log` is used for well, regular necessary logging), so it comes really handy to avoid spam when testing some other feature. Of course, some more proper loggers systems could be used, but across serval projects I had no need to go that far.
* I love ES6+, async, promises and stuff, so its only natural for me to use `parseAsync` over synchronous `parse`.
* Then, I enclose the `parseAsync` with `catch` for error handling and `finally` for any clean up tasks (in my case I also use util to keep track of those).
* You can notice some some additional error handling: Some errors could have CLI related tip - as it shouldn't be visible in the error message itself, as in my case the Stellaris Save API can be used without the CLI. 

<sub>https://github.com/AgainPsychoX/Stellaris-Save-API/blob/main/src/commands/InteractiveCommand.ts</sub>
```ts

import { Command, Option } from "commander";
import registerCombatTestCommand from "./commands/CombatTestCommand";
import registerInteractiveCommand from "./commands/InteractiveCommand";
import registerListCommand from "./commands/ListCommand";
import { registerPackCommand, registerUnpackCommand } from "./commands/PackingCommands";
import registerPrecursorsCommand from "./commands/PrecursorsCommand";
import registerReportCommand from "./commands/ReportCommand";
import { runCleanUpTasks } from "./utils/cleanup";
import { MyError } from "./utils/common";
import { setGameDirectory } from "./utils/gameData";
import { setupLogging } from "./utils/logging";

if (process.platform != 'win32') {
	console.error('Only Windows is supported for now!')
	process.exit(1);
}

const program = new Command();
program
	.name('ssa-cli')
	.version('0.1.0')
	.description('Set of tools to work with Stellaris save files.')
	.addOption(
		new Option('-d, --debug', 'output extra debugging info')
			.default(false)
			.env('DEBUG')
	)
	.addOption(
		new Option('--debug-except <exceptions>', 'output extra debugging info with exception for comma-separated list of named loggers')
			.default(false)
			.argParser(s => s && s.split(','))
			.env('DEBUG_EXCEPT')
			.implies({ debug: true })
			.hideHelp()
	)
	// TODO: 
	// .option('--saves-directory <path>', 'set custom saves directory')
	.option('--game-directory <path>', 'set path to game directory (if not specified, tries to detect or continue without)')
	.hook('preAction', async (thisCommand, actionCommand) => {
		const options = thisCommand.opts();

		// Ignore debug output if no debug flag specified
		setupLogging(!!options.debug, options.debugExcept);

		if (options.gameDirectory) {
			await setGameDirectory(options.gameDirectory);
		}
	})
;

registerListCommand(program);
registerPackCommand(program);
registerUnpackCommand(program);
registerInteractiveCommand(program);
registerPrecursorsCommand(program);
registerReportCommand(program);
registerCombatTestCommand(program);

program
	.parseAsync(process.argv)
	.catch(error => {
		console.error(error);
		switch ((error as MyError).code) {
			case 'no-game-directory': 
				console.error(`Use '--game-directory' option to provide custom path.`);
				break;
		}
	})
	.finally(async () => {
		runCleanUpTasks();
	})
;
```

**Comment by shadowspawn** [comment]
Thanks for sharing. 

For interest, an alternative style for aggregating the commands from separate files would be to export a factory routine and use `.addCommand()` rather than passing around the program:

```js
program
  .addCommand(makeListCommand())
  .addCommand(makePackCommand())
  .addCommand(makeUnpackCommand())
...
```
