### ISSUE TITLE
Unable to use consistent option names between program and subcommand 

### ISSUE THREAD

**Issue by danieldelcore** [tj/commander.js#1616]
Hi there 👋 

I've noticed that I'm unable to use an option in a subcommand if the option's name is already in use by the parent command. 
My aim to use consistent language across both commands.

```tsx
import { Command, Option } from 'commander';

const program = new Command();

program
  .name('foo')
  .usage('[global options] <file-paths>...')
  .option(
    '-t, --transform <value>',
    'The transform to run, will prompt for a transform if not provided and no module is passed',
  )
  .action((options, command) => main(command.args, options));

program
  .command('init [path]')
  .description('creates a new package')
  .requiredOption('--package-name <value>', 'Name of the package')
  .option('-t, --transform <value>', 'Transform version')
  .option('-p, --preset <value>', 'Preset transfrom')
  .action((path, options) => console.log(path, options));
```

Output: 

```diff
$ yarn start:codemods init --package-name bar --transform foo --preset fooo src/dir

- src/dir { packageName: 'bar', transform: 'foo' preset: 'fooo' }
+ src/dir { packageName: 'bar', preset: 'fooo' }
```

If I comment out the "transform" option on the parent I get the expected result.

**Reproducible on versions: 7.2.0 & 8.2.0**

**Comment by shadowspawn** [comment]
Is your "parent command" effectively an independent command with its own options separate from the subcommands? (I think so from your example.)

A tidy way of doing this is moving your "parent command" to a subcommand, and making this new subcommand the default command using `isDefault` configuration. This keeps its options separate from the other commands.

https://github.com/tj/commander.js/blob/master/examples/defaultCommand.js

**Comment by danieldelcore** [comment]
Oooooh I never thought about that. Ok I'll give that a go now! Thanks for the prompt response!

**Comment by danieldelcore** [comment]
@shadowspawn, do you know if it's possible to use a subcommand without specifying a command name? 


Ie, i'm looking to have a default command of `$ foo` and a subcommand `$foo init`.

**Comment by danieldelcore** [comment]
Works a treat!

For future reference this was the working code: 


```diff
program
-  .name('foo')
+  .command('foo', { isDefault: true })
  .usage('[global options] <file-paths>...')
  .option(
    '-t, --transform <value>',
    'The transform to run, will prompt for a transform if not provided and no module is passed',
  )
  .action((options, command) => main(command.args, options));
```
