### ISSUE TITLE
Version flag inconsistent with other packages

### ISSUE THREAD

**Issue by jbburf** [tj/commander.js#1621]
Hi, I raised this on the [expo-cli](https://github.com/expo/expo-cli/issues/3883#issuecomment-939383566) which pointed me back here. I've gotten used to using either  the "-v" flag or the "--version" flag to get a packages version from the CLI. I've checked the following packages and they all follow this convention: node, nvm, npm, yarn, make, brew. Why have you all standardized around "-V" instead of "-v"?

**Comment by shadowspawn** [comment]
One thing that is widely consistent across applications and cli frameworks is the long flag `--version`.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
For interest a couple more references:

From https://clig.dev/#arguments-and-flags

> --version: Version.
> -v: This can often mean either verbose or version. You might want to use -d for verbose and this for version, or for nothing to avoid confusion.

From https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax

- `--version` is the built-in option to display the version in `System.CommandLine`
- `-v` should only be used as the short form of `--verbosity`
