### ISSUE TITLE
The registered option could not be obtained,result undefined.               commander 注册命令后，无法通过 "program.命令" 获取

### ISSUE THREAD

**Issue by ranxin001** [tj/commander.js#1622]
**
**environment：**
**
node:v13.14.0
commander: "^8.2.0",

**
**code:**
**
var program = require('commander');

program
  .version('0.1.0')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineapple')
  .option('-b, --bbq-sauce', 'Add bbq sauce')
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) {
  console.log('  - peppers');
}
if (program.pineapple) {
  console.log('  - pineapple');
}
if (program.bbqSauce) {
  console.log('  - bbq');
}
console.log('  - %s cheese', program.cheese);

**
**result：**
**

you ordered a pizza with:
  - undefined cheese
  
  +++++++++++++++++++++++++++++++++++++++++++++++++
The registered option could not be obtained,result undefined.
commander 注册命令后，无法通过 "program.命令" 获取

**Comment by shadowspawn** [comment]
That is an an old example file. By default the options are now stored separately, and not as properties on the Command object (to avoid conflicts with existing properties).

You access the program options by calling `.opts()` like:

```js
const options = program.opts();
console.log('you ordered a pizza with:');
if (options.peppers) {
  console.log('  - peppers');
}
```

https://github.com/tj/commander.js/blob/master/examples/pizza

**Comment by FIWE2030** [comment]
oh, thanks！
but, The Internet is still full of such old examples, and it feels like a lot of people are still being misled,
hope you can find this issues...
