### ISSUE TITLE
Is there a way to add subcommand options desc to the default help output

### ISSUE THREAD

**Issue by kuncevic** [tj/commander.js#1624]
Current output:

```
Options:
  -v, --version                 output the version number
  -h, --help                      display help for command

Commands:
  cmd1                     Desc1
  cmd2 [options]           Desc2
  cmd3 [options]           Desc3
```

So in order to figure out options you have to run another command `cmd2 --help` which prints the options details.

I am wondering if it is possible to print that options details as a part of the default help output, or something similar to that:

```
Options:
  -v, --version                 output the version number
  -h, --help                      display help for command

Commands:
  cmd1                     Desc1
  cmd2 [options]           Desc2
         -o1, option1      ODesc2  
  cmd3 [options]           Desc3
         -o2, option2      ODesc3  
```

**Comment by shadowspawn** [comment]
Nice description, thanks. 

There is not direct support for adding subcommand options into the program help (top-level command). 

-----

To do it yourself, you could subclass/override the Help class.

The shortcut would be to override `subcommandDescription`, and tack on the options:
https://github.com/tj/commander.js/blob/950f742e60ae6b30a3d4e945db6d4322919628fd/lib/help.js#L224

The full-blown approach with more control would be to override `formatHelp` to more explicitly extend the lines that do the subcommands:
- https://github.com/tj/commander.js/blob/950f742e60ae6b30a3d4e945db6d4322919628fd/lib/help.js#L293
- https://github.com/tj/commander.js/blob/950f742e60ae6b30a3d4e945db6d4322919628fd/lib/help.js#L334

For subcommands with a lot of options adding the options may be a bit noisy, but I can imagine it working for modest subcommands!

**Comment by kuncevic** [comment]
Yeah understood, it is very hard to please each and every use-case. 
Thank you for pointing out to the right direction.

It is something that we should not expect to be a part of the default functionality, right?

**Comment by shadowspawn** [comment]
> It is something that we should not expect to be a part of the default functionality, right?

Correct. (Not at this time, based on current utility conventions, and current Commander feedback.)

**Comment by shadowspawn** [comment]
Interesting idea to mark individual options, but I don't this this scales very well.

No further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
