### ISSUE TITLE
Alternative order of arguments supplied to action handler

### ISSUE THREAD

**Issue by edmundmaruhn** [tj/commander.js#1639]
I have a rather simple question (and suggestion):
Why is the order of arguments passed in to the action handler function the way it is?

Usually I would expect all fixed parameters at the beginning while all the others follow afterwards.

So currently I have to do something like this in order to pick the options and the command from the arguments:
```javascript
const actionHandler = (...args) => {
	const command = args[args.length - 1]
	const options = args[args.length - 2]
}
```
Or I could do something like:
```javascript
const actionHandler = (...args) => {
	const a = args.reverse()
	const command = args[0]
	const options = args[1]
}
```

Both feel quite odd and in the latter one I would have to re-reverse everything from index 2 in order to get back the correct order of arguments.

So the more natural, thus straightforward alternative would be:
```javascript
const actionHandler = (command, options, ...args) => {
	// ...
}
```

The only reason I can see for having it like it is right now, is that one requires to access the options and command less frequent than the arguments, which makes sense then. However, still in this case there would be a better alternative, by just passing a single object like so:

```javascript
const actionHandler = (actionArguments) => {
	actionArguments.command
	actionArguments.options
	actionArguments.args
}
```

So my suggestion would be to change this in one or the other way. However, I'm aware that this would be a breaking change, but probably there's also a way to make that backward compatible.

What do you think?

Source location:
https://github.com/tj/commander.js/blob/43f4743864e2f670db5eebcf88c92aa4612c54f1/lib/command.js#L476-L492

**Comment by shadowspawn** [comment]
> Why is the order of arguments passed in to the action handler function the way it is?

History! Initially the action handler was only passed the command-arguments. To better support subcommands, the "options" (actually, the command object) were added on the end of the arguments in this commit: #28

> So my suggestion would be to change this in one or the other way. 

The alternative I have been wondering about is passing just the command. It already `.opts()`, `.args`, and `.processedArgs`.

> However, I'm aware that this would be a breaking change, but probably there's also a way to make that backward compatible.

Very breaking! 😢 

Thinking out loud, not deeply considered:
- I like how `.parse(args, { from: 'user')})` works, but adding a parameter after the callback might be a bit clumsy
- could offer another callback method which is passed the different arguments, say `.run()`
- I don't like making the signature a configuration setting

Related: #1277

**Comment by shadowspawn** [comment]
A related technical detail. The action handler is called in the style of an `EventEmitter` listener function, as was originally implemented using events. The `EventEmitter` description:

https://nodejs.org/dist/latest-v16.x/docs/api/events.html#passing-arguments-and-this-to-listeners

So the command itself is available without using the action handler arguments at all.

```js
function actionHandler() {
  console.log('args %s', this.processedArgs);
  console.log('opts %s', this.opts());
}

program
  .argument('<file>')
  .option('-d, --debug', 'dummy option')
  .action(actionHandler);

program.parse();
```

```
% node index.js --debug  foo
args [ 'foo' ]
opts { debug: true }
```

**Comment by shadowspawn** [comment]
Documenting the existing `EventEmitter` style setting of `this` be useful for people wanting a more direct way of getting at the command from an action handler, and not require any code changes.

**Comment by shadowspawn** [comment]
Commander v9 has been released.
