### ISSUE TITLE
Option failing to create

### ISSUE THREAD

**Issue by shinspiegel** [tj/commander.js#1640]
I do have this small [utility](https://github.com/shinspiegel/react-generator/) that I use to create components for my personal projects,

When I'm using the local branch on the utility project, `commander` works fine, everything just works.
But when I'm using it on different projects as a utility it breaks with the following message:

```
$ /Users/shin/Documents/Personal/Code/NODE/testone/node_modules/.bin/rg -c one
/Users/shin/Documents/Personal/Code/NODE/testone/node_modules/react-generator-tool/src/App.js:15
            .option('-c, --component <component_name>', 'will create a new react component')
            ^

TypeError: Cannot read properties of undefined (reading 'option')
    at new App (/Users/shin/Documents/Personal/Code/NODE/testone/node_modules/react-generator-tool/src/App.js:15:13)
    at Object.<anonymous> (/Users/shin/Documents/Personal/Code/NODE/testone/node_modules/react-generator-tool/index.js:6:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Could anyone give some insight on what's is wrong?
This is the [relevant file](https://github.com/shinspiegel/react-generator/blob/main/src/App.js).

**Comment by shadowspawn** [comment]
```js
this.program
     .version(FileHelper.readJson("package.json").version, "-v, --version", "output the current version")
     .option("-c, --component <component_name>", "will create a new react component")
```

If `FileHelper.readJson("package.json").version` is undefined then `program.version()` will return the current version, which is undefined. Then the chained call to `.option()` will fail.

I suspect finding `package.json` is failing when you call your utility in a different way or from a different location.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
