### ISSUE TITLE
Using `Option.parseArgs` with variadic and default options

### ISSUE THREAD

**Issue by joshuakarp** [tj/commander.js#1641]
I'm trying to create an `Option` that supports:
* argument validation (through a `parseArgs` function)
* being variadic
* retrieval from an environment variable, and
* a default value (when none of the prior sources are available)

However, I'm noticing that there's some interference between my `parseArgs` function and specification of a default value. Consider the following minimal example, where I hypothetically want to provide multiple ports in the arguments, but want to default to a single port 80 if none are provided:

```js
#!/usr/bin/env node

import commander from 'commander';
const program = new commander.Command();

function parsePorts(curr, prev) {
  return prev.concat([parseInt(curr)]);
}

program.addOption(new commander.Option('-p, --port [number...]', 'specify port number')
  .argParser(parsePorts)
  .default([80])
);

program.parse();
console.log(program.opts());
```

Executing this with `--port 123 124` provides the following output:

```
{ port: [ 80, 123, 124 ] }
```

Without the `argParser` added, I get the expected `{ port: [ '123', '124' ] }`, but I'm no longer able to validate the provided arguments. It seems that `argParser` is also parsing the default port as well, and appending this to the returned list. Is there a way to circumvent this?

**Comment by shadowspawn** [comment]
Nice example and description, thanks. 

You have hit a tricky part of the option-argument processing! Long story...

The "default value" for an option is used in two ways: it is set as the option value when the option is added to the command, and also the default value gets passed into the argument parser as the "previous" value the first time the parser is called. This often works fine.

With a variadic option you probably want the command-line items in a fresh array without the default value, and Commander does some extra work to make this happen when you don't have a custom parser. The internal support for adding to variadic options makes a fresh array if the previous value is the default value.

https://github.com/tj/commander.js/blob/43f4743864e2f670db5eebcf88c92aa4612c54f1/lib/option.js#L105

Four different work-around ideas for your use case:
1) use a default value of an empty array, and supply port 80 afterwards if the option value is empty
2) store the default value yourself and do the same test as Commander in your parsing function
3) use the built-in variadic support with strings and convert to numbers afterwards
4) subclass Option so your parser has access to the default value without needing to store it separately

Ask if you would like to see code for one of those approaches.

(I have wondered about adding the ability to set the Option default value and the starting value separately. And wondered about passing in Option object and even Command into parse function. But not many reports of problems to justify the additional complexity so far, so only been thinking about it!)

**Comment by shadowspawn** [comment]
FYI: a custom `argParser` gets called on the string values from the command-line, or the string value of an environment variable. A custom `argParser` does not get called on the default value as that is supplied by code and is assumed to be pre-parsed.

**Comment by joshuakarp** [comment]
Thanks a lot for all this information - those work-arounds will work just fine for me. Appreciate the help.
