### ISSUE TITLE
customize the welcome message 

### ISSUE THREAD

**Issue by VenomFate-619** [tj/commander.js#1646]
I wanted to do this 
![image](https://user-images.githubusercontent.com/67755128/144368024-f4f22563-6457-452b-99ec-88395ed16dfd.png)

So how do I achieve this.

**Comment by shadowspawn** [comment]
If you want to display only your example usage when there are no arguments, just test for it yourself first. e.g.

```
if (process.argv.length <= 2) {
   displayMyExampleUsage();
   process.exit(2);
}
```

If you would like to integrate into Commander and the built-in help, then you could add an example section after the help using `.addHelpText()`.

https://github.com/tj/commander.js#custom-help

**Comment by VenomFate-619** [comment]
Thx ✨ for the solution
But addHelpText() method does not override the whole message, it only appends the help text.
I want to completely edit it.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
