### ISSUE TITLE
customizing error message

### ISSUE THREAD

**Issue by VenomFate-619** [tj/commander.js#1647]
How to customize the error message?
Output:-
```
/task add
error: missing required argument 'priority'
```
Expected:-
```
/task add
Error: Missing tasks string. Nothing added!
```
Is there any way to achieve this?

**Comment by shadowspawn** [comment]
There is not direct support for overriding error messages. 

Three ideas for how you might alter the error message with extra work:
1) You could use `.configureOutput()` and override `outputError`, and change what is output for certain strings.
2) You could use `.exitOverride()` and catch the exception, and write out more output like "Nothing added!" on another line. The exception happens after the built-in error message is displayed.
3) You could make the argument optional and check for it missing in the action handler. (This would affects how it is displayed in the help.)

**Comment by VenomFate-619** [comment]
Thanking you @shadowspawn for the help
