### ISSUE TITLE
How do you call one command from another command with options?

### ISSUE THREAD

**Issue by mkiddTempus** [tj/commander.js#1649]
I've created multiple subcommands in my cli.

cli subcommand1
cli subcommand2
cli subcommand3

Each subcommand1 creates a JSON input for subcommand2. Subcommand2 takes that JSON input and does something. subcommand3 is not dependent on 1 or 2 but is related.

I want to add a 'menu' command that allows the user to select a predetermined JSON to use and provides that as input into SubCommand2.

I found [this issue](https://github.com/tj/commander.js/issues/643) that comes close but I don't see a means to provide options input. Any ideas?

**Comment by shadowspawn** [comment]
Commander does not directly support chaining together commands, or running one command from another command. I suggest it is easiest to just call your own routines that do the work directly from (say) the menu routine.

> I don't see a means to provide options input

Options to the commands?

```js
program
  .command('lint')
  .option('-d, --debug)
  .action((options) => lint(options))
```

**Comment by mkiddTempus** [comment]
Thanks @shadowspawn!
