### ISSUE TITLE
Not being able to execute .sh file

### ISSUE THREAD

**Issue by CB0rghi** [tj/commander.js#1650]
For some reason, when I try to exec('pathToBash.sh') on the action of a command, nothing happens.

Do you have any idea of what might be?

Thanks in advance

**Comment by shadowspawn** [comment]
I am not sure what you are trying to do. Do you want to implement a subcommand using a stand-alone executable which is a shell script?

Can you share a code sample?

**Comment by CB0rghi** [comment]
### Yes, I was able to solve it already, it wasn't a issue with commander, but with the way I was trying to call the file.

Thank you
