### ISSUE TITLE
Colouring fails in options

### ISSUE THREAD

**Issue by GHNewbiee** [tj/commander.js#1651]
The following works:

```js
  .option(`${chalk.cyan('-c')}, --config [file]`, 'the file name')
```
but not the next one:
```js
  .option(`${chalk.cyan('-c')}, ${chalk.cyan('--config [file]')}`, 'the file name')
```

It returns:
```text
/.../node_modules/commander/lib/option.js:181
    return str + word[0].toUpperCase() + word.slice(1);
```
*Tia*

**Comment by shadowspawn** [comment]
First, the problem. Commander is using that first parameter to determine:
- short flag `-c`
- long flag `--config`
- whether has option argument `[file]`
- whether option-argument is required or optional

Commander uses some simple code to pull apart the parameter. Colouring the text is inserting a bunch of ascii escape sequences into the string, and that is not going to go well...

I tried your first example to check, and although the short flag is displayed in cyan in the help, it does not work on command line.

```
% node index.js -c fhf
error: unknown option '-c'
```

**Comment by shadowspawn** [comment]
The way to change the format of the help is to modify the Help class, either by a subclass or by overriding individual methods using `configureHelp()`.

See: https://github.com/tj/commander.js#more-configuration-2

For your case, the option flags are supplied by the `optionTerm` method:

```
program.configureHelp({
  optionTerm: (option) => {
    return chalk.cyan(option.flags);
  }
});
```

**Comment by GHNewbiee** [comment]
> For your case, the option flags are supplied by the optionTerm method:

I am not sure I fully understand.

In the following option
```js
  .option('-v, --verbose', 'verbosity that can be increased', increaseVerbosity, 0)
```
there are 5 parts or 4 arguments:
- `-v` (as a part),
- `--verbose (as a part)`
- ,`-v, --verbose` (as an argument)
- `verbosity that can be increased`,
- `increaseVerbosity`
- `0`

Please, clarify which method can format each/part or argument. *Tia*

**Comment by shadowspawn** [comment]
The `Help` class has methods for what is displayed in the help. The two methods used for each option are `.optionTerm()` and `.optionDescription()`. If your colour customisation fits into that pattern, you could supply a custom version of those routines.

The `Help` class takes the Option created by:
```
.option('-v, --verbose', 'verbosity that can be increased', increaseVerbosity, 0)
```

and displays it in the help as "term" and "description":
```
  -v, --verbose        verbosity that can be increased (default: 0)
```

The `Option` class has properties for: `short`, `long`, `flags`, `description`, `parseArg`, `defaultValue` and more.

The default implementation of `Help.optionTerm()` is:

```
  optionTerm(option) {
    return option.flags;
  }
```

**Comment by shadowspawn** [comment]
For interest, reopened: #301
