### ISSUE TITLE
Complete list of all (sub)commands and their options

### ISSUE THREAD

**Issue by p3k** [tj/commander.js#1653]
I got a user request for providing a list of all commands, subcommands and their options, available in a script.

E.g. something like this:

| Command | Options | Arguments | Description
| --- | --- | --- | ---
| build | | [what] | build something
| build | --debug | [what] | build something in debug mode
| build foo | | | build something called foo
| build foo | --bar | | enable bar option
| run | | \<name\> | run something called name
| run | --development | | run something in development mode
| … 

Any suggestion on how to implement this? Is this something CommanderJS can help to generate?

**Comment by shadowspawn** [comment]
It isn't hard to generate a list of commands, options, and arguments. But your table has a lot more useful information, with the combinations of options and arguments and what they are used for. You could perhaps store the table rows in each command with a custom subclass.

**Comment by p3k** [comment]
> It isn't hard to generate a list of commands, options, and arguments.

OK – how would I start generating this list?

> But your table has a lot more useful information, with the combinations of options and arguments and what they are used for. 

Actually, the information in the table is (or should be, as it contains just fictitious examples) the same as defined with the `program` methods in the main script and the corresponding script files for the subcommands:

```js
// main script
program
  .command("build [what]", "build something")
  .option("--debug", "build something in debug mode")
  // …

program
  .command("run <name>", "run something called name")
  .option("--development", "run something in development mode")
  // …

// build script
program
  .command("foo", "build something called foo")
  .option("--bar", "enable bar option")
  // …
```

(I made this all up in my head, apologies if it looks illogically – I hope it still makes the point.)

**Comment by shadowspawn** [comment]
You can iterate over the `commands` and `options` and `arguments` properties of the program, or as in this example you can use the `Help` class to do some of the work for you. Sometimes the `Help` methods will be useful, but sometimes because they are intended for the help they may not suit what you want in the table (like showing `--help` for every command).

```
program.command("build [what]")
  .description("build something")
  .option("--debug", "build something in debug mode");

program.command("run <name>")
  .description("run something called name")
  .option("--development", "run something in development mode");

program.command("foo")
  .description("build something called foo")
  .option("--bar", "enable bar option")

program.command('dump')
  .action(() => {
    const helper = program.createHelp();

    const commands = helper.visibleCommands(program);
    commands.forEach(cmd => {
      console.log(`Command: ${cmd.name()}`);
      console.log(`   ${helper.subcommandTerm(cmd)} ${helper.subcommandDescription(cmd)}`);

      console.log('Options:');
      const options = helper.visibleOptions(cmd);
      options.forEach(option => {
        console.log(`  ${helper.optionTerm(option)} ${helper.optionDescription(option)}`);
      });
      console.log();

      // arguments
    });
  });
```

```
% node example dump
Command: build
   build [options] [what] build something
Options:
  --debug build something in debug mode
  -h, --help display help for command

Command: run
   run [options] <name> run something called name
Options:
  --development run something in development mode
  -h, --help display help for command

Command: foo
   foo [options] build something called foo
Options:
  --bar enable bar option
  -h, --help display help for command

Command: dump
   dump 
Options:
  -h, --help display help for command

Command: help
   help [command] display help for command
Options:
```

**Comment by p3k** [comment]
Awesome, this is exactly what I need! Thanks a lot, @shadowspawn
