### ISSUE TITLE
Is there any (better) way share a global state object throughout the app?

### ISSUE THREAD

**Issue by kasipavankumar** [tj/commander.js#1666]
My app's structure roughly looks as shown below:

```
.
├── actions/
│   ├── login.js
│   └── register.js
└── app.js
```

**The requirement here is to have an object (consider this as a global state) that is initialized once in the `app.js` and is available in all the sub-commands.** The reason I have mentioned "better" in the question is because there are couple of ways I have tried to achieve this.

1. **Using `hook()`**

```js
// app.js

program
  .name("the-cli-app")
  .description("The CLI App.")
  .version("v0.0.0-alpha", "-v, --version", "display current version")
  .hook("preAction", (_, actionCommand) => {
    actionCommand["__store"] = {
      isAuthed: true,
    };
  });
```

```js
// login.js

export default function login(name, options, command) {
  const store = options.__store
 
  console.log(store.isAuthed) // true

  //.. action specific logic
}
```

**Notice how I am using the hook associated with top-level command which makes the `__store` available to all the sub-commands actions.** 

I understand that it is not a good practice to attach a property to an existing object (or the `Command` class in this case).

2. **Using curried functions as actions handlers**

```js
// login.js

export default function login(store) {
    return async function(name, options, command) {
        console.log(store.isAuthed) // true
        
        //.. action specific logic
    }
}
```

```js
// app.js

const store = {
    isAuthed: true,
}

// The login sub-command
program
  .command("login")
  .description("Login to JSCrates ecosystem")
  .action(login(store));
```

I think, this would be the recommended approach since it has no side effects as opposed to the aforementioned approach but the `store` has to be explicitly passed to each action in all the sub-commands.

Curious to know if there are (any) better approaches?

**Comment by shadowspawn** [comment]
A possible correction in the sample code. I think the code for `login.js` in approach (1) should be getting the store from the command, rather than the options?

```
// login.js

export default function login(name, options, command) {
  const store = command.__store
```

**Comment by shadowspawn** [comment]
A couple more ideas, not necessarily "better".

3. Use subclass of Command to add `__store` property, and set same reference on subcommands. This amounts to much the same as using hook (as per 1) but a bit more formally.

4. Access a global store outside the command hierarchy. (Does it make sense that this global state is part of the commands, or does the global state stand-alone?)

**Comment by kasipavankumar** [comment]
> Use subclass of Command to add __store property, and set same reference on subcommands. This amounts to much the same as using hook (as per 1) but a bit more formally.

I didn't think of this, will surely try this approach and revert back on how it works.

> Access a global store outside the command hierarchy. (Does it make sense that this global state is part of the commands, or does the global state stand-alone?)

We should be able to keep it stand-alone since it will be initialized for each command invoked.

**Comment by kasipavankumar** [comment]
> A possible correction in the sample code. I think the code for `login.js` in approach (1) should be getting the store from the command, rather than the options?
> 
> ```
> // login.js
> 
> export default function login(name, options, command) {
>   const store = command.__store
> ```

Weird, `command` is undefined in my case.

**Comment by shadowspawn** [comment]
Does the login command have a specified command-argument matching the "name" parameter in the action handler? (If you don't have any arguments defined while trying things out, the options and command will be getting passed in the first two parameters.)

**Comment by kasipavankumar** [comment]
> If you don't have any arguments defined while trying things out, the options and command will be getting passed in the first two parameters.

Okay, now I understand why the `command` argument is undefined in this case.

> Does the login command have a specified command-argument matching the "name" parameter in the action handler?

No, the login command doesn't have any arguments or options associated with it (standalone sub-command).

Anyways, I have used approach 3, i.e., creating a custom class extending the `Command` class.

```js
// app.js

class BaseCommand extends Command {
  constructor(store) {
    super();
    this.store = store;
  }
}

const store = { isAuthed: true };
const program = new BaseCommand(store);
```

It works fine but the store is only accessible using `options.parent` in the action handler (as shown below) and I am curious to know why is that the case? 

```js
// login.js

export default function login(name, options) {
  const { store } = options.parent

  //.. action specific logic
}
```

Thank you.

**Comment by shadowspawn** [comment]
The program is now a `BaseCommand`, but the subcommands by default are still `Command`. The design pattern is you override `.createCommand()` which is used to create the subcommands, so you can configure with access to the same store.

```js
class BaseCommand extends Command {
  // ...
  createCommand(name) {
    const cmd = new BaseCommand(this.store);
    cmd.name(name);
    return cmd;
  }
}
```

**Comment by kasipavankumar** [comment]
Okay, I can see the pattern here. Thanks for your response, will try this and revert back.

**Comment by kasipavankumar** [comment]
> The program is now a `BaseCommand`, but the subcommands by default are still `Command`. The design pattern is you override `.createCommand()` which is used to create the subcommands, so you can configure with access to the same store.
> 
> ```js
> class BaseCommand extends Command {
>   // ...
>   createCommand(name) {
>     const cmd = new BaseCommand(this.store);
>     cmd.name(name);
>     return cmd;
>   }
> }
> ```

This worked.
Thanks a lot for your help.
Cheers!
