### ISSUE TITLE
async parseAsync(argv, parseOptions) {

### ISSUE THREAD

**Issue by wuqiren** [tj/commander.js#1672]
```
const { program } = require('commander');
program.version('0.0.1');
```
![image](https://user-images.githubusercontent.com/54806027/148066069-a66b1f66-51d7-4c71-9d0e-6ec7d91700fa.png)

Has anyone come across a situation like this?

**Comment by shadowspawn** [comment]
What version of node are you using?

I can reproduce that error by using node 6, which did not support `async`. If that is the problem, you either need to use a newer version of node or an older version of Commander.

**Comment by wuqiren** [comment]
Yes I am using node 6x.
Thanks
