### ISSUE TITLE
Equal subcommand arguments dont get passed

### ISSUE THREAD

**Issue by AntonBallmaier** [tj/commander.js#1674]
Given a command and a subcommand with the same option, than the option isnt passed when calling the subcommand.

```js
program.command("command")
       .option('-o, --option', 'some option')
       .command("subcommand")
       .option('-o, --option', 'some option')
       .action(args=>console.log(args))

program.command("command2")
       .command("subcommand")
       .option('-o, --option', 'some option')
       .action(args=>console.log(args))

```
```bash
$ node bug.js command subcommand -o
{ }
$ node bug.js command2 subcommand -o
{ option: true }
```

**Comment by shadowspawn** [comment]
Yes, the outer command is consuming the option.  Example with one less layer:

```
program.option('-o, --option', 'some option')

program
  .command("subcommand")
  .option('-o, --option', 'some option')
  .action(args=>console.log(program.opts()))
```

```
 $ node index.js -o subcommand
{ option: true }
$ node index.js subcommand -o
{ option: true }
```

The good news is you can change the behaviour. Have a look at the Parsing Configuration section in the README, in particular at `.enablePositionalOptions()`.
- https://github.com/tj/commander.js#parsing-configuration

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
