### ISSUE TITLE
How to disable the help command messages?

### ISSUE THREAD

**Issue by DhiaDjobbi** [tj/commander.js#1677]
I am using commander version ^8.3.0
I used the `program.helpOption(false);`
But I can't understand why those messages are still showing ?

![image](https://user-images.githubusercontent.com/40583006/149624355-c4074546-f057-49d6-949a-a9bc3bcf11d1.png)

How can I disable the **Usage:** , **Options:** and **Commands:** ?

Here is my code:

```
const { Command } = require("commander");
const program = new Command();
program.version("0.0.1");

program.helpOption(false);

program
  .command("test")
  .description("testing")
  .action(() => {
    console.log(table.toString());
  });

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
`.helpOption(false)` removes the default help option.

```
% node index.js --help
error: unknown option '--help'
```

`.addHelpCommand(false)` prevents the automatic help command when your program has subcommands.

```
% node index.js help test
error: unknown command 'help'
```

The help is still automatically displayed when there are subcommands but the user does not specify a subcommand. What do you want to happen in this case?

The simplest way to get a different behaviour is test for this case yourself before calling parse, which used to be the way of getting the help displayed before that was made the default behaviour! For example:

```
if (process.argv.length < 3)
  console.log('error: subcommand not specified')
else
  program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
