### ISSUE TITLE
Ignore-case for options?

### ISSUE THREAD

**Issue by Pzixel** [tj/commander.js#1680]
I think it would be a great option to allow options to be ignore case so 
```js
 .addOption(new Option('--drink <drink>').choices('Water', 'Soda')
```
would parse `--drink Water` , `--drink water`, `--drink WATER` and so on

**Comment by shadowspawn** [comment]
For historical interest: there was support for a regular expression for validation, and people did use it for supporting mixed case like this. (The old regular expression support is deprecated as it was implemented by overloading the `.option()` arguments and not very robust.)

I am currently happy with case-sensitive as the default behaviour. 

But also happy to leave this open for a while to see if there is interest for case-insensitive. Or even regular expression!

**Comment by Pzixel** [comment]
If you're happy with case-sensitive you can just set is as default but add possibility to change it if needed.

**Comment by shadowspawn** [comment]
This issue has not had any interest in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
