### ISSUE TITLE
Variadic option with env

### ISSUE THREAD

**Issue by trhinehart-godaddy** [tj/commander.js#1687]
```js
// cli.js
const choices = ['a', 'b'];
program
  .addOption(new Option('--test <ex...>')
    .choices(choices)
    .default(choices)
    .env('CLI_TEST')
  )
```

Works fine if I set `CLI_TEST` to `a` or `b`, but unable to do with `a b` or a serialize array.

**Comment by shadowspawn** [comment]
There is not built-in support for encoding an array in an environment variable.

One possible approach is to handle the splitting a different way that works both from the command-line and from and environment variable.

```js
const { Command, Option } = require('commander');
const program = new Command();

function commaSeparatedList(value, dummyPrevious) {
  return value.split(',');
}

program
  .addOption(new Option('-c <value>').argParser(commaSeparatedList).env('COMMA'));

program.parse();
console.log(program.opts())
```

```
% COMMA=a,b node index.js 
{ c: [ 'a', 'b' ] }
```

**Comment by trhinehart-godaddy** [comment]
I'm not looking to encode, I'm looking for env to handle `a b` the same way using an option works.

ie:
```js
cross-env CLI_TEST="a b" ./cli.js
```
should be the same as
```js
node ./cli.js --test a b
```

The workaround you provided doesn't work with `<value...>` which I need since I'm using `choices`

**Comment by shadowspawn** [comment]
The shell passes node an array of arguments, which Commander gets from `process.argv` by default. It is not Commander that is splitting up `a b` into `a` `b`. Your example might help make this clearer:

```
cross-env CLI_TEST="a b" ./cli.js
```

is the same as

```
node ./cli.js --test "a b"
```

**Comment by shadowspawn** [comment]
To roll-your-own solution, you could implement the validation (choices) yourself in your custom option processing function.

**Comment by trhinehart-godaddy** [comment]
I think I understand the problem, env needs to be processed just like argv. Here's a hack to work around that, however security might be a concern.

https://github.com/tj/commander.js/compare/master...trhinehart-godaddy:patch-1

**Comment by trhinehart-godaddy** [comment]
Not sure if it's a conflict of interest, you could also just use `yargs-parser` or similar code to https://github.com/yargs/yargs-parser/blob/yargs-parser-v21.0.0/lib/tokenize-arg-string.ts which simply takes a string (or in this case an env variable) and returns an array so an env like `"some value with spaces" plus this` get properly parsed into 3 values. This also would enable a program to be called manually instead of requiring process.argv.

**Comment by shadowspawn** [comment]
Another possible utility for doing your own command-line splitting is: https://www.npmjs.com/package/shell-quote

> This also would enable a program to be called manually instead of requiring process.argv.

Not sure what you mean here, but you can call parse with an array, say: `program.parse(myArgs, { from: 'user' })`

**Comment by trhinehart-godaddy** [comment]
Yes! That's another fitting example of something that could be used to solve this issue. Are you open to me creating a PR? Or do you not think this is something commander should solve with its env feature?

**Comment by shadowspawn** [comment]
Thanks. I don't want to attempt to solve this in Commander. Environment variables are a single string by their nature, and any processing that splits up the strings on some convention (like spaces) breaks strings that innocently include those characters. I don't currently think this is a common enough problem, or that there is a solid enough solution, to build into Commander.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
