### ISSUE TITLE
Is there a way to show global options in subcommand help?

### ISSUE THREAD

**Issue by nitzano** [tj/commander.js#1689]
```typescript
import { Command } from 'commander';

const subCommand = new Command('sub').option('-s1 --sub1', 'sub option')

const globalCommand = new Command('global');

globalCommand 
	.description('global command')
	.option('-g1 --global1', 'global option')
	.addCommand(subCommand)
```

Is there a way to show `-g1` exists when running `global sub --help`? (which shows only `-s1` )

I know I can use `optsWithGlobals()` inside the action but was wondering if there is an option to also show
in the subcommand's help the existance of it's global options from the parent command(s)?

Thanks :)

**Comment by nitzano** [comment]
Thanks @shadowspawn, if there is a way to vote for this feature again I'd be happy to give my +1

**Comment by shadowspawn** [comment]
Added `showGlobalOptions` in Commander 9.5.0.
