### ISSUE TITLE
Setting and saving default values 

### ISSUE THREAD

**Issue by matzar** [tj/commander.js#1690]
Is there a way to set and overwrite default variables? I think I could deal with it myself by reading and writing default variables into a file but I've been wondering if there's maybe something similar already implemented?

**Comment by shadowspawn** [comment]
Like a configuration file? No.

There was a recent issue about adding config file support . From the discussion it was not clear there was a good solution that would suit most people, so the outcome was adding some methods to enable people writing their own solutions. #1584
