### ISSUE TITLE
Not sure how unknown options work

### ISSUE THREAD

**Issue by p3k** [tj/commander.js#1693]
Here is a small test case for integrating unknown options in a command (using version 9 of Commander.js):

```js
program
	.command("test")
	.argument("[foo]")
	.option("-b, --bar")
	.allowUnknownOption(true)
	.action((args, options, command) => console.log(args, "***", options, "***", command))
```

For a call like `./program test foo --bar -- --unknown` I would expect to see `unknown` somewhere in `options` but instead the option is missing completely:

```sh
$ ./program test foo --bar -- --unknown
foo *** { bar: true } *** <ref *1> Command {
# (truncated)
``` 

What am I doing wrong?

**Comment by shadowspawn** [comment]
The unknown options are passed through as command-arguments. This is the behaviour when using `--` on the command line, and when using `allowUnknownOption()`.

```js
program
	.command("test")
	.argument("[myArgs...]")
	.option("-b, --bar")
	.allowUnknownOption(true)
	.action((myArgs, options, command) => {
    console.log({ myArgs, options, commandArgs: command.args });
  });
```

```
% node index.js test foo -- --bar --unknown  
{
  myArgs: [ 'foo', '--bar', '--unknown' ],
  options: {},
  commandArgs: [ 'foo', '--bar', '--unknown' ]
}
% node index.js test foo --bar --unknown
{
  myArgs: [ 'foo', '--unknown' ],
  options: { bar: true },
  commandArgs: [ 'foo', '--unknown' ]
}

```

**Comment by p3k** [comment]
thanks for your reply @shadowspawn.

so you are saying i need to add the three dots `...` to my argument (`foo` in my case, `myArgs` in yours) to make it a variadic one.

however, this way i am losing the actual context or the semantics of the argument. e.g. if my argument is called `name` it suddenly would look like i could provide multiple names. if i rename it to something more abstract (like `args`) it is not self-explaining, anymore.

would it be better to fall back to `process.argv` in this case?

**Comment by shadowspawn** [comment]
> so you are saying i need to add the three dots ... to my argument (foo in my case, myArgs in yours) to make it a variadic one and then i can see the additional options?

Sorry, that was just so you could see where `--unknown` was going, and be aware that the plain arguments and the unprocessed "options" were mixed together. I was not suggesting you needed to change the declared arguments. As you say, the semantics matter for the help.

> would it be better to fall back to process.argv in this case?

Have a look at `command.args` in my example. It has the arguments which are left after the known options and option-arguments are removed.

**Comment by p3k** [comment]
great, gonna use `command.args` then. thanks @shadowspawn 🌞
