### ISSUE TITLE
[Q]: multiple choise command

### ISSUE THREAD

**Issue by matzar** [tj/commander.js#1696]
Is it possible to make a multiple choice command like we get eg. when running 
`ionic start` which gives us a list of frameworks to choose from:

![Recording-241](https://user-images.githubusercontent.com/15261018/156771173-a1063fd4-e39a-4e94-98af-bc8f8fdcec73.gif)

or a multiple choice list where we can choose many different options and then run with them (I couldn't find the exmaple I have in mind but I'm sure I've seen it before)?

**Comment by shadowspawn** [comment]
Commander does not prompt for user input. You can use another library to prompt for selections from a list, for example [Inquirer](https://github.com/SBoudrias/Inquirer.js).

**Comment by matzar** [comment]
@shadowspawn thanks so much for the tip! I'll definitely check it out!
