### ISSUE TITLE
feature: cache commands to speed up boot time

### ISSUE THREAD

**Issue by erezrokah** [tj/commander.js#1699]
Hi 👋 

## Problem

The more commands you add, the longer it takes the CLI to "boot up", due to the need to `import/require/load/execute` the code that generates the CLI's interface.

## Proposal

Add a caching mechanism CLI authors can execute in development, and the CLI can load at runtime to improve startup time.

## Additional context

We recently switched [Netlify CLI](https://github.com/netlify/cli) from `oclif` to `commander` and facing this issue. `oclif` allows generating a [commands manifest](https://github.com/oclif/dev-cli/tree/ef2ec22438e87fb7107b4c49d2c47584a2222817#oclif-dev-manifest-path) that acts as such cache.

Would you consider adding a similar mechanism or have other thoughts on how to improve startup time?
I understand this makes sense for "big" CLIs and might not be relevant to many use case, so happy to receive any feedback on this topic.

## Alternatives

Use something like https://github.com/sindresorhus/import-lazy or dynamically loading of modules can help

**Comment by shadowspawn** [comment]
Interesting problem. Has not come up much.

Somewhat related previous issue for lazy loaded options: #1383

You do get a form of lazy-loaded behaviour by using separate stand-alone executables rather than action handlers within single executable. But trade-offs, less integrated, no global options, et al.

My guess is that the boot time is dominated by loading all the files for the program and all the commands rather than generating the CLI as such. Do you have metrics about what is actually slow?

**Comment by erezrokah** [comment]
Thank you for the quick reply @shadowspawn!

> My guess is that the boot time is dominated by loading all the files for the program and all the commands rather than generating the CLI as such. Do you have metrics about what is actually slow?

Your guess is correct. I don't think the slowness comes from arg parsing, etc.

We have some benchmarks deployed to a Netlify site here https://netlify-cli-performance.netlify.app/.
You can dive into it and see that a lot of the work is loading different `node_modules`.

**Comment by erezrokah** [comment]
> You do get a form of lazy-loaded behaviour by using separate stand-alone executables rather than action handlers within single executable. But trade-offs, less integrated, no global options, et al.

Your comment made me think on this a bit more, and I do think the performance benefit  comes from having to load all commands (without cache) vs a single command (with cache).

I think a cache might not suite `commander` and we're better of fixing this in our CLI.

Going to close this for now until I dig more into it.
