### ISSUE TITLE
Parse command

### ISSUE THREAD

**Issue by alejonext** [tj/commander.js#170]
I was thinking about this

``` js
program
    .command('slipt [number]', parseInt)
//.. bla 
```

And in this

``` js
program
    .command('* [number]', parseInt)
//.. bla 
```

Since it does not work (Linux) if you put anything.

``` console
$ myComand 10
$
```

Well, I think that the two proposals can go in one issues

**Comment by abetomo** [comment]
Closing due to possible answer suggested and no response registered. Feel free to comment and we can re-open in case this issue persisted.
