### ISSUE TITLE
`commander.Argument` is undefined

### ISSUE THREAD

**Issue by ShaMan123** [tj/commander.js#1707]
Tried following this [example](https://github.com/tj/commander.js#more-configuration-1)

**Comment by shadowspawn** [comment]
What version of Commander do you have installed?

Bonus questions in case that isn't the problem!
- Are you using `import` or `require` to import commander?
- Are you using JavaScript or TypeScript?
- Are you using the setup code from the example?
```
const commander = require('commander'); // (normal include)
const program = new commander.Command();
```

**Comment by ShaMan123** [comment]
> What version of Commander do you have installed?

"commander": "^9.1.0",

> 
> Bonus questions in case that isn't the problem!
> 
> * Are you using `import` or `require` to import commander? `require`
> * Are you using JavaScript or TypeScript? **js**
> * Are you using the setup code from the example? yes
> 
> ```
> const commander = require('commander'); // (normal include)
> const program = new commander.Command();
> ```

**Comment by shadowspawn** [comment]
I can't reproduce this problem. Use `npm ls` to see the version(s) of Commander you have installed in your project, in case there is an old version being found somehow.

```
% npm ls commander
1707@1.0.0 /Users/john/Documents/Sandpits/commander/issues/1707
└── commander@9.1.0
```

**Comment by ShaMan123** [comment]
installation was corrupted
