### ISSUE TITLE
Access global options like --debug in other file

### ISSUE THREAD

**Issue by firmart** [tj/commander.js#1712]
I'm migrating from `yargs` and struggling to consume global options :

```js
// options.js
import { Command } from 'commander';
const program = new Command();
// ...
// Some functions of program's (sub)commands call log() from logger.js 
// ...
const options = program.opts();
export default options;
```

```js
// logger.js
import options from "./options.js"

const log = (string) => {
   if (options.debug) {
   //   ReferenceError: Cannot access 'options' before initialization
   }
}
```
Is there a way to expose globally some flags ?

**Comment by firmart** [comment]
@shadowspawn Many thanks for your quick reply! With your hint, I managed to pass down global options to subcommand actions and functions by writing `const options = program.opts` inside them. However, I cannot access subcommand options. Here is a minimal not working example.

```js
// options.js
import { program } from 'commander';
import subCommand from './subcommand.js';

const increaseVerbosity = (dummyValue, previous) => {
    return previous + 1;
}

program
    .usage("<cmd> <subcmd> [options]")
    .option("-g, --debug", "Activate debug mode.")
    .option("-v, --verbose", "Force the execution even if tasks are complete.", increaseVerbosity, 0)


program.addCommand(subCommand);

await program.parseAsync(process.argv);

const options = program.opts();
console.log("options.js", options);
```

```js
// subcommand.js
import { program } from 'commander';

const options = program.opts();

const getStatus = async () => {
    console.log("subcommand.js::getStatus", options)
}

const sub = program
    .command("sub")
    .usage("<subcmd> [options]");

sub
    .command('status')
    .usage("[options]")
    .option("-d, --date <date>", "Show the status of a date (YYYY-MM-DD).")
    .action(getStatus);

export default sub;
```

Now, executing `node options.js sub status -vv -g -d 2020-02-02` gives 

```
subcommand.js::getStatus { verbose: 2, debug: true }
options.js { verbose: 2, debug: true }
```

But the subcommand's options `date` is missing. Any idea what I'm doing wrong ?

**Comment by shadowspawn** [comment]
The program and the subcommand have their own options.

An action handler gets passed the parsed command-arguments and subcommand options (and the subcommand itself). Read about the arguments passed to the action handler: https://github.com/tj/commander.js#action-handler

From an action handler you have some other ways of getting at the global/program options without using a global. See  `.optsWithGlobals()` which is mentioned briefly as one of the additional routines available for options: https://github.com/tj/commander.js#options 

Bug: in `subcommand.js` you are creating `sub` by adding it to `program`, and then in `options.js` you are calling `addCommand` and adding it again. You'll notice you see sub` twice in the help: `node options.js -h`.

Here is a slightly modified `options.js` to return a new Command for `sub`, and adding the arguments in the action handler.

```
// options.js
import { program, Command } from 'commander';

const getStatus = async (options, cmd) => {
    console.log("subcommand.js::getStatus");
    console.log(`    subcommand options: %o`, options);
    console.log(`    program options: %o`, program.opts());
    console.log(`    combined options: %o`, cmd.optsWithGlobals());
}

const sub = new Command("sub");
sub
    .usage("<subcmd> [options]");
sub
    .command('status')
    .usage("[options]")
    .option("-d, --date <date>", "Show the status of a date (YYYY-MM-DD).")
    .action(getStatus);

export default sub;
```
 
```
% node options.js sub status -vv -g -d 2020-02-02
subcommand.js::getStatus
    subcommand options: { date: '2020-02-02' }
    program options: { verbose: 2, debug: true }
    combined options: { date: '2020-02-02', verbose: 2, debug: true }
options.js { verbose: 2, debug: true }
```

**Comment by shadowspawn** [comment]
(Thanks for the minimal example too!)

**Comment by firmart** [comment]
@shadowspawn Thanks you very much for your helps ! I migrated successfully from `yargs` (in which I didn't know how to deal with subsubcommands painlessly). `commander` is absolutely a relief, and your helps are very valuable. Thanks for spotting the bug and giving the example of the action handler, now everything is clear to me. Have a good day.
