### ISSUE TITLE
accumulate options

### ISSUE THREAD

**Issue by jeffmcaffer** [tj/commander.js#1715]
I have a hierarchy of nested commands each of which has a set of options. I've been trying to get all of the options available to the action that ultimately handles the user input. For example, the user should be able to do the following

```shell
myapp foo bar fred -a -b -c
```
where the code is roughly 

```javascript
const foo = program.command('foo').option('-a')
const bar= foo.command('bar').option('-b')
const fred = bar.command('fred').option('-c')
```
Ideally the options can all go at the end as shown. 

the motivation here is that each (sub)command is it's own little world and has user context shared across all of its subcommands. The subcommands add context (e.g., options). For example, `-b` on `bar` applies to all it's subcommands. I could replicate the parent options on all the subcommands but gets messy at scale and forces the children to know about their parents.

I've tried using various combinations of `passThroughOptions` and `enablePositionalOptions` but cannot get the effect described. Any suggestions?

**Comment by shadowspawn** [comment]
Quick answer: this is the default behaviour. What may have caught you out is that the option values will be available on the same command as defined the option, so via `foo.opts()`, or `fred.parent.opts()` et al. To make this scenario more convenient there is a recently added `.optsWithGlobals()` method which you can use in the action handler for `fred`.

**Comment by jeffmcaffer** [comment]
Ah, very nice. That did the trick. Thanks for the fast answer and sorry for missing that in the doc.
