### ISSUE TITLE
Way to hide options from help.

### ISSUE THREAD

**Issue by wandyezj** [tj/commander.js#1716]
The autogenerated help is quite convenient!

There are some test and other options that I would like to be able to automatically hide from help.

Would it make sense when specifying the `.option` to have a way to hide that option from help?

Perhaps something like:

```typescript
.option("--old", undefined, undefined, {
    hide: true,
});
```

**Comment by shadowspawn** [comment]
This has been made available via the Option class (as the `.option()` call was already too overloaded).


```js
program.addOption(new Option("--old").hideHelp());
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
