### ISSUE TITLE
Ability to pass options via a single array?

### ISSUE THREAD

**Issue by j-d-carmichael** [tj/commander.js#1717]
The standard method of declaring options:
```
commander
    .option('--init', 'some description')
    .option('-i, --input [path]', 'some description')
    .option('-o, --output [path]', 'some description')
```
This is fine, but is there a way to pass in those options via a simple array? EG Pass array to declare options in 1 go:
```
const optionsToDeclare = [
    ['--init', 'some description'],
    ['-i, --input [path]', 'some description'].
    ['-o, --output [path]', 'some description']
];
commander.options(optionsToDeclare)
```

Kind of similar to how https://www.npmjs.com/package/inquirer allows you to pass an array of questions instead of declaring 1 by 1.

**Comment by shadowspawn** [comment]
No, there is not a method taking an array of options, or an object of options.

You might do it yourself with your example array:

```
optionsToDeclare.forEach(args => program.option(...args));
```

**Comment by j-d-carmichael** [comment]
ok thanks

yes that workaround would do 👍
