### ISSUE TITLE
Is there any way to have an argument *before* the command?

### ISSUE THREAD

**Issue by Boiethios** [tj/commander.js#1723]
Hi, I create a CLI in which *all* the commands need to be passed a config file:

```
$ node my-command.js ConfigFile.toml foo --foo-option
$ node my-command.js ConfigFile.toml bar <bar argument> --bar-option
```

Is it possible to do something like that? I've spent a lot of time on custom command, but it doesn't work. My code looks like that:

```typescript
class MyCommand extends Command {
  createCommand(name: string) {
    return new MyCommand(name)
      .argument('config file')
      .option('-v', 'Display debug informations', false);
  }
}

new MyCommand()
  .name('My Command')
  .description('My awesome command')
  .version('0.1.0')
  // `foo` and `bar` are `Command`:
  .addCommand(foo)
  .addCommand(bar)
  .parse();
```

When I run the command, I get:

```
error: unknown command 'ConfigFile.toml'
```

Thanks by advance!

**Comment by shadowspawn** [comment]
No, you can not pass an argument before a command.

You might add a global option, or an option to each of the leaf commands, to pass in the config file.

**Comment by Boiethios** [comment]
It works if I don't use a custom class:

```typescript
new Command()
  .name('My Command')
  .description('My awesome command')
  .version('0.1.0')
  .option('-c <configFile>', 'Configuration file')
  .option('-v', 'Display debug informations', false)
  .addCommand(foo)
  .addCommand(bar)
  .parse();
```

Globally, I find that commander is hard to use. I usually write my CLI in Rust with `clap`, and it feels easier to use.

---

My solution to the problem I posted is that:

- I parse the first parameters by hand
- Then I call `command.parse(process.argv.slice(...))`

It works well that way.
