### ISSUE TITLE
Variadic <key, value...> option with choices for the keys

### ISSUE THREAD

**Issue by Till-G** [tj/commander.js#1744]
I'm trying to add a filter-option to my CLI, where the key is the type of filter like 'color' and the value might be 'blue'. The set of keys should be limited by a certain amount of choices: choices(['color', 'number', 'name']) etc. This option should be variadic as well so filtering for 'color' and 'name' is possible.

My current approach looks like this but I can't get everything working as one option.

```
.option('-c, --collect <value>', 'A repeatable value', collect, []) //from another issue
.addOption(new Option('-f, --filter <key, value...>', 'attribute').choices(['color','name']))
```

**Comment by shadowspawn** [comment]
It sounds like you need a custom option processing function (and can't use `.choices()`). What do you want the calling signature to be like when there are multiple filters/keys?

Variadic allows more than one option-argument like the following (but makes parsing ambiguities more likely if you also have positional arguments):

```
photos --filter color,red number,3 name,house
```

The "collect" style function needs the option specified multiple times (which also works with variadic):

```
photos --filter=color,red --filter=number,3 --filter=name,house

```

**Comment by Till-G** [comment]
Thank you for your reply. I've took the approach to make each filter an individual option to avoid parsing all arguments.

```
.option('--filter_col <value>', 'Filter color', collectValues, [])
.option('--filter_num <value>', 'Filter number', collectValues, [])
.option('--filter_name <value>', 'Filter name', collectValues, [])
```

It's easier to read and if a filter is called twice the options are already stored in a neat array.

**Comment by shadowspawn** [comment]
(Thanks for update.)
