### ISSUE TITLE
Command functions hanging

### ISSUE THREAD

**Issue by akrulwich** [tj/commander.js#1745]
Using commander 9.3.0, I have a project like this:

```
const program = new Command();

program
  .name('name')
  .description('description');

program.command('init')
  .description('Initialize')
  .action(() => {
    console.log(123)
  });

program.parse()
```

When I run the script on the command line, it does the log and then hangs

```
me@me repo (main) $ ../repo/bin/cli init
123

```

However, when I add a readline to the command, it exits normally afterwords.

```

const program = new Command();

program
  .name('name')
  .description('description');

program.command('init')
  .description('Initialize')
  .action(() => {
    init()
  });

program.parse()

const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function init() {
	const main = async () => {
	  await requestName((name) => {
	      console.log(name);
	  });

	  rl.close();
	}

	main();
}

function requestName(uponAnswerCallback) {
  return new Promise((resolve, reject) => {
    rl.question('Default topic name: ', (answer) => {
    	uponAnswerCallback(answer);
        resolve();
    })
  })
}
```

It seems like something about the readline call is reseting the terminal but I'm not sure how.

Thanks!

**Comment by akrulwich** [comment]
It looks like I can get it working by terminating all of my action functions with `process.exit();`, but I'm curious why that's necessary. Thanks!

**Comment by shadowspawn** [comment]
I suspect you have a couple of problems.

First, the hang may be if you create a readLine interface but don't close or `unref` it. The [documentation](https://nodejs.org/dist/latest-v16.x/docs/api/readline.html#readlinecreateinterfaceoptions) says:

> When creating a readline.Interface using stdin as input, the program will not terminate until it receives an [EOF character](https://en.wikipedia.org/wiki/End-of-file#EOF_character). To exit without waiting for user input, call process.stdin.unref().

Second, if you have any async action handlers, then you need to call `.parseAsync()` instead of `parse()` and handle the returned promise.

-----

Your init routine does not look like I expected, I expected an `async` and another `await`:
```
function async init() {
	const main = async () => {
	  await requestName((name) => {
	      console.log(name);
	  });

	  rl.close();
	}

	await main();
}
```

**Comment by canopy-js-user** [comment]
@shadowspawn Thanks for the help! Sorry if I was unclear – the program _works_ when there's a readline call, but when this is the entire program:

```
const program = new Command();

program
  .name('name')
  .description('description');

program.command('init')
  .description('Initialize')
  .action(() => {
    console.log(123)
  });

program.parse()

```

it hangs. Any idea why that might be?

Thanks!

**Comment by akrulwich** [comment]
@shadowspawn Thanks for the help! Sorry if I was unclear – the program works when there's a readline call, but when this is the entire program:

const program = new Command();

program
  .name('name')
  .description('description');

program.command('init')
  .description('Initialize')
  .action(() => {
    console.log(123)
  });

program.parse()

it hangs. Any idea why that might be?

Thanks!

**Comment by shadowspawn** [comment]
Er, no!  How are you running the program? 

What shell environment are you running the program from? (e.g. Terminal on MacOS, docker container using Ubuntu, PowerShell on Windows.) 

Is that code the only code that node is loading, or it is the CLI part of an application and there is other code involved? 

(I don't have any theories yet, but I think it is something outside that code that is causing the hang.)

**Comment by akrulwich** [comment]
Hi there,

Sorry for the delay.

I am running the code on Mac OS 12.4 on an Apple Processor. I am using iTerm 2.

The code is being run from an executable that loads just that code, looking like this:

```
#!/usr/bin/env node

const { Command } = require('commander');

const program = new Command();

program
  .name('project')
  .description('etc');

program.command('init')
  .description('Initialize a project')
  .action(() => {
  });

```

As written, running ./file init will cause the terminal to hang. However, like I said, if the action function does a readline call, or does a `process.exit();` then it works fine.

Thanks for your help!

**Comment by shadowspawn** [comment]
Thanks for details. I can't reproduce in Terminal or in iTerm 2.

I'll keep thinking, but some more questions in meantime.

1) The example code is missing a call to `program.parse()` ?

2) Are you using zsh as your shell?
```
echo $SHELL
```

3) What version of node are you using?

```
node --version
```

**Comment by akrulwich** [comment]
1. Sorry, the code did end with `program.parse();` but I forgot to include that
2. yes `/bin/zsh`
3. `v14.17.4`

Thanks!

**Comment by shadowspawn** [comment]
To eliminate any recent code changes, would you please try installing `commander@5` and run the test program again?

(And then switch back for Commander v9, so you aren't surprised later there are less features. 😄  )

**Comment by shadowspawn** [comment]
Another question. All questions, not answers. Until I get the right question... What architecture is the node you are running? (I am guessing it might be Intel running in Rosetta. Not a problem as such, just another data point.)

Run:
```
file $(which node)
```

**Comment by akrulwich** [comment]
Hi there,

So when installing commander@5, I think I realized what the problem was, you guessed it earlier when you said that opening a readline interface without an EOF would cause a problem.

The reason I was confused was because I had code like this:

```
#!/usr/bin/env node

const { Command } = require('commander');
const init = require('./commands/init');

const program = new Command();

program
  .name('project')
  .description('description');

program.command('init')
  .description('Initialize a project')
  .action(() => {
  	//init();
  });

```

So I thought that if I commented out `init()` in the action function, then there was no way that that code could be affecting the script, but in `'./commands/init'` I was making a readline interface, and requiring it ran that code whether `init()` was called or not, so ironically every command _except_ init wasn't working, because when `init()` actually got called, it closed the readline interface so there wasn't a problem.

So sorry about that, I should have been more careful in the debugging process. Thank you again for all of your help.

Best
Allen

**Comment by shadowspawn** [comment]
Ah ha! Glad we got to the bottom of that. Thanks for the update.
