### ISSUE TITLE
feature: allow to save userdefaults in a seperate file

### ISSUE THREAD

**Issue by mknj** [tj/commander.js#1748]
Env variables work nicely for programs with a small number of arguments.

With more arguments it would be nice to be able to save the given arguments as defaults. (i.e. as json file under $HOME/.config/programname.json)

## example
```sh
# save defaults without actually calling the program
$ program --saveAsDefaults --host google.com --port 42 --username bob --color blue
$ cat ~/.config/program.json
{
  "host":"google.com",
  "port":42,
  "username":"bob",
  "color":"blue"
}
```

**Comment by shadowspawn** [comment]
Thanks for the description.

Configuration files is a big topic, with lots of variation in where they are stored, and the configuration file format, let alone writing. Configuration files were discussed in #1584, and there was so little common ground in that discussion that we ended up just improving support for authors doing it themselves. (e.g as being used in #1713)

You are describing something (deliberately) more self-contained and limited. I'm not sure what percentage of users that will suit. Happy to leave this open for a while and see what feedback and likes it gets.

**Comment by mknj** [comment]
My intention was a bit different, but after reading the comments i understand that this is a broader issue.

you could align my  need with the '-c --config <file>' proposal by making ~/.config/program.json the default config file.

Feel free to close the issue.

**Comment by jpilgrim** [comment]
I have written an extension to commander.js which does exactly this: [cmdsettings](https://www.npmjs.com/package/cmdsettings)

So, this issue is just to inform people if they need this feature -- there it is.

It may not cover all cases, but it serves me well in several projects.
