### ISSUE TITLE
Multi Value Flags?

### ISSUE THREAD

**Issue by leeola** [tj/commander.js#175]
Is there a way that i am missing to handle multi-value flags? Eg: `foo --flag bar baz` would output parse to `program.flag = ['bar', 'baz']`

If there isn't support, any opinion on the best option for this? Currently i am planning on using a string and splitting spaces, but `foo --flag 'bar baz'` is sub-optimal in my opinion.

Any thoughts would be appreciated, thank you

**Comment by th0r** [comment]
There is a [Coercion](https://github.com/tj/commander.js#coercion) section in documentation that contains simpler implementation of `appender` function:
```js
function collect(val, memo) {
  memo.push(val);
  return memo;
}

program.option('-c, --collect [value]', 'A repeatable value', collect, []);
```

**Comment by ryan-williams** [comment]
The Python [`click`](https://click.palletsprojects.com/) library has a notion of ["count" flags](https://click.palletsprojects.com/en/8.1.x/options/#counting):

```python
@click.command()
@click.option('-v', '--verbose', count=True, 'Pass 1, 2, or 3 times for different verbosity levels')
def main(verbose):
    print(f'verbose level: {verbose}') 
```

It's a special case of the "multiple-value flags" discussed here, and seems to be doable in `commander` like:

```js
import program from "commander";

const options =
    program
        .option('-v, --verbose', 'Pass 1, 2, or 3 times for different verbosity levels', (_, v) => v + 1, 0)
        .parse(process.argv)
        .opts()

const { verbose = 0 } = options
console.log(`verbose level: ${verbose}`)
```

For some reason, the default `0` from the `.option` doesn't seem to work, I got `undefined` unless I also specified it in the `const { verbose = 0 } = options` 🤷.

**Comment by shadowspawn** [comment]
@ryan-williams This is a 10 year old closed issue, so not the best place to get a response.

I was unable to reproduce getting `undefined` for `verbose` in the options using your example program. I suggest you open a new issue if you are still having problems. (Perhaps that was happening in a larger program with different code.)

Note: there is an example function `increaseVerbosity()` in the README. It does effectively the same as you are doing in your example.

https://github.com/tj/commander.js#custom-option-processing
