### ISSUE TITLE
[question] Reusing options between subcommands and 'main'

### ISSUE THREAD

**Issue by darcyrush** [tj/commander.js#1750]
I can 'reuse' commands between subcommands nicely, which populates the options in the call backs as expected
```ts
const program = createCommand();
  program
    .command('one')
    .description(desc')
    .requiredOption('--reuse-example [reuseExample]', 'Example of reusable option')
    .requiredOption('--example [example]', 'Example of separate required option')
    .action(asyncCallBackOne);
  program
    .command('two')
    .description(desc')
    .requiredOption('--reuse-example [reuseExample]', 'Example of reusable option')
    .action(asyncCallBackTwo);
await program.parseAsync(process.argv);
```
And when I run help for each I see as expected;
```
Usage: program one [options]

desc

Options:
  --reuse-example [reuseExample]      Example of reusable option
  --example [example]                 Example of separate required option
  -h, --help                          display help for command
```
```
Usage: program two [options]

desc

Options:
  --reuse-example [reuseExample]      Example of reusable option
  -h, --help                          display help for command
```

However, if i try and reuse options between a sub command and the 'main' program;
```ts
const program = createCommand();
  program
    .requiredOption('--reuse-example [reuseExample]', 'Example of reusable option')
    .action(asyncCallBackMain);
  program
    .command('one')
    .description(desc')
    .requiredOption('--reuse-example [reuseExample]', 'Example of reusable option')
    .requiredOption('--example [example]', 'Example of separate required option')
    .action(asyncCallBackOne);
  program
    .command('two')
    .description(desc')
    .requiredOption('--reuse-example [reuseExample]', 'Example of reusable option')
    .action(asyncCallBackTwo);
await program.parseAsync(process.argv);
```
then the sub commands will always complain of the missing requiredOption - even if it is passed
```
error: required option '--reuse-example [reuseExample]' not specified
```

I can work around this my making the 'main' program a subcommand (like 'start'), but I would _prefer_ if I didn't have to invoke a subcommand just to start the main program.

I'm not sure I am creating the 'main' program correctly though. I tried `new Command()` but with the same outcome. I also tried two separate command instances with two `parseAsync(process.argv)` calls (one for 'main' and one for the commands), but then commander doesn't register the commands in the second instance.

```
Linux: Ubuntu 20.04
Commander: 9.3.0
NodeJS: 18.2.0
```

**Comment by shadowspawn** [comment]
A quick answer (time limited).

Options on the program are "global" and get processed when calling a subcommand, so the program consumes your required option and the subcommand does not see it.

To get the behaviour you want, add a subcommand (like `start`) as you suggested, but also pass configuration to make it the default command to run when no subcommand is specified. Look for `isDefault` in the README, and here is an example: 

- https://github.com/tj/commander.js/blob/master/examples/defaultCommand.js

**Comment by darcyrush** [comment]
Apologies, I did try to search beforehand. Thank you for the solution and rapid response!
