### ISSUE TITLE
Variadic options return first value only

### ISSUE THREAD

**Issue by ben-biddington** [tj/commander.js#1752]
When I run [the variadic options sample](https://github.com/tj/commander.js/blob/master/examples/options-variadic.js) 

```
var commander = require("commander");
const program = new commander.Command();

program
  .option("-n, --number <value...>", "specify numbers")
  .option("-l, --letter [value...]", "specify letters");

program.parse(process.argv /* Fails without this supplied */);

console.log("Options: ", program.opts());
console.log("Remaining arguments: ", program.args);

// Try the following:
//    node options-variadic.js -n 1 2 3 --letter a b c
//    node options-variadic.js --letter=A -n80 operand
//    node options-variadic.js --letter -n 1 -n 2 3 -- operand

```

I get this output:

```
node options-variadic.js -n 1 2 3 --letter a b c
Options:  { number: '1', letter: 'a' }
Remaining arguments:  [ '2', '3', 'b', 'c' ]
```

```
$ node -v
v16.6.0
```

```
 "commander": "^4.1.1",
```

Whatever I try I only ever get the first value in the list.

**Comment by shadowspawn** [comment]
I suspect you are using an older version of Commander that does not have the variadic support. Try running this in your project directory to see what version(s) of Commander are being used:

```
npm ls commander
```

**Comment by ben-biddington** [comment]
Oh I see my version is very old -- will try latest

**Comment by ben-biddington** [comment]
Weird yep sorry latest version works

**Comment by shadowspawn** [comment]
Variadic option support was added in Commander v6.

Thanks for the detailed description of the problem. Good to see the examples being used. 😄
