### ISSUE TITLE
Feature discussion: Inherit options in subcommands

### ISSUE THREAD

**Issue by arve0** [tj/commander.js#1753]
Hi! Thanks for commander 🙌
Is commander considered feature complete? Any chance for a *inherit options* feature? Or always populating options in subcommands when same is also defined in parent commands?

I find it hard to create a hierarchy of commands that share common options. I also find the "options are global behavior" unintuitive. Especially when you are unaware of any parent command using the same option.

I've read issues like #1750, #1739, #1616 and #1229.

Take this example, where `print` and `print pdf` would have very different action-implementations:
```js
#!/usr/bin/env node
const { Command } = require('commander');

class MyRootCommand extends Command {
  createCommand(name) {
    const cmd = new Command(name);
    cmd.option('-v, --verbose', 'use verbose logging');
    return cmd;
  }
}

const program = new MyRootCommand();

const print = program.command('print')
  .option('--a4', 'Use A4 sized paper')
  .action((options) => {
    console.log('print options: %O', options);
  });

print.command('pdf')
  .option('--a4', 'Use A4 sized paper')
  .action((options) => {
    console.log('print pdf options: %O', options);
  });

program.parse();
```

The help suggests that `--a4` is available to both "print" and "print pdf":
```sh
> ./common-options.js print --help
Usage: common-options print [options] [command]

Options:
  -v, --verbose  use verbose logging
  --a4           Use A4 sized paper
  -h, --help     display help for command

Commands:
  pdf [options]
```
```sh
> ./common-options.js print pdf --help
Usage: common-options print pdf [options]

Options:
  --a4        Use A4 sized paper
  -h, --help  display help for command
```

Though, it is not:
```sh
> ./common-options.js print --a4
print options: { a4: true }

> ./common-options.js print pdf --a4
print pdf options: {}
```

Solvable through `optsWithGlobals` or splitting into `print-printer` and `print-pdf` commands. Maybe also with splitting `print pdf` to separate executable?

Anyhow, would be nice if options was set in subcommands when same options are defined longer up in the hierarchy.

**Comment by shadowspawn** [comment]
Thanks for the detailed description.

The feature which is a good match for most of your description is `.enablePositionalOptions()`. This turns off the "global" behaviour where the option can appear before or after a subcommand.

> Especially when you are unaware of any parent command using the same option.

With positional options, options after the subcommand belong to the subcommand.

> Take this example, where print and print pdf would have very different action-implementations

With positional options, the `print --a4` sets the print option and `print pdf --a4` sets the pdf option.

**Comment by shadowspawn** [comment]
> Is commander considered feature complete? Any chance for a _inherit options_ feature? Or always populating options in subcommands when same is also defined in parent commands?

Have a look at #1551 for some previous coverage of enhancements to global options. I have had a go at the two most popular: one turned into an example file instead, and `.optsWithGlobals()` came out of the other.

"always populating" is similar to https://github.com/tj/commander.js/issues/1551#issuecomment-869093223, and was the least popular (somewhat to my surprise at the time).

**Comment by shadowspawn** [comment]
(`.enablePositionalOptions()` came out of #1229 which you mentioned, so you may have already looked at it.)

**Comment by shadowspawn** [comment]
> Out of curiosity, that is useful when running both actions?

Yes, the command-specific option is passed into the action handler (if that is what you are asking).

> Do you want to keep it the way it is? 

I don't think "inherit" is a common or clean enough use case to try and add explicit support. But willing to discuss it in more detail if you wish.

> What about throwing when defining the same option twice?

A major consideration for throwing is it would completely break any existing programs that happen to have overlapping options across levels, and are currently working fine _apart_ from the overlapping option in the subcommand. Commander has a big installed base, so adding throws with helpful guidance to authors of new code has to be balanced against breaking existing code. It could be considered in a major release.

Can the guidance in a `throw` cover enough of the likely cases, not just that there is a problem? The two scenarios that spring to mind are:
- program with a subcommands and a default behaviour with own options, where a solution is move default behaviour into a subcommand and use `isDefault`
- overlapping flags at different levels, where a solution for some cases is `.enablePositionalOptions()`)

**Comment by arve0** [comment]
> Yes, the command-specific option is passed into the action handler (if that is what you are asking).

But that action handler never runs? Am I missing something? Take this example:

```js
const commonOption = createOption("-d, --debug");

const program = new Command()
  .addOption(commonOption)
  .action((options) => {
    console.log("program options: %O", options)
  })
  .enablePositionalOptions();

const print = program.command('print')
  .addOption(commonOption)
  .action((options) => {
    console.log('print options: %O', options);
  });

print.command('pdf')
  .addOption(commonOption)
  .action((options) => {
    console.log('print pdf options: %O', options);
  });

program.parse();
```

Running yields:
```sh
❯ ./option.js -d print -d pdf -d
print pdf options: { debug: true }
```

Adding tests in global scope works:
```js
if (program.opts().debug) {
  console.log("program debug set")
}

if (print.opts().debug) {
  console.log("print debug set")
}
```

```
❯ ./option.js -d print -d pdf -d
print pdf options: { debug: true }
program debug set
print debug set
```

That is how it's intended?

> A major consideration for throwing is it would completely break any existing programs that happen to have overlapping options across levels, and are currently working fine apart from the overlapping option in the subcommand. Commander has a big installed base, so adding throws with helpful guidance to authors of new code has to be balanced against breaking existing code. It could be considered in a major release.

Fully agree!

> Can the guidance in a throw cover enough of the likely cases, not just that there is a problem? 

Sounds reasonable to try covering the likely cases 👍 The second one is probably common error (as multiple issues state).

> program with a subcommands and a default behaviour with own options, where a solution is move default behaviour into a subcommand and use isDefault

I do not understand this sentence, but am eager to learn the use case. Can you provide an example?

**Comment by arve0** [comment]
Btw, an alternative to throwing would be not showing option in help, when it isn't considered an "regular" option to that nested subcommand.

**Comment by arve0** [comment]
> Can you provide an example?

Aha, this is the "make sure commands using the same options never follow a chain command -> subcommand". Like this?

```js
const program = new Command()
  .addOption(commonOption)
  .action((options) => {
    console.log("program options: %O", options)
  });

program.command('print')
  .addOption(commonOption)
  .action((options) => {
    console.log('print options: %O', options);
  });
```

which should be changed into:

```js
const program = new Command()

program.command("main", { isDefault: true })
  .addOption(commonOption)
  .action((options) => {
    console.log("program options: %O", options)
  })
  .enablePositionalOptions();

program.command('print')
  .addOption(commonOption)
  .action((options) => {
    console.log('print options: %O', options);
  });
```

Right?

**Comment by shadowspawn** [comment]
From https://github.com/tj/commander.js/issues/1753#issuecomment-1158595721

> That is how it's intended?

Yes, the options for each nested command are available on the command. 

A helper method for some setups is `.optsWithGlobals()` which merges together the options in the hierarchy.

To access the global/inherited options from within an action handler, you can access `cmd.parent`, but up to you to make sense of the hierarchy! For example:

```js
print.command('pdf')
  .addOption(commonOption)
  .action((options, printCmdParam) => {
    console.log('print pdf options: %O', options);
    console.log('print options looking up: %O', printCmdParam.parent.opts());
    console.log('program options looking up: %O', printCmdParam.parent.parent.opts());
  });
```

**Comment by shadowspawn** [comment]
> > program with a subcommands and a default behaviour with own options, where a solution is move default behaviour into a subcommand and use isDefault

> Aha, this is the "make sure commands using the same options never follow a chain command -> subcommand". Like this?
> ...
> Right?

Yes indeed. 😄

**Comment by shadowspawn** [comment]
I think we covered some good ground with scenarios with options at multiple levels, and the existing support. I don't see any action items I want to followup for now.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by jcalfee** [comment]
Maybe a bit more in the help?  I can't figure out how to share options between commands and get them to show up in the help for each command.  I ended up copying the options twice.  Thank you!

**Comment by shadowspawn** [comment]
@jcalfee 

Have a look at: https://github.com/tj/commander.js/blob/master/examples/global-options.js

**Comment by jcalfee** [comment]
Thanks, the file got refactored, and this one did the trick:  https://github.com/tj/commander.js/blob/master/examples/global-options-nested.js
