### ISSUE TITLE
Ommitting an optional argument causing wrong options values

### ISSUE THREAD

**Issue by devklick** [tj/commander.js#1755]
I have a simple command with an optional argument, `src`, which has a default value. I also have an option, `-o`, with no default value. 

When I omit the argument and specify the option, the value I specify for the option is used for the argument, and I end up with an arbitrary value for the option. 

Example code:
```js
program
  .command('process')
  .argument('[src]', 'The source file', 'data.csv')
  .option('-o, --overwrite')
  .action((arg, options) => {
    console.log('arg', arg);
    console.log('options', options);
  })

program.parse();
```
Example invocation
```
node index.js process -o false
```
Logs:
```
arg false
options { overwrite: true }
```
Expectation
I would expect my command to be translated to the following
```
node index.js process data.csv -o false
```
And log the following:
```
arg data.csv
options { overwrite: false }
```

**Comment by shadowspawn** [comment]
Commander does not support passing `false` as an option-argument for boolean options. Boolean options are either specified on the command-line, or not, and never take an option-argument.

There is support for options which can be negated. You could add an option for `--no-overwrite`. 

If you do want `--overwrite` to take an option-argument, you would declare it like:

```
.option('-o, --overwrite <value>')
```

(I wasn't sure what you intended for `overwrite` so covered a few possibilities. Ask again if you still have questions.)

**Comment by devklick** [comment]
>Commander does not support passing false as an option-argument for boolean options

That makes total sense. So my `overwrite` option was being logged as true because it's a boolean flag that exists in my command, hence... it's can only be true. 

I'm glad you covered both possibilities there, because my problem was a mix of the two. Thanks for your help :grinning:
