### ISSUE TITLE
exitOverride not work when required option is missing?

### ISSUE THREAD

**Issue by yangmiao7** [tj/commander.js#1757]
```
const flash = createMyCommand().exitOverride()

myCommand
        .command('download')
        .description('description')
        .requiredOption('--path <path>', '....')
        .option('--files <files...>', '....')
        .option('--output [output]', '....')
        .action(action)
```

When I call without passing in the `path` option, When I call without the path option, the process is forced to exit, with exit code 1.

cause my `Jest` to not continue to run.

It is expected that the `exitOverride` method will not exit the process

Version：9.3.0

**Comment by shadowspawn** [comment]
I think there is a problem outside the code in your sample. How does `myCommand` get created?

I tried something similar:

```js
const { createCommand } = require('commander');

const flash = createCommand().exitOverride()

flash
    .command('download')
    .requiredOption('--path <path>', '....')

try {
    flash.parse();
} catch (err) {
    console.log (`Caught error: ${err.message}`)
}
```

And see an exception being thrown:
```console
$ node index.js download
error: required option '--path <path>' not specified
Caught error: error: required option '--path <path>' not specified
```

**Comment by yangmiao7** [comment]
The exception code like this:
```
const { createCommand } = require('commander');

const flash = createCommand()

flash
    .command('download')
    .requiredOption('--path <path>', '....')

try {
    flash.exitOverride().parse();
} catch (err) {
    console.log (`Caught error: ${err.message}`)
}
```

**Comment by shadowspawn** [comment]
> I probably found the reason, does `exitOverwrite` need to be called before registering the command?

Yes. Do the program configuration early, before adding subcommands.

For interest, a whole lot of configuration is inherited by the subcommand from the program when the subcommand is registered: https://github.com/tj/commander.js/blob/dccc90676aa960563ae0d0f3414a64a231286a69/lib/command.js#L90

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
