### ISSUE TITLE
Command cannot be parsed correctly when description provided

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [tj/commander.js#1764]
This works fine.

```
import {Option, program} from "commander";

program
  .command("serve")
  .addOption(new Option("-p, --port <port>", "Port number").env("PORT").default(8080))
  .addOption(new Option("-D, --database-url <url>", "Database URL").env("DATABASE_URL"))
  .action((options) => {
    console.log(options);
  });

program
  .command("migrate")
  .addOption(new Option("-D, --database-url <url>", "Database URL").env("DATABASE_URL"))
  .action((options) => {
    console.log(options);
  });

program.parse();
```

But if I add a description to a command - it stops working.
```
program
  .command("serve", "Run server")
...
```
Command line: `$ ts-node src/app.ts serve -p 8083`
Console output:
```
Uncaught Error: Cannot find module './app-serve'
```

**Comment by shadowspawn** [comment]
There are two very different styles of command. One uses an action handler and the description is supplied in a separate method call, like:

```js
program
  .command("serve")
  .description("Run server")
  .action((options) => {
    console.log(options);
  });
```

The other form of command calls out to a separate executable to implement the subcommand. This form includes the  description  in the `.command()` call and that is the only configuration:

```js
program
  .command("serve", "Run server")
  .command("migrate", "Migrate database");
```
 
Have a look at the section on Commands in the README.

- https://github.com/tj/commander.js#commands

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@shadowspawn oh, I see. My apologies.
