### ISSUE TITLE
Executable terminating while program is still parsing

### ISSUE THREAD

**Issue by jcandell2023** [tj/commander.js#1765]
I have an electron application and am trying to use commander to add a command line interface. I am using an async action and parseAsync. When I run the command line it works but the terminal shows it has terminated immediately and it then prints out and finishes running after this. Any ideas about what I am doing wrong or is this a commander issue?

**Comment by shadowspawn** [comment]
I am not sure what is happening. What do you mean by "the terminal shows it has terminated immediately"? Can you reproduce this in a small program you can share?

(It does not sound like a Commander issue.)
