### ISSUE TITLE
`store_true`/`store_false` if flag passed then true, if not passed then false

### ISSUE THREAD

**Issue by dereckdemezquita** [tj/commander.js#1766]
Did I miss something? I cannot get my programme to have a boolean flag. If flag is not passed the argument is `false` if it is passed then it is set to true. In the python module this can be achieved by passing `store_true`/`store_false`.

How can I do this in `commander`?

```js
program
    .addHelpCommand("-h, --help")

    .requiredOption('-s, --str <string>', 'Some string argument.')
    .option('-v, --verbose <boolean>', 'Verbosity.', "store_true") // this is what I would want to do
```

**Comment by shadowspawn** [comment]
The default behaviour for a boolean flag is that the option is undefined if not used, and `true` if the option is passed. A boolean option does _not_ take an option argument.

```
program
   .option('-v, --verbose')
```

If you want the option explicitly false/true you can supply a default value, like:

```
program
   .option('-v, --verbose', 'Verbosity.', false)
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
