### ISSUE TITLE
Option always undefined

### ISSUE THREAD

**Issue by NathanC** [tj/commander.js#1769]
Options are ***always*** showing up as undefined (both in the error message and in my action handler).

I have my program set up like this:
```
program.command("deploy")
    .description("kick off a deploy")
    .addOption(
        new Option(
            "--only", "perform a partial deploy"
        ).choices(["frontend", "backend"])
    )
    .action((args, options) => console.log("only deploying: " + options.only))
    .parse();
```

When I try to run this command:
`myScript deploy --only frontend`

I get this error:
`error: option '--only' argument 'undefined' is invalid. Allowed choices are frontend, backend.`

If I try it with a disallowed choice (e.g., `--only foo`), I still get
`error: option '--only' argument 'undefined' is invalid. Allowed choices are frontend, backend.`

I logged out my argv, and the script is correctly getting all the args:
```
args:  [
  'C:\\Program Files\\nodejs\\node.exe',
  {script path},
  'deploy',
  '--only',
  'frontend'
]
```

If I don't pass an only flag at all (e.g, `myScript deploy`), I get the handler console log statement:
`only deploying: undefined`

This is happening on Windows, with Node v16.4.2,

Any idea what might be happening? Am I constructing something wrong, or is this a bug?

**Comment by shadowspawn** [comment]
(Quick answer without trying code, so may be some errata.)

1) You have accidentally created a boolean option and the choices will be broken. Add an option-argument to the declaration:

```js
 new Option("--only <partial>"...
```

2) Your command does not have any command-arguments, at least in the example. So your action handler should look like:

```js
.action((options)...
```

**Comment by shadowspawn** [comment]
(Good details in the description, thanks.)

**Comment by NathanC** [comment]
Perfect, that solved my issue! Thanks for the prompt response. Great library by the way, I really like the help messages it generates.

**Comment by Loque18** [comment]
I'm having the same issues 

```
const { program } = require('commander');

program.name('template scripts').version('1.0.0').description('Set of scripts to bootstrap development');

program
    .command('gen-template')
    .description('Generate a template page')
    .argument('<page-name>', 'Page name')
    .option('-o, --output <folder>', 'Output folder')
    .action((pageName, options) => {
        console.log('pageName', pageName);
        console.log('options', options);
    });
    
   program.parse();
```
npm run scripts gen-template --output=./pages test

I always get 
pageName test
options {}

**Comment by shadowspawn** [comment]
@Loque18 
You have a different problem, which is that `npm run` is eating the options before they reach your script. 

See #1761 for a longer explanation.

**Comment by Loque18** [comment]
Yep, it worked!!! thank you so much

**Comment by KeanuTomatoMomotaro** [comment]
Node version v16.15.1.
MAC OSX 11.15.1.

Accessing the `options` value in a callback returns `undefined`. 

```
import { Command } from 'commander';

const app = new Command();

app
  .name('some-app')
  .description('Some new cli app')
  .version('0.1')
  .option('-f, --flag <string>', 'some flag parameter')
  .option('-d, --date <dd/mm/yyyy>', 'some date parameter')
  .action((str, options) => {
    console.log(options.flag);
    console.log(options.date);
  });

app.parse();
```
example output:
```
node index.js -f abc -d 20/04/2022
undefined
undefined
```

However, this works:
```
import { Command } from 'commander';

const app = new Command();

app
  .name('some-app')
  .description('Some new cli app')
  .version('0.1')
  .option('-f, --flag <string>', 'some flag parameter')
  .option('-d, --date <dd/mm/yyyy>', 'some date parameter');

app.parse();

const options = app.opts();

console.log(options.flag);
console.log(options.date);
```

example output:
```
node index.js -f abc -d 20/04/2022
abc
20/04/2022
```

**Comment by shadowspawn** [comment]
@KeanuTomatoMomotaro 

The action handler receives one parameter for each declared command-argument, then the options, then the command object. You have not declared any command-arguments so the signature should look like:

```js
//  .action((str, options) => {
  .action((options) => {
```

(A quick check for this sort of mistake is to log out the parameters and see if they are a string or the options or a command.)

**Comment by backrunner** [comment]
Windows 11 with PowerShell v7.2.5
Node v16.15.1
Commander v9.4.0

Always got `{}` for options, I'm running the script directly and already defined a parameter to the option.
Things seems weird, cannot figure out what's wrong.
Could someone help me out of my issue?

Here's the code:
```ts
// this main command works well
program
  .argument('<folder>', 'the folder to upload')
  .option('-c, --config <configPath>', 'path to r2 batch upload config file.')
  .option('-l, --limit <limit>', 'limit upload files count (useful for testing)')
  .action(async (folder: string | undefined, options: UploadOptions) => {
     // something to do
  });

// the options of this sub-command always come up an empty object
program
  .command('retry')
  .argument('<logFilePath>', 'the previous upload log file generated by this tool')
  .option('-c, --config <configPath>', 'path to r2 batch upload config file.')
  .option('-l, --limit <limit>', 'limit upload files count (useful for testing)')
  .action(async (logFilePath: string, options: RetryOptions) => {
    console.log(logFilePath, options, process.argv);
  });
```

Here's my command and output:
```
r2upload retry "./upload_log-1660502164172.json" -c "./upload_config.json"
./upload_log-1660502164172.json {} [
  'C:\\Program Files\\nodejs\\node.exe',
  'H:\\nodejs\\node_global\\node_modules\\r2-batch-upload\\bin\\cli.js',
  'retry',
  './upload_log-1660502164172.json',
  '-c',
  './upload_config.json'
]
```

**Comment by shadowspawn** [comment]
@backrunner 

Good description and information, thanks.

You have the same options at the program level as in your subcommand. By default the options for the program can appear anywhere in the command line, so the program is eating the options before your subcommand gets a chance to see them.

You could:
- treat the program options as global, and read the program options in the subcommand
- move the program action into a subcommand and make it the default command
- turn on positional options (`enablePositionalOptions()`)

Have a look at the middle option first, it is likely what you want.

See for example: #1616 #1750

**Comment by shadowspawn** [comment]
I'm going to close this issue as the original issue was been resolved, and the title fits a number of different underlying problems.
