### ISSUE TITLE
Node.js CLI program hangs till broken with Ctrl-C.

### ISSUE THREAD

**Issue by ibacompre** [tj/commander.js#1772]
The issue I'm facing is very similar to Issue# 1745 (https://github.com/tj/commander.js/issues/1745#issue-1260088398). I'm using commander and inquirer. 

I've a simple Node.js command line program that uses commander and inquirer for taking command line inputs. After taking inputs and printing `Hello World` it just hangs there till the process is broken with Ctrl-C. I've tried both `program.parse()` and `program.parseAsync()`.

Here is the code:

```
#!/usr/bin/env node

const program = require('commander');
const { prompt } = require('inquirer');

const questions = [
    {
        type: 'input',
        name: 'id',
        message: 'Your Name: '
    }
];

program
    .version('1.0.0')
    .description('Test Node CLI program');

program
    .command('search')
    .alias('s')
    .description('Welcome a user')
    .action(() => {
        prompt(questions). then((answers) => {
           console.log('Hello world!');
        })
    }); 

// program.parse(process.argv); 
program.parseAsync(process.argv); 
```  

Environment is as follows: 
OS: Mach-O 64-bit executable arm64
Shell: /bin/zsh - Terminal and iTerm2 
Version: "commander": "^9.4.0", "inquirer": "8.2.4"
Node version: v16.15.1

Program launch and sample output:
> node start.js search
? Your Name:  John Doe
Hello world!
^C
>

**Comment by shadowspawn** [comment]
I can't reproduce the problem using the sample program. What version of node and inquirer are you using? (I tried with `inquirer@8` and node v16.16.0.

My guess is a dangling promise.

`parseAsync` is the correct call if any of your action handlers are async. At the moment you are leaving the inquirer promise to sort itself out. If you make the async explicit, it could look like:

```js
program
    .command('search')
    .alias('s')
    .description('Welcome a user')
    .action(async () => {
        const answers = await prompt(questions);
        console.log('Hello world!');
    }); 
```

**Comment by ibacompre** [comment]
@shadowspawn Thank you for your response. As you pointed out it was a dangling database connection, once closed, program ended without any issues.

**Comment by shadowspawn** [comment]
Thanks for update. I am glad you have it sorted out.
