### ISSUE TITLE
Typescript's new moduleResolution breaks commander's typing

### ISSUE THREAD

**Issue by kwasimensah** [tj/commander.js#1773]
See https://github.com/microsoft/TypeScript/issues/49160 . Typescript's new moduleResolution type doesn't look at the top-level types field in your package.json (it now uses the logic specified in https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)

**Comment by shadowspawn** [comment]
What version of Commander are you using?

There was support added in Commander v9.2.0 for (at the time) "NodeNext" type resolution.

Reference: #1703 #1704

**Comment by kwasimensah** [comment]
yup, nevermind. I'm using 9.1.0. I'll update. Thanks!

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
