### ISSUE TITLE
arguments become undefined under powershell

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [tj/commander.js#1775]
Hello,

I have two machines, and on one the provided arguments won't work. I can't tell where this originates from. I use it like: 

`npm start -- -s "A-001"`

On my second machine, which has the exact same operating system, the code works.
Using cmd, it's perfectly fine. 

Update:

this has become strange: It seems that it works only if I'm not using npm scripts

```
PS C:\Users\_\Desktop\test> node index -- -s "AHSD"
{ separator: 'AHSD' }
PS C:\Users\_\Desktop\test> npm start -- -s "AHSD"
{}
```

Anyone knows what the reason is?

**Comment by shadowspawn** [comment]
One tip is that calling through npm affects the options that reach node, separate from possible PowerShell issues: https://github.com/tj/commander.js/issues/1761

**Comment by shadowspawn** [comment]
I'm not sure if you answered your own question, but no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
