### ISSUE TITLE
The parseAsync method doest not trigger the catch method if an error occurs.

### ISSUE THREAD

**Issue by yankos** [tj/commander.js#1777]
I am trying to log an error into a file with winstone module. Winston writes logs asynchronously, so the program must wait a while before exiting. I want to do this in the catch method - catch returns a promise that will be resolved when winstone completes. But the catch method, from the chain after the parseAsync method, is not executed. [Live example](https://replit.com/@yan_kos/Commander-Async-Issue#catch_issue.js)

```
...
program.parseAsync(process.argv)
    .then(
        () => {
            console.log("Done.");
        },
        errorHandler, // <-- here.
    )
    .catch(errorHandler) // <-- or here.
    .finally(() => {
        console.log("Exit.");
    });
...
```

I have:
```
~/Commander-Async-Issue$ node ./catch_issue.js test_as_var
error: unknown command 'test_as_var'
~/Commander-Async-Issue$ node ./catch_issue.js test
error: required option '--arg <arg[,...]>' not specified
~/Commander-Async-Issue$ 
```
Expecting:
```
~/Commander-Async-Issue$ node ./catch_issue.js test_as_var
error: unknown command 'test_as_var'
Error error: unknown command 'test_as_var'
errorHandler finished.
Exit.
~/Commander-Async-Issue$ node ./catch_issue.js test
error: required option '--arg <arg[,...]>' not specified
Error error: required option '--arg <arg[,...]>' not specified
errorHandler finished.
Exit.
```

Is this a bug or am I misunderstanding the documentation and i can't implement my idea?

**Comment by shadowspawn** [comment]
(Thanks for the detail and the full example in the link. Including full examples in the issue itself is fine too, and the example code is very useful for reproducing and getting to the bottom of the problem.)

The default behaviour when Commander finds a parsing error is to display a message and call `process.exit()`, which happens before the `catch`.

To modify the exit behaviour and instead throw, use `.exitOverride()`.

https://github.com/tj/commander.js#override-exit-and-output-handling

(Note also, you are using `.addCommand()` in the linked example code and the exit behaviour is an inherited setting. Either copy the inherited settings like in #1778, or call `.exitOverride()` on the subcommand too.)

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
