### ISSUE TITLE
requiredOption with choices

### ISSUE THREAD

**Issue by firmart** [tj/commander.js#1779]
I already had 
```js
.addOption(new Option("-s, --service <service>", "Service provider to use.")
        .choices(["a", "b"])
        .default("a", "A"))
```
I want to make this option required. There is `.requiredOption` but not as powerful as `.addOption` (i.e. cannot specify `choices`). AFAIK there is no way to specify an option `choices` and make it required at the same time.
An `.addRequiredOption` would seem redundant. Would it be possible to add a `.required()` method to `Option` ?

**Comment by shadowspawn** [comment]
Use `.makeOptionMandatory()`.

Background: the reason for the name change is that "required" inside the Option class has always meant the option has a required option-argument, as opposed to an optional option-argument, or no option-argument for a boolean option. When we added `.requiredOption()` the naming made sense at the Command level, but I felt it was too confusing to use "required" in two different ways in the Option class and used "mandatory" for the new functionality.

**Comment by shadowspawn** [comment]
Note: the runtime test for a required option is that it has a value after parsing. When you make your option required (mandatory) you probably want to drop the default value to make the user specify a value.

**Comment by shadowspawn** [comment]
Related issues: #1495 #1564

**Comment by firmart** [comment]
@shadowspawn Thanks for the quick reply and the remarks. I have checked the code source, but completely missed that method as I kept searching for the word "required" and only found, as you said, required argument. Will keep this issue opened as it is needed to be documented.

**Comment by shadowspawn** [comment]
Added to README in #1797

**Comment by shadowspawn** [comment]
Added mention to README in Commander v9.4.1
