### ISSUE TITLE
There is can not get option value with jsfile?

### ISSUE THREAD

**Issue by lkzwc** [tj/commander.js#1780]
![image](https://user-images.githubusercontent.com/84896877/187036142-849e3707-1a75-4337-8c51-dee9587aaa29.png)
is something wrong?

**Comment by lkzwc** [comment]
![image](https://user-images.githubusercontent.com/84896877/187037930-61cb6dc4-f337-4a27-b103-d265289147d7.png)
program.option has value,but program.opts() not value

**Comment by shadowspawn** [comment]
`.option('--name')` is a boolean option that does not take an option-argument. Used like:
```
node index.js --name
```

You want `.option('--name <component-name>')`, which can be used like:
```
node index.js --name=ppp
node index.js --name ppp
```
