### ISSUE TITLE
choices select

### ISSUE THREAD

**Issue by JoeABCDEF** [tj/commander.js#1782]
`addOption(new Option('-d, --drink <size>', 'drink size').choices(['small', 'medium', 'large']))`

May I ask whether choices support interaction, and select several values that have been determined, this may be more convenient, I did not find it in the document.

as shown below
![image](https://user-images.githubusercontent.com/39638510/187068936-bf718b9f-97e3-43c2-afe0-44f4ef17d8b5.png)

**Comment by shadowspawn** [comment]
No, Commander does not prompt for values or support interaction.

**Comment by JoeABCDEF** [comment]
> No, Commander does not prompt for values or support interaction.

OK, thanks
