### ISSUE TITLE
[Question]How to pass commands？

### ISSUE THREAD

**Issue by childrentime** [tj/commander.js#1783]
I want to ```bash -c 'echo "$PATH"'```  passed as an option, how can I parse it correctly？
 
tried

```ts
.option("--command <command...>")
```

command ```bash -c 'echo "$PATH"'```  will throw ```     error: unknown option '-c'```

**Comment by shadowspawn** [comment]
You need to tell Commander the short option too:

```
.option("-c, --command <command...>")
```

**Comment by childrentime** [comment]
but it will parse options to ``` command: [ '--bash', 'echo "$BASIC"' ]```

I don't want to parse the `-c` after bash as a flag,

expect [ '--bash', '-c', 'echo "$BASIC"' ]

**Comment by shadowspawn** [comment]
Commander does not break up a single string into arguments.  Is that what you are trying to do?

Commander works with an array of arguments, usually passed by the shell which launched node. (i.e. `process.argv`)

**Comment by childrentime** [comment]
my code
```ts
program..command("exec").option("-c --command <command...>")
```

exec
```ts
node index.js exec bash -c 'echo "$BASIC"'
```

expect `bash -c 'echo "$BASIC"'`

My point is, can we not parse flags like -c at some point?

**Comment by shadowspawn** [comment]
Have a look at `.passThroughOptions()` which is intended for this sort of situation. 

https://github.com/tj/commander.js#parsing-configuration

```js
program.command("exec").passThroughOptions()
```

Everything that comes after the first command-argument, like the `-c` after `bash`, is just treated as an original argument and not processed as an option. 

```
node index.js exec bash -c 'echo "$BASIC"'
              ^ find exec command, look for first command-argument
                   ^ find bash, stop looking for options
                        ^ -c is passed through as a plain command-argument, and not processed as an option
```

**Comment by childrentime** [comment]
thx!!! I'm sorry I missed this.
