### ISSUE TITLE
Add addOption method with customization.

### ISSUE THREAD

**Issue by mshima** [tj/commander.js#1786]
Command implements `createOption()` for convenience when extending options.
```js
class CustomCommand extends Command {
  createOption(...) {
    return new CustomOption(...);
  }
}
```

Works great for `option()`:
```js
new CustomCommand().option('foo');
```

Not so much for `addOption()`:
```javascript
const command = new CustomCommand();
command.addOption(command.createOption('foo').env('FOO'));
```

Would be nice an method like:
```js
new CustomCommand().addOption('foo', opt => opt.env('foo'));
```

**Comment by shadowspawn** [comment]
That is an interesting pattern. Thanks for sharing. 

My first thought is not compelling enough to add another way of adding options.

(In the context of the example, could be added to CustomCommand. I would suggest calling it something different to `.addOption` rather than overloading though.)

**Comment by shadowspawn** [comment]
This issue has not had any activity in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
