### ISSUE TITLE
Handling of remaining arguments that start with a hypthen "-"

### ISSUE THREAD

**Issue by tomtom** [tj/commander.js#179]
Let's consider the following example:

```
var clargs = require('commander').parse(process.argv);
console.log(clargs.args);
```

When I run this from the command line as:

```
example ls -h .
```

the program prints

```
[ 'ls' ]
```

The expected output would have been the same as with `example -- ls -h` since the `-h` argument clearly isn't meant as an argument for the script and since it gets ignored anyway (no help is printed).

Suggested change: Once a unhandled argument is encountered, the remaining arguments should be added to `args`.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
