### ISSUE TITLE
Better approach to follow dokku cli schema

### ISSUE THREAD

**Issue by 50l3r** [tj/commander.js#1793]
Hi guys,

I have read the documentation and tested but I can't get closer to the Dokku cli scheme:

![example](https://files.calltek.dev/2022/09/WindowsTerminal_OBppHdlKfb.gif)
https://files.calltek.dev/2022/09/WindowsTerminal_OBppHdlKfb.gif

I want to follow this schema:

- mycli
  - version
  - help
  - model
    - model:list
    - model:add
    - model:create
    - model:delete

  - workspace
    - workspace:list
    - workspace:add
    - workspace:create
    - workspace:delete

If you type the root command ```mycli``` it serves the 1st level help buyt if you type ```mycli model``` you recieve the model help.

Somebody have an idea how can i do this with commander? I am quite meticulous and the use of the ":" I like it a lot 😁

**Comment by shadowspawn** [comment]
From watching the gif, I was focused on just the help, and hence the suggested code. I realised later this is probably the same style as Heroku uses and you type the `foo:bar` commands too? 

This came up once before, see also #1260

**Comment by 50l3r** [comment]
> From the question and watching the gif, I was focused on just the help, and hence the suggested code. I realised later this is probably the same style as Heroku uses and you type the `foo:bar` commands too?
> 
> This came up once before, see also #1260

Indeed, that's the idea
