### ISSUE TITLE
Cannot write `.conflicts("option-name")`; we should write like `.conflicts("optionName")` ?

### ISSUE THREAD

**Issue by wataash** [tj/commander.js#1796]
```js
// this is INVALID
program
  .addOption(new Option('--option-a').conflicts('option-b'))
  .addOption(new Option('--option-b'))

// this works
program
  .addOption(new Option('--option-a').conflicts('optionB'))
  .addOption(new Option('--option-b'))
```

Is it intended design? I think `.conflicts('option-b'))` is natural.

**Comment by wataash** [comment]
And I think specifying the leading hyphens (`.conflicts("--option-b"))`) is also natural, should be accepted.

**Comment by shadowspawn** [comment]
Reasonable question. This is intended design, the conflicting option is identified by the camelCase option name. This is the same pattern used with the other routines passed an option identifier, like `.getOptionValue()`.

This is not mentioned in the README but is included in the example file: https://github.com/tj/commander.js/blob/master/examples/options-conflicts.js

( Supporting the option flags would lead to some additional questions. If you were allowed to use the long flag, would you also be allowed to use the short flag? Would you need to list both to cover both flags?)

**Comment by shadowspawn** [comment]
I was actually thinking we might use raw option originally, but when I saw camelCase used in the development of the feature I liked it much better.

https://github.com/tj/commander.js/pull/1678#issuecomment-1013762273

**Comment by wataash** [comment]
Thanks for the explanation!
Sorry, I didn't see the example file.
It's OK if it's the intended -- I just wondered this specification was just out of consideration.
I understood using camelCase is the consistent way in the commander API/implementation.

**Comment by wataash** [comment]
> If you were allowed to use the long flag, would you also be allowed to use the short flag? Would you need to list both to cover both flags?

At least `Option('-v')` should be identified as `-v`.

But, as you said, there's room for debate how to identify `Option('   -v,   --verbose   ')`...
Personally I prefer accepting all of these:

- `-v`
- `--verbose`
- `(SPACE)-v(SPACE)`
- `(SPACE)-v  ,   --verbose(SPACE)`

because it's obvious that the user is trying to select the `-v` option. There's no other way to interpret.
