### ISSUE TITLE
Using a short option name with no space before the value still works

### ISSUE THREAD

**Issue by omerschapiro** [tj/commander.js#1799]
Steps to reproduce:
1. Have command with a required option argument with a short name (e.g -a).
2. Run the command with the option argument but with no space after the argument name (e.g commandname -asdf).

Expected result:
An error about optional argument "asdf" is invalid.

Actual result:
Command runs and option argument -a has value "sdf".

From what I could debug, the issue seems to be [here](https://github.com/tj/commander.js/blob/master/lib/command.js#L1454) and [here](https://github.com/tj/commander.js/blob/master/lib/command.js#L1456).

**Comment by shadowspawn** [comment]
This is a feature, and a standard POSIX behaviour. Have a look at the README description of the supported option forms.

https://github.com/tj/commander.js#options

There is also a some background discussion of this in https://github.com/tj/commander.js/blob/master/docs/options-taking-varying-arguments.md#combining-short-options-and-options-taking-arguments

**Comment by shadowspawn** [comment]
No further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
