### ISSUE TITLE
Capitalization inconsistency in description

### ISSUE THREAD

**Issue by luzianscherrer** [tj/commander.js#1800]
I think there is an inconsistency regarding the capitalization of the description. 

- When writing the first character of the description of a command in upper case, it is not in line with the description of the built in option and command for help but it is looking good on the detail page (ie. `mycli help mycommand`).
- When writing the first character of the description of a command in lower case, it is in line with the description of the built in option and command for help but it is not looking good on the detail page (ie. `mycli help mycommand`).

The inconsistency is also visible in the given example in the README:

```
$ node ./examples/pizza --help
Usage: pizza [options]

An application for pizza ordering

Options:
  -p, --peppers        Add peppers
  -c, --cheese <type>  Add the specified type of cheese (default: "marble")
  -C, --no-cheese      You do not want any cheese
  -h, --help           display help for command
```

**Comment by shadowspawn** [comment]
Yes, that particular example uses inconsistent case. For interest, it dates back to 2011!  https://github.com/tj/commander.js/commit/c34851dc275ab53cbeb4a49388501a1f3a4c8aa2

Both the help and version options allow customising their descriptions, so you can use sentence caps in your own descriptions and have the built-in ones match.
