### ISSUE TITLE
Q: Output in VSCode's debug console

### ISSUE THREAD

**Issue by jpilgrim** [tj/commander.js#1809]
I have a question related to VSCode and commander.js. When I run a `program` (as in `program=new Command()`) in a terminal, everything works fine. However, when running or debugging in VSCode (via F5), I do not see any output emitted by `program` on the debug console (nor anywhere else). I see console.log and console.error messages though.

Do I need to configure anything special in the launch configuration?

Example to reproduce:

```
import { Command } from 'commander';

const program = new Command();
program.name('Minimal')
program.command('cmd')
    .description('does something')
    .action(()=>{
        console.log("Console log message");
        console.error("Console error message");
        program.error("Program error message")
    });

program.parse();
```

Launch configuration:
```
{
    "version": "0.2.0",
    "configurations": [ {
            "type": "node", 
            "request":  "launch",
            "name": "Min",
            "program": "${workspaceFolder}/src/cliMin.ts",
            "args": ["cmd"],
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": ["${workspaceFolder}/dist/*.js"]
        }
    ]
}
```

Output in debug console:
```
/usr/local/bin/node ./dist/cliMin.js cmd
Console log message                                                 src/cliMin.ts:9
Console error message                                                 src/cliMin.ts:10
Process exited with code 1
```

Output in terminal:
```
~/myproject$ /usr/local/bin/node ./dist/cliMin.js cmd
Console log message
Console error message
Program error message
~/myproject$
```

As you can see, the last line "Program err message" is not visible in VSCode's debug console.

In the example, I use `program.error`. However nothing emitted from `program` is visible in the debug console, e.g. help output.

**Comment by shadowspawn** [comment]
I found a difference, but I don't know yet what a solution is.

Commander uses `process.stdout.write()` and `process.stderr.write()` to output messages, and these are normally much the same as `console.log()` and `console.error()`. But apparently not when launched in VSCode.

**Comment by shadowspawn** [comment]
And having worked that out, easy to find other people having the same problem. 😄 

Try adding this to your launch configuration (and relaunch VSCode if it doesn't have an immediate affect):

```
"outputCapture": "std"
```

**Comment by jpilgrim** [comment]
Great, thank you very much! Wow! Fast response time, on weekend and for free -- kudos to you!
