### ISSUE TITLE
Path arguments are not as expected above on Git Bash

### ISSUE THREAD

**Issue by filway** [tj/commander.js#1810]
windows system

commander version:  6.2.1
  
index.js:
```
const commander = require('commander')

const program = new commander.Command()

program.name('test-cli').usage('<command> [options]').version('1.0.0')

program
  .command('publish')
  .option('--uploadPath <uploadPath>', 'upload path')
  .action(async (options) => {
    console.log(options.uploadPath)
  })
```

Output:
```
$ node index.js publish --uploadPath '/home/work'
D:/Program Files/Git/home/work
```

**Comment by shadowspawn** [comment]
This is a somewhat surprising "feature" of the Git Bash shell trying to do some clever path conversions between posix and Windows:

- https://github.com/moby/moby/issues/24029
- https://stackoverflow.com/questions/54258996/git-bash-string-parameter-with-at-start-is-being-expanded-to-a-file-path
- https://docs.cloudbees.com/docs/cloudbees-cd-kb/latest/cloudbees-cd-kb/kbec-00420-stopping-path-conversion-for-git-bash

(I personally have switched from Git Bash to using a real Linux shell on Windows using WSL2.)

**Comment by shadowspawn** [comment]
To confirm it is the shelll, try logging `process.argv` to see what is getting passed into the program.

**Comment by filway** [comment]
> To confirm it is the shelll, try logging `process.argv` to see what is getting passed into the program.

Thanks, I replaced '/' with '//' and that solved the problem

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
