### ISSUE TITLE
Command context

### ISSUE THREAD

**Issue by sgb-io** [tj/commander.js#1812]
As far as I can tell, there is currently no way to understand the context of a command before going ahead and parsing the input (and triggering the relevant actions).

I noticed that as part of custom help, a `context` object is made available, containing `error` and `command`.

It would be useful to have access to a similar context when defining my program: in particular, the `command` being executed.

Example: I have a program like so:

```
my-cli foo red // Runs anywhere
my-cli foo blue // Runs anywhere
my-cli bar yellow // Designed to run in a git project
my-cli bar green // Designed to run in a git project
```

Let's say that commands under `foo` can be called from anywhere, but commands under `bar` are supposed to be called from a git project directory. If the user attempts to use `bar` commands from elsewhere, I want to throw, _except_ if the user is calling `--help` / `-h`.

Maybe I'm missing something that commander provides but this gives me 2 problems:

1. I can't catch if help commands are being run. My action handlers don't get activated, because help options seem to cause commander to handle the action, rather than my user-land action handler (which makes sense).
2. I can catch this bad-directory scenario in my individual command action handlers, but it requires me to repeat that for every subcommand (i.e. for both `yellow` and `green`).

If I had access to a `context` at the top (`my-cli`) level, which contained the command but also a flag to say if the input results in a help handler, it solves both problems:

1. I would know if it's a help command, and let the user continue from any directory, since no action will actually be taken
2. I could catch this bad-directory scenario once, and shield entire subcommands against it

FWIW, I am currently working around this by manually parsing `process.argv` before `program.parseAsync`.

**Comment by sgb-io** [comment]
After further digging, I see that I can access the command name by using `program.hook` and attaching to the `preSubcommand` lifecycle hook. However, there is still no commander way to tell if a command was a help one (I can manually parse the `args` as a workaround). It would be useful to have something like `isHelpCommand` exposed.

**Comment by shadowspawn** [comment]
Thanks for the detailed description.

I suggest adding a hook to the `bar` command for `preAction` which checks for the bad-directory scenario and handles the error, say by throwing or calling `.error()`. The help won't be affected as the `preAction` hook is only called when an action handler is about to be called. I think this may be a good match for your scenario.

The command structure is hierarchical, so if you want some custom behaviour just for `bar` and its subcommands you can modify the `bar` command. I can write an example if you would like one.

**Comment by shadowspawn** [comment]
Just a skeleton.

```js
const { Command } = require('commander'); 

const program = new Command();
const foo = program.command('foo');

foo.command('red')
  .action(() => console.log('called red'));
foo.command('blue')
  .action(() => console.log('called blue'));

const bar = program.command('bar');
bar.hook('preAction', () => console.log('check for git context'))

bar.command('yellow')
  .action(() => console.log('called yellow'));
bar.command('green')
  .action(() => console.log('called green'));

program.parse();
```

```console
% node index.js foo red
called red

% node index.js bar yellow
check for git context
called yellow

% node index.js bar yellow -h
Usage: index bar yellow [options]

Options:
  -h, --help  display help for command
```

**Comment by sgb-io** [comment]
Thanks for the example! This will work for me.
