### ISSUE TITLE
Dot-nested commands

### ISSUE THREAD

**Issue by Coachonko** [tj/commander.js#1816]
I would love to have commands like these:
```
cli command.nested option
```

Is it possible, would it be difficult to add this functionality to commander?

**Comment by shadowspawn** [comment]
You can get parts of this working, but there are likely to be some short-comings. 

To get the command recognised, you could pre-process the arguments and replace a dot with a space before passing the arguments to Commander, or you could define flat commands and fake the nesting (so `main.sub` is just one command and not really nested).

There have been a couple of questions about colon-separated commands, with replies which include modifying the help: #1260 and #1793 

Is there a particular reason you want to use this syntax?

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
