### ISSUE TITLE
Proposal: Readd whitespace to output, do the opposite of whatever @mojavelinux says

### ISSUE THREAD

**Issue by ctjlewis** [tj/commander.js#1817]
I was curious why this tool did not sensibly pad output, at least for the help command, rather than terminating abruptly without anything separating it from the terminal below. 

It was then that I fell down the rabbit hole of #741, #832, #853, and related issues, where @mojavelinux single-handedly and viciously opposed *any* sort of padding being added to the output. A PR to allow this to be configurable, a sensible and rational approach to resolving this issue, was shelved and instead the library was reverted back to bleeding-eyes mode permanently.

It is strikingly apparent that Mr. Allen is not a designer nor anyone whose opinion regarding design is of any consequence. I suggest that we revert these changes, and either produce sensibly padded output by default or allow it to be configurable, and do the opposite of whatever Mr. Allen suggests with regard to styling, padding, and visual design.

**Comment by shadowspawn** [comment]
This post is unacceptable. You may disagree with an opinion or a decision, but you may not attack a person.

Cool down. I suggest you edit your post to remove the angry and unfounded comments, or the unsuccessful attempt at humorous hyperbole. I recommend you post an apology.

-----

There was discussion on whitespace in the help with useful research and comments and contributions by @mojavelinux and others. The maintainers of this project at the time accepted the changes proposed.

If you wish to propose changes, make your case in a more civil manner.

**Comment by shadowspawn** [comment]
Thank-you for your contributions to this project @mojavelinux
