### ISSUE TITLE
Sub Commands with the same option as the parent comand do not receive the options

### ISSUE THREAD

**Issue by jmcdo29** [tj/commander.js#1824]
# Command and Sub Command with Same Option

## Current Behavior

If you have a command and a sub command with the same option, then when you
invoke `program command subcommand -o option` the subcommand will not receive
the option.

## Expected Behavior

When you invoke `program command subcommand -o option` the subcommand recieves
the options passed, just like the command does.

## Reproduction Repository

https://github.com/jmcdo29/commander-sub-command-same-option-name

## Reproduction Steps

1. Clone https://github.com/jmcdo29/commander-sub-command-same-option-name
2. Run your package manager install of choice e.g. `pnpm i`
3. Run `node index.js say -m hello` to see the main command output
4. Run  `node index.js say yellow -m hello` to see the sub command output
5. Observe that the sub command does not have any options passed to it

To see that the sub command does work, you can run the command
`node main.js say yellow -y hello`. 

## Commander Info

version: 9.4.1

[Related Issue](https://github.com/jmcdo29/nest-commander/issues/663)

**Comment by shadowspawn** [comment]
Thanks for the detailed description and reproduction.

The default behaviour is that options can come before or after command-arguments, and before or after subcommands. So the first command is eating the  option before the subcommand parsing starts.

You can change this behaviour with `.enablePositionalOptions()`. See the README for some additional description and link to an example file.

(Sometimes this comes up when the top-level command and options are not really hierarchical but a shortcut to the most common use. In this case the command can be made a default command, and the options no longer get used at two levels. See #1616. )

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
