### ISSUE TITLE
Subcommand Holds onto `_optionValues` Between Executions

### ISSUE THREAD

**Issue by manunamz** [tj/commander.js#1829]
I am setting up some unit tests around a commander.js cli tool. I verify that the args and opts the program is holding onto internally matches expectations for each test. It seems that subcommands, and possibly the `Command` object in general, is holding onto options between executions.

This means, if I test a command with options and then test the same command without any options, the second test will still have the options from the first execution.

```js
// test with options pass
program.parse(['program', 'command', '-o', 'stuff']);
// test without options still have previous options
program.parse(['program', 'command']); // '-o' and 'stuff' will still be parsed
```

I am currently working around this issue by manually clearing options between each test -- see the following:

```js
  afterEach(() => {
    const cmd: any = program.commands.find((cmd) => cmd.name() === 'command');
    cmd._optionValues = {};
  });
```

This is just a short description to notify the commander.js maintainer. I think the issue is probably a simple reset of `_optionValues` or class properties more generally...If more detail is required, I can fill out a more detailed ticket upon request.

**Comment by shadowspawn** [comment]
Thanks for the clear description.

Yes, there isn't any code to reset state after calling `.parse()`. The intended pattern is make a new command for each test. 

Related: #438 #1565 #1819

**Comment by manunamz** [comment]
Thanks for the issue numbers! The relevant conversation is useful, particularly your other comment [here](https://github.com/tj/commander.js/issues/1819#issuecomment-1309276026).

This feels like a duplicate of https://github.com/tj/commander.js/issues/1819 , so I'll close this out. Thank you again!

**Comment by shadowspawn** [comment]
Support was added in Commander v13 for calling parse more than once: https://github.com/tj/commander.js/pull/2299
