### ISSUE TITLE
Option values should not be added to the command instance.

### ISSUE THREAD

**Issue by badsyntax** [tj/commander.js#183]
Adding the option values to the command object will only cause conflicts between the properties of the command object and of the command options. 

Let's take this example:

``` javascript
program.option('--parse', 'parse');
program.option('--parse2', 'parse');

program.parse(['node', 'test', '--parse', '--parse2']);
console.log(program.parse); // undefined
console.log(program.parse2); // true
```

**This seems like a pretty serious bug to me**, certainly it's prevented me from naming my option 'parent' because of conflicts with this particular line: https://github.com/visionmedia/commander.js/blob/master/index.js#L155

Why can't the option values just be added to a new empty object?? Something like this;

``` javascript
program.option('--parse', 'parse');
program.option('--parse2', 'parse');

program.parse(['node', 'test', '--parse', '--parse2']);
console.log(program.input.parse); // true
console.log(program.input.parse2); // true
```

**Comment by shadowspawn** [comment]
There is some good discussion in #404

**Comment by shadowspawn** [comment]
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102

**Comment by shadowspawn** [comment]
Added `. storeOptionsAsProperties()` and `. passCommandToAction()` in Commander 4.1. 

See: https://github.com/tj/commander.js#avoiding-option-name-clashes
