### ISSUE TITLE
[Question] How to create a command and subcommands

### ISSUE THREAD

**Issue by ramsesgarate** [tj/commander.js#1830]
Hello, I would like to know if with commander it is possible to create a command that is executed with a main command that does not show the help and at the same time can have subcommands, I mean something like this:

```bash
$ my-cli
> hello world

$ my-cli -s
> hello world with option s

$ my-cli addition 2 2
> Result is 4

$ my-cli subtraction 8 2
> Result is 6
```

**Comment by shadowspawn** [comment]
Yes. that is a supported setup. The main command can have an action handler, and that will get called instead of showing the help when a subcommand is not specified.

**Comment by shadowspawn** [comment]
Also, another approach is to specify a default command. A reason for doing it with a default command is to avoid having the top-level options as global options, like the `-s` in your example.

Does it make sense to do: `my-cli -s addition 2 2` ?

See for example: #1616 #1750

**Comment by ramsesgarate** [comment]
Thank you very much, leaving a default command worked for me!

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
