### ISSUE TITLE
[docs] `.alias()` support is not documented in the Readme

### ISSUE THREAD

**Issue by viglucci** [tj/commander.js#1831]
I only found that commander support aliasing via searching and finding the below issues/PRs:

- https://github.com/tj/commander.js/pull/1236
- https://github.com/tj/commander.js/issues/531

Is it correct that this is not documented, or did I miss it somewhere?

**Comment by shadowspawn** [comment]
You are right, it is not mentioned in the README and should be.

It was used in one example in the README until v9. It got lost when the examples got reworked in #1665. (I didn't want it in the starting example, but didn't add it elsewhere.)

**Comment by shadowspawn** [comment]
Added mention in Commander v9.5.0

**Comment by viglucci** [comment]
@shadowspawn excellent, thanks!
