### ISSUE TITLE
Variadic of numbers

### ISSUE THREAD

**Issue by ThalusA** [tj/commander.js#1839]
Hi, I'm actually looking for a way to use commander to parse a variadic option as a list of numbers however I get TypeScript error using : `.option('-e, --example <numbers...>', 'List of numbers', parseInt, [])`

![image](https://user-images.githubusercontent.com/15985204/210425326-c4208664-79a2-4bc5-8293-5063027d512d.png)

Based on this error I don't know if by using it like that (using ts-ignore) I will get an array of numbers or not.

PS: Making a function parseIntArray doesn't help me because the provided value is forced to string type and not string[] type. Maybe I can do :
```ts
program
	.option('-e, --example <numbers...>',
				  'List of numbers',
				  (value, previous: number[]) => previous.concat(parseInt(value)),
                  [])
```
But I'm not sure

**Comment by shadowspawn** [comment]
Short version: yes!

Long version:

Commander will call your custom option parsing function multiple times, but it is up to your routine to put the values into an array. With your first try, in JavaScript you would get just one number (from calling `parseInt`). TypeScript can tell you that the signature does not make sense as the return type of `parseInt` does not matching the starting value of `[]`.

Your second example is as intended. The parsing routine gets passed a string value, you parse it and add it to the array, and return the result. Pulling it out into a routine and making the types explicit for clarity:

```
function myParseInts(value: string, previous: number[]): number[] {
  const parsedValue = parseInt(value, 10);
  return previous.concat(parsedValue);
}
```
