### ISSUE TITLE
[Question] How to prevent commander from exiting on 'help' or invalid user input in REPL mode ?

### ISSUE THREAD

**Issue by KaKi87** [tj/commander.js#1841]
Hello,

When using `commander` with `node:repl`, the script exits when the user types `help` or any incorrect input.

Instead, I would like to still display the error but also keep the REPL active, thus displaying another prompt and let the user type another command.

Here's my minimal reproducible example :

```js
import repl from 'node:repl';

import { Command } from 'commander';
import { createEmitter } from 'simpler-emitter';
import { parse } from 'shell-quote';

const
    program = new Command(),
    emitter = createEmitter();

program.hook('postAction', () => emitter.emit('idle'));

program.command('split')
    .description('Split a string into substrings and display as an array.')
    .argument('<string>', 'string to split')
    .option('--first', 'display just the first substring')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((str, options) => {
        const limit = options.first ? 1 : undefined;
        console.log(str.split(options.separator, limit));
    });
program.command('join')
    .description('Join the command-arguments into a single string')
    .argument('<strings...>', 'one or more strings')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((strings, options) => {
        console.log(strings.join(options.separator));
    });

repl.start({
    eval: (
        line,
        _,
        __,
        callback
    ) => {
        emitter.once('idle', callback);
        program.parse([undefined, undefined, ...parse(line)]);
    }
});
```

Thanks

**Comment by shadowspawn** [comment]
Short version: see `.exitOverride()`
https://github.com/tj/commander.js#override-exit-and-output-handling

Long Version

More details and tips

1) `program.parse([undefined, undefined, ...parse(line)]);`

For interest, there is an optional second parameter to `.parse()`. See https://github.com/tj/commander.js#parse-and-parseasync

So you could specify: `program.parse(parse(line), { from: 'user' });`

2) Commander only supports calling `.parse()` once. You should construct a new Command for each call to eval.

3) The default behaviour after an error, including displaying help for missing arguments, is to call `.exit()`. Use `.exitOverride()` to change this.

(Disclaimer: Thanks for the example code. I have not tried running your code yet! I'll try that later and post again if I find anything else.)

**Comment by KaKi87** [comment]
Nice, this is much cleaner already.

However, the prompt still can't reappear when help or an error is outputted.

Here's the updated code :

```js
import repl from 'node:repl';

import { Command } from 'commander';
import { parse } from 'shell-quote';

const program = new Command();

program.exitOverride();

program.command('split')
    .description('Split a string into substrings and display as an array.')
    .argument('<string>', 'string to split')
    .option('--first', 'display just the first substring')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((str, options) => {
        const limit = options.first ? 1 : undefined;
        console.log(str.split(options.separator, limit));
    });
program.command('join')
    .description('Join the command-arguments into a single string')
    .argument('<strings...>', 'one or more strings')
    .option('-s, --separator <char>', 'separator character', ',')
    .action((strings, options) => {
        console.log(strings.join(options.separator));
    });

repl.start({
    eval: async (
        line,
        _,
        __,
        callback
    ) => {
        try {
            await program.parseAsync(
                parse(line),
                {
                    from: 'user'
                }
            );
            callback();
        }
        catch {}
    }
});
```

Thanks

**Comment by KaKi87** [comment]
Ideally, `commander` wouldn't output help or an error message by itself, but return it to `parseAsync` so that I could do it myself using the `callback` function provided by `node:repl` for that purpose.

**Comment by shadowspawn** [comment]
I suspect there should be a call to `callback()` in the catch too?

**Comment by KaKi87** [comment]
Well you're right, more precisely, I could move the existing one below the `catch` so that it's executed in both cases of success and failure, solving the problem in this scope.

However, I failed to mention that my scope is actually larger, so I had to create a [new issue](https://github.com/tj/commander.js/issues/1842) to take that into consideration. :sweat_smile: 

Sorry, and thank you for being so responsive.

**Comment by KaKi87** [comment]
Turns out I got a big problem with this : option values are preserved through prompts.

The following example :

```js
import repl from 'node:repl';

import { Command } from 'commander';
import { parse } from 'shell-quote';

const program = new Command();

program.exitOverride();

program
    .command('foo')
    .option('-b, --bar')
    .option('-B, --baz')
    .option('-f, --fum')
    .action(options => console.log(options));

repl.start({
    eval: async (
        line,
        _,
        __,
        callback
    ) => {
        try {
            await program.parseAsync(
                parse(line),
                {
                    from: 'user'
                }
            );
        }
        catch {}
        callback();
    }
});
```

Outputs the following :

```
> foo
{}
> foo -b
{ bar: true }
> foo
{ bar: true }
> foo -B
{ bar: true, baz: true }
> foo
{ bar: true, baz: true }
```

Thanks

**Comment by shadowspawn** [comment]
Yes, the state does not get reset when you call `parse()`. Make a new Command each time.

This earlier [tip](https://github.com/tj/commander.js/issues/1841#issuecomment-1381190869) might make more sense now.:

> 2. Commands only supports calling .parse() once. You should construct a new Command for each call to eval.

**Comment by KaKi87** [comment]
Actually I found a workaround :

```js
program.hook(
    'postAction',
    (
        thisCommand,
        actionCommand
    ) => {
        for(const option in actionCommand._optionValues)
            delete actionCommand._optionValues[option];
    }
);
```

Or are there other side effects that I overlooked ?

Because reinstantiating the whole thing for each prompt seem rather bad in terms of memory usage, isn't it ?

**Comment by shadowspawn** [comment]
> Or are there other side effects that I overlooked ?

Yes indeed, there are other side effects. For example deleting the option values deletes the option default values too.

> Because reinstantiating the whole thing for each prompt seem rather bad in terms of memory usage, isn't it ?

Well, there will be some minor churn but nothing taxing for the computer. The loop is running at the speed a person types (i.e. slow), and the garbage collector can free previous commands when (if) it runs.

**Comment by KaKi87** [comment]
Alright, thanks

```js
import repl from 'node:repl';

import { Command } from 'commander';
import { parse } from 'shell-quote';

const createProgram = () => {
    const program = new Command();
    program.exitOverride();
    program
        .command('foo')
        .option('-b, --bar')
        .option('-B, --baz')
        .option('-f, --fum')
        .action(options => console.log(options));
    return program;
};

repl.start({
    eval: async (
        line,
        _,
        __,
        callback
    ) => {
        try {
            const program = createProgram();
            await program.parseAsync(
                parse(line),
                {
                    from: 'user'
                }
            );
        }
        catch {}
        callback();
    }
});
```

**Comment by shadowspawn** [comment]
(Thanks for the updated example code.)
