### ISSUE TITLE
[Question] Support `--flag true/false` options

### ISSUE THREAD

**Issue by dmaklygin** [tj/commander.js#1847]
I have a question, whether commandJS is able to support **boolean** options with values, namely:

```
--flag=true
--flag=false
--flag true
--flag false
```

I've checked the current functionality, and then I define option like that: `.option('--flag')`
CommanderJS does not recognize the `value` of that option, so the value `true or false` is moved to arguments.

If I define option like that: `.option('--flag [value]')` — the library handles it properly, however, the value is in string type, so I have to perform type casting.

**Comment by shadowspawn** [comment]
There is not built-in support for this. What Commander does have is support for negated options, so the supported pattern is (say) `--flag` and `--no-flag`.

> If I define option like that: .option('--flag [value]') — the library handles it properly, however, the value is in string type, so I have to perform type casting.

Yes, correct, you supply the custom option processing to turn the desired strings into a boolean.

**Comment by dmaklygin** [comment]
Got it! Thank you, @shadowspawn so much for your answer!
