### ISSUE TITLE
Version 10.0.0 has removed the advanced argument functions.

### ISSUE THREAD

**Issue by cjrutherford** [tj/commander.js#1850]
Previously, in 9.2.0, I was able to call `.argument()` or `.addArgument` on my `command()` chain but it appears only the `.arguments()` function remains. I personally am rolling back to 9.2.0, but I wanted to be sure this reversion in the feature set was noted.

**Comment by shadowspawn** [comment]
I don't know what went wrong for you, but `.argument()` and `.addArgument()` were not removed in Commander v10.0.0.

```js
const { program, Argument } = require('commander');

const extraArg = new Argument('<extra>', 'my extra argument');

program
  .argument('<example>', 'this is an example')
  .addArgument(extraArg);

program.parse();
```

```console
$ node index.js --help
Usage: index [options] <example> <extra>

Arguments:
  example     this is an example
  extra       my extra argument

Options:
  -h, --help  display help for command
```
