### ISSUE TITLE
Feature request: promtOption for arguments | user-input | stdin scenario

### ISSUE THREAD

**Issue by ThePlenkov** [tj/commander.js#1851]
**Use case**.
Sometimes I don't want my parameters to be sent as arguments, but they are required.

**The desired behavior**
I run commander-based command from the console. If argument is provided - we just use it as a normal option, if not - Instead of raising the immediate error the program suggests to input it from the prompt. 

The current workaround is to use option along with other modules such as [inquirer](https://www.npmjs.com/package/inquirer).
Meanwhile I'd suggest something like this:
```
program.
  promtpOption({

flags: ''-p,--password <password>", 
description: "User password", 
promptText: "Please provide password"
defultValue: process.stdin 
})
```

Thus I can be always sure that this parameter is provided by arguments or user ( or may be by stdin ). Of course syntax will be different but this is just to share an idea.

Thanks!

**Comment by shadowspawn** [comment]
My initial thought is we are likely to leave this to third-party libraries, but more comments and reactions welcome.

For historical interest, Commander did once have support for a variety of input methods which were removed in v2.0.0 back in 2013.

- https://github.com/tj/commander.js/commit/bf5e1f5ec9fb1af23dd873117558575cd01d7415

**Comment by anran758** [comment]
> My initial thought is we are likely to leave this to third-party libraries, but more comments and reactions welcome.
> 
> For historical interest, Commander did once have support for a variety of input methods which were removed in v2.0.0 back in 2013.
> 
> * [bf5e1f5](https://github.com/tj/commander.js/commit/bf5e1f5ec9fb1af23dd873117558575cd01d7415)

When I need to provide login feature for a user, I don't want the user's password to leave a trace.
In this scenario only introduce third party libraries, such as inquirer to achieve it?

**Comment by shadowspawn** [comment]
Yes, prompting for password is up to author and not offered by Commander.

**Comment by anran758** [comment]
> Yes, prompting for password is up to author and not offered by Commander..

Okay, thanks!

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
