### ISSUE TITLE
Help for option choices?

### ISSUE THREAD

**Issue by robross0606** [tj/commander.js#1856]
Is it possible to add help descriptions for option choices?  If not, this would be a nice feature.

**Comment by shadowspawn** [comment]
No, there is not specific support for help for choices.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a couple of months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.

**Comment by KaKi87** [comment]
Hello,
I would like to request this feature as well.
Thanks
