### ISSUE TITLE
`conflicts` and `implies` are not compatible

### ISSUE THREAD

**Issue by 3Gorec** [tj/commander.js#1857]
I am trying to use options like this:
```
        .addOption(
            new Option('--strict', 'Set strict behavior')
                .implies({ processingMode: "strict" })
        )
        .addOption(
            new Option('--processingMode <mode>', 'Processing mode')
                .choices(['strict','normal'])
                .conflicts(['strict'])
                .default('normal')
        )
```

Those options are not allowed together because they manage the same flag. 
When i pass `--strict` I get an error that `--processingMode` cannot be used with `--strict`, because of `implies`.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
