### ISSUE TITLE
helpOption does not support more than 2 flags

### ISSUE THREAD

**Issue by mitsukuri** [tj/commander.js#1862]
For example, using `.helpOption ('-h, --help, --something-else')` and running with `--something-else` results in

`error: unknown option '--something-else'`, while `-h` and `--help` still work.

Use case: not sure about others, but me personally, I'd also like to add `-?` as an extra help flag.

**Comment by shadowspawn** [comment]
Options support a short flag and a long flag, and this applies to the built-in version and help options too.

**Comment by mitsukuri** [comment]
I see, so I guess no luck adding a third option.
