### ISSUE TITLE
.helpOption(false) also disables subcommand help command

### ISSUE THREAD

**Issue by mitsukuri** [tj/commander.js#1863]
In this example, I'd like to disable impilcit help **option** and only leave impicit help **command**.
`test.mjs`:
```
#!/usr/bin/env node
import { Command } from 'commander';
const cmd = new Command ();
cmd
   .helpOption (false)
   .command ('meow')
   .option ('-l, [--loud]')

cmd.parse ();
```
If I run `test.mjs`, I get 
```
Usage: test [command]

Commands:
  meow [options]
  help [command]  display help for command
```
as expected, but if I run `test.mjs help meow`, I get an error:

`error: unknown option '--help' // what option, I thought I was calling help command?`,

while expected outcome would be
```
Usage: test meow [options]

Options:
  -l, [--loud]
```

**Comment by shadowspawn** [comment]
You have found a shortcoming in the help support! 

The `help` command is implemented by passing `--help` into the subcommand. It was done this way so it could also work with stand-alone external subcommands.
- https://github.com/tj/commander.js/blob/33195f189b1ffa568c232503fb6ac0cf5548eb74/lib/command.js#L1254

I think it would be reasonable to call directly into the help for a known (non-external) command. This would make the support more robust.

**Comment by shadowspawn** [comment]
This is fixed in v11

Thanks @mitsukuri
