### ISSUE TITLE
Feature Request: Allow -- to escape commands in argument parsing

### ISSUE THREAD

**Issue by snowfoxsh** [tj/commander.js#1865]
# 📖 Description
I propose adding a feature to allow using `--` to escape commands when parsing arguments in Commander. This would be particularly useful for programs that take in tokens, such as the Unix `echo` command. In cases where a user wants to add a sub-command with `.command()`, the parser currently cannot distinguish between tokens and commands.

# 🌟 Problem Example
Below is a simplified version of a program for illustration purposes:
```js
const {Command} = require("commander");
const program = new Command();

program.command("test").action(() => console.log("test command run"));
program.arguments("[tokens...]").action((tok) => console.log(tok));

program.parse();
```
Desired behavior:
`node ./index.js some tokens` | ['some', 'tokens']
`node ./index.js test the test cmd is run` | 'test command run'
`node ./index -- test the test cmd is not run` |  ['test', 'the', 'test', 'cmd', 'is', 'not', 'run'] | note: in this example the test command is not run because of the escape sequence `--`

# 💡 Proposed Solution
Introduce a method to toggle command escaping on and off. Here are a few options:
```js
// Option 1
program.allowCommandEscape();

// Option 2
program.addCommandEscape("--");

// Option 3: Escaping enabled by default
program.disableCommandEscape();
```
With the proposed solution in place, the parser would be able to properly handle tokens and commands when the escape sequence is present. I would be willing to attempt to add this change and submit a pull request.

**Comment by shadowspawn** [comment]
A couple of comments:

1) While it is possible to have an action handler at the top level in addition to subcommands, this does lead to the ambiguity you describe. I suggest one approach is don't do this! Just have action handlers at the leaf subcommands.

2) The `--` is used as an escape sequence already. However, what it does is disable the option recognition and processing. From the README:

> You can use `--` to indicate the end of the options, and any remaining arguments will be used without being interpreted.

**Comment by shadowspawn** [comment]
Can you expand on your description a little to explain why you are interested in an action handler both at the root and in a subcommand? i.e. what scenario is this an approach for? 

(I don't doubt you have an interesting scenario in mind, but I'm not understanding why `echo` would have a subcommand.)

**Comment by shadowspawn** [comment]
A good way of setting up a top level command in addition to subcommands is using the "default command" support. You declare a subcommand for the default processing, and make it the default command (instead of adding an action handler to the program). See `isDefault` in the README.

Say the new default subcommand was called top. In your examples:
```console
node ./index.js some tokens # handled by top
node ./index.js test foo # handled by test subcommand
node ./index.js test this-is-for-top # oops, handled by test
node ./index.js top test this-is-for-top # specify the subcommand explicitly, handled by top

Related: #1616

**Comment by snowfoxsh** [comment]
Thats a really good way of handling things. I will give it a shot. Thank you. 

To answer the original question. I'm currently building a tool to query gpt models. It has to accept tokens as well as containing sub commands for setup, and installing non OpenAI models like llama. My tool is qut (QUery Transformer). 

```
node ./qut.js what is the capitol of the united states # Washington DC
node ./qut.js -p temp=0.3 what is the capitol of the united states # Washington DC
node ./qut.js run-wizard # runs setup wizard
node ./qut.js -- run-wizard # does NOT run wizard instead would pass as a token
```

Hopefully this is a more clear example. The proposal is to add a method to allow `--` to escape commands to be treated as tokens.

**Comment by shadowspawn** [comment]
If this comes up again, I would be interested in examples in the wild of similar behaviour.

An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
