### ISSUE TITLE
is it possible to make an option required based on some other option value

### ISSUE THREAD

**Issue by shivimakwana** [tj/commander.js#1867]
Can we do something like this currently using commander ?

there is option x 
if x == "some value":
    program.requiredOption("-y, --y<>", "description");

**Comment by shadowspawn** [comment]
No, there is not built-in support for this. The available routines are `.requiredOption()` and `.conflicts()` and `.implies()`. 

Related: #1802

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
