### ISSUE TITLE
Nested sub-commands with options that overlap their parent do not work as expected

### ISSUE THREAD

**Issue by laureline-xborg** [tj/commander.js#1868]
When a sub-command has an option with the same name as one of its parent commands, the parent command "steals" the value and it is never passed down to the child.

Minimal Reproduction:
```javascript
const { program } = require('commander');

const _user =
  program
    .command('profile')
    .option('--handle <name>')
    .action((opts) => {
      console.log('profile', opts);
    });

_user
  .command('update')
  .option('--handle <name>')
  .action((opts, cmd) => {
    console.log('update', opts);
    console.log('parent', cmd.parent._optionValues);
  })

program.parse();
```

When executed the following happens:
```
$ node index.js profile --handle "Hello"
> profile { handle: 'Hello' }

$ node index.js profile update --handle "Hello"
> update {}
> parent { handle: 'Hello' }
```

Expected Behavior:  
The parser only parses the arguments and options of the currently executing (sub-)command.

```
$ node index.js profile --handle "Hello"
> profile { handle: 'Hello' }

$ node index.js profile update --handle "Hello"
> update { handle: 'Hello' }
> parent {}
```

**Comment by laureline-xborg** [comment]
This is solved by using `enablePositionalOptions` and `passThroughOptions`

**Comment by shadowspawn** [comment]
Yes, you already worked it out. To stop the higher level commands "stealing" the options from the subcommand you can use `.enablePositionalOptions()`. This allows same name option in a command and subcommand.
