### ISSUE TITLE
main command action handler options empty

### ISSUE THREAD

**Issue by machinshin** [tj/commander.js#1869]
Hey all, i'm trying to separate out the action handler for a top-level command with the code below. 

the options variable in my action handler is undefined, and it's unclear why.

```typescript 
  // src/ts/program.ts
import { Command } from 'commander';

const program = new Command('cmd-name');
program
  .version('0.0.1') // real code loads this from package.json
  .description("program description string")
  .argument('<input-file>', 'file for operations')
  .requiredOption('-c --customer-name <comp>', 'description');
  //add more .option()

export default program;
```
```typescript
//src/ts/cli.ts
import program from './program';
program.action((input_file: string, options: Object): Promise<any> => {
  console.log(`input_file: ${input_file}`);
  console.log(`options: ${JSON.stringify(options, null, 2)}`);
 /* more code here */
});
(async () => {
  return await program.parseAsync(process.argv);
})();
```
so per the documentation, options should be an Object, but running this code, i get
`$> node dist/cli-bundle.js -- -c upt ./foo-bar.txt`
which displays: 
```
input_file: ./foo-bar.txt
options: undefined
```

**Comment by shadowspawn** [comment]
I am unable to reproduce your problem using the sample code, and haven't worked out what might be wrong.

There is something odd in your steps, in this command:
```
$> node dist/cli-bundle.js -- -c upt ./foo-bar.txt
```
the `--` disables the option processing so `-c` is not recognised as an option and the missing required option causes an error to be displayed. Perhaps you were running it though npm?

Oh, having suggested that... npm will eat all the options if you don't use the `--`! That would fit with the problem you described.

Here is what I see running your example code:

```console
% node dist/cli.js -- -c upt ./foo-bar.txt
error: required option '-c --customer-name <comp>' not specified

% node dist/cli.js -c upt ./foo-bar.txt 
input_file: ./foo-bar.txt
options: {
  "customerName": "upt"
}
```

**Comment by machinshin** [comment]
@shadowspawn  Thank you for responding so quickly! you are correct , I have a couple of npm scripts.

```json
{
  "main": "dist/bundle.js",  
  "scripts": {  
    "build": "rollup -c rollup.config.mjs"  -- generates dist/bundle.js
    "start" : "node ./dist/bundle.js"
  }
}
```
It seemed to be that the `--` are needed as testing any of the cli options, like, `npm run start -h` fails as the option is being handled by npm.

but still when I remove the `--` , now i get a different issue.

`$> npm run start ./foo-bar.txt -c upt` gives
`error: required option '-c, --customer-name <comp>' not specified`

**Comment by shadowspawn** [comment]
> update, i ran the node script explicitly on the commandline:
> `node dist/bundle.js ./foo-bar.txt -c upt` and that gives the undefined options error from my original comment.

I am not seeing that behaviour when I run your sample code, so I think there is something missing from the example. If you had another optional argument like `.argument('[output-file]')` then it would explain the observed behaviour.

Do you see anything for the `options` when you run this?

```
% node dist/bundle.js -c upt ./foo-bar.txt ./another-file
```

**Comment by machinshin** [comment]
no, I don't have any other argument()'s. also, does the order of the call-chain matter? 

the contents of program.ts are basically this:

```typescript
// src/ts/program.ts
const program = new Command('cmd-name');

program
  .description('program description')
  .version('0.0.1')
  .argument('<input-file>', 'file we expect')
  .requiredOption('-c, --customer-name <comp>', 'customer.short_name')
  .option('-o, --output-dir <path>', 'directory to output to', 'out')
  .option('-q, --quiet', 'do not log progress', false)
  .option('-y, --dry-run', 'show what should be run', false)
  .usage('[options] <input-file>');

export default program;
```

**Comment by shadowspawn** [comment]
> the contents of program.ts are basically this:

Plugging that in with your example cli, I see:

```
% node ./dist/cli.js -c foo INPUT
input_file: INPUT
options: {
  "outputDir": "out",
  "quiet": false,
  "dryRun": false,
  "customerName": "foo"
}
```

**Comment by shadowspawn** [comment]
I have not come up with an explanation that matches all of your description, and can't reproduce with your example code, so currently stumped.

You could check whether your examples files actually show the problem for you, and then compare with your real program to narrow down where the problem lies. Or if your real code is available, I could take a look. 

(Note: I appreciate the effort to offer a minimal reproducible example, but currently not reproducible. 😢 )

**Comment by machinshin** [comment]
so closing as it turns out to have been an issue on my end.
@shadowspawn thank you for being so attentive & quick in helping out!
