### ISSUE TITLE
Adding command implies.

### ISSUE THREAD

**Issue by YPetremann** [tj/commander.js#1871]
Sometimes I make programs that does similar things like "nuxt dev" and "nuxt build" but that implies diferences
For now I do the following but it's a bit hacky and not explicit:

    const program = new Command();
    program
      .command("build")
      .addOption(new Option("--no-optimize").hideHelp())
      .description(" Build and optimize")
      .option("-w, --watch", "Will automatically recompile on file change")
      .action(build);
    
    program
      .command("dev")
      .addOption(new Option("--no-run").hideHelp())
      .addOption(new Option("--no-watch").hideHelp()
      .description(" Build, watch, and launch")
      .action(build);

I would prefer to do this:

    const program = new Command();
    program
      .command("build")
      .implies({optimize: true})
      .description(" Build and optimize")
      .option("-w, --watch", "Will automatically recompile on file change")
      .action(build);
    
    program
      .command("dev")
      .implies({watch: true, run: true})
      .description(" Build, watch, and launch")
      .action(build);

**Comment by shadowspawn** [comment]
Interesting idea. Given the options are largely not intended for use on the command-line, I suggest something like:

```
const program = new Command();
program
  .command("build")
  .description(" Build and optimize")
  .option("-w, --watch", "Will automatically recompile on file change")
  .action((options) => { 
    build({ optimize: true, watch: options.watch }); 
  });

program
  .command("dev")
  .description(" Build, watch, and launch")
  .action((options) => { 
    build({ watch: true, run: true }); 
  });
```

**Comment by YPetremann** [comment]
Yeah I know I can do that, here I've put a simplier version of my whole problem, since in my program some commands are simply another one with some options toggled by default, so I'm working on something to clone a command and all it's parameters in another one so defining the action like that could be a bit redondant.

the cloning mecanism is something for another issue.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a month. It isn't likely to get acted on due to this report. 

The parallel between Option.implies and Command.implies is interesting, but I think writing values into the option values this way is not consistent with the normal case of option values being associated with options. If anyone comes across other libraries solving this problem, I am interested in prior art.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
