### ISSUE TITLE
How to check the parameters

### ISSUE THREAD

**Issue by cc-cherry** [tj/commander.js#1873]
How to check the parameters and re-enter the program when it is wrong instead of throwing an exception to interrupt the program, I think this is very bad.

**Comment by shadowspawn** [comment]
The default behaviour is to call `process.exit()` when there is a problem. You can use `.exitOverride()` to have it throw instead, then then you can call `program.parse()` inside a `try`/`catch` and carry on.

I am not sure what you were wanting to do and what you mean by "re-enter". Perhaps you could give an example of what the user typed on the command line, what you want to "check", and what you want to happen.

**Comment by cc-cherry** [comment]
> 

Sorry, I thought about it carefully and found that there is really no need for secondary output. I confused Commander with inquirer. Regarding the verification, I understand what to do. Thanks

**Comment by cc-cherry** [comment]
ok
