### ISSUE TITLE
Add an option to generate man pages

### ISSUE THREAD

**Issue by tukusejssirs** [tj/commander.js#1875]
I want to generate (Linux) man pages for my apps.

Now, I don’t necessarily need to have man page generator built into `commander` (although it would be nice :wink:), however, at the very least I need to get _full_ help of all commands and subcommands with all their options and descriptions. I’d like to get an object with all those information, than generating a man page could be doable.

Now the object type could be something like this (note that this is just an initial, quickly written example):

```ts
interface Option {
  name: string,
  description: string,
  flags: string[],
  /** What should be printed after flags in square or angle brackets */
  argsPlaceholder?: string,
  /** When a flag accepts an argument, `args` should be defined */
  argsRequired?: boolean,
  argsDescription: Record<string, string>,
  arguments?: string,
  required: boolean,
  choices?: string[],
  default?: string
  isDefault: boolean,
  aliases?: string[]
}

interface Command {
  name: string,
  description: string
  options: Option[],
  subcommands: Command[]
}

/* Full help */
type FullHelp = {
  /** App name */
  name: string,
  /** App description */
  description: string,
  comands: Command[],
  options: Option[]
}
```

**Comment by shadowspawn** [comment]
The Help object is useful for building user facing descriptions. There are methods to leave out the hidden items and add placeholders for the built-in help:
```
const helper = cmd.createHelp();
const visibleCommands = helper.visibleCommands();
const visibleOptions = helper.visibleOptions();
```

Or you can access the arrays directly, the Command object has properties for:
```
  readonly commands: readonly Command[];
  readonly options: readonly Option[];
```

The Option class properties are all public. The Command class has accessors for the properties you listed:
```
const name = cmd.name();
const description - cmd.description();
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

I had a bit of a look at man page generation. It looks a bit gnarly, with nroff/troff/groff variations and various tools for making it easier for writing them by hand.

There are occasional requests for the "full" program details. Most of the info is currently available via properties or getters, but there are a couple of pieces of information only available via private fields (i.e. starting with `_`). If there is demand, being able to get a full json description of program is something I would consider.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
