### ISSUE TITLE
optional exit value for Help. (feature request)

### ISSUE THREAD

**Issue by CrisFavero** [tj/commander.js#188]
It would be extremely convenient for help to take an optional return value so that the program could easily exit with an error code. This is useful in cases where a combination of options are required together and you would want to report to the user the usage but also to the system not to continue with anything else that may be in the execution chain.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

This is reference in meta issue  #934.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
