### ISSUE TITLE
> Could you elaborate on why Array.isArray(values) can be false?

### ISSUE THREAD

**Issue by Sammiegirl411** [tj/commander.js#1889]
> Could you elaborate on why Array.isArray(values) can be false?

Hmm, good question. Probably not needed! I was being paranoid, and had in mind perhaps passing `undefined` or `null` to remove the choices, although that is not supported either in the code or in the typings.

_Originally posted by @shadowspawn in https://github.com/tj/commander.js/issues/1667#issuecomment-1003246354_

**Comment by shadowspawn** [comment]
This looks like a plain repost of a question and answer from another thread. If you had a question about this @Sammiegirl411 just add a new comment here and I can reopen.

**Comment by Sammiegirl411** [comment]
Ok help me. I'm blocked on bluewallet. Please help

**Comment by shadowspawn** [comment]
This is the wrong project for help on bluewallet. Commander parses command-line arguments, and has nothing to do with bluewallet.

**Comment by Sammiegirl411** [comment]
Yes wrong one

Samantha Henson
