### ISSUE TITLE
`-d` short option not handling

### ISSUE THREAD

**Issue by letavocado** [tj/commander.js#1890]
`-d`  short option not handling
```
[nodemon] starting `ts-node bin/crawler.ts`
```
But works with other short options, for example `-l`

## with -d option
```ts
#!/usr/bin/env node
import { Command } from 'commander'
const program: Command = new Command()
//...
program.version(version).option('-d, --depth <number>', 'depth level')

program.parse(process.argv)

const options = program.opts()

console.log(program.args)
console.log(options)
```

run `npx nodemon --exec ts-node bin/crawler.ts -d 3`

![image](https://github.com/tj/commander.js/assets/31704887/90e27183-035b-46ff-a3f9-a6e3718afc21)

## with -l option
```ts
#!/usr/bin/env node
import { Command } from 'commander'
const program: Command = new Command()
//...
program.version(version).option('-l, --depth <number>', 'depth level')

program.parse(process.argv)

const options = program.opts()

console.log(program.args)
console.log(options)
```
![image](https://github.com/tj/commander.js/assets/31704887/c18e3930-27b9-49bd-9f3c-30210a283b50)

```
OS: Arch Linux x86_64
Node: v19.8.1
npm: @9.5.1
"commander": "^10.0.1"
```

**Comment by shadowspawn** [comment]
Thanks for the clear examples.

`nodemon` is eating the `-d` as a "delay" option and it is not being passed through to your program. A good check in these sorts of situations is to log `process.argv` and see what actually reached your program.

The work-around is that `nodemon` supports passing `--` to stop the option processing. The remaining arguments will be left alone. (This is a widely supported behaviour, and Commander supports it too.)

So you could launch your program like:
```console
npx nodemon --exec -- ts-node bin/crawler.ts -d 3
```

**Comment by letavocado** [comment]
@shadowspawn, thank you for providing clarity! :+1:
