### ISSUE TITLE
Parent command with argument that also has subcommands

### ISSUE THREAD

**Issue by sammy-da** [tj/commander.js#1892]
Apologies if this is asked before, I couldn't figure out how to do this from the docs.

I'm trying to come up with something like this:
```
$ mycli parent-command-foo <arg1> subcommand-1
$ mycli parent-command-foo <arg1> subcommand-2
$ mycli parent-command-foo <arg1> subcommand-3
```

**`arg1` must be provided before the subcommands!**
(and, perhaps obviously, every subcommand needs access to that `<arg1>`).

Is it possible to do this?

**Comment by shadowspawn** [comment]
No, this is not supported. You can have a global option that can go before a subcommand, but not a positional command-argument.

**Comment by sammy-da** [comment]
😿 
Okay.
Guess this could turn into a feature request, then. Thanks.

Up to y'all whether to close or keep this issue!

**Comment by shadowspawn** [comment]
The widely followed convention is that arguments follow subcommands, and I don't think this is something we will add to Commander.

A reasonably simple way to implement it yourself would be to remove the leading argument before calling Commander to process the subcommands and options.
