### ISSUE TITLE
Options with optional option argument seem too greedy. A way to change it is needed

### ISSUE THREAD

**Issue by aweebit** [tj/commander.js#1899]
I've read into the [documentation](https://github.com/tj/commander.js/blob/master/docs/options-taking-varying-arguments.md#parsing-ambiguity) explaining how to deal with parsing ambiguities and am not entirely satisfied with the suggested solutions. Below is a simple use case scenario where one required argument is expected and there is one option with an optional option argument.

```javascript
// test.js
import { Command } from 'commander';

const program = new Command()
  .argument('<filename>')
  .option('-p, --preprocess [program]', 'Program to run before processing the file. Default preprocessor is used if no option argument is provided')
  .exitOverride();

try {
  program.parse();
} catch {} finally {
  console.log(program.opts().preprocess);
  console.log(program.args);
}
```

I run following tests:
```bash
# Test 1
node test.js -p file

# Test 2
node test.js --preprocess file

# Test 3
node test.js -pfile

# Test 4
node test.js --preprocess=file

# Test 5
node test.js file -p

# Test 6
node test.js file --preprocess
```

The expected behavior is that `file` be treated as the `filename` argument value in tests 1 and 2, but it was only treated as such in tests 5 and 6, when placed before the option.

So my question is, would it be possible to add a way to make an option with optional option argument _lazy_, so that it would only grab the immediately following argument value if there was no other interpretation for it? (In my example, this would be the case if a second argument was provided, e.g. `node test.js -p program file`.)

Maybe something like the following:
```javascript
program.addOption(new Option('-p, --preprocess [program]').lazy());
```

Or is there any particular reason why this would not work well?

**Comment by aweebit** [comment]
Sorry that I posted the issue too early by accident, it is now complete.

**Comment by shadowspawn** [comment]
For interest, the POSIX behaviour for an option taking an optional argument is that it never takes the following space-separated argument. The option argument can only be specified directly with the option:

```
node test.js -pfile
node test.js --preprocess=file
```

Not many argument parsers support this mode, but I do like that it avoids the parsing ambiguity with optional arguments.

**Comment by shadowspawn** [comment]
> So my question is, would it be possible to add a way to make an option with optional option argument _lazy_, so that it would only grab the immediately following argument value if there was no other interpretation for it?

It is technically possible, but...

1) Harder to implement. The current implementation looks at one argument at a time to see if it is a an option or command, and for options taking optional values then looks ahead one argument at a time to see if the argument starts with a dash. 

2) I think this is an uncommon approach. Are you aware of any utilities or libraries that work this way?

**Comment by aweebit** [comment]
> 2\. I think this is an uncommon approach. Are you aware of any utilities or libraries that work this way?

Unfortunately, I could not find any. There is only this 13 year old Python issue dealing with a similar problem in the argparse module that still has not been resolved: python/cpython#53584.

It is the first time I am creating a command line interface and this seemed to me like the most logical approach, so I am surprised to see there are no libraries that take it.

**Comment by shadowspawn** [comment]
For interest, I did some research when working on `parseArgs` into some widely used implementations and found what I called "greedy" vs "choosy" vs "embedded":

- https://github.com/pkgjs/parseargs/issues/79

**Comment by aweebit** [comment]
That is interesting indeed :) Well, if my suggestion does not seem feasible, maybe adding an option to make an option-argument "embedded" (and thus conforming to POSIX) should be considered.

**Comment by shadowspawn** [comment]
I have nearly written up POSIX-style a couple of times, done now: #1901

**Comment by shadowspawn** [comment]
No further activity in a month. Closing this in favour of #1901.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
