### ISSUE TITLE
Unable to exit with any code other than 0

### ISSUE THREAD

**Issue by jwartofsky-yext** [tj/commander.js#1906]
Hi all,

I'm using CommanderJS and have been unable to get it to exit with any code other than code 0. In the case of errors, I would like to have it exit with code 1.

```
import { Command } from "commander";

const program = new Command();

program.name("mycli").description("My CLI");
program.command("build")
  .description("build site")
  .option("scope <string>", "the folder to build from")
  .action(async (options, command) => {
      try {
          build(); // set to intentionally throw an error
     } catch (e) {
        console.log("Caught the error here!"); // this gets printed
        process.exitCode = 1; // but it exits with code 0
        throw new Error("bad thing happened here");   
     }
  });
  
await program.parseAsync(process.argv);
```
  
When I run the command, I get the log 'Caught the error here!', but the exit code is always 0.
Have also tried with [Yargs](http://yargs.js.org/) and ran into a similar issue.

Is there a solution or way to get an exit code of 1 when encountering an error from running a command?

**Comment by shadowspawn** [comment]
1) I can not reproduce this saving this code as `index.mjs` and running with node. I see an exit code of 1. How are you running this code?

2) You could try Commander's `program.error()` which will call `process.exit()` directly.

https://github.com/tj/commander.js#display-error

**Comment by jwartofsky-yext** [comment]
This was caused by a spawnSync which was masking the exit code, not a problem with commanderjs.
