### ISSUE TITLE
Enhancement request: Try loading environment variables from ".npmrc" first, and only later in OS environment variables

### ISSUE THREAD

**Issue by mirobo** [tj/commander.js#1914]
Hey there

I use cypress-cloud plugin which uses commander.js here and uses the "env(..)" option:
https://github.com/currents-dev/cypress-cloud/blob/656473c126d4751549b70eb56bcccfabca18f3cb/packages/cypress-cloud/bin/lib/program.ts#L51

Here I see that it only checks for the real environment variable:

https://github.com/tj/commander.js/blob/4ef19faac1564743d8c7e3ce89ef8d190e1551b4/lib/command.js#L1619

I think it could greatly add to the flexibility of commander.js if it were to look for an environment variable "npm_config_foobar" first and if not defined, look for "foobar" afterwards.

Before checking for "foobar" anywhere, it might be helpful to preprocess all variables to lowercase, just in case any OS handles case-sensitivity different; on Windows for example I can set the variable FOOBAR=123 in npmrc and it will show as "npm_config_foobar".

What do you think of this idea?

**Comment by shadowspawn** [comment]
Interesting idea, but I don't think this is appropriate. The npm environment variables will only be defined if you launch your command through npm. The name reinforces that this is a feature for npm configuration: `npm_config_*`.

I do use npm myself to support cross-platform developer workflows with `run-scripts`, so I empathise with looking to npm. But I don't think the environment variables is a good match.

I see in the `cypress-cloud` [setup](https://github.com/currents-dev/cypress-cloud#setup) that there is support for a configuration file. This seems like a better place to put cypress configuration than in an `npmrc` file.

**Comment by mirobo** [comment]
Thanks for your response :)

I already use the configuration file for cypress-cloud, but it has the drawback that, if you have multiple e2e projects in a mono repo, that you either:
- have to copy&paste the same old configuration files to different places
- execute a configuration-script that copies the file to the e2e project directory before execution
- or that you have to set the environment variables for example in gitlab CI yaml (or whatever CI solution you're using) - in this case you cannot easily test or run something locally because the variables are "hidden" in some yaml file. 

That's why I came up with the idea of .npmrc, because it is accessible to both CI and local environment through one single file and it can be accessed in multiple e2e projects in the same repo :)

**Comment by shadowspawn** [comment]
Thanks for the idea, but I don't see Commander having built-in support for reading `.npmrc` or detecting npm environment variables.
 
Thank you for your contributions.
