### ISSUE TITLE
Cannot get options if command's option name is the same as progam's.

### ISSUE THREAD

**Issue by zanminkian** [tj/commander.js#1932]
```js
// cmd.mjs
import { program } from 'commander'

program
.option('--fix', 'fix')
.action((options)=>{
  console.log('main', options)
})

program
.command('run')
.option('--fix', 'fix')
.action((options)=>{
  console.log('run', options)
})

program.parse()
```

run: `node cmd.mjs run --fix`
Expected output: `run { fix: true }`
Actual output: `run {}`

**Comment by shadowspawn** [comment]
This is expected default behaviour. By default, Commander looks for the program options anywhere on the command line. So it consumes the option before the subcommand has a chance. You can see the option has been read if you log `program.opts()`.

Depending on why you have the same option at two levels, there are various approaches you can take:

- To make it more convenient to work with "global" (program) options from a subcommand, there is `.optsWithGlobals()` to get the subcommand and global options all at once.

- You can change the default behaviour to make options positional so program options have to come before subcommands with `.enablePositionalOptions()`: 
https://github.com/tj/commander.js#parsing-configuration

- If the option is only on the program for when you run the program without specifying a subcommand, you can shift that functionality into a default command. That gets the option out of the hierarchy.

If you want to know more about one of those approaches just ask, I can link to some previous issues.

**Comment by zanminkian** [comment]
`.enablePositionalOptions()` and `.optsWithGlobals()` work for me. Thanks!
