### ISSUE TITLE
`allowUnknownOption` missing in `.copyInheritedSettings()`?

### ISSUE THREAD

**Issue by aweebit** [tj/commander.js#1944]
#1557 shows that the `allowUnknownOption` setting was already available at the time when `.copyInheritedSettings()` was introduced. Is there a particular reason why it was not included in the inherited settings unlike the very similar `allowExcessArguments`, or was it simply forgotten? If so, should it be added?

**Comment by shadowspawn** [comment]
This is as intended. I think `allowUnknownOption` is more likely to apply to particular commands than all commands. So somewhat like `.passThroughOptions()`, for special cases.

(I don't consider `allowUnknownOption` a first-class feature. It is a bit of a simple historical "hack" that just turns off the error handling. Hopefully it does help in some hybrid parsing scenarios!)
