### ISSUE TITLE
`passThroughOptions` being a superset of `enablePositionalOptions`

### ISSUE THREAD

**Issue by aweebit** [tj/commander.js#1947]
```js
new Command()
  .passThroughOptions()
  .command('sub')
  .passThroughOptions();
```

Running this code results in the following error:

```
Error: passThroughOptions can not be used without turning on enablePositionalOptions for 
parent command(s)
    at Command.passThroughOptions (lib/command.js:739:13)
```

But actually, using `passThroughOptions` on a subcommand whose parent also uses it should be okay because `passThroughOptions` makes options positional just like `enablePositionalOptions`. That is demonstrated by the following snippet

```js
const program = new Command()
  .passThroughOptions()
  .option('-x');
const sub = program.command('sub')
  .option('-x');
program.parse(['sub', '-x'], { from: 'user' });
console.log(program.opts()); // {}
console.log(sub.opts()); // { x: true }
```

and explained by the fact `passThroughOptions` is included in the check in [`lib/command.js`](https://github.com/tj/commander.js/blob/master/lib/command.js), [line 1522](https://github.com/tj/commander.js/blob/4ef19faac1564743d8c7e3ce89ef8d190e1551b4/lib/command.js#L1522).

So is there any point in requiring `enablePositionalOptions` when `passThroughOptions` which too has the needed effect is already on?

My suggestion is
- either not to throw the error when the parent command uses `passThroughOptions`,
- or to change the semantics for `passThroughOptions` so that there is no functionality overlap with `enablePositionalOptions`.

The latter idea introduces a breaking change but could be justified by some absurd use cases like
```bash
# --verbose to be passed through due to using passThroughOptions
node program --trace curl --verbose https://github.com/

# --verbose to be consumed by program command due to not using enablePositionalOptions
node program utility-subcommand --verbose
```

**Comment by shadowspawn** [comment]
In normal use, `.enablePositionalOptions()` will be enabled globally while `.passThroughOptions()` will be enabled in specific leaf commands.

The two concepts are separate.

**Comment by aweebit** [comment]
> The two concepts are separate.

I see, but there is still a functionality overlap that makes the error unnecessary when the parent command uses `passThroughOptions`.

**Comment by shadowspawn** [comment]
I understand the error may not be strictly required. I'll take another look, but it is currently as I intended.

**Comment by aweebit** [comment]
Here is my mental model for how options should be handled ideally, in which there is no functional overlap between settings, and including the modified semantics for `operands` and `unknown` suggested in the now-closed #1945 in _italics_.

The change suggested by this issue is in **bold**.

#### Default behavior:
Consume all known options.

Pass unknown options on for reprocessing _by pushing to `unknown` in `.parseOptions()`_ if there is a subcommand.
Otherwise, exit with an error message as soon as an unknown option is found.

#### When using `enablePositionalOptions`:
Same as default, but don't consume known options after subcommand.

Since it is now not needed, don't process arguments after subcommand in `.parseOptions()` and pass them to the subcommand instead by pushing to `unknown`. **Currently also happens when using `passThroughOptions`, but should not!**

#### When using `passThroughOptions`:
Same as default, but **if there is no subcommand** and a command-argument is encountered, don't consume the remaining known options and ignore the remaining unknown options (treated as command-arguments _and therefore pushed to `operands` in `.parseOptions()`_ in this case).
 
#### When using `allowUnknownOption`:
Same as default, but if there is no subcommand, ignore the remaining unknown options (treated as command-arguments _and therefore pushed to `operands` in `.parseOptions()`_ in this case).

### P.S.
<details>
<summary>Reiterating the suggestion from #1945</summary>

As seen here, the suggestion from #1945 would make `unknown` only ever used to store arguments that are passed on to a subcommand for further processing (even your comment https://github.com/tj/commander.js/issues/1945#issuecomment-1667103439 suggested that should be the case).

If I still wanted to document the `operands` and `unknown` semantics here without the suggested modification applied, it would get really, really messy, especially because the combination of `passThroughOptions` and `allowUnknownOption` is currently confusing as shown in https://github.com/tj/commander.js/issues/1945#issuecomment-1675544846, and so the `passThroughOptions` section would have to include a remark on the special treatment of the first argument when it is an unknown option and the combo is used.

Both this comment and https://github.com/tj/commander.js/issues/1936#issuecomment-1675866069 show that the suggestion from #1945 has the potential to make some explanations about the library's internals less confusing and more precise.
</details>

**Comment by shadowspawn** [comment]
> I understand the error may not be strictly required. I'll take another look, but it is currently as I intended.

I am still happy with the behaviour.

Morally, perhaps the code could check `this._passThroughOptions` more selectively than `this._enablePositionalOptions` as I think pass-through is only needed for the default command, but easier to just test at the top of the block and not be too clever.

https://github.com/tj/commander.js/blob/4ef19faac1564743d8c7e3ce89ef8d190e1551b4/lib/command.js#L1522

**Comment by shadowspawn** [comment]
In absence of other issues coming up, I don't currently want to change the behaviour.

Thank you for your contributions.
