### ISSUE TITLE
On `@api` JSDoc tag

### ISSUE THREAD

**Issue by aweebit** [tj/commander.js#1949]
The `@api` JSDoc tag has been used in the library code since [the initial commit](https://github.com/tj/commander.js/commit/672c7d01d8382257226d67c39c6e1002c881d95f). However, I have not been able to find any documentation on it. The fact its values are properly highlighted in VS Code is due to microsoft/vscode@9ad4bcd66f8c7d9bd71a400efd07f1fdaa454ab2, which includes no explanation on why the highlighting was added. My best guess is that it was added just to cover de facto usage like that in Commander (see microsoft/vscode#189812).

The well-documented alternatives to `@api private` (which is currently used throughout the library) are [`@private`](https://jsdoc.app/tags-private.html) and [`@access private`](https://jsdoc.app/tags-access.html). Should we use one of them instead?

**Comment by aweebit** [comment]
Found the progenitor commit adding the highlighting later adopted by VS Code: [31d2a5f](https://github.com/atom/language-javascript/pull/512/commits/31d2a5f3d321761a1b2d1ec85ed3d507f76b5812)

My assumption was right. The commit description reads:

> Not part of the official JSDoc spec, yet occasionally used in-the-wild.

**Comment by aweebit** [comment]
I found other usage examples and opened jsdoc/jsdoc#2066. Excited to see where it leads, but not expecting quick reaction since there has not been much activity in the repo recently.

**Comment by aweebit** [comment]
I've just realized `@package` should be used instead of `@private` or `@api private` because classes use each others' "private" methods all over the library.

**Comment by shadowspawn** [comment]
`@package` is technically accurate, but I had never seen it and had to look it up to confirm the meaning. I think @private is much clearer for Commander users seeing the tag.

**Comment by aweebit** [comment]
> `@package` is technically accurate, but I had never seen it and had to look it up to confirm the meaning.

Unfortunately, it is indeed quite uncommon ([only 10k results](https://github.com/search?q=language%3AJavaScript+OR+language%3ATypeScript+%22*+%40package%22+NOT+%22*+%40packageDocumentation%22+NOT+%22*+%40package+%22&type=code) in GitHub Search).

> I think `@private` is much clearer for Commander users seeing the tag.

The problem is that if you replace all `@api private` occurrences by `@private`, you will see a bunch of TypeScript errors that were not show before because `@api private` is not valid JSDoc, and in particular not currently supported by the TypeScript flavor of JSDoc, but that could change in the future.

I don't think we should keep using `@api private` just so that we can avoid errors because actually, it is supposed to simply be a synonym for `@private`, even though it currently isn't in tools other than [Dox](https://github.com/tj/dox).

**Comment by aweebit** [comment]
And by the way, the TypeScript team [strongly advocates](https://github.com/microsoft/TypeScript/issues/1867#issuecomment-209018980) for having public declarations even for private class members.

But again quite unfortunately, TypeScript does not have an accessibility modifier that would be matched by the JSDoc `@package` tag (although an issue proposing such a modifier has been open since 2015: microsoft/TypeScript#5228).

So if we follow the guidelines and add typings for all package-private stuff, nothing will stop library users from accessing it, and they will even see it suggested by IntelliSense. It really frustrates me that TypeScript is such a mess :(

**Comment by shadowspawn** [comment]
> The problem is if you ...  replace all `@api private` occurrences by `@private`, you will see a bunch of TypeScript errors that were not show before because @api private is not valid JSDoc

Oh, yes indeed. And to be fair, correct! I have been accessing some methods as "package" accessible rather than being strict. That raises the bar. Not sure whether I want to change anything.

**Comment by aweebit** [comment]
Just found out TypeScript recognizes `@internal` as a way to omit stuff from being included in declaration files under the [`stripInternal`](https://www.typescriptlang.org/tsconfig#stripInternal) option. Could be exactly what we need.

**Comment by shadowspawn** [comment]
Released in Commander v12.0.0.
