### ISSUE TITLE
Add regex parameter to `.argument`

### ISSUE THREAD

**Issue by MaxumCSmith** [tj/commander.js#1953]
I find myself having to validate arguments more thoroughly using Regex. I end up doing this from within the action method, but it would be nice if we could pass another parameter into `.argument` as a regex that would be used to validate.

Maybe something like this would be nice?

`argument(name: string, description?: string, defaultValue?: unknown): this;` -> `argument(name: string, description?: string, defaultValue?: unknown, validationRegex: Regex): this;`

**Comment by shadowspawn** [comment]
You can write a custom processing function that validates the argument with a regular expression. 

See https://github.com/tj/commander.js#custom-argument-processing and have a look at `myParseInt` in the [Custom option processing](https://github.com/tj/commander.js#custom-option-processing) section

To avoid writing multiple parsers if you want to use different regex you can write a function to generate the parser from the regex, see later comments in #1130

**Comment by MaxumCSmith** [comment]
I see. I didn't notice the ability to pass in a processing function. `fn` should enable what I need.
* `argument<T>(flags: string, description: string, fn: (value: string, previous: T) => T, defaultValue?: T): this;`

Thank you.

**Comment by shadowspawn** [comment]
I'll close this issue, but #1909 is still open and flagged for reviewing the documentation.
