### ISSUE TITLE
Proper way to get value of argument

### ISSUE THREAD

**Issue by pkropachev** [tj/commander.js#1959]
Could you please advice proper way to get value of argument?
I'd like to set "port" as not mandatory argument without option (like in python http.server).

```ts
import { program, InvalidArgumentError } from 'commander';

let PORT: number = 8000;

function startServer(address: string, port: number) {
  console.log(`${address}:${port}`);
}

function checkPort(value: string) {
  const parsedValue = +value;
  if (isNaN(parsedValue)) {
    throw new InvalidArgumentError('Invalid int value.');
  }
  PORT = parsedValue;
  return PORT;
}

program.option('-b ,--bind <address>', 'bind to this address (default: all interfaces)');
program.argument('[port]', 'bind to this port', checkPort, PORT);

program.parse(process.argv);

startServer(program.opts().bind, PORT);
```

Is it correct way or it may be done easier?
Thanks!

**Comment by aweebit** [comment]
In the [Custom argument processing](https://github.com/tj/commander.js/#custom-argument-processing) section, the docs says:

> The processed argument values are passed to the action handler, and saved as `.processedArgs`.

So if you want to adhere to the idiomatic pattern, you should

- make `PORT` a `const` (and maybe rename to `DEFAULT_PORT`),
- replace these lines

    ```js
    PORT = parsedValue;
    return PORT;
    ```

    with

    ```js
    return parsedValue;
    ```

- and either replace

    ```js
    startServer(program.opts().bind, PORT);
    ```

    with

    ```js
    startServer(program.opts().bind, program.processedArgs[0]);
    ```

    or move the call to an action handler like this:

    ```js
    program.action((port: number) => {
        startServer(program.opts().bind, port);
    });
    ```

    (This code must come before the `.parse()` call.)

----

By the way, you can also access the unprocessed command-arguments via `.args` as suggested by the docs [here](https://github.com/tj/commander.js/#common-option-types-boolean-and-value):

> `program.parse(arguments)` processes the arguments, leaving any args not consumed by the program options in the `program.args` array.

And you could also omit `process.argv` from the `.parse()` call because it is the default value as the docs states in the sentence right after:

> The parameter is optional and defaults to `process.argv`.

**Comment by pkropachev** [comment]
@aweebit, thanks for detailed message! In the result I've done it in the following way:

```ts
function checkPort(value: string) {
  const parsedValue = +value;
  if (isNaN(parsedValue)) {
    throw new InvalidArgumentError('Invalid int value.');
  }
  return parsedValue;
}

program
  .option('-b ,--bind <address>', 'bind to this address (default: all interfaces)')
  .option('-v ,--verbose', 'be verbose')
  .argument('[port]', 'bind to this port', checkPort, 8000)
  .allowExcessArguments(false)
  .parse(process.argv);

const opts = program.opts();
const [port] = program.processedArgs;

startServer(opts.bind, port);
```

Basically it works, but still not sure if this is correct way.

**Comment by aweebit** [comment]
> Basically it works, but still not sure if this is correct way.

Looks good to me 👍

**Comment by shadowspawn** [comment]
> Basically it works, but still not sure if this is correct way.

Yes, this is correct @pkropachev and as intended. 

The only thing you missed in your original example was `.processedArgs`. 

Programs with subcommands use an action handler for each command and get passed the "processed" args. You can optionally use an action handler for a single command program like yours, but simpler and normal to do it just as you did.

**Comment by pkropachev** [comment]
Thanks @aweebit , @shadowspawn!
