### ISSUE TITLE
Pull request catalog by @aweebit

### ISSUE THREAD

**Issue by aweebit** [tj/commander.js#1964]
I try my best to keep this PR list sorted by the importance of the changes (and also how easy they are to accept) while at the same time keeping it structured well.

The list was originally placed in a random comment ([#1919 (comment)](https://github.com/tj/commander.js/pull/1919/#issuecomment-1675985995)), which I didn't like. I hope it's okay that I've moved it to an issue.

----

### Patches
_ChangeLog type:_ `Fixed`

- #1974
- #1956

### Enhancements / changes in behavior
_ChangeLog type:_ `Added` / `Changed`

#### Changes in behavior fixing open issues
- #1924 (fixes [#1903](https://github.com/tj/commander.js/issues/1903))

#### Misc
- #1923 (closely related to [#1924](https://github.com/tj/commander.js/issues/1924) from right above)
- #1970
- #1951 (fixes [#1901](https://github.com/tj/commander.js/issues/1901), quite robust and thus ready for review in my opinion, only tests missing)

### Pure refactors and other changes of low importance
- #1961

### On hold
- #1950

#### Misc
- #1967 (reconsider with increased granularity if stricter type checking is adopted)
- #1966 (a subset of [#1967](https://github.com/tj/commander.js/issues/1967) from right above)
- #1935 (might want to decouple from [#1929](https://github.com/tj/commander.js/issues/1929))
- #1934
- #1929 (a subset of [#1934](https://github.com/tj/commander.js/issues/1934) and [#1935](https://github.com/tj/commander.js/issues/1935) from right above)
- #1922
- #1919 (partially fixes [#1916](https://github.com/tj/commander.js/issues/1916) and a lot of older issues)
- #1941
- #1933 (the version number part, see [#1954 (comment)](https://github.com/tj/commander.js/pull/1954#issuecomment-1675952316))
- #1921

#### With warnings about presumably wrong library usage
- #1940 (partially fixes [#1916](https://github.com/tj/commander.js/issues/1916))
- #1938 (includes an arguably questionable enhancement to parent handling, so might require more time to think about than the previous PR, but the warning is very, very, [VERY](https://github.com/tj/commander.js/pull/1938#issuecomment-1667037227) useful) (partially fixes [#1916](https://github.com/tj/commander.js/issues/1916))
- #1931 (not as useful as the previous ones because it is likely the developer is okay with the help option being obscured, but a good complement to [#1923](https://github.com/tj/commander.js/issues/1923))
- #1955 (a reasonable addition since all warnings introduced in the PRs above are for usage patterns that are not always wrong, just often connected with a developer mistake)

#### Pure refactors and other changes of low importance
- #1946 (discussion finished in [#1945](https://github.com/tj/commander.js/issues/1945), but reiterated in [#1947 (comment)](https://github.com/tj/commander.js/issues/1947#issuecomment-1675914455))
- #1957
- #1927

#### Changes to core project principles
- #1975

----

### Issues that might need a PR
- #1976
- #1968
- #1936 (awaiting feedback)
- #1947 (awaiting feedback)
- #1973
- #1949
- #1916 (document the lack of support for repeated parse calls as suggested in [#1919 (comment)](https://github.com/tj/commander.js/pull/1919#issuecomment-1683544641) unless [#1919](https://github.com/tj/commander.js/pull/1919) is reconsidered)

----

### Completed
- #1904
- #1915
- #1925
- #1928
- #1930
- #1937
- #1939
- #1943
- #1965
- #1971

**Comment by shadowspawn** [comment]
In general, if you keep the Pull Requests independent then they will be dealt with from oldest to newest.

But note also, you are opening Pull Requests far faster than I can review them.

**Comment by aweebit** [comment]
> But note also, you are opening Pull Requests far faster than I can review them.

Good news: I think I am going to run out of ideas in a day or two :)

**Comment by aweebit** [comment]
### Note mainly for myself

[`Array.at`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) is only supported starting Node.js v16.6.0 (see nodejs/node#39534). Do not use it like I did in #1904.

**Comment by aweebit** [comment]
I will be very busy during the next few days, gonna reply to new comments on the PRs when I am free again.

**Comment by shadowspawn** [comment]
Thanks for update, no problem.

**Comment by shadowspawn** [comment]
Down to just a few open PRs so an overview of the backlog is no longer needed.
