### ISSUE TITLE
TypeScript definitions missing Option.envVar

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#1972]
`Option.envVar` is a public property of the JavaScript class.

The `index.d.ts` TypeScript definition is missing the `envVar` property for the `Option` class.

(Raised in #1971)

**Comment by aweebit** [comment]
`presetArg`, `conflictsWith` and `implied` are also missing.

Same with `parseArg`, `defaultValue`, `defaultValueDescription` and `argChoices` in the `Argument` class. Also might want to consider making `_name` public (for comparison, option-argument names can be accessed by extracting them from the public `flags` property).

**Comment by shadowspawn** [comment]
> are all explicitly marked as private in JSDoc despite having no underscores in their names. Historical reasons, I guess?

Yes indeed. I did add an issue about renaming those, but decided to minimise breakages and leave them alone:  #1104

**Comment by shadowspawn** [comment]
The TypeScript has never had 1:1 match with properties visible from JavaScript, but adding them as needed, and intend to usually add them for new properties.

(The dual purpose getter/setter does at least reduce the number of properties exposed, much as I dislike the overload on return type!)

**Comment by shadowspawn** [comment]
Shipped in Commander v11.1.0
