### ISSUE TITLE
Option gets capitalized when using 3 or more flag options

### ISSUE THREAD

**Issue by cameronwilson99** [tj/commander.js#1979]
for example,
 
```js
program.addOption(
    new Option(
      "-e, -env, --env <env>",
      "The env to use. (defaults to prod)",
      "prod"
    )
      .default("prod")
      .hideHelp()
  );
```
  
  when accessing this option later, using options.env, it comes out as undefined, because it expects options.Env. Doesn't matter the option name or anything else, just with three or more flag options, it capitalizes the option.
  
this works fine, for example.

```js
program.addOption(
    new Option(
      "-env, --env <env>",
      "The env to use. (defaults to prod)",
      "prod"
    )
      .default("prod")
      .hideHelp()
  );
```

**Comment by shadowspawn** [comment]
Options may have a short flag, which is one dash and one character. Like `-e`.
Or a long flag, which is two dashes followed by one or more characters. Like `--env`.
Or both. Like `-e, --env`.

So two problems. Commander does not support:
- `-env` as flag option
- 3 or more flag options

`-env` may currently work by accident, but that could break in the future as it is not a supported form.

**Comment by shadowspawn** [comment]
For interest, multi-character short options are being used in the wild:

https://github.com/search?q=%2Fprogram%5C.option%5C%28%27-%5B%5E-%5D%5Ba-z%5D%2F+++%22commander%22+%28language%3Ajavascript+OR+language%3Atypescript%29+AND+NOT+is%3Afork&type=code

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

At some point in future, Commander might throw an error if the flags setup for the option is incorrect. I am not treating this issue as a request for that. 😄 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
