### ISSUE TITLE
version conflict with subcommand options

### ISSUE THREAD

**Issue by answer-huang** [tj/commander.js#1980]
```javascript
const { program } = require('commander');

program.version('1.0.2')
program.command('split')
  .option('--version', 'display just the first substring')

program.parse();
```

<img width="617" alt="image" src="https://github.com/tj/commander.js/assets/1219398/e614583b-b03d-4e7e-9f94-cc12e9041c6c">

how should i do to resolve this conflict

**Comment by shadowspawn** [comment]
From the README:
> By default program options are recognised before and after subcommands. To only look for program options before subcommands, use `.enablePositionalOptions()`. This lets you use an option for a different purpose in subcommands.

So you want to call `program.enablePositionalOptions()`.

**Comment by answer-huang** [comment]
> From the README:
> 
> > By default program options are recognised before and after subcommands. To only look for program options before subcommands, use `.enablePositionalOptions()`. This lets you use an option for a different purpose in subcommands.
> 
> So you want to call `program.enablePositionalOptions()`.

Thank you bro, sorry for my careless.
