### ISSUE TITLE
2.2.0 isn't compatible any more with parseInt used with default arguments

### ISSUE THREAD

**Issue by kornelski** [tj/commander.js#201]
``` js
 require('commander').
 option('--port <num>', 'Port number to listen on', parseInt, 9000).
 parse([ 'node', 'main.js', '--port=80' ]).
 port
```

This works as expected in 2.1.0, but in 2.2.0 `parseInt` is given 9000 as a second argument, which makes it output nonsense.

**Comment by shadowspawn** [comment]
Oops, used this as the earliest bug and want it open as I am linking to it from multiple places!

**Comment by shadowspawn** [comment]
I have proposed a large update to options coverages in README in #953

**Comment by shadowspawn** [comment]
The options coverage in the README has been updated and includes new description of custom option processing, including a working `parseInt` example.

https://github.com/tj/commander.js#custom-option-processing
