### ISSUE TITLE
Hello, I would like to add a method to obtain non defined parameters

### ISSUE THREAD

**Issue by hengshanMWC** [tj/commander.js#2020]
Hello, I would like to create a proxy package manager function. I hope to obtain non defined argv through getUnknownArgv, so that I can transfer this part of argv to the package manager for operation
`
argv = ['...', '...', 'run', 'test', '--type', 'all', '--color']

program.command('run <cmd>').options(['--type <type>', 'all | work | stage | repository'])
.action(() => {
const arr = program.getUnknownArgv()
console.log(arr) // ['--color']
})
.parse(argv)
`

**Comment by shadowspawn** [comment]
`.passThroughOptions()` is intended for this use case. It expects your command options like `--type` to come before the command-argument ('test' in your example) and then anything after that is passed through. Here is an example based on your code:

```js
import { Command, Option } from 'commander';
const program = new Command();

program.enablePositionalOptions();

program.command('run')
  .passThroughOptions()
  .addOption(new Option('--type <TYPE>', 'specify type').choices(['all',  'work', 'stage', 'repository']))
  .action((options, cmd) => {
    console.log(options);
    console.log(cmd.args);
  });

program.parse();
```

```console
% node index.mjs help run
Usage: index run [options]

Options:
  --type <TYPE>  specify type (choices: "all", "work", "stage", "repository")
  -h, --help     display help for command
% node index.mjs run --type all test --color
{ type: 'all' }
[ 'test', '--color' ]
```

**Comment by shadowspawn** [comment]
Another approach is to use `.allowUnknownOptions()` but it is not smart and makes the parsing less strict.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
