### ISSUE TITLE
Function in default argument always gets executed

### ISSUE THREAD

**Issue by garysassano** [tj/commander.js#2022]
```
function findEntrypoints(pattern: string): string[] {
  const entrypoints = glob.sync(pattern);
  if (entrypoints.length === 0) {
    throw new Error(`No file matching default pattern '${pattern}' found in current directory.`);
  }
  return entrypoints;
}  

program
    .command("test")
    .argument("[entrypoint...]", "all entrypoints to test", findEntrypoints("*.test.w"))
```

In this example, `findEntrypoints("*.test.w")` always gets executed even when I call the CLI without specifying any command at all.

**Comment by shadowspawn** [comment]
Yes. There is support for a default value, which you are passing by calling `findEntrypoints("*.test.w")`.

There is not support for a callback to only supply the default value if needed, which I think is what you were hoping for? That idea was suggested in #1036

**Comment by garysassano** [comment]
I don't understand. Let's say I have a CLI called `foo`. This CLI has several commands called `test`, `run`, `compile`, etc. The default value `function()` is present only within the `test` command, so I would expect that the function representing the default value of the `test` command gets executed only when calling `foo test`. Instead, that function gets always executed at any invocation of my CLI, even just calling `foo` would execute the function and I just don't get this behaviour.

**Comment by shadowspawn** [comment]
> The default value `function()` is present only within the `test` command`

The code isn't passing a default value `function()`. The code is calling the `findEntrypoints` function and passing the result as a default value. So it always gets run.

This is _not_ supported, but to do what you describe the code would nee to pass a function to call later to get the function results, like say:

```js
.argument("[entrypoint...]", "all entrypoints to test", () => findEntrypoints("*.test.w"))
```

Does that make sense?

**Comment by shadowspawn** [comment]
The way to achieve what you expected is to leave out the default value when defining the argument, and do a check inside the action handler to look up the default value if the argument is the empty array. (Empty array because your argument is defined as variadic.) Then the code will only get executed when the subcommand is used.

```js
import { program } from 'commander';

function findEntrypoints() {
  console.log('called findEntrypoints');
  return ['example.test.w'];
}

program
  .command("test")
  .argument("[entrypoint...]", "all entrypoints to test")
  .action(entryPoints => {
    if (entryPoints.length === 0)
      entryPoints = findEntrypoints();
    console.log({ entryPoints });
  });

program.parse();
```

```console
% node index.mjs test                 
called findEntrypoints
{ entryPoints: [ 'example.test.w' ] }
% node index.mjs test one.test.w two.test.w
{ entryPoints: [ 'one.test.w', 'two.test.w' ] }
```

**Comment by garysassano** [comment]
I had actually used another approach initially:

```
function runSubCommand(subCommand: string) {
  return async (...args: any[]) => {
    if (args[0] === "DEFAULT_TEST_ENTRYPOINTS") {
      args[0] = glob.sync("*.test.w");
      if (args[0].length === 0) {
        throw new Error("No '.test.w' file found in current directory.");
      }
    }
	[...]
}

program
    .command("test")
    .argument("[entrypoint...]", "all entrypoints to test", "DEFAULT_TEST_ENTRYPOINTS")
	[...]
    .action(runSubCommand("test"));
```

I thought this wasn't the proper way to achieve what I wanted, but apparently it is.

**Comment by garysassano** [comment]
And yes, I had tryed also this code as a workaround:
```
.argument("[entrypoint...]", "all entrypoints to test", () => findEntrypoints("*.test.w"))
```

**Comment by garysassano** [comment]
The issue #1036 is indeed what I expected to do. Do you think it would be possible to support a callback function to resolve the default value of an argument in the future?

**Comment by garysassano** [comment]
What's described in #1036 is indeed what I expected to do. Do you think it would be possible to support a callback function to resolve the default value of an argument in the future?

**Comment by garysassano** [comment]
Why the following code works just fine?
```
program
  .command("test")
  .argument("[entrypoint...]", "all entrypoints to test", glob.sync("*.test.w"))
```

**Comment by shadowspawn** [comment]
I don't understand, what is the question?

This code looks very similar to your first example, and I expect works much the same way.

**Comment by shadowspawn** [comment]
Something you might want to consider is what the help will look like. The default value is included in the help, but you can optionally specify the text to use instead of the actual value. For example:

```
  .addArgument(new Argument("[entrypoint...]", "all entrypoints to test")
    .default(glob.sync("*.test.w"), '*.test.w')
  )
```

or like your other approach:

```
  .addArgument(new Argument("[entrypoint...]", "all entrypoints to test")
    .default('DEFAULT_TEST_ENTRYPOINTS', '*.test.w')
  )
```

**Comment by garysassano** [comment]
@shadowspawn That code actually works perfectly fine, contrary to my `findEntrypoints()` function. For some reason, `glob.sync()` doesn't execute immediately, only when calling the `test` command from the CLI.

**Comment by garysassano** [comment]
So, with this approach, the `glob.sync()` function gets executed only when calling the `test` command.
```
.addArgument(new Argument("[entrypoint...]", "all entrypoints to test")
  .default(glob.sync("*.test.w"), '*.test.w')
)
```

Whereas, with this other approach, the `glob.sync()` function would always execute even if the `test` command isn't called.
```
.argument("[entrypoint...]", "all entrypoints to test", glob.sync("*.test.w"))
```

If what I described above is the actual behaviour, then I think this is a good workaround and we can then close the issue.

Thanks for all your help.

**Comment by shadowspawn** [comment]
> If what I described above is the actual behaviour

No, the call to `glob.sync("*.test.w")` still gets executed immediately, and not later during parsing.

**Comment by garysassano** [comment]
Oh ok, so my original solution (using a placeholder string which gets resolved later in another function) would still be the most efficient. In any case, matching files with a glob pattern takes only a few ms, so I'll still stick with the more readable solution given the negligible performance hit.

Since other people before me asked you about this feature already 4 years ago, I think it would be a nice addition.

That said, thank you again for your time.
