### ISSUE TITLE
How do I implement `$ program help command`

### ISSUE THREAD

**Issue by MarcDiethelm** [tj/commander.js#205]
I looked through the code and docs but don't understand how to get it to work.
There's a reference to this functionality at [Command.prototype.addImplicitHelpCommand](https://github.com/visionmedia/commander.js/blob/master/index.js#L167)

But the method is marked as private, yet it's never called anywhere.

Either I just don't get it or this is a bug.

**Comment by shadowspawn** [comment]
The two forms supported by default in later versions of Commander are:
```
program help command
program command --help
```
