### ISSUE TITLE
Remove README.md from bundle

### ISSUE THREAD

**Issue by H4ad** [tj/commander.js#2056]
By NPM itself is impossible to remove, `pack` command will always include the `Readme.md` in the bundle, but maybe we can use another tool to pack or just try to reduce the size of the `Readme` by splitting the documentation in another file.

This change can save 25% of the bundle size, from 177kb to 134,7kb, saving up to 4,3TB/week of bandwidth.

**Comment by shadowspawn** [comment]
I have wondered about this sometimes, but the size is reasonably small in the overall scheme of things, and caching can eliminate the download entirely as a global approach. And no one has complained recently. :-)

npm decided long ago to always include the README, I am guessing so available offline, or so always available on the npm package page (or both).

Have you seen other packages that deliberately have a placeholder README for their npm packages?

**Comment by shadowspawn** [comment]
Discussion about npm treatment of README: https://github.com/npm/rfcs/issues/744

**Comment by shadowspawn** [comment]
There wasn't concern expressed by npm folks about README bandwidth in https://github.com/npm/rfcs/issues/744 and the README does get displayed in a number of other contexts. I am subscribed to that issue for updates.

There hasn't been further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
For interest: https://github.blog/changelog/2024-07-09-leaner-npm-packument-metadata-contents/
