### ISSUE TITLE
--no is bugged with default arguments

### ISSUE THREAD

**Issue by Zamiell** [tj/commander.js#2068]
Hello, and thanks for the useful library.

Consider the following program:

```ts
const { program } = require('commander');

program.option('--no-foo', true)
program.option('--no-bar', false)
program.parse();

const options = program.opts();
console.log(options)
```

Running this program will result in the following output:

```
{ foo: true, bar: true }
```

This is a bug, because commander.js is not using the default value that was specified. Specifically, I would expect specifying `true` for the default value of `--no-foo` would mean that `false` should be the default value of `--foo`, which means that the correct output should be:

```
{ foo: false, bar: true }
```

Additionally, I will say that I do not like the special/magic behavior of commander.js to invert my `--no` arguments. It makes for a more confusing code base, *especially* when bugs like the above exist! Is there some way to disable this special/magic behavior?

**Comment by shadowspawn** [comment]
Thanks for the example code. 

You are missing the description argument in your example, so the `true`/`false` are being read as a description and not a default value.

Try:
```
program.option('--no-foo', 'foo description', true)
program.option('--no-bar', 'bar description', false)
```

>  Is there some way to disable this special/magic behavior?

No, it is a built-in feature which can not be disabled.

(I think you can flip the results by specifying both a default value and a preset value, but I suggest it is not worth the effort!)

**Comment by Zamiell** [comment]
Sorry about that. With the following program:

```js
const { program } = require('commander');

program.option('--no-foo', 'foo description', true)
program.option('--no-bar', 'bar description', false)
program.parse();

const options = program.opts();
console.log(options)
```

I get the following output:

```
{ foo: true, bar: false }
```

However, as I said above, this output is a bug, because the following line:

```js
program.option('--no-foo', 'foo description', true)
```

When translated to English, this line means: "By default, we want there to be no foo."
Thus, the output should be:

```
{ foo: false, bar: true }
```

I understand that Commander.js has magic behavior to transform `no-foo` --> `foo`, but this special behavior should also properly flip the default argument as well.

**Comment by shadowspawn** [comment]
> I understand that Commander.js has magic behavior to transform no-foo --> foo, but this special behavior should also properly flip the default argument as well.

Here is another way of describing it. Adding an option with flags `--no-foo` creates an option named `foo`. Specifying a default value sets the starting value of option `foo`, just like with any other option.

I see your interpretation, but it isn't the only interpretation and I don't think is worth considering changing the behaviour. Not least because specifying a default value for a negated option is probably rare.

**Comment by Zamiell** [comment]
Ok, I will close this issue, thank you.

In the future, a way to disable the magic behavior would be welcome, I see that it was also previously requested here: #979
