### ISSUE TITLE
Having the same option multiple times

### ISSUE THREAD

**Issue by timvol** [tj/commander.js#2071]
Hi, is it possible to have the same option multiple times. For example, I've the following command:

`my-script.js set-vars --var="value1" --var="value2" --var="value3" `

In this case, the `--var` option appears multiple times and I've no idea how I can handle this with commander.js. Is this possible and if so, how?

**Comment by shadowspawn** [comment]
By default, options are last-one-wins. To do something different, you can add your own [custom option processing](https://github.com/tj/commander.js#custom-option-processing). In particular, look at the `collect` and `commaSeparatedList` examples in the README as two that might suit your use case.

You could also use a [variadic option](https://github.com/tj/commander.js#variadic-option), but I suggest don't use variadic if you also also have non-option arguments as the parsing can be ambiguous.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
