### ISSUE TITLE
importing `program` type in typescript

### ISSUE THREAD

**Issue by TheMikeyRoss** [tj/commander.js#2086]
I'm passing down `program` in a function and I'm try to infer the type in the args ( i don't want to use `any` and would prefer to use a type for `program`)

```js
const myFunc = (program: any) => {
    const something = program.command("add")
   // the rest of the code
   return something
}
```
and I'm using it like this

```js
import { program } from "commander"
myFunc(program)
```

What can I use instead of `any`?

**Comment by shadowspawn** [comment]
It is a `Command`:

```
import { Command } from "commander"

const myFunc = (program: Command) => {
...
```

**Comment by TheMikeyRoss** [comment]
Awesome! Thanks @shadowspawn 👌
