### ISSUE TITLE
Call to _exit still exits the process, despite registering a callback

### ISSUE THREAD

**Issue by febeling** [tj/commander.js#2092]
Call to _exit still exits the process (e.g. from `process.error`), despite registering a callback via `exitOverride`.

https://github.com/tj/commander.js/blame/f1ae2db8e2da01d6efcbfd59cbf82202f864b0c1/lib/command.js#L459-L465

What was the purpose of #1040?

Is the idea that I register a callback, but I _have_ to throw an error from it?

Why isn't the exit skipped over if there's an override?

**Comment by shadowspawn** [comment]
Commander is not set up to gracefully recover from an error that would normally call `process.exit()`, it expects processing to stop. So the `exitOverride` callback still has to terminate the normal program flow, usually by throwing an error but could also be by calling `process.exit()` with a custom error.

**Comment by febeling** [comment]
Ok. Thanks for the quick response. Fwiw, I didn't understand that from reading the docs of exitOverride.

**Comment by shadowspawn** [comment]
I had a go at making this clearer: #2098

**Comment by febeling** [comment]
That sets expectations clearly. Thanks for addressing the issue!
