### ISSUE TITLE
Capturing Ctrl+C (SIGTERM) in a subcommand

### ISSUE THREAD

**Issue by gvensan** [tj/commander.js#2109]
Hello, This may have been discussed before - I could not find a way for this.

I am not using executable for the subcommand, hence cannot use exitHandler where I can catch the signals at process level. In a classic use of commander, subcommand execution - is there anyway to capture the SIGTERM in order to do some housekeeping work. An example would be of great help.

If this is already answered/resolved, my apologies - please point me to a sample.

**Comment by shadowspawn** [comment]
Not sure about your subcommand setup. Are you using subcommands with action handlers?

**Comment by gvensan** [comment]
Yes, have action handlers. sorry, If I was not clear.

**Comment by shadowspawn** [comment]
Ok, so the action handlers are just running javascript callbacks. Node supports listening for signals. So nothing Commander specific, just the normal signal handling?

```js
const { Command } = require('commander');
const process = require('node:process');

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

const program = new Command();
program.command('sleep')
  .action(async () => {
    await sleep(5000);
  });

process.on('SIGINT', () => {
  console.log('Received SIGINT.');
  // Should we exit here?
});

console.log('Before parse');
program.parseAsync().then(() => {
  console.log('After parse');  
});
```

```console
% node index.js sleep
Before parse
After parse
% node index.js sleep
Before parse
^CReceived SIGINT.
After parse
```

**Comment by gvensan** [comment]
Thank you very much. The snippet helped!

I was running on a older version of commander (npm) and had the experimental warning suppressed as recommended by 
https://github.com/nodejs/node/issues/30810#issuecomment-1433950987
```
const { emit: originalEmit } = process;
process.emit = (event, error) => event === 'warning' && error.name === 'ExperimentalWarning' ? false : originalEmit.apply(process, arguments);

```

I realize now, this is not required as I had upgraded to latest commander verision. This was prevenring the signal handling.

Again, thanks a lot for a quick turn around. Much appreciated!

BTW, Love commander - well structured, friendly and covers all my scenarios.

**Comment by shadowspawn** [comment]
(Thanks for update.)
