### ISSUE TITLE
How to pass key value pairs?

### ISSUE THREAD

**Issue by zzzgit** [tj/commander.js#2118]
```sh
command config foo bar
command config foo2 bar2
```

How do we pass key-value pairs like this?

**Comment by shadowspawn** [comment]
You could parse them as separate key and value arguments, or in a single argument like `key=value` and split them in your code. If you may be passing more than one key/value pair then I suggest `key=value` style so the pairs are clear on the command line.

(Not sure quite what you are wondering about, so ask again with some more info if this does not help.)
