### ISSUE TITLE
Rewrite error message log function

### ISSUE THREAD

**Issue by kolserdav** [tj/commander.js#2126]
Hi, Thanks for your great work!

I have a stylized logger but commander's error messages have an another view,  how can I rewrite error messages?

```sh
error: missing required argument 'name'
```
Maybe you'll could provide a way like this for example:
```javascript
const program = new Command();
program.errorLogHandler((data) => customLogFunction(data));
```

**Comment by kolserdav** [comment]
https://github.com/tj/commander.js/pull/2127

**Comment by shadowspawn** [comment]
There is support for customising the error display using `.configureOutput()` and supplying `writeErr`.

https://github.com/tj/commander.js#override-exit-and-output-handling

-----

You are actually using this as the implementation in the PR. What is the problem with using it directly to achieve your goals?

**Comment by Hugos68** [comment]
@kolserdav I'm trying to overwrite `error: missing required argument <arg>` message but it does not seem to work?

```js
#!/usr/bin/env node
import { program } from 'commander';
import { migrate } from './commands/migrate/index.js';
import { intro, outro, log } from "@clack/prompts";
import {bgBlue, bgGreen, bgRed, black } from 'colorette';

program.name('Skeleton');
program.description('A CLI tool for Skeleton related functionality');
program.addCommand(migrate);


program.configureOutput({
	writeErr(str: string) {
		log.error(str);
	},
	writeOut(str: string) {
		log.info(str);
	}
});

program.exitOverride();

try {
	intro(bgBlue(black(` Skeleton CLI `)));
	program.parse(process.argv);
	outro(bgGreen(black(` Success `)));
} catch (e) {
	console.log(e);
	outro(bgRed(black(` Failed `)));
}
```

Output:

```bash
┌   Skeleton CLI 
error: missing required argument 'migration'
```

The `log.info` should output:
```bash
┌   Skeleton CLI 
│
■  This is an error message
``

**Comment by shadowspawn** [comment]
@Hugos68 

Firstly, If you want to make changes to the program that affect subcommands (Which is normal) then you configure the program before adding the subcommands. 

Secondly, there is an extra step when using `.addCommand()` to copy the settings from the program to the subcommands. 

So your code would look like:
```js
program.configureOutput({ ... });
program.addCommand(migrate);
migrate.copyInheritedSettings(program);
```

**Comment by Hugos68** [comment]
@shadowspawn Thank you! The `migrate.copyInheritedSettings(progam)` fixed what I was struggling with.

**Comment by Hugos68** [comment]
@shadowspawn Is there a place where I can ask about help around Commander? I have a lot of questions about the program, which I can't see to grasp.

**Comment by shadowspawn** [comment]
The main forum for free and community support is the Issues here on this repo.

Help questions are welcome. Keep it to question around one topic per issue.

> I have a lot of questions about the program, which I can't see to grasp.

Hopefully it will make sense quickly after getting answers to a few questions!

**Comment by kolserdav** [comment]
Hi, @Hugos68 I use `program` as an instance of `Command` https://github.com/kolserdav/conhos-cli/blob/1e535633805a9b8da9c9c473fb90e402e695a07e/src/index.js#L47
