### ISSUE TITLE
Double Dash Feature

### ISSUE THREAD

**Issue by lxchurbakov** [tj/commander.js#2139]
Hey guys! I am trying to do something like that:

`npx my-program other-program-or-file-name -- arg1 arg2 --flag 10`

The problem I face is that I expect everything after double dash not to be parsed and just passed to "other-program" as-is just like `npm` does (e.g. `npm jest -- filename` - for `jest` it's process.argv is gonna be `['filename']`).

Do we have a way to replicate that behaviour? If no, is it okay if I try to make a PR for that?

**Comment by shadowspawn** [comment]
Commander has built-in support for `--` to indicate the end of the options, and any remaining arguments will be used without being interpreted.

Alternatively, you may be able to use `.passThroughOptions()` so you don't even need to use the `--`. In your example, this is similar to how npx works.

https://github.com/tj/commander.js#parsing-configuration

**Comment by lxchurbakov** [comment]
Oh yeah, I see! That is fantastic. Do you think it would be nice to separate "the rest" of options from the original list? Looks like currently I get all the args altogether (including `--`) - so I have to manually look for `--` and trim array

**Comment by shadowspawn** [comment]
If you use `.passThroughOptions()` then the user does not need to use the `--`. The arguments after the first one are automatically passed through as normal command-arguments. Try:

```
./index.js file-name --value 10
```

**Comment by lxchurbakov** [comment]
I see, awesome! Only thing is how would I differentiate between my args (if --value is for me) and pass-through options if they come after the command? If I have a flag `--silent` to run that script without attaching it to stdout/stderr, I won't be able to run this like `./index.js filename --silent`? I would expect something like `./index.js filename --silent -- --value 10` to make sense. 

I mean I understand `.passThroughOptions()` and I can achieve the behavior I want, but it kinda looks easier to just do `--` and pass everything else unvalidated to some kind of `program.rest`. Anyway, this is a suggestion and the issue is answered, so I will close it shortly. Thank you for your patience and responsiveness

**Comment by shadowspawn** [comment]
The options before the first argument are parsed as normal, so you would call like:

```
// with passThroughOptions
./index.js --silent filename --value 10
```

But using `--` is fine too! And may be clearer if the syntax of your command does not make it feel natural which option belongs to the program and which gets passed through.
