### ISSUE TITLE
The root `--help` doesn't respect `.usage()` in a command

### ISSUE THREAD

**Issue by samcx** [tj/commander.js#2148]
## Example

```
.usage('[directory] [options]')
```

![CleanShot 2024-02-07 at 17 39 20@2x](https://github.com/tj/commander.js/assets/28912696/b2fe28bd-b3de-4c19-b789-3459208a6144)

Let me know if I'm missing something here!

On the latest version v12.

**Comment by shadowspawn** [comment]
This is historical behaviour (which I am still wondering whether to change).

You can configure the help so the subcommand list displays your custom usage.

Example file: [help-subcommands-usage.js](https://github.com/tj/commander.js/blob/master/examples/help-subcommands-usage.js)

```
program.configureHelp({ subcommandTerm: (cmd) => cmd.name() + ' ' + cmd.usage() });
```

Related: #1853 #1885

**Comment by samcx** [comment]
@shadowspawn Thank you for the confirmation!

Given how things are nicely updated in the root help output (e.g., `description()`) when things are updated in a subcommand), I was expecting it to also change for `usage()`, so maybe it would be a nice change!

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

See also poll in #2268

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.

**Comment by samcx** [comment]
@shadowspawn Will take a look at the poll! Thanks for responding.

**Comment by samcx** [comment]
@shadowspawn Seems like I was late to voting, but casted my vote anyways!
