### ISSUE TITLE
wish: explicitly support input validation

### ISSUE THREAD

**Issue by markstos** [tj/commander.js#215]
I see there is "coercion" now for input parameters, but it's not clear what happens if an invalid value is given that doesn't coerce. 

For example, I have an option named `--format` that I want to restrict to values of `csv` or `json`. 

If the coercion system already serves the purpose, the documentation should be updated to explain what happens when an argument is provided, but it fails to coerce.

**Comment by cirosantilli** [comment]
Keyword: choices like in python argparser choices: https://docs.python.org/3/library/argparse.html#choices

**Comment by shadowspawn** [comment]
Thanks for link @cirosantilli , added to open issue #518
