### ISSUE TITLE
Add support for option to output object 

### ISSUE THREAD

**Issue by j-refs** [tj/commander.js#2155]
Hey y'all. Been trying to find out if this is possible and came up empty.handed. What I'd like more or less is to pass options like:
`node program.js --obj[key]=value`
And have `options` contain:

```

{
    obj: {
        key: "value"
    }
}

```

Is this currently possible? And if not, how possible would it be to implement?

It would benefit by allowing config objects to be built automatically and also simplify usage by reducing the overall number of options that need to be parsed. Small example of how I can see this benefiting:

```

//Instead of 
node cli.js backup --sqlite-path=/path/to/db --sqlite-timeout=1000 --sqlite-verbose
//And ending up with
{ 
    sqlite-path: "/path/to/db",
    sqlite-timeout: 1000,
    sqlite-verbose: true
} 
// That you then also have to process again
//You could simply have
node cli.js backup --sqlite[path]=/path/to/db --sqlite[timeout]=1000 --sqlite[verbose]
//And have nicely
{
    sqlite: {
        path: "/path/to/db",
        timeout: 1000,
        verbose: true
    }
}

```

**Comment by shadowspawn** [comment]
Basically, probably not.

I wonder if it might mostly work on the implementation end by hacking `getOptionValue()` and `setOptionValue()`.

However, I think a practical obstacle for the end-user is that the brackets are interpreted by some shells as a pattern match, so you can't supply the command-line options in this form without extra work:

```sh
% echo --obj
--obj
~ % echo --obj[key]
zsh: no matches found: --obj[key]
% ls -d D[oa]cuments
Documents
% echo '--obj[key]'   
--obj[key]
```

**Comment by shadowspawn** [comment]
Some other packages allow `--obj.key=value` syntax for this use case.

**Comment by j-refs** [comment]
@shadowspawn  ahh, completely forgot about that (don't do shell scripting much 😅)

I just checked if mine allowed it (bash 5.2.15) and it does, so maybe it can be hidden behind an option as an opt in feature?

I'd be super down to help you implement that feature!

Also, p.s. I know there's others that have that format, but I like your package! I don't wanna switch just for that lil feature😅 (also just like brackets better than dot 😣😁)

**Comment by shadowspawn** [comment]
A quick hack of the sort I had in mind:

```js
import { Command } from 'commander';

class MyCommand extends Command {
  createCommand(name, description) {
    return new MyCommand(name, description);
  }

  setOptionValueWithSource(key, value, source) {
    const objectExpr = /^([^[]*)\[([^[]+)\]$/;
    let match;
    if (match = key.match(objectExpr)) {
      const objKey = match[1];
      const prop = match[2];
      const obj = this.getOptionValue(objKey) ?? {};
      obj[prop] = value;
      super.setOptionValueWithSource(objKey, obj, source);
    }
    
    return super.setOptionValueWithSource(key, value, source);
  }
}

const program = new MyCommand();

program.option('-s, --sqlite[path] [path]', 'sqlite database path')
program.option('-v, sqlite[verbose]', 'verbose diagnostics')

program.parse();
console.log(program.opts());
```

```
% node custom.mjs '--sqlite[path]=/path/to/db' -v
{
  sqlite: { path: '/path/to/db', verbose: true },
  'sqlite[path]': '/path/to/db',
  'sqlite[verbose]': true
}
```

**Comment by j-refs** [comment]
That'll actually work pretty good for my case. I really just didn't wanna have to copy a parser into every option or have to post process everything 😅

**Comment by shadowspawn** [comment]
An answer was provided, and "good enough". Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by j-refs** [comment]
@shadowspawn much appreciated!
