### ISSUE TITLE
Compatible with deno

### ISSUE THREAD

**Issue by tch1121** [tj/commander.js#2165]
Don't ignore the first two argv

```js
program.parse(Deno.args);
```

I now use it like this

```js
program.parse(["null", "null", ...Deno.args]);
```

**Comment by shadowspawn** [comment]
Deno have done a great job of filling out node compatibility so Commander works out of the box.

I found three approaches you might use:

1) the modern Commander way, leave it to Commander (and the Deno node compatibility):

```ts
program.parse();
```

2) if you want to use `Deno.args` then `.parse()` supports a second parameter to indicate the argument conventions:

```ts
program.parse(Deno.args, { from: 'user' });
```

3) or you could use the compatibility layer explicitly

```ts
import * as process from 'node:process';
program.parse(process.argv);
```

**Comment by tch1121** [comment]
thank you for your work
