### ISSUE TITLE
When use .command("dtsgen <files>")，this params files in macOS and Windows is errors caused by differences

### ISSUE THREAD

**Issue by maxiaoqu** [tj/commander.js#2184]
this is my code
```
#!/usr/bin/env node
import path from "path";
import fs from "fs-extra";
import {Command} from "commander";

const program: Command = new Command();

const PackageString = fs.readFileSync(
  path.resolve(__dirname, "../package.json"),
  "utf8"
);
const PackageData: any = JSON.parse(PackageString);

program
  .version(PackageData.version)
  .name("ibuild")
  .usage("command [options]");

program
  .command("dtsgen <files>")
  .description("为.vue文件生成.d.ts文件")
  .option("-o, --outDir <direname>", "Specify an output folder for all emitted files")
  .action((files: string, options: any) => {
    dtsgen(files, options);
  });

program.parse(process.argv);
```

No1、when i use ibuild in my project package.json is 
```
 "scripts": {
    "build:dtsgen": "ibuild dtsgen 'src/**/*.{ts,tsx}' -o types"
  }
```

when i use macOS，at .command("dtsgen <files>") [dtsgen(files, options);], this files is 'src/**/*.{ts,tsx}'   (this is ok)
when i use Windows, at .command("dtsgen <files>") [dtsgen(files, options);], this files is "'src/**/*.{ts,tsx}'"  (this is fail)

No2、and whe my project package.json is 
```
 "scripts": {
    "build:dtsgen": "ibuild dtsgen src/**/*.{ts,tsx} -o types"
  }
```
when i use macOS，at .command("dtsgen <files>")  [dtsgen(files, options);] , this files is 'src/common/api.ts'   (this is fail) \ 'src/common/api.ts' is my project first file;
when i use Windows, at  .command("dtsgen <files>") [dtsgen(files, options);], this files is "src/**/*.{ts,tsx}"  (this is ok)

this is debugger img!

![WX20240415-151536@2x](https://github.com/tj/commander.js/assets/25891598/d79287f3-159d-4147-a212-d472036a49b8)
![WX20240415-151641@2x](https://github.com/tj/commander.js/assets/25891598/d6e6c406-0a52-4481-ad1c-5be766887fce)
![WX20240415-151914@2x](https://github.com/tj/commander.js/assets/25891598/8f4e8ac6-a5d8-4a5f-bf26-c42e05b9c1f6)
![WX20240415-152008@2x](https://github.com/tj/commander.js/assets/25891598/62271ce6-6bf5-473d-9a5b-2e5123928130)

**Comment by shadowspawn** [comment]
Commander is not doing any interpretation of the file pattern you are trying to pass in. That is happening in the shell used by `npm run`. 

> The actual shell your script is run within is platform dependent. By default, on Unix-like systems it is the `/bin/sh` command, on Windows it is `cmd.exe`. 

https://docs.npmjs.com/cli/v10/commands/npm-run-script

**Comment by shadowspawn** [comment]
Try using double quotes to surround the pattern and protect it from the shell. I think that might work in both (I don't have Windows available to check at the moment).

```
"scripts": {
    "build:dtsgen": "ibuild dtsgen \"src/**/*.{ts,tsx}\" -o types"
  }
```

**Comment by maxiaoqu** [comment]
> 尝试使用双引号将模式括起来并保护它免受 shell 的影响。我认为这可能对两者都有效（我目前没有可用的 Windows 来检查）。
> 
> ```
> "scripts": {
>     "build:dtsgen": "ibuild dtsgen \"src/**/*.{ts,tsx}\" -o types"
>   }
> ```

The solution solved my problem for now, thank you.
