### ISSUE TITLE
how to use the ESM module to import and export ?

### ISSUE THREAD

**Issue by chen-ziwen** [tj/commander.js#2186]
How to use the ESM module to import and export

**Comment by shadowspawn** [comment]
Do you want to import Commander from esm? This is covered in the README:

```javascript
// ECMAScript (.mjs)
import { Command } from 'commander';
const program = new Command();
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
