### ISSUE TITLE
Is it possible for an option to conflict with an argument? 

### ISSUE THREAD

**Issue by muttonchop** [tj/commander.js#2194]
I tried using `.conflicts` for an option that is incompatible with an optional argument, but I am not getting the kind of error I would expect. Is this something that is currently supported?

```
const program = new Command();
program
    .command('example')
    .addArgument(new Argument('[optional]', 'Optional argument'))
    .addOption(new Option('--conflict', 'conflicts with optional').conflicts('optional'))
```

**Comment by shadowspawn** [comment]
Thanks for the example code.

No, that is not currently supported. `.conflicts()` works with options and not arguments.

**Comment by muttonchop** [comment]
Two followup questions:

1. Is this something that could added as a new feature?
2. What would be the best way to handle this behavior currently?

```typescript
const program = new Command();
program
    .command('example')
    .addArgument(new Argument('[optional]', 'Optional argument'))
    .addOption(new Option('--conflict', 'conflicts with optional').conflicts('optional'))
    .action((optional, options) => {
        if(optional && options.conflict){
            // how to make this behave like the existing .conflicts() behavior.
        }
    });
```

**Comment by shadowspawn** [comment]
> 1. Is this something that could added as a new feature?

Doubtful. I suspect it would be quite a bit of work to do properly. In particular, the command-arguments are not currently known or referenced by "name".

**Comment by shadowspawn** [comment]
> 2. What would be the best way to handle this behavior currently?

One approach could be to move the optional argument into an option. Then you can use `Option.conflicts()`. Whether that makes sense in your CLI depends on how the two values are normally used.

> `// how to make this behave like the existing .conflicts() behavior.`

For rolling your own checks, there is support for generating errors using Commander with `cmd.error()`.

```js
program
    .command('example')
    .addArgument(new Argument('[optional]', 'Optional argument'))
    .addOption(new Option('--conflict', 'conflicts with another-option').conflicts('anotherOption'))
    .addOption(new Option('--another-option'))
    .action((optional, options) => {
        if(optional && options.conflict) {
            program.error("error: option '--conflict' cannot be used with argument 'optional'");
        }
        console.log("Called command 'example'");
    });
```

```console
% node index.js example                             
Called command 'example'
% node index.js example --conflict --another-option 
error: option '--conflict' cannot be used with option '--another-option'
% node index.js example --conflict optional-argument
error: option '--conflict' cannot be used with argument 'optional'
```

**Comment by muttonchop** [comment]
That solution works well for me, thanks!
