### ISSUE TITLE
Action not exiting when using nodejs streams

### ISSUE THREAD

**Issue by Ivor808** [tj/commander.js#2198]
Hey all,

Scenario: I am reading and writing via the streams api. However, the action handler doesn't exit even if both streams are destroyed/closed. It seems to hang indefinitely unless we force call process.close. The below code is wrapped in a command action.

```js
    const readStream =
      await sourceSql`COPY (select * from test) to stdout WITH (FORMAT CSV, NULL "NULL", HEADER)`.readable();
    const writeStream = await createWriteStream(
      `${os.homedir()}/cms/${testname}`
    );
    pipeline(readStream, writeStream);
    readStream.destroy();
    writeStream.close(() => {
      console.log('done');
      console.log(writeStream.destroyed);
    });
```

**Comment by Ivor808** [comment]
Moving the stream function out of the command.action exits properly. So there is some issue with using streams in the command.action flow it seems.

**Comment by Ivor808** [comment]
Turns out the postgres js client has to be manually closed down.

**Comment by shadowspawn** [comment]
One tip: are you calling `program.parseAsync()` rather than `program.parse()` since you have an async action handler?
