### ISSUE TITLE
Help option disappears when configuring visible options

### ISSUE THREAD

**Issue by Taib-Rabah** [tj/commander.js#2206]
What I'm trying to achieve is to hide the negated options: `--no-test` in this example, and it worked, but the help option disappears as a result.

Before Code:

```js
import { Command } from "commander";

const program = new Command().name("my-cli").version("0.0.0", "-v, --version");

program
   .command("test")
   .option("--test")
   .option("--no-test")
   .action(() => {
      console.log("I said test!");
   });

program.parse(process.argv);
```

As you can see, the help option is present in the output:

```
Usage: my-cli [options] [command]

Options:
  -v, --version   output the version number
  -h, --help      display help for command

Commands:
  test [options]
  help [command]  display help for command
```

However, when I hide the negated options:

```js
const program = new Command()
   .name("my-cli")
   .version("0.0.0", "-v, --version")
   .configureHelp({
      visibleOptions: (cmd) => cmd.options.filter((opt) => !opt.negate),
   });
```

and run it again, the help option disappears:

```
Usage: my-cli [options] [command]

Options:
  -v, --version   output the version number

Commands:
  test [options]
  help [command]  display help for command
```

Notes:

- The help option can still be used, it's just not printed in the help message.
- I used the main program to configure the visible options so they apply to all commands recursively.

**Comment by shadowspawn** [comment]
Thanks for example code and clear explanation.

The problem is the built-in help option is not in `cmd.options` and gets added into the visible options in the base implementation.

An easy change for a simple setup could be to use the unmodified Help class to do the initial work:

```js
import { Command, Help } from "commander";

...

   .configureHelp({
      visibleOptions: (cmd) => new Help().visibleOptions(cmd).filter((opt) => !opt.negate),
   });

```

A more complete solution, but more code, would be to subclass the Help class (to remove the negated options) or the Option class (to make the negated options hidden). The Help subclass is close to your example, so I'll show that: 

```js
import { Command, Help } from "commander";

class MyHelp extends Help {
  visibleOptions(cmd) {
    return super.visibleOptions(cmd).filter((opt) => !opt.negate);
  }
}

class MyCommand extends Command {
  createCommand(name) {
    return new MyCommand(name);
  }
  createHelp() {
    return new MyHelp();
  }
}

const program = new MyCommand("my-cli").version("0.0.0", "-v, --version");

program
   .command("test")
   .option("--test")
   .option("--no-test")
   .action(() => {
      console.log("I said test!");
   });

program.parse(process.argv);

```

(Ask if you would like to see an Option subclass example too.)

**Comment by Taib-Rabah** [comment]
Yes, I’d like to see an Option subclass example too. Ty for your time

**Comment by Taib-Rabah** [comment]
> (Ask if you would like to see an Option subclass example too.)

Yes, I’d like to see an Option subclass example too. Ty for your time

**Comment by Taib-Rabah** [comment]
> A more complete solution, but more code, would be to subclass the Help class (to remove the negated options) or the Option class (to make the negated options hidden). The Help subclass is close to your example, so I'll show that:

I'm just wondering, if they give the same result, why would I choose the more complete solution?

**Comment by Taib-Rabah** [comment]
I tried the subclass solution and it worked but it can't be overridden with `.configureHelp()` function

My implementation for the subclass (Same as yours but with different names)

```js
import {
   Command as CommanderCommand,
   Help as CommanderHelp,
   Option,
} from "commander";

class Help extends CommanderHelp {
   visibleOptions(cmd: CommanderCommand): Option[] {
      return super.visibleOptions(cmd).filter((opt) => !opt.negate);
   }
}

class Command extends CommanderCommand {
   createCommand(name?: string): CommanderCommand {
      return new Command(name);
   }
   createHelp(): CommanderHelp {
      return new Help();
   }
}
```

Now, when I create a command and hide all its options like this:

```js
const program = new Command().name("my-cli").version("1.0.0", "-v, --version");

program
   .command("foo")
   .option("--bar")
   .configureHelp({
      visibleOptions: () => [], // hide all options
   });

program.parse(process.argv);
```

The output is still the same as defined in the `Help` subclass:

```
Usage: my-cli foo [options]

Options:
  --bar
  -h, --help  display help for command
```

In the other hand, when I tried the simpler solution:

```js
import { Command, Help } from "commander";

const program = new Command()
   .name("my-cli")
   .version("1.0.0", "-v, --version")
   .configureHelp({
      visibleOptions: (cmd) =>
         new Help().visibleOptions(cmd).filter((opt) => !opt.negate),
   });

program
   .command("foo")
   .option("--bar")
   .configureHelp({
      visibleOptions: () => [], // hide all options
   });

program.parse(process.argv);
```

The options are successfully hidden from the output:

```
Usage: my-cli foo [options]
```

For now, I'm going to stick with the simpler solution.
And thank you for your time

**Comment by shadowspawn** [comment]
> I tried the subclass solution and it worked but it can't be overridden with `.configureHelp()` function

I wondered whether to include the full implementation in my example, I chose wrong! This is what you need to still support `.configureHelp()` too:

```diff
  createHelp() {
-    return new MyHelp();
+    return Object.assign(new MyHelp(), this.configureHelp());
  }
```

**Comment by shadowspawn** [comment]
And for interest, here is same pattern but subclassing Option rather than Help. 

```js
import { Command, Option } from "commander";

class MyOption extends Option {
  constructor(flags, description) {
    super(flags, description);
    this.hidden = this.negate; // Hide negated options in help by default.
  }
}

class MyCommand extends Command {
  createCommand(name) {
    return new MyCommand(name);
  }
  createOption(flags, description) {
    return new MyOption(flags, description)
  }
}

const program = new MyCommand("my-cli").version("0.0.0", "-v, --version");
```
