### ISSUE TITLE
Issue running on Linux

### ISSUE THREAD

**Issue by sorinmarta** [tj/commander.js#2215]
Hi there,

I'm trying to run a script that I wrote using this package on a Ubuntu server.

Everything works as expected when I run the script on my Mac or Windows machines, however, when I run the same code on an Ubuntu server I get the following error.

```bash
/path/to/project/node_modules/commander/lib/command.js:396
    enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/path/to/project/node_modules/commander/index.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I'm running the same Node version on both machines. `v20.14.0`

Any ideas why?

**Comment by shadowspawn** [comment]
The most likely answer is you are running an older version of node on Ubuntu, despite you mentioning v20.14.0. 😅 

You can check where node is installed and the version with:
```
 % command -v node
/usr/local/bin/node
~ % node --version
v20.15.0
```

How are you launching node, what are you typing on the command-line?

**Comment by sorinmarta** [comment]
I made sure I'm on the version I mentioned before adding the Issue 😅

I use NVM and the default version was `v20.14.0`. I changed it to `v20.15.0` to see if that changes anything.

Here is what `node --version` returns:
<img width="469" alt="Screenshot 2024-06-28 at 12 40 54" src="https://github.com/tj/commander.js/assets/41399704/77c236eb-d6a0-4cd6-a763-953dd637bb81">

And the way I launch is through the default `node index command etc`

**Comment by shadowspawn** [comment]
`nvm` modifies the path in the shell to change what version of node is found. When running the script and it fails, are you running it directly from an interactive shell, or from some other context? As an example, cron jobs run with quite a different context. (I am a bit stumped.)

**Comment by sorinmarta** [comment]
Thanks for the context tip! 

It seems like the server also had Node 14 installed with `apt-get`. I was running node as `sudo` (because it's a local VM in which I run experiments 😁).

It turns out that if I run node with `sudo` it uses the one installed by `apt-get` and not the one that NVM installed.

So I'll have to sort the permissions so that I can run it without sudo and that will probably fix it.

**Comment by sorinmarta** [comment]
Yes, fixing the permissions so that I can run the script without `sudo` fixed it.

So the problem was that I was running Node with `sudo` and that was not using the version set by NVM.

Thanks a lot for helping me @shadowspawn!

**Comment by shadowspawn** [comment]
Thanks for update.

Related, you can "preserve" environment variables like `PATH` when you run commands with `sudo` using `-E` (`--preserve-env`).

```
sudo -E node --version
```
