### ISSUE TITLE
Options are not parsed on wildcard command

### ISSUE THREAD

**Issue by tandrewnichols** [tj/commander.js#222]
If I do something like:

``` javascript
program.name = 'demo';

program
  .command('*')
  .option('-f --foo', 'Do foo')
  .option('-b --bar', 'Do bar')
  .option('-q --quux', 'Do quux', [])
  .action(function() {
    console.log(arguments);
  });
```

And call it with `demo blah -f`, the log shows that argument 0 is "blah" (correctly) and argument 1 is options, or, I should say, an option-like object. It has all the normal stuff the option hash has, but doesn't parse the command line options. That is to say, `options.quux` WILL equal `[]`, but `options.foo` will not exist.

Maybe that's intentional and the wildcard command is not meant to accept options, but in that case, I would expect 1) that `quux` would not be populated, and/or 2) that some sort of warning would be generated. On the other hand, if wildcard IS supposed to support options, then I would expect `foo` and `bar` to work like normal.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
