### ISSUE TITLE
[Feature request] More than 2 flags per option / case-insensitive flags

### ISSUE THREAD

**Issue by KaKi87** [tj/commander.js#2222]
Hi,

I'm trying to add a `-f, -F, --foo` option, but when doing so, the first two flags are passed as `options.F` and the last one is ignored.

So, it seems that `option()` only supports up to 2 flags.

Therefore, I would like to request being able to either specify any number of flags, or optionally mark flags as case-insensitive.

Thanks

**Comment by shadowspawn** [comment]
Having more than 1 short and 1 long flag does come up very occasionally: #1862

This is not something I want to add to Commander. 

For an extra flag, you could perhaps add a hidden option which sets the "real" option value when used.

For case insensitive, you could perhaps subclass the Option class to change how options are matched

```js
import { Command, Option } from 'commander';

class MyOption extends Option {
  is(arg) {
    return this.short?.toLowerCase() === arg.toLowerCase() || this.long === arg;
  }
}

class MyCommand extends Command {
  createOption(flags, description) {
    return new MyOption(flags, description);
  }
  createCommand(name) {
    return new MyCommand(name);
  }
}


const program = new MyCommand();
program.option('-f, --foo', 'enable some foo');
program.parse();

console.log(program.opts());
```

```console
% node index.mjs -f
{ foo: true }
% node index.mjs -F
{ foo: true }
```

**Comment by KaKi87** [comment]
> This is not something I want to add to Commander.

Why not ?

> For an extra flag, you could perhaps add a hidden option

Okay, for anyone else interested, here's a workaround :

```js
.option('-f, -F, --foo')
.addOption(new Option('--foo').hideHelp())
.action(options => {
    if(options.F || options.foo){}
});
```

> For an extra flag, you could perhaps add a hidden option

So you wouldn't want to implement case insensitivity either ? If no, why ?

Thanks.

cc. @mitsukuri

**Comment by shadowspawn** [comment]
> Why not?

Basically, I don't think it is useful enough or commonly used enough to add to Commander.

I leave enhancement requests open for six months to see if they get upvotes or further comments. So there is a chance for other people to show interest with upvotes or comments, and make a case for the feature.

Why do you think it should be added?

- What is your use case? 
- Do you see more than two flags or case-insensitive flags in common tools you use? 
- Do you see support in other parsing libraries?

**Comment by shadowspawn** [comment]
> For an extra flag, you could perhaps add a hidden option

 I had this approach in mind.

```js
const fooOption = new Option('-f, --foo', 'enable some foo');
const extraFooFlag = new Option('-F').hideHelp();
fooOption.flags = '-f, -F, --foo'; // to show extra flag in help and error messages
program
   .addOption(fooOption)
   .addOption(extraFooFlag)
   .on('option:F', () => program.setOptionValue('foo', true));
```

-----

```
.option('-f, -F, --foo')
.addOption(new Option('--foo').hideHelp())
```

> That said, I would argue that if option() only handles 2 flags, then it should treat this as invalid, even though it means ruining this 😅

Yes, I have been thinking about adding an error for unsupported flags! 😁

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month.

I have opened an issue to make more than 2 flags an error: #2235

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by KaKi87** [comment]
Hi,

I upgraded commander.js during a refactor today, and used your approach for displaying the options, though I kept my initial `if`-based workaround in `action` :

```js
program
    .addOption((() => {
        const option = new Option('-f, --foo', 'Foo');
        option.flags = '-f, -F, --foo';
        return option;
    })())
    .addOption(new Option('-F').hideHelp())
    .action(options => {
        if(options.F || options.foo){}
    });
```

I'm just posting this here for anyone interested.
