### ISSUE TITLE
Better TypeScript typings

### ISSUE THREAD

**Issue by segevfiner** [tj/commander.js#2225]
Using some advanced TypeScript type expressions, it might be possible to correctly type the parameters to the `action` callback, and options on the `command` object, like the `@types/yargs` package tries to do for `yargs`, though it is quite complex to do so, it would improve the usage with TypeScript quite a bit.

**Comment by shadowspawn** [comment]
Possible, and complex, and done.

From the README:

> extra-typings: There is an optional project to infer extra type information from the option and argument definitions. This adds strong typing to the options returned by `.opts()` and the parameters to `.action()`. See [commander-js/extra-typings](https://github.com/commander-js/extra-typings) for more.

```ts
import { Command } from '@commander-js/extra-typings';
```

**Comment by segevfiner** [comment]
Oh cool. Missed that. Will try it.
