### ISSUE TITLE
Bug in regex for lone short flag

### ISSUE THREAD

**Issue by sorawee** [tj/commander.js#2227]
https://github.com/tj/commander.js/pull/1256 added a support for lone short flag.

Unfortunately, this only works correctly on short flags with one character. Short flags with multiple characters (Java-style short flags) will incorrectly create incorrect field names. For example, `.option('-name')` will result in a field `Name`, which is not in camelCase.

The reason is that [this regex](https://github.com/tj/commander.js/blob/970ecae402b253de691e6a9066fea22f38fe7431/lib/option.js#L322) only matches a short flag with one character. This means a short flag with multiple characters will be categorized as a long flag. Consequently, Commander.js attempts to strip `--` from `-name`, which is a no-op, resulting in `-name`. Then, the camel case conversion of `-name` results in `Name`, which is not a camel case as intended.

**Comment by shadowspawn** [comment]
Short flags with more than one character are not supported. Short flags are a dash followed by a single character. See #2211 for more details.

(Feel free to ask if you have more questions.)

**Comment by sorawee** [comment]
Thanks @shadowspawn! That makes sense. But if Java-style short flags are intentionally not supported, shouldn't `.option('-name')` result in an error to let users know that it is not supported? I think we agree than categorizing `-name` as a long flag should not happen, right?

**Comment by shadowspawn** [comment]
Closing in favour of #2235, adding an error for short flag longer than one character

**Comment by shadowspawn** [comment]
FYI, there is a recent issue asking to allow multiple character short options: #2307
