### ISSUE TITLE
Example from `README.md` does not work when using `npm run start`

### ISSUE THREAD

**Issue by wojtekKrol** [tj/commander.js#2228]
Hi, I'm using windows and example from readme does not work as expected, same in sandbox

![image](https://github.com/user-attachments/assets/1e8ed87c-a12f-4e5b-91f8-bb2838b5183e)
![image](https://github.com/user-attachments/assets/d61894a5-c871-4caf-8d1a-fa80a1101a45)

https://codesandbox.io/p/live/6fbd7a8b-cd25-4b8f-bca2-c9d71863a471

**Comment by shadowspawn** [comment]
What is happening is that `npm` is processing and removing the `--separator` before node and Commander get a chance to see them.

You can see this happening your example. You typed:
```
npm run start split a/b/c -- separator=/
```

but what actually got run was:
```
node index-js split a/b/c
```

This traps people so often there is a special section in the README: https://github.com/tj/commander.js?tab=readme-ov-file#npm-run-script

Try:
```
