### ISSUE TITLE
[Bug] Wrong types for defaultValue

### ISSUE THREAD

**Issue by Sadzurami** [tj/commander.js#2236]
Example:
```ts
import { program } from 'commander';
program.option('-n, --num', 'test num value', 10)
```

Result:
```sh
No overload matches this call.
  Overload 1 of 3, '(flags: string, description?: string, defaultValue?: string | boolean | string[]): Command', gave the following error.
    Argument of type '10' is not assignable to parameter of type 'string | boolean | string[]'.
  Overload 2 of 3, '(flags: string, description: string, parseArg: (value: string, previous: unknown) => unknown, defaultValue?: unknown): Command', gave the following error.
    Argument of type 'number' is not assignable to parameter of type '(value: string, previous: unknown) => unknown'.
  Overload 3 of 3, '(flags: string, description: string, regexp: RegExp, defaultValue?: string | boolean | string[]): Command', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'RegExp'.
```

**Comment by shadowspawn** [comment]
The TypeScript types are deliberately stricter than the JavaScript implementation to help guide users to safer patterns by default. In this case if this was silently allowed, you would have your option being a `number` if it came from the default and a `string` if from the parsed arguments.

See #1792

**Comment by shadowspawn** [comment]
The Pull Request that removed multiple uses of `any` including for the `.option()` default value: #1119

**Comment by shadowspawn** [comment]
In many cases, you can get the type you want _and_ strict types by also specifying a custom [option processing function](https://github.com/tj/commander.js?tab=readme-ov-file#custom-option-processing).

If that isn't a match for what you want you can also use the `Option` class directly and it allows any type in the `.default()` call:

```
.addOption(new Option('-n, --num <value>', 'test num value').default(10));
```
