### ISSUE TITLE
Did not work with MiniDsp 4x8 at all on Raspberry Pi 4

### ISSUE THREAD

**Issue by DrCWO** [tj/commander.js#2239]
This is what I see in the Plugin:
![image](https://github.com/user-attachments/assets/f542fa21-440f-4fde-a7c9-ff10ad67e406)

I did this on Raspbebry Pi 4 with DietPi:
```
su 
<password>
uname -a
Linux rooExtend 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux

wget -q https://github.com/mrene/minidsp-rs/releases/download/v0.1.9/minidsp_0.1.9_arm64.deb
apt install ./minidsp_0.1.9_arm64.deb

minidsp
Error: No devices found
```
After a reboot of the Pi:
```
minidsp probe

minidsp
Error: No devices found
```

I see this with `lsusb`
`Bus 001 Device 010: ID 04d8:003f Microchip Technology, Inc. miniSHARC v1.0b`

I believe the physical connection is fine as with the elder `minidsp.js` I was able to set the gain after changing 
```
	USB_VID: 0x04d8,
	USB_PID: 0x003f,
```
in `constants.js`.

Service is running...
```
ps -ef | grep minidsp
root         462       1  0 18:29 ?        00:00:03 /usr/bin/minidspd --config /etc/minidsp/config.toml
```

Help would be appreciated.

**Comment by shadowspawn** [comment]
I think you posted this in the wrong project.

**Comment by DrCWO** [comment]
Uuuuh, two open Guthub windows and I got the wrong one.
If you can please delete...
