### ISSUE TITLE
Enhancement: allow arguments/options to have their own sub-options. 

### ISSUE THREAD

**Issue by aramando** [tj/commander.js#2245]
It would be useful to be able to use a syntax like this, where options can be separated by and associated with or belong to the last argument they were passed in after, to make them options to arguments, or sub-options to options:

`scripts.js path1 --exclude path1SubDir1 --exclude path1SubDir2 path2 --exclude path2SubDir`
or 
`scripts.js --path path1 --exclude path1SubDir1 path1SubDir2 --path path2 --exclude path2SubDir`

The only way I can currently see to implement this is to use custom parser functions to react to arguments/options in the order they are parsed to construct a custom options object, which feels clunky. Furthermore, I notice this won't work with the former syntax, combining arguments and options, because all options are processed before all arguments, regardless of their order in the command being parsed.

**Comment by shadowspawn** [comment]
As you noted, the options get processed before the arguments, so the example won't work with current parsing.

Have you seen this supported in a utility you use?

You could achieve something functionally similar with a custom syntax like:
```
scripts.js --path path1:!path1SubDir1,path1SubDir2 --path path2:!path2SubDir
scripts.js path1:!path1SubDir1,path1SubDir2 path2:!path2SubDir
```

I think you could roll your own support using custom option processing for the option syntax example. When you process `--exclude` you can look at the last entry in `--path` to work out what it should be attached to.
```
scripts.js --path path1 --exclude path1SubDir1 path1SubDir2 --path path2 --exclude path2SubDir
```

**Comment by aramando** [comment]
I admit I didn't submit this with a particularly amazing idea in mind of how it could be supported! But Node's own `parseArgs` utility usefully offers a tokenised form of the command that can be used for custom parsing where the order is important:

```js
 {
  "values": {
    "include": [
      "include1",
      "include2"
    ]
  },
  "positionals": [
    "/path",
    "/another-path"
  ],
  "tokens": [
    {
      "kind": "positional",
      "index": 0,
      "value": "/path"
    },
    {
      "kind": "option",
      "name": "include",
      "rawName": "--include",
      "index": 1,
      "value": "include1",
      "inlineValue": false
    },
    {
      "kind": "option",
      "name": "include",
      "rawName": "--include",
      "index": 3,
      "value": "include2",
      "inlineValue": false
    },
    {
      "kind": "positional",
      "index": 5,
      "value": "/another-path"
    }
  ]
}
```

This would be an improvement for my use case is it would enable me to use a combination of arguments and options rather than only options, and obviate the need to press custom argument/option parser functions into what feels a little like misuse!

That said, I like your suggestion of just using a custom syntax within each `path` option (or even argument) and will probably proceed that way on this project.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
