### ISSUE TITLE
Boolean option does not reset between parse() and parseAsync() calls

### ISSUE THREAD

**Issue by edmsamuel** [tj/commander.js#2247]
### Español:
**Descripción del Problema:**
Al usar `commander.js`, la opción booleana `--json` no se restablece correctamente cuando se analiza varias veces. En el siguiente ejemplo, la opción `--json` se mantiene en `true` después de que se establece, incluso cuando no se pasa en la siguiente llamada a `parse`. Esto causa un comportamiento inesperado, ya que la opción debería restablecerse a `false` si no se incluye en la entrada.

**Código de ejemplo:**
```javascript
const { Command, createCommand } = require('commander');
const program = createCommand();

const tmp = program
  .option('--json', 'output extra debugging', false)
  .action(options => console.log(options));

const r1 = program.parse(["node", "app.js"]);
const r2 = program.parse(["node", "app.js", "--json"]);
const r3 = program.parse(["node", "app.js"]);
```

**Salida esperada:**
```javascript
{ json: false }
{ json: true }
{ json: false }
```

**Salida actual:**
```javascript
{ json: false }
{ json: true }
{ json: true }
```

**Comportamiento esperado:**
La opción `--json` debería ser `false` en la última llamada a `parse`, pero se mantiene en `true`, lo que indica que no se restablece correctamente entre llamadas.

### Inglés:
**Problem Description:**
When using `commander.js`, the boolean option `--json` does not reset correctly when parsing multiple times. In the following example, the `--json` option remains `true` after it is set, even when it is not passed in the subsequent `parse` call. This leads to unexpected behavior, as the option should reset to `false` if not included in the input.

**Example Code:**
```javascript
const { Command, createCommand } = require('commander');
const program = createCommand();

const tmp = program
  .option('--json', 'output extra debugging', false)
  .action(options => console.log(options));

const r1 = program.parse(["node", "app.js"]);
const r2 = program.parse(["node", "app.js", "--json"]);
const r3 = program.parse(["node", "app.js"]);
```

**Expected Output:**
```javascript
{ json: false }
{ json: true }
{ json: false }
```

**Actual Output:**
```javascript
{ json: false }
{ json: true }
{ json: true }
```

**Expected Behavior:**
The `--json` option should be `false` in the final `parse` call, but it remains `true`, indicating that it is not resetting properly between calls.

---

### Evidencia / Evidence

![image](https://github.com/user-attachments/assets/d8fe70c8-0a04-4d44-bd2a-00ece42195b8)

**Comment by shadowspawn** [comment]
Thanks for the clear description.

Commander does not support calling parse multiple times. The intended approach is you create a fresh program for each call.

See https://github.com/tj/commander.js/pull/2036 for some background and past issues.

Also with the last 12 hours, someone else hit same issue! #2246

**Comment by edmsamuel** [comment]
Thank you for the clarification. I wasn't aware that Commander doesn't support multiple calls to `parse`. 🫣 I will definitely use a fresh program instance for each call going forward. Appreciate the guidance and reference to the related issues. 🖖🏽

**Comment by shadowspawn** [comment]
Opened a PR to allow multiple calls to `.parse()`: #2299

**Comment by shadowspawn** [comment]
Support for multiple parse added in version 13.0.0
