### ISSUE TITLE
How to specify that an option can be repeated but must use the option flag for each value?

### ISSUE THREAD

**Issue by twilson90** [tj/commander.js#2265]
`node index.js -m 1 -m 2 -m 3`
When parsed should be:
`{m: ['1','2','3']}`

But I don't want to be able to parse the following and see the same result:
`node index.js -m 1 2 3`

To my mind the 2 and 3 look more like positional arguments and it's counter-intuitive.

(maybe I've been using argparse too long.)

Is there any way to enforce this?

**Comment by shadowspawn** [comment]
The default parsing in Commander agrees with you about positional arguments. Options only take multiple values if you make the option variadic, by specifying it like `-m <value...>`.

```js
const {program} = require('commander');

function collect(value, previous) {
    return previous.concat([value]);
  }
  
  program
     .option('-m, more <value>', 'repeatable value', collect, [])
     .argument('[args...]')
     .action((args, options) => {
       console.log({more: options.more, args});
     });
  
  program.parse();
```

```console
% node index.js  -m 1 -m 2 -m 3
{ more: [ '1', '2', '3' ], args: [] }
% node index.js  -m 1 2 3      
{ more: [ '1' ], args: [ '2', '3' ] }
```
