### ISSUE TITLE
Accessing writeOut from actions

### ISSUE THREAD

**Issue by hypeJunction** [tj/commander.js#2277]
I am working on a web app that doesn't have access to stdout and I was able to replace the output of the program with `.configureOutput()`, but I am not really sure how I would access the API from inside the actions. All examples use `console`, and I don't see any public API to write/print with `Command`. For now, I am using a proxy on top of `window.console` to be able to print from the actions, but perhaps there is a more elegant way, or something that I am missing.

**Comment by shadowspawn** [comment]
There isn't a custom API for using `writeOut` and `writeErr` directly. The main use of `writeOut` is displaying the help, and there are `.help()` and `.outputHelp()` routines to trigger that directly. For errors, there is the `.error()` method to display and handle a custom error the same way Commander does.

However, you can retrieve the configured output and use it yourself:

```js
program
  .action((options, command) => {
    const output = command.configureOutput();
    output.writeOut('Hello, world!\n');
  });
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by hypeJunction** [comment]
All good, thanks a lot. Our work is on pause for now, but we will pick it up later. I will let you know how it goes.
