### ISSUE TITLE
Strange API behaviour for command description

### ISSUE THREAD

**Issue by PFight** [tj/commander.js#2290]
When adding description to command declaration, command does not work.

Working code:

```
program.command('analyze')
  .description('Do analyze.')
  .action(() => console.info("Hello explain!");
```
Execute:
```
> node index.js analyze
> Hello explain!
```

Not working code:
```
program.command('analyze', 'Do analyze.')
  .action(() => console.info("Hello explain!");
```
Execute:
```
> node index.js analyze
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Dev\stuff\npm-dependency-inspector\index-analyze'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)?[39m
?[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)?[39m
?[90m    at internal/main/run_main_module.js:17:47?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}
```

I spent HOURS to find a way to make commander work for simpliest command. Read all docummentation, tried several versions, and only happy accident helped me - I added description for one command, and do not added to another. So I found, that another command working and this give me a tip.

I think, when description specified, or command options specified, commander begin interpretate it as executable command. If it is true, then action() should throw error - it is usless for executable command. WTF? Why simple adding description change behaviour totally? And where in documentation this behaviour is specified?

**Comment by shadowspawn** [comment]
Sorry you hit this problem. This used to be a common source of confusion: #938

The README was updated to mention the behaviour. In particular in the example code in the Commands section: https://github.com/tj/commander.js?tab=readme-ov-file#commands

https://github.com/tj/commander.js/blob/970ecae402b253de691e6a9066fea22f38fe7431/Readme.md?plain=1#L519-L541

And in the section: https://github.com/tj/commander.js?tab=readme-ov-file#stand-alone-executable-subcommands

> When `.command()` is invoked with a description argument, this tells Commander that you're going to use stand-alone executables for subcommands. Commander will search the files in the directory of the entry script for a file with the name combination `command-subcommand`, like `pm-install` or `pm-search` in the example below. The search includes trying common file extensions, like `.js`.

There is also a message explaining the possible problem if a missing external command is detected at runtime, but you didn't see that. I suspect a different error may be getting thrown on Windows or in recent versions of node. I'll look into that.

https://github.com/tj/commander.js/blob/970ecae402b253de691e6a9066fea22f38fe7431/lib/command.js#L1222

**Comment by shadowspawn** [comment]
Running your example program, I see this on macOS:
```console
% node index.mjs analyze
/Users/john/Documents/Sandpits/commander/my-fork/lib/command.js:1234
        throw new Error(executableMissing);
        ^

Error: 'index-analyze' does not exist
 - if 'analyze' is not meant to be an executable command, remove description parameter from '.command()' and use '.description()' instead
 - if the default executable name is not suitable, use the executableFile option to supply a custom name or path
 - searched for local subcommand relative to directory '/Users/john/Documents/Sandpits/commander/issues/2290'
 ...
 ```

**Comment by shadowspawn** [comment]
Ah, the way the stand-alone executable commands get launched varies by platform, and the Windows code path does not trigger the extra message. I think we can improve that by checking for the file before spawning the process.

https://github.com/tj/commander.js/blob/970ecae402b253de691e6a9066fea22f38fe7431/lib/command.js#L1183

**Comment by shadowspawn** [comment]
Fix for missing helpful message added in version 13.0.0
