### ISSUE TITLE
Required arguments for options and commands are not enforced

### ISSUE THREAD

**Issue by foxx** [tj/commander.js#230]
It would be pretty awesome to have support for required arguments. Although there is support for required argument values, there doesn't appear to be anything for ensuring the argument has been specified.

For example;

```
    -e, --entry <name>          Add module to entry point
```

I'd like to make it so an error is raised if `-e` has not been specified like so;

```
  error: option `-e, --entry <name>' missing
```

**Comment by NameFILIP** [comment]
I see a lot of open pull-requests.. Will this be merged if I spend time implementing it?

**Comment by SomeKittens** [comment]
@NameFILIP Hopefully.  If you want to ensure your PR is merged, make sure it's wanted (already shown in this case), and has proper tests & documentation.

**Comment by czardoz** [comment]
Is anyone actually working towards this?

**Comment by marcelofarias** [comment]
My 2 cents: https://github.com/tj/commander.js/pull/462

**Comment by foxx** [comment]
Just come up against this again, seems to be quite a few PRs, are any due to be merged by core dev?

**Comment by foxx** [comment]
Any word on this @tj?

**Comment by Petah** [comment]
![Any word yet?](https://i.ytimg.com/vi/bDQpF92l1vg/mqdefault.jpg)

**Comment by amrynsky** [comment]
just came across this issue and didn't really get why it's still not implemented. I saw different reasons for not doing it, but the main problem that current implementation is not really consistent:
- In some cases, validation is performed 
`program.command('command <option>')`
in some not
`program.option('--option <option>', 'option')`

what the reason to define required option and don't perform any validation? Of course, it's possible to implement custom validation, but then you need to align error messages with standard validation messages like '  `error: missing required argument `option''`

**Comment by ratancs** [comment]
Any update on this?

**Comment by Strandedpirate** [comment]
I immediately regret using this library.

**Comment by schovi** [comment]
Any update? :)

**Comment by amir-arad** [comment]
+1

**Comment by cyrfer** [comment]
+1

**Comment by teazean** [comment]
+1
really want this feature

**Comment by joereynolds** [comment]
Just came across this thread and I'm wondering the same thing. How is there not support for required arguments, and why the reluctance? :(

**Comment by danihwsr** [comment]
+1

**Comment by Tiim** [comment]
+1

**Comment by chumster** [comment]
+1

**Comment by xCykrix** [comment]
The fact that this **still** isn't a thing almost hurts. If you want to be a command-line library this should be one of the core features.

**Comment by tecfu** [comment]
There needs to be a Github downvote functionality to flag repositories like this. 

Usage statistics and stars are useless for determining whether basic features are broken or code simply doesn't work like you expect it to.

**Comment by dessant** [comment]
After battling with commander.js for some time, I've finally switched to [yargs](https://github.com/yargs/yargs). It has all the features one commonly needs to build CLI tools, including support for required options.

Here's an example with some basic functionality:

```js
yargs
  .command(
    'create',
    'Create a new storage version',
    {
      message: {
        alias: 'm',
        describe: 'Storage version description',
        demandOption: true,
        requiresArg: true,
        type: 'string',
        nargs: 1
      },
      location: {
        alias: 'l',
        describe:
          'Directory where storage versions are kept, grouped by storage area',
        default: 'storage/versions',
        requiresArg: true,
        type: 'string',
        nargs: 1
      },
      storage: {
        alias: 's',
        describe: 'Storage area',
        choices: ['local', 'sync'],
        default: 'local',
        requiresArg: true,
        type: 'string',
        nargs: 1
      }
    },
    function(argv) {
      createVersion(argv);
    }
  )
  .demandCommand(1)
  .help()
  .alias('help', 'h')
  .version()
  .alias('version', 'v')
  .strict().argv;
```

**Comment by tecfu** [comment]
@dessant Beautiful example. Thank you. 

I ended up modifying it a bit because I didn't like seeing the "help" and "version" fields appear in each commands options when failed. 

```
        .help(false)
        .version(false)
```
Like so: 
```
yargs
  .command(
    'insert',
    'insert an array of asset objects into ...',
    (yargs) => {
      yargs
        .option('filepath', {
          alias: 'f',
          describe: 'Filepath to JSON array',
          demandOption: true,
          requiresArg: true,
          type: 'string',
          nargs: 1
        })
        .option('test', {
          alias: 't',
          describe:
            'Test conversion, but do not insert',
          requiresArg: false,
        })
        .help(false)
        .version(false)
    }
  )
  .command(
    'map',
    'create a document mapping for a given index',
    (yargs) => {
        yargs
        .option('filepath', {
          alias: 'f',
          describe: 'Filepath to ...',
          demandOption: true,
          requiresArg: true,
          type: 'string',
          nargs: 1
        })
        .options('index', {
          alias: 'i',
          describe: 'Index name to apply the mapping on',
          demandOption: true,
          requiresArg: true,
          type: 'string',
          nargs: 1
        })
        .help(false)
        .version(false)
    }
  )
  .demandCommand(1)
  .help(true)
  .strict().argv;
```

**Comment by ifeltsweet** [comment]
For simple scenarios, following code works well for me:

```js
program
  .description('Makes any type of pie.')
  .arguments('<type>')
  .action(function (type) {
     // Bake that pie.
  });

program.parse(process.argv);

if (!process.argv.slice(2).length) {
  program.outputHelp(() => program.help());
}
```

**Comment by shadowspawn** [comment]
This issue has been quite active over the years and mandatory options comes up multiple times, so I'll add a long comment here.

 @foxx asked in original post about making an option mandatory:

> I'd like to make it so an error is raised if -e has not been specified

## option with required value (already supported)

As noted in the original post, there is already support for making an option have a required value so *if* you specify the option you must also specify the value. 

```
.option('-c, --config <path>'

$ myCommand -c
error: option `-c, --config <path>' argument missing
$ myCommand
$
```

A common confusion or expectation is that an option with a required value makes the option itself mandatory (PRs #70 #462 #503 #601). That is not our desired behaviour as most options are optional.

So to be clear I consider these two different things:
- an option having a required value (currently supported)
- a mandatory option which must be supplied

I think we should expand on our conventions in the README and be more careful about the terms used to reduce this confusion.

## mandatory option (not currently supported)

Now as for making an option mandatory. It has been turned down at least once (#98). At that time it didn't seem worth adding the complexity for something which was easy to check yourself. 

However, it is a popular request so I think we shall consider it again!

Questions for readers:
- what is your favourite example of a common command line application with mandatory options? 
- how is that shown in the command line help?

And:
- have you got a suggestion for a clean syntax for specifying a mandatory option?

**Comment by mrgrain** [comment]
> Questions for readers:
> 
> * what is your favourite example of a common command line application with mandatory options?
> * how is that shown in the command line help?
AWS CLI
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --role-arn is required
```
Last line mainly.

> And:
> 
> * have you got a suggestion for a clean syntax for specifying a mandatory option?
Option 1: Additional boolean parameter at the end:
```js
program.option('-o', '--option <value>', 'A mandatory option.', true)
```

Option 2: Fancy string syntax => Add (a) star(s) somewhere with the value
```js
program.option('-o', '--option <*value>', 'A mandatory option.')
```

**Comment by schof** [comment]
Not a fan of the asterisk. I prefer appending `true` to the end of the option as you have suggested.

**Comment by carlesnunez** [comment]
I rather prefeer the usage of a property or function call which is more explicit and readable:

```javascript
program.option('-o', '--option <*value>', 'A mandatory option.').required
```

**Comment by musicin3d** [comment]
Relatedly, required arguments should be enforced. It should do more than produce nothing.

See [above comment](https://github.com/tj/commander.js/issues/230#issuecomment-424897234) for an example.

**Comment by vedmant** [comment]
Can be better to add options in case something else has to be passed:

```
program.option('-o', '--option <*value>', 'A mandatory option.', {required: true})
```
This also can distinguish from default value, as well as can accept just an object for all settings, this is convenient if options come from somewhere else:
```
program.option({short: '-o', full: '--option <value>', description: 'A mandatory option.', required: true})
```

**Comment by shadowspawn** [comment]
Thanks for the aws example @mrgrain. I tracked down the associated help, and aws explicitly marks all the optional options. Not what I want to do, but interesting.

```
$ aws sts assume-role 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: --role-arn, --role-session-name

$ aws sts assume-role help
...
SYNOPSIS
            assume-role
          --role-arn <value>
          --role-session-name <value>
          [--policy-arns <value>]
          [--policy <value>]
...
```

**Comment by shadowspawn** [comment]
Syntax:
- a suggestion in #462 is adding `.requiredOption()`
- a suggestion in #44  is adding * to flag like `.option('-b, --bar*', 'add some bar - mandatory');`

**Comment by ngocdaothanh** [comment]
> I am currently liking .requiredOption()

I prefer that too.

**Comment by mrgrain** [comment]
> I tracked down the associated help, and aws explicitly marks all the optional options. Not what I want to do, but interesting.
Yes, they do it pretty much the other way around and documentation-wise the square brackets are certainly common. But for now anyway of requiring an option to be present would be nice. One can always add their own message styling.

I'm very much like `.requiredOption()`.

**Comment by shadowspawn** [comment]
I do also like the idea in principle of supporting an options/settings parameter to allow for future additions: https://github.com/tj/commander.js/issues/230#issuecomment-520127955

But I think it needs to be a new method as `.options` has enough overloads already. I remembered a pattern I think from the Windows API, where X stands for extra or extended and means there is an extra parameter with settings. e.g.

```
program
   .optionX('-o, --option <value>', 'A mandatory option.', { required: true });
   .optionX('--secret', '(secret mode)', { noHelp: true });
```

**Comment by shadowspawn** [comment]
I added an issue to get some visibility on possible API, vote for preferred API there: #1038

**Comment by shadowspawn** [comment]
Implementing `.requiredOption()` in #1071.

**Comment by shadowspawn** [comment]
Added `.requiredOption()` to v4.0.0 prerelease: #1067

**Comment by shadowspawn** [comment]
v4.0.0 has been released.

There were some other things raised in various comments, but the main issue discussed of allowing a mandatory option has been added.

Feel free to open a new issue for other aspects, with new information and renewed interest.

**Comment by Tofandel** [comment]
@shadowspawn That's already a start but the other main issue of this thread was mandatory arguments, which still isn't a thing :(

**Comment by shadowspawn** [comment]
@Tofandel 

Missing arguments generate an error from Commander v5: #1149

Using the example code from: https://github.com/tj/commander.js/issues/230#issuecomment-424897234

```
% node args.js 
error: missing required argument 'type'
```

**Comment by mikkimichaelis** [comment]
So I’ve been trying to use the .requiredOption() feature, but it simply is not work for me:

"commander": "^10.0.0",

```nodejs
test.ts
var program = new commander_1.Command();
program.requiredOption('-mid', '--meetingId <string>', 'Specifies the meeting.id of target meeting');
program.parse();

console:
nodes ./lib/test.js
mikki@macBookPro ~/test
```

It returns no error.  This is a pretty serious issue I think.

**Comment by shadowspawn** [comment]
A quick answer: the short and long option go in the same string parameter, and the short option is a single character. So try:
```console
program.requiredOption('-m, --meetingId <string>', 'Specifies the meeting.id of target meeting');
```

(If you tried logging out `program.opts()` after parsing, you would find the third string has been used as the default value, so the "required option" had a value. Although not the option you intended and not the value you intended!)

**Comment by mikkimichaelis** [comment]
Wow!  Thanks so much for the quick response and guidance!  Yes, you are exactly right, but you knew that :-)
