### ISSUE TITLE
Is it possible to pass the same option more than once?

### ISSUE THREAD

**Issue by tandrewnichols** [tj/commander.js#235]
I'd really like to accept something like `-f foo.js -f bar.js -f baz.js` and get the list `[ 'foo.js', 'bar.js', 'baz.js' ]`.

My testing so far shows that the last in wins. Can someone confirm that I'm not missing something?

If I'm _not_ missing something . . . that seems like something that _should_ be added.

**Comment by JanisE** [comment]
+1
