### ISSUE TITLE
when specifying options, the "--no" version of a flag must appear after the flag

### ISSUE THREAD

**Issue by boneskull** [tj/commander.js#238]
We had this problem in visionmedia/mocha#1296.

The below works great:

``` js
  .option('-c, --colors', 'force enabling of colors')
  .option('-C, --no-colors', 'force disabling of colors')
```

In the example below, `--no-colors` does not work:

``` js
  .option('-C, --no-colors', 'force disabling of colors')
  .option('-c, --colors', 'force enabling of colors')
```

**Comment by himynameisdave** [comment]
Would like this option, there are plenty of valid reasons for wanting to do this.

At the very least, please make it clear in the docs that `--no` won't work, thanks

**Comment by shadowspawn** [comment]
Closing in favour of #108
