### ISSUE TITLE
Accessing parent options from subcommand

### ISSUE THREAD

**Issue by marc0s** [tj/commander.js#243]
Are parent's options available to subcommands? In my tests, they aren't.

It would be nice to have them available. In my case is for configuring the remote server my CLI app needs to connect to, so I have not to define the same options in every subcommand.

``` javascript
# ./cmd
#!/usr/bin/env node

var program = require("commander");
program.version("0.0.1")
  .option("-H, --host <host>", "server host")
  .command("sub", "subcommand");
program.parse(process.argv);
console.log(program.host);

# ./cmd-sub
#!/usr/bin/env node

var program = require("commander");
program.version("0.0.1");
program.parse(process.argv);
console.log(program.host);
```

And if you run them:

```
$ ./cmd --host localhost 
localhost
$ ./cmd-sub --host localhost 
error: unknown option `--host'
```

Any trick to get them from the subcommand or is just not possible?

Thanks.

**Comment by aynik** [comment]
Resurrecting this issue from the dead just to explain I used a little filthy hack to inherit options from the top-most command (because I'm into that):

On the top command you can export `program` with:

```javascript
if (!module.parent) {
  program.parse(process.argv)
} else {
  program.commands = []
  program._execs = []
  module.exports = program
}
```

And then from any subcommand you can replace:

```javascript
var program = require('commander')
```
For:

```javascript
var program = require('./<top-command>')
````
This way just the options will be inherited.

**Comment by b4dnewz** [comment]
hi @marc0s, can you share some code or example of how you did? just for the records, thankx

**Comment by pburgmer** [comment]
@b4dnewz I did it like this

```
const command = commander.command('merge');

command
      .description('foo')
      .option('--bar', 'really?', false)

addLoggingOption(command);

command
      .action(async (args: any) => { });
```

and

```
function addLoggingOption(command: Command): void {
  command
    .option('--log-level <level>', 'print log messages of given level and above only', 'info')
    .option('--verbose', 'set log level to debug')
    .option('--quiet', 'set log level to warn');
}
```

**Comment by shadowspawn** [comment]
Opened poll on possible enhancements to global options: #1551

**Comment by shadowspawn** [comment]
Opened a draft PR for `.addCommonOption()` #1670
