### ISSUE TITLE
Extra "padding" argument: what is it for?

### ISSUE THREAD

**Issue by rrthomas** [tj/commander.js#255]
In the code for the `action` method of sub-commands is the following code:

```
// Always append ourselves to the end of the arguments,
// to make sure we match the number of arguments the user
// expects
if (self._args.length) {
  args[self._args.length] = self;
} else {
  args.push(self);
}
```

What is it for? Why would the user expect an extra argument at this point? It means that detecting a missing argument is a bit tricky, as it can be either an object (if only one argument is missing at the end of a list) or `undefined` (if more than one is missing). Normally one only has to check for `undefined`.

**Comment by rrthomas** [comment]
I looked into this history of this code, and it was added for the benefit of subcommands, so that the `action` routine never receives undefined arguments. But it seems to me that it is perfectly reasonable for an argument to be undefined if the corresponding command-line argument was not supplied.

**Comment by rrthomas** [comment]
I offer a PR that removes this code, which avoids some checks for undefined arguments in `action` routines at the expense of making it much harder to check whether there were missing or superfluous arguments.

The case of dealing with undefined arguments in `action` routines will be better addressed by strict argument spec parsing; on the other hand, this change makes it easier to implement automatic strict checking, and possible to implement such checking manually in the mean time.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
