### ISSUE TITLE
Inconsistent behavior when defining sub-command

### ISSUE THREAD

**Issue by rrthomas** [tj/commander.js#256]
The documented API for defining a sub-command is:

```
  program
    .command('setup')
    .description('run remote setup commands')
    .action(function(){
      console.log('setup');
    });
```

This does not automatically call `addImplicitHelpCommand`. The undocumented form

```
 program.command('setup', 'run remote setup commands')
```

does. It would seem reasonable to move the code that sets the `executables` flag, which in turn causes `addImplicitHelpCommand` to be called, from the `parse` method into the `description` method. Would a patch to do this be acceptable?

**Comment by abetomo** [comment]
Closing due to possible answer suggested and no response registered. Feel free to comment and we can re-open in case this issue persisted.

**Comment by rrthomas** [comment]
I don't understand why you closed this: my "possible answer" involved patching commander.js, so it's not a workaround.

**Comment by abetomo** [comment]
I'm sorry! I was mistaken.

**Comment by abetomo** [comment]
I am looking forward to PR.

**Comment by rrthomas** [comment]
(Note: my original comment had one incorrect detail: the setting of `executables` is in the `command` method, not the `parse` method.)

**Comment by rrthomas** [comment]
After finding a test failure and studying the code some more, I see that actually the problem is with my reading of the current documentation. Closing.
