### ISSUE TITLE
Allow rejection of wrong number of arguments

### ISSUE THREAD

**Issue by rrthomas** [tj/commander.js#259]
At present, it's really hard to tell whether your command was passed the number of arguments it asked for. I gave up and patched commander, and still had to check in two places (one for too many, one for zero; too few and greater than zero are checked automatically by the argument parser).

A solution would be to insist that the arguments have to match the syntax (i.e. optional arguments may be omitted, required arguments must be present, additional arguments are not allowed), and if zero arguments is not a valid number, treat that case as if "--help" were given (but preferably exit with error).

I have a patch for this which I can make into a pull request.

**Comment by tecfu** [comment]
+1

**Comment by tecfu** [comment]
At a minimum, it is a lot of extra, superfulous code that goes into validating the number of arguments passed to each command individually. 

Granted, I don't know the POSIX spec, but being able to generate a list of commands that enforce the number and type of arguments passed would be ideal.

What is the difference between the <value> and [value] notation? If there is, can we reference this in the README? If there is no spec for this, can we consider a notation that enforces argument type? 

i.e.
.option('-C, --action [alphanumeric] --qty <numeric> --price <numeric>', 'require all these args or return an error', callback)

**Comment by shadowspawn** [comment]
I think the PR referred to here has been merged so this particular report is now stale.

This issue has not had much activity in four years. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
