### ISSUE TITLE
"name" option is broken as of 2.4.0

### ISSUE THREAD

**Issue by lakenen** [tj/commander.js#284]
One of my command line flags is called '--name', but as of https://github.com/tj/commander.js/commit/bfa7a73d5ad6671fb89b027bfcc5f53d08385121, if the name option is left off, `cmd.name` is a function. I suppose this is indicative of a larger problem, i.e., options are stored on top-level namespace of the command object.

e.g., say you have this file, mycmd.js

``` js
var prog = require('commander');
var command = prog
    .command('mycmd')
    .option('-n, --name [name]', 'specify a name (duh)')
    .action(function(cmd){
      console.log(cmd.name);
    });

prog.parse(process.argv);
```

you will see the following output:

```
$ node mycmd.js mycmd
[Function]

$ node mycmd.js mycmd --name Cameron
Cameron
```

Thoughts?

Is this wrong, or am I missing something?

**Comment by vanesyan** [comment]
Similar to #105, closed, keep your eyes on the issue.
