### ISSUE TITLE
Subcommand option with dashes

### ISSUE THREAD

**Issue by achingbrain** [tj/commander.js#289]
This might be related to #250 but I've only been able to reproduce the problem reliably with subcommands.

The following test fails:

``` javascript
var program = require('../')
  , should = require('should');

program
  .version('0.0.1')
  .option('-f, --foo <foo>', 'a main command argument');

program
  .command('sub')
  .description('a subcommand')
  .option("-b, --bar <bar>", "a subcommand argument")
  .action(function(options) {
    options.bar.should.equal('-c -d');
  });

program.parse(['node', 'test.js', 'sub', '-b', '-c -d']);
```

This can be triggered in a real app by invoking it like:

``` bash
$ node test.js sub -b '-c -d'
```

If you remove the `-` characters from the option value (and the assertion in the test) it works as expected.

I think the problem is in the [`normalize`](https://github.com/tj/commander.js/blob/master/index.js#L474) method - it [looks up](https://github.com/tj/commander.js/blob/master/index.js#L483) the `Option` object for the previous argument.  It consults `this.options` which seems to be populated with options for the main command (`-f` in the example above) so the subcommand's options list is not checked and the method always returns undefined.

If it found the right `Option`, it'd trigger [this branch](https://github.com/tj/commander.js/blob/master/index.js#L491) which would add the option to the `ret` array but instead it reaches [this one](https://github.com/tj/commander.js/blob/master/index.js#L493) with undesirable results in this case.

**Comment by curtisr7** [comment]
Still seeing this problem on commander@2.9.0. 

A workaround for the problem is to use the long version of the option ie: `--bar='-c -d'`

**Comment by achingbrain** [comment]
In the end my workaround was to switch to [yargs](https://www.npmjs.com/package/yargs).

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
