### ISSUE TITLE
_name variable conflict with mocha

### ISSUE THREAD

**Issue by DinisCruz** [tj/commander.js#297]
I was writing a unit test for the command line options I was adding to a tool I'm creating using commander, and I hit on a conflict with mocha

here is my test

``` coffeescript
  describe 'executing ./bin/node-webkit-repl', ->

    bin_node_webkit_repl = (params..., callback)->
      path = './bin/node-webkit-repl'.assert_File_Exists()
      path.start_Process_Capture_Console_Out params, callback

    it '(no params)', (done)=>
      bin_node_webkit_repl (result)=>

        helpInformation = _program.helpInformation()
        #hack to fix conflict with mocha
        helpInformation = helpInformation.replace('Usage: _mocha [options]', 'Usage: node-webkit-repl [options]')

        result.assert_Is(helpInformation)
        done()
```

which runs ok (due to the helpInformation hack)

![image](https://cloud.githubusercontent.com/assets/656739/5325835/31c89c5a-7cf2-11e4-9a5f-68d6cb0b073a.png)

but if I comment that line:

![image](https://cloud.githubusercontent.com/assets/656739/5325840/51a12394-7cf2-11e4-88e9-74644f986490.png)

the test will fail with 

![image](https://cloud.githubusercontent.com/assets/656739/5325843/5ed5c858-7cf2-11e4-8431-62402e3ecb86.png)

here is the assert error:

```
AssertionError: "\n  Usage: node-webkit-repl [options]\n\n  Options:\n\n    -h, --help     output usage information\n    -V, --version  output t == "\n  Usage: _mocha [options]\n\n  Options:\n\n    -h, --help     output usage information\n    -V, --version  output the version
Expected :"\n  Usage: _mocha [options]\n\n  Options:\n\n    -h, --help     output usage information\n    -V, --version  output the version number\n    -gui           Start GUI\n\n"
Actual   :"\n  Usage: node-webkit-repl [options]\n\n  Options:\n\n    -h, --help     output usage information\n    -V, --version  output the version number\n    -gui           Start GUI\n\n"
 <Click to see difference>
```

here is the graph view of the difference:

![image](https://cloud.githubusercontent.com/assets/656739/5325845/75d71d90-7cf2-11e4-9eae-95f1b738af67.png)

I had a look at the code, and the issue is with the this._name variable which is being changed by mocha:

https://github.com/tj/commander.js/blob/master/index.js#L890

![image](https://cloud.githubusercontent.com/assets/656739/5325846/91f98ee0-7cf2-11e4-887b-1d29d62092bd.png)

Note: I tried using the **_program** variable name in my test, instead of **program** , but that didn't seem to make a difference

**Comment by pensierinmusica** [comment]
+1 Same problem here!

**Comment by jamesr73** [comment]
An old issue, but just in case this is useful to someone...

Mocha is not interfering with the _name variable. Mocha and the CLI under test are sharing the same commander singleton. Mocha get's there first so the command name is set to _mocha.

If you're writing the CLI under test you could do this:

```javascript
var Command = require('commander').Command
var program = new Command();
```

**Comment by F1LT3R** [comment]
Thanks @jamesr73 !

Note: I had to add process.argv in order that commander always had the arguments available on initialization.

```javascript
const Command = require('commander').Command;
const program = new Command(process.argv);
```

**Comment by shadowspawn** [comment]
Thanks for explanation and solution @jamesr73 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
