### ISSUE TITLE
With '*' commands, options doesn't work

### ISSUE THREAD

**Issue by acemtp** [tj/commander.js#314]
In this case:

    program
      .command('*')
      .option('-g, --github', 'display GitHub url')
       .action(function () {
           console.log('a', program);
       });
      program.parse(process.argv);

options are not parsed, you can run the command with a bad option or with g, it doesn't generate an error or give the option.

If you change * with a real command, 'a' for example, it works fine.

**Comment by noamokman** [comment]
Duplicate of #222

**Comment by SomeKittens** [comment]
Closing as dupe.
