### ISSUE TITLE
Allow config option for subcommands to be resolved by directory '/' instead of '-' concat

### ISSUE THREAD

**Issue by rdodev** [tj/commander.js#325]
Currently the way subcommands are found are run is by '-' concatenation [1]. It would be greatly advantageous if there were a config option to use directories, for instance, instead of dashes.

So `command subcommand` would resolve to `command/subcommand` instead of `command-subcommand`. While the latter is fine for a command with small number of subcommands, it doesn't scale well once you have, say, 15+ subcommands.

To better illustrate the use case think of the following contrived example:

```
car
car-engine
car-engine-start
car-engine-warmup
car-engine-stop
car-headlights
car-headlights-on
car-headlights-highbeam
car-headlights-lowbeam
car-headlights-off
...
```

or you could have it:

```
car
car/engine/start
car/headlights/on
...
```

this would be transparent to the end user who will still use commands and subcommands as usual (i.e. `command subcommand subsubcommand`)

[1] https://github.com/tj/commander.js/blob/master/index.js#L459-L461

**Comment by SomeKittens** [comment]
Subcommands are this style thanks to git (`git status` is really an alias for `git-status`).  I'm not a big fan of adding this to core.

**Comment by zhiyelee** [comment]
As @SomeKittens describe, we adopt git-style subcommand here.

```
car-headlights-on
car-headlights-highbeam
car-headlights-lowbeam
car-headlights-off
```
For the example, I think you can use option instead, such as `--on` , `--off`,  `--highbeam` etc

**Comment by rdodev** [comment]
Our subcommands are too complex with differing parameters to be able to be passed as a flag. Anyway, we are going to run with modified fork of this library which is great in many other respects. :+1:

**Comment by bucaran** [comment]
@zhiyelee  Any chance you may reconsider this? I would gladly work on this.

**Comment by rdodev** [comment]
@bucaran unfortunately, due to the way npm works, when you declare your `bin` list in `package.json` upon `-g` install it will flatten them to the whatever the `/usr/local/bin` is. That means having the commands in a hierarchy doesn't work because the directory hierarchy won't be in `PATH`. We had to abandon that approach and keep using dashed commands.

**Comment by bucaran** [comment]
@rdodev What `bin` list?

**Comment by rdodev** [comment]
@bucaran https://docs.npmjs.com/files/package.json#bin

**Comment by bucaran** [comment]
Where is this in the commander.js documentation?

**Comment by rdodev** [comment]
No idea. I just knew I had to because of the standard way of how npm works.

**Comment by bucaran** [comment]
Ah, I see. I thought I had to do something special to make commander work. We are talking about declaring your app executables under `bin`. Cool.
