### ISSUE TITLE
Set the parameter for options individually

### ISSUE THREAD

**Issue by sierisimo** [tj/commander.js#326]
When I wrote something like:

`$node program.js -a 1 2 3 -b 4 5 6` 

and my code looks like:

``` javascript
...
program.version('0.0.3')
  .usage("[option] <file ...>")
  .option('-a, --add <file1> [file2 ...]',"Adds"),
  .option('-b, --block <file1> [file2 ...]', 'Block');
```

Both 'a' and 'b' have an array with just the first element passed:

a >>> [ '1','4']
b >>> [ '1','4']

also if I do:

`$node program.js -a 1 2 3`

and in the code:

``` javascript
if(program.block){...}
```

the if always work, because block is an array holding the parameters passed to 'add'.

It would be awesome that instead of this behavior the result was:

a >>> ['1','2','3']
b >>> ['4','5','6']

**Comment by SomeKittens** [comment]
I'm unaware of a UNIX-style utility that parses things this way - care to suggest one?

**Comment by sierisimo** [comment]
Totally true, I was a little confused about this behavior.

But I think the issue about having the same param for both options is still important because of the `if(program.block)` part, where you put the value for an option and another that could take a optional option also has that valule.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
