### ISSUE TITLE
command '*' action callback arguments in 0.5

### ISSUE THREAD

**Issue by donpark** [tj/commander.js#33]
For command '*', action callback arguments are documented as:

> When the `name` is "*" an un-matched command
> will be passed as the first arg, followed by
> the rest of **ARGV** remaining.

but for:

```
$ html2jade http://www.mcli.dist.maricopa.edu/tut/tut1.html
```

I'm getting `http://www.mcli.dist.maricopa.edu/tut/tut1.html` as first argument
and some mysterious `Object` as second argument.

I've added argument type check as workaround so issue is not urgent but thought you should know.

**Comment by vanesyan** [comment]
Closed, outdated. Feel free to reopen.
