### ISSUE TITLE
incomplete JSDoc comments

### ISSUE THREAD

**Issue by DarkPark** [tj/commander.js#330]
in some places there are some problems preventing IDE from validating code successfully
for example `Command.prototype.option`
this function has two last arguments as optional but JSDoc comments don't show this

```
@param {Function|Mixed} fn or default
```

but should be

```
@param {Function|Mixed} [fn] or default
```

or even better

```
@param {Function|*} [fn] or default
```

**Comment by zxqfox** [comment]
Probably a big part of mistakes like this can be found automatically with jscs-jsdoc.

**Comment by vanesyan** [comment]
Merged
