### ISSUE TITLE
Custom help not output on Windows when using pipe

### ISSUE THREAD

**Issue by feklee** [tj/commander.js#333]
On Windows, there is an [issue](https://github.com/joyent/node/issues/3584) with flushing the output buffer upon calling `process.exit`. This causes the [custom help example](https://github.com/tj/commander.js/tree/v2.6.0#custom-help) to fail when piping help output:

```
C:\Temp>node custom-help.js -h | more

  Usage: custom-help [options]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
    -f, --foo      enable some foo
    -b, --bar      enable some bar
    -B, --baz      enable some baz



C:\Temp>
```

This is totally unexpected, and just confused me when I was calling `node custom-help.js -h` from within an IDE (EMACS) where shell output is redirected prior to displaying it.

A workaround is wrapped up in the [exit NPM package](https://www.npmjs.com/package/exit).

**Comment by SomeKittens** [comment]
Looks like a problem, and thanks for bringing a solution along with the report!

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
