### ISSUE TITLE
Subcommands not found when installed globally (npm) on Unix-type environments

### ISSUE THREAD

**Issue by BobDickinson** [tj/commander.js#335]
I have implemented a command line interface using Commander and the "subcommand" feature.  I have a main called xxxx.js, and a series of commands in files named like xxxx-command.js.  This command line interface is intended to be used via npm (and typically installed globally)

The sub-command launching works fine under Windows, but fails in Unix-type environments.  The reason it fails is when installed globally via npm (using install -g or just npm link), which seems like a reasonable use case for a CLI with subcommands, the process.argv received by the base process (xxxx.js) is NOT that file itself, but rather the symlink that launched it, which is /usr/local/bin/xxxx.

The various machinations in executeSubCommand are of course never going to find the subcommand file (since it's not in /usr/local/bin - the only thing there is the symlink to the "main" command that npm created).  Thus it fails to load the module, with a fairly unhelpful generic module load stack trace from Node.

As far as I can tell, the idea is that executeSubCommand should be looking in the same directory where the actual main command file lives.  I am working around this for now by doing:

    process.argv[1] = __filename;

right before I call the Commander parse.

**Comment by vleango** [comment]
+1

**Comment by adius** [comment]
+1
