### ISSUE TITLE
Custom version command

### ISSUE THREAD

**Issue by goloroden** [tj/commander.js#340]
According to the auto help, commander automatically attaches itself to the `-v` and `--version` options to output the version number.

That's fine.

Unfortunately, it also does this for a `version` sub command, and I am apparently not able or allowed to overwrite this.

In lots of tools (I think of Vagrant and Docker, e.g.), calling the tool with `--version` only prints out the version number as commander does, but calling it with `version` without the dashes output way more details on the version.

Example with `docker --version`:

```
Docker version 1.3.1, build 4e9bbfa
```

Example with `docker version`:

```
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): darwin/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa
```

Now I would like to have something similar in my application. How can I override the `version` sub command?

**Comment by zhiyelee** [comment]
@goloroden  It's not allowed to custom the `version` output now.  A PR is needed for that. Would u mind make a PR,otherwise I'll make it some day later.

**Comment by erming** [comment]
Hey guys!

Heh, random. I just finished implementing this minutes ago before I discovered this issue.

Here's what I came up with:

```javascript
program.option("-v, --version", "output the version numer", function() {
  if (process.argv.indexOf("version") !== -1) {
    // print
    // the
    // long
    // version
    // list
    // here
  } else {
    // short
  }
  process.exit(0);
});
```

Hope this helps!

**Comment by zhiyelee** [comment]
@erming LGTM, but a `callback` argument for the `.version()` is much better to me.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

There has been a patch to disambiguate emit for version option and command, so behaviour may have been improved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
