### ISSUE TITLE
Support explicit boolean flag

### ISSUE THREAD

**Issue by Globegitter** [tj/commander.js#344]
I have a cli where I want to be able to set flags such as `--docker=true` as well as `--docker=false` and have the true/false automatically been interpreted as boolean.

```js
program
  .command('up')
  .option('-D, --docker [boolean]', 'Run Sails server and dependencies within docker containers.', config.docker || false)
```

is the code I have and I also have a config file where you can set `{ "docker": true}`, but then still overwrite that via setting the flag `--docker=false`.

To support this I currently have to check `if (options.docker && options.docker !== 'false')` but think just checking for `if (options.docker)` keeps it simpler especially since I want to support this for multiple flags throughout the whole app.

Is there any way to do this, or a possibility to implement boolean interpretation?

**Comment by SomeKittens** [comment]
You will have to implement the interpretation yourself.

I'm not sure about the internals of your CLI but it usually makes more sense to have the absence of a flag be `false`

**Comment by shadowspawn** [comment]
Commander supports negated options, so rather than:

```sh
launch up
launch up --docker=true
launch up --docker=false
```

the calls could look like:

```sh
launch up
launch up --docker
launch up --no-docker
```
