### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by goloroden** [tj/commander.js#348]
Today I stumbled upon the problem that exit codes of git-style sub commands are not handed through to the main app.

I have seen that [this has been fixed](https://github.com/tj/commander.js/commit/29b4ea91a18679546980ce1a1e07957d1cbf9fb5) a while ago, but no new version has been released since then.

Could you please release a bug-fix version of commander soon?

**Comment by zhiyelee** [comment]
@goloroden I'll release a new version after #349 get merged

**Comment by goloroden** [comment]
Great, thanks :-)
