### ISSUE TITLE
addImplicitHelpCommand() adds implicit help twice

### ISSUE THREAD

**Issue by shakiba** [tj/commander.js#350]
`addImplicitHelpCommand()` adds implicit help twice, once when called and once in `parse()`. When I only add commands with action, implicit help is not added by default and I have to add it manually which results in this issue.

**Comment by shakiba** [comment]
Moreover it seems that `command help subcommand` doesn't work for commands with action.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
