### ISSUE TITLE
Using commander I describe a command line based API. How about an HTTP API?

### ISSUE THREAD

**Issue by rjsteinert** [tj/commander.js#351]
Using commander I describe a command line based API. It seems to me the same description could translate to an HTTP API. Now I know it's probably not ideal... But let's just say I'm lazy and interested in writing things that have to be a command line interface and an HTTP API that comes for free would be nice to have. Does anyone know of any work/thoughts on this idea?

**Comment by SomeKittens** [comment]
Writing something that works via command-line *and* HTTP is a neat idea!  However, that's not the goal of this project.

**Comment by aemonge** [comment]
I agree, but If you found any resources can you post them here ?
