### ISSUE TITLE
Git-style command with support of JS 6

### ISSUE THREAD

**Issue by khanh-nguyen** [tj/commander.js#355]
I'm implementing some *git-style* commands using ES 6. I use [this hack](https://github.com/olov/node-harmony-wrapper/blob/master/hello-es6) to run commands with `--harmony` option. However, *sub-commands* are not executed with `harmony`. Hence, all JS 6 features are broken. 

Is there any workaround for this?

Thanks,

**Comment by zhiyelee** [comment]
```
#! /usr/bin/env node --harmony
// code here
```

Does not this way work?

**Comment by khanh-nguyen** [comment]
@zhiyelee, I tried it. Didn't work for me. Did it work for you?
```
let program = require('commander'),
^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by khanh-nguyen** [comment]
Just to be clear, here's a simple example of my setup:
```
.
├── bin
│   ├── cmd
│   └── cmd-test
├── node_modules
│   └── commander
└── package.json
```
bin/cmd
```
#!/usr/bin/env node --harmony
let program = require('commander');
program
    .version(require('../package.json').version)
    .command('test [something]', 'test git-style command with ES6')
    .parse(process.argv);
```
bin/cmd-test
```
#! /usr/bin/env node --harmony
let program = require('commander');
// process options
// code ommitted
program.parse(process.argv);
let files = program.args;
// code ommitted
```
Here's the result
```
$ ./bin/cmd test foo
/Users/khanh.nguyen/opower/test_code/test_commander/bin/cmd:1
(function (exports, require, module, __filename, __dirname) { 
                                                            ^
SyntaxError: Illegal let declaration outside extended mode
```

**Comment by zhiyelee** [comment]
add `'use strict'; `  below shebang

**Comment by khanh-nguyen** [comment]
```
$ bin/cmd test foo
/path/to/test_commander/bin/cmd-test:3
let program = require('commander');
^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by zhiyelee** [comment]
@khanh-nguyen Seems a bug, I'll look into it.

**Comment by khanh-nguyen** [comment]
:+1: Thanks.

**Comment by zhiyelee** [comment]
I checked again, seems works for me here.

```
#! /usr/bin/env node --harmony
'use strict';
if (1) { let foo = 1; }
console.log(typeof foo === 'undefined');
console.log('========')
```

**Comment by khanh-nguyen** [comment]
Did you put this code in `cmd` or `cmd-test`? I only have problem with the code in `cmd-test`, not with `cmd`.

**Comment by khanh-nguyen** [comment]
I'm not sure what the issue is. I repro the examples above inside `examples/` directory in `commander` repo and everything works fine.
I notice that if I install `commander` as dependency, even though, the version is `2.6.0`, the code in `Command.prototype.executeSubCommand` is slightly different:
```
// run it
args = args.slice(1);
args.unshift(local);
var proc = spawn('node', args, { stdio: 'inherit', customFds: [0, 1, 2] });  
```
If I use git-url to point to `git://github.com/tj/commander.js.git#master`, this issue is fixed, no more problem with ES6.

**Comment by zhiyelee** [comment]
There is some changes after `v2.6.0`  which have not been released

**Comment by khanh-nguyen** [comment]
It's good to know. Thanks.
