### ISSUE TITLE
command parsing in 2.7 possibly should have bumped major

### ISSUE THREAD

**Issue by timoxley** [tj/commander.js#367]
Apparently something went amiss with command parsing in the latest release:

https://github.com/timoxley/linklocal/pull/16

**Comment by yoshuawuyts** [comment]
When running `linklocal link`, the `link` part is now seen as a file instead of a subcommand. This is possibly caused by changes to the [`subcommand`](https://github.com/tj/commander.js/commit/0109a4407e88d10e70e3538c14adf57149f4d972) functionality.
```txt
/Users/yoshuawuyts/.nvm/versions/io.js/v1.3.0/lib/node_modules/linklocal/bin/linklocal.js:73
  if (err) throw err
                 ^
Error: ENOENT: no such file or directory, open '/Users/yoshuawuyts/dev/wercker/wercker/src/list/package.json'
    at Error (native)
```

**Comment by zhiyelee** [comment]
The abnormal is incurred by #347 https://github.com/tj/commander.js/pull/347/files#diff-168726dbe96b3ce427e7fedce31bb0bcR565

Would u mind reviewing this?  @tonylukasavage @SomeKittens

**Comment by SomeKittens** [comment]
@zhiyelee At this point we should probably revert that commit to restore previous functionality.  We can inspect the bug #347 was trying to fix later.

**Comment by zhiyelee** [comment]
@SomeKittens Sounds good to me

**Comment by zhiyelee** [comment]
@timoxley @yoshuawuyts I have released a patch version for the bug. Sorry for the Inconvenience.

**Comment by timoxley** [comment]
@zhiyelee no worries, thanks for tackling it promptly!
