### ISSUE TITLE
Issues with 2.7.1 when using sub commands

### ISSUE THREAD

**Issue by AdamMagaluk** [tj/commander.js#372]
Sub commands are not working on the lastest, was working in 2.6.0. 

Running `node cli` works but `node cli subcommand` fails with the error below.

```
fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/commander-test/cli'
```

**Comment by zhiyelee** [comment]
Could u provide more detail information?  thx

**Comment by AdamMagaluk** [comment]
See files below, i have a base `cli.js` file and a subcommand `cli-stacks.js` breaks on the latest release when running `node cli stacks`.

`node cli -h` both 2.7.1 and 2.6.0 prints help message showing stacks command and top level options.

2.6.0

```
λ: node cli stacks -h

  Usage: cli-stacks [options] [command]


  Commands:

    create [name]   install one or more packages
    delete [query]  search with optional query
    help [cmd]      display help for [cmd]

  Options:

    -h, --help  output usage information

```

2.7.1

```
λ: node cli stacks -h

fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/ApigeeCorporation/Software/commander-test/cli'
    at fs.lstatSync (fs.js:691:18)
    at exports.readlinkSync (/Users/ApigeeCorporation/Software/commander-test/node_modules/commander/node_modules/graceful-readlink/index.js:5:7)
    at Command.executeSubCommand (/Users/ApigeeCorporation/Software/commander-test/node_modules/commander/index.js:472:14)
    at Command.parse (/Users/ApigeeCorporation/Software/commander-test/node_modules/commander/index.js:443:17)
    at Object.<anonymous> (/Users/ApigeeCorporation/Software/commander-test/cli.js:7:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

cli.js
```js
var program = require('commander');
 
program
  .version('0.0.1')
  .option('-C, --chdir <path>', 'change the working directory')
  .command('stacks [cmd]', 'install one or more packages')
  .parse(process.argv);
```

cli-stacks.js
```js
var program = require('commander');
program
  .command('create [name]', 'install one or more packages')
  .command('delete [query]', 'search with optional query')
  .parse(process.argv);
```

**Comment by csrbwilson** [comment]
I'm experiencing the same issue on linux, on windows the sub command is found. I'm getting the following error:

clitest-install(1) does not exist, try --help

Another issue - list coercion function not working, under 2.6.0 working

**Comment by AdamMagaluk** [comment]
Issue i'm seeing stems from https://github.com/tj/commander.js/commit/154fb8b37223a7f3910757d3edc4e68348f02770 appears your not calling `node sub-command` anymore but directly calling `sub-command`. For my code this means removing the `.js` extension and making them executable with the typical `#!/usr/bin/env node`, or pin the commander version to v2.6.0 the latter is probably what i'll stick with.

**Comment by adius** [comment]
I'm having the same issue!

**Comment by zhiyelee** [comment]
@AdamMagaluk yep, I will find a way to fix this.  You can add `#!/usr/bin/env node` simply(command will handle the `.js` itself)  OR pin to v2.6.0 before the bug get fixed. Sorry for that.

**Comment by zhiyelee** [comment]
@AdamMagaluk yep, u are right. I am working on this bug now. Hope to release a patch version later.

**Comment by yordis** [comment]
Just for leave a note about this.

I was using the git style and because I didn't use `.js` when I called the file with `node` it gave me this error

```
node bin/npm-packager <--- no extension, this fails
```
