### ISSUE TITLE
How to use program.command ?

### ISSUE THREAD

**Issue by rusikf** [tj/commander.js#384]
fun.js 

``` javascript
  1 #!/usr/bin/env node
  2 var program = require('./index');
  3 
  4 program
  5   .version('0.0.1')
  6   .command('capture <world>')
  7   .action(function(world){
  8     console.log("Let's capture the", world);
  9   })
 10   .parse(process.argv);
```

bash
`./fun.js capture Earch`
( Nothing is in stdout)
**Question:** Why i don't see console.log message ?

**Notice**: 
1)Yes i know, i can use desc for `command` and add script, which i want to execute.
But i also noticed, that in this [example](https://github.com/tj/commander.js#variadic-arguments) we can use command without desc and use action for command , but it doesn't work
2) I am using commander.js from the latest github source.
3) Also, i find in comments of index.js [this example](https://github.com/tj/commander.js/blob/master/index.js#L118-123), which doesn't write any output too.

**Comment by SomeKittens** [comment]
I've edited your post - there's no need to ping all the contributors of a project.

**Comment by djMax** [comment]
Failing for me too. Not sure how this thing is passing all the tests and such if something so basic is broken. I must be doing something wrong but I have no idea what.

**Comment by rusikf** [comment]
@SomeKittens , ok :wink:
I find the bug, in index.js there is a method:
[Command.prototype.command ] (https://github.com/tj/commander.js/blob/master/index.js#L159-177)
which returns ```cmd``` if there is no desc. 
So, if it(method) returns ```this``` my example is valid.
But if return this, there are a lot of tests, which failed because they depends from ```cmd```.

Can you explain how to fix it ?

**Comment by hildjj** [comment]
You can fix this by modifying line 10 to be `program.parse(process.argv);`.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
