### ISSUE TITLE
Tab completion?

### ISSUE THREAD

**Issue by bitjson** [tj/commander.js#385]
Has anyone implemented tab completion with commander? [Complete](https://github.com/hij1nx/complete) looks like a working module, but it seems like this would be perfect territory for commander.

Another module: [completion](https://github.com/twolfson/completion)

**Comment by okv** [comment]
It would be great to have shell auto-completion for already generated program help without write much code. Suggestions? I can't find anything suitable at npm.

**Comment by zhiyelee** [comment]
Interesting. PR about this feature is welcome~

**Comment by okv** [comment]
E.g.:
- if input starts with `-` then autocomplete global options and command options (if command is already typed)
- if you don't yet choose a command - suggest commands
- allow to extend/override autocompletion behaviour programmatically (to suggest custom parameters for options (as branches in git), etc)

**Comment by arthurafarias** [comment]
This would be a great feature. =D

**Comment by thethomaseffect** [comment]
I looked into this in the past and had a working prototype (not using a third party module). However, getting it working for windows is a whole other ballgame. I'd like to see a powershell solution so commander can continue to be multi-platform

**Comment by plusmancn** [comment]
I have found [commander-auto-complete](https://www.npmjs.com/package/commander-auto-complete), but which is not good enough to use for product.

**Comment by tonylukasavage** [comment]
Windows support has been one of the reasons in the past that I never pursued this personally. That, and the fact that I think a solid usage doc with a levenshtein distance check on attempted command executions (like git) usually covers the case. IMHO, I feel like if you're leaning on autocomplete for your CLI, you might have a design issue with it. Not to say that they're aren't real cases that could use it, but I'm of the opinion they should be rare.

**Comment by bitjson** [comment]
Just an update on this – those looking for CLI auto-completion might want to consider switching to [Vorpal](https://github.com/dthree/vorpal). Vorpal is a bit more involved, but it has a lot of the more advanced features built-in.

**Comment by k0pernikus** [comment]
@bitjson [Vorpals autocompletion](https://github.com/dthree/vorpal/wiki/Docs-%7C-Autocomplete) is quite awesome, yet the lack of typescript typings is a dealbreaker for me. Yet [commander](https://www.npmjs.com/package/@types/commander) has them.

I wished commander would also support autocompletion :)

**Comment by atheros** [comment]
@tonylukasavage don't dismiss autocompletion as being a quick fix for poor design decisions. It can also be user for values for example:

addpermission user@<tab>... system.admin system.<tab>...

Many database CLIs implement this kind of autocomplete for table names and fields.

@bitjson Vorpal works great as a shell, however due to some bugs, it's pretty much impossible to invoke a single command from command line and quit

**Comment by BafS** [comment]
An alternative is also Yargs: https://github.com/yargs/yargs

**Comment by bitjson** [comment]
For anyone following this issue, I strongly recommend you check out [oclif](https://github.com/oclif/oclif). 

It's extremely well-designed, and the autocompletion is fantastic.

**Comment by shadowspawn** [comment]
@bencao has done an integration with Omelette in #907, but it was decided not to include it in Commander itself at this time.

**Comment by shadowspawn** [comment]
Not currently planning to build tab completion into Commander itself, so closing this issue.

I am interested in this as a problem, so please let us know about packages which integrate well with Commander.

**Comment by keidrych** [comment]
Leaving breadcrumbs for anyone who is wanting to get this up and running simply:

hello.js
```
const {Command} = require('commander')
const omelette = require('omelette')
const process = require('node:process')

const cli = new Command('hello')
omelette('hello').tree({
  cruel: ['world']
  beautiful: ['mars']
}).init()

if (!~process.argv.indexOf('--completion')) {
  cli.command('cruel')
  cli.command('beautiful')
}
cli.parse()
```

to make it work source omelette output to your shell and alias as explained in omelette documentation

```
source <(node hello.js --completion)
alias hello='nodejs hello.js'
```

Then just `hello` <tab> <tab> etc...

**Comment by gagregrog** [comment]
> Leaving breadcrumbs for anyone who is wanting to get this up and running simply:

This was very helpful to get things started, thank you! I'd like to point out one thing in case others are initially unable to get this example working.

First, add a comma after `cruel: ['world']` 😉.
Secondly, if you are running this with zsh it will not work. The alias will not work with tab completion, but it does work if you wrap it in a function:

```sh
hello() {
	node index.js $@
}
```

[source](https://github.com/f/omelette/issues/33#issuecomment-717313368)

**Comment by KaKi87** [comment]
Hi,
Did anyone implement commander autocompletion with [`node:repl`](https://nodejs.org/docs/latest-v20.x/api/repl.html#replstartoptions) ?
Thanks

**Comment by jchook** [comment]
Revisiting this problem again and it appears there is still no well-supported solution. See:

- https://github.com/oclif/plugin-autocomplete/issues/426#issuecomment-1434113454
- https://github.com/twolfson/commander-completion

And as a potential alternative:

- https://oclif.io/docs/features/#autocomplete
- https://github.com/oclif/plugin-autocomplete/

**Comment by gutenye** [comment]
For anyone seeking a solution, I’ve developed [@gutenye/commander-completion-carapace](https://github.com/gutenye/commander-completion-carapace) using Carapace. It's fast, works well, and supports numerous shells like Bash, Zsh, Fish, Nushell, and others.

**Comment by jchook** [comment]
Why YAML??????

**Comment by shadowspawn** [comment]
I came across a new completion package with a Commander integration. Supports zsh, bash, fish, and powershell. In development at version 0.0.17, but being used in a few products and getting almost a million weekly downloads on npmjs.org.
- https://github.com/bombshell-dev/tab
- https://www.npmjs.com/package/@bomb.sh/tab
