### ISSUE TITLE
Manually triggering usage

### ISSUE THREAD

**Issue by remy** [tj/commander.js#39]
My app wanted to trigger the usage if there's no arguments, but I couldn't see from the docs the right way of doing this.

Checking the code, I ended up calling the `program.helpInformation()` directly - not sure if this is right.  If it is, possibly worth adding to the README?

Usage example:

```
  if (program.args.length == 0) {
    console.log(program.helpInformation());
    process.exit();
  }
```

Except I've just also noticed that it doesn't include my custom help I added via the `on('--help', fn)` ... or is there something obvious I'm missing?

**Comment by vanesyan** [comment]
Closed, outdated. Feel free to reopen.
