### ISSUE TITLE
Question: Passing '' (two single quotes) for optional arguments

### ISSUE THREAD

**Issue by anuchandy** [tj/commander.js#394]
Hi,

We are taking dependency on commander in one of our project. We have a requirement to allow user to pass empty string from the command line for optional argument. 

We found that if we use --option-name "" (double quotes) then commander throws error saying option is missing.

If we use --option-name '' (single quotes) then we are getting this option from commander as '', which works fine in our case.

Question is: Can be use this solution in a reliable way? is there any chance in future to modify commander that it throws error in case of ''? and break us

**Comment by SomeKittens** [comment]
Hello!  This is a great question - can you provide some sample code (how you're requiring the empty string)?  It'll help us a lot.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
