### ISSUE TITLE
short switches don't take numeric arguments

### ISSUE THREAD

**Issue by Sequoia** [tj/commander.js#395]
in minimist (or `tail` for that matter), `-n10` sets `n` (or the switch it aliases) to `10`.

A similar call with `commander` sets `n` (or the switch it aliases) to `-1`. This seems to mean a minimist to commander rewrite forces a CLI change, i.e. a cronjob that previously called `foo -n10` will stop functioning properly if `foo` is upgraded from the minimist version to the commander version.

Is there a workaround? Am I mistaken?

**Comment by TheRoSS** [comment]
The same issue.
commander.option("-c, --count <positiveInteger>", "...")
with call:
node myCoolScript -c2
gives:
commander.count = -2

**Comment by TheRoSS** [comment]
This is a bug in the Command.prototype.normalize method
It is him who splits -c2345 option with parameter to set of no parameter options -c -2 -3 -4 -5
Then parser behaves correctly and takes "correct" parameter for option "c"

**Comment by shadowspawn** [comment]
This issue will be partially  resolved when v3.0.0 is released. Available now as a prerelease. See #1001

Support for passing option directly with short flags is added for recognised options (but not for options for subcommands with executable file as handler.)

**Comment by shadowspawn** [comment]
Support for directly appending values to short options has shipped in v3 (thanks @TheRoSS): https://github.com/tj/commander.js/releases/tag/v3.0.0

As per previous comment, currently only working for action handler based subcommands.
