### ISSUE TITLE
Regression in multiline descriptions

### ISSUE THREAD

**Issue by simast** [tj/commander.js#396]
Any chance [this feature](https://github.com/tj/commander.js/commit/6134fe44992a301485b087cc7d74a2634311e99d) can be reverted?

Previously, using the newline and tab characters in descriptions allowed us to provide an extended description/help of a command with a lot of space available immediately after the command syntax line. However after this change - all multiline description text lines are crammed and aligned in a column right after the command syntax text..

Example of previous functionality:
```
    -d, --date <YYYY-MM-DD>      select date
    -t, --time <HH:MM>           select time

        Time can also be specified using special values:

        "dawn" - From night to sunrise.
        "sunrise" - Time around sunrise.
        "morning" - From sunrise to noon.
        ...
```

.. and after the change:
```
    -d, --date <YYYY-MM-DD>      select date
    -t, --time <HH:MM>           select time

                                 Time can also be specified using special values
:

                                 "dawn" - From night to sunrise.
                                 "sunrise" - Time around sunrise.
                                 "morning" - From sunrise to noon.
                                 ...
```

**Comment by zhiyelee** [comment]
Sorry, seems that I't a break change.  I think it should be revert, what's your opinion  @SomeKittens ?

**Comment by SomeKittens** [comment]
Yes, this is a bug, should be reverted.  Sorry about that.
