### ISSUE TITLE
Booleans are not converted by default

### ISSUE THREAD

**Issue by ensonic** [tj/commander.js#399]
See https://gist.github.com/ensonic/5a4d727cbc6f5fc36655

If that is WAI, should it be mentioned in the docs?

**Comment by SomeKittens** [comment]
Yes, this is WAI, and should be in the docs.  Nice catch.

As a sidenote, I don't have CS installed, so it's a lot easier if you submit bug reports in JS.

**Comment by ensonic** [comment]
Here you are:
https://gist.github.com/ensonic/60b8fc278da53b2dde45

**Comment by SimplGy** [comment]
I am not clear if this is the same issue I'm working on. For me, boolean flags are not correctly converted from `undefined` into `false`. This messes up some downstream build processes.

    program.option('-b, --is-blue', 'The color should be blue')
    program.isBlue // `undefined`. would prefer `false`

I'm trying to find a workaround to this. Tried passing a parser to the `fn` third argument:

    program.option('-b, --is-blue', 'The color should be blue', Boolean, false);

Then I tried writing my own "parser"

        program.option('-b, --is-blue', 'The color should be blue', function(x){ return !!x }, false);

Any tips?
