### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by Desmodue** [tj/commander.js#401]
Hi

I am getting this error

(node) warning: possible EventEmitter memory leak detected. 11  listeners added. Use emitter.setMaxListeners() to increase limit.

Node v0.12.2
commander v2.8.1, also had it in v2.3.0

It is resolved by adding  self.setMaxListeners(0); at line 213 in index.js.
However I do not know enough to know whether this is the best place to put the statement in the application or whether it works for all tests.

Gary

**Comment by SomeKittens** [comment]
Can you provide some sample code which repros this?

**Comment by Desmodue** [comment]
I am using forever-service
https://github.com/zapty/forever-service

commander is a module used by forever-service
On Debian 7 when using forever-service to create startup scripts, I get the error
'(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.'

This is how forever-service is called
forever-service install flashconnectbridge --script bin/www -e "PATH=/usr/local/bin:\$PATH NODE_ENV=production PORT=3000" --logrotateFrequency daily -u
forever-service version 0.4.6

The trace I get is

Trace
    at Command.addListener (events.js:179:15)
    at Command.option (/usr/local/lib/node_modules/forever-service/node_modules/commander/index.js:327:8)
    at /usr/local/lib/node_modules/forever-service/bin/forever-service:40:4
    at Walker.<anonymous> (/usr/local/lib/node_modules/forever-service/lib/platforms.js:28:3)
    at Walker.emit (events.js:104:17)
    at Walker.doneOne (/usr/local/lib/node_modules/forever-service/node_modules/walker/lib/walker.js:109:35)
    at /usr/local/lib/node_modules/forever-service/node_modules/walker/lib/walker.js:99:12
    at FSReqWrap.oncomplete (fs.js:95:15)
Platform - Debian GNU/Linux 7 (wheezy)

Thinking about it now, it could be the way that forever-service uses commander ?
Maybe I should have started with forever-service first ?
I can reproduce this on all of my Debian instances.

**Comment by SomeKittens** [comment]
Yes, file this against forever-sevice.  Thanks!

**Comment by mouramario** [comment]
Try using: program.removeAllListeners();
from: [581](https://github.com/tj/commander.js/issues/581#issuecomment-416642980)
