### ISSUE TITLE
Alias support for Git-style sub-commands

### ISSUE THREAD

**Issue by wayneashleyberry** [tj/commander.js#402]
Aliases don't seem to work _at all_ when using subcommands...

**Comment by SomeKittens** [comment]
Can you provide an example?

**Comment by wayneashleyberry** [comment]
```js
#!/usr/bin/env node
// example.js
var app = require('commander')

app
  .version('1.0.0')
  .command('foo', '...').alias('f')
  .command('bar', '...').alias('b')
  .command('baz', '...').alias('bz')
  .parse(process.argv)
```

```js
#!/usr/bin/env node
// example-foo.js
console.log('hello foo')
```

```sh
$ ./example.js foo // hello foo
$ ./example.js f // nothing...
```

**Comment by leesei** [comment]
It should be "Alias support for Git-style sub-commands".

**Comment by SpencerCDixon** [comment]
Any plans on adding this/would authors be open to a PR?

**Comment by zhiyelee** [comment]
PR is welcome!

**Comment by jontonsoup** [comment]
Did we determine if this is a bug or lack of feature? The label says bug, but the docs are unclear.

**Comment by hedgerh** [comment]
For anyone wondering, a fix for this has been merged into master, but the fix has not been published to npm.

In the meantime, I'm pointing my dependency to the repo:
```
"commander": "git+https://github.com/tj/commander.js.git"
```

**Comment by philostler** [comment]
+1 for releasing with this fix

**Comment by rt2zz** [comment]
@SomeKittens any chance we can get a new release?
