### ISSUE TITLE
Have an option as a DEFAULT argument

### ISSUE THREAD

**Issue by bradparks** [tj/commander.js#403]
I think often given the unix philosophy of "do one thing well", I'd like to have a command line app that accepts a single simple argument, for example the following which would mute the system volume with an argument of true or false.

`mute {true|false}`
`mute`, which would default to `mute true`

There should be a way to specify an `option` as a default, so if no options are recognized, but there is an argument, it's assumed to be the value for the option.

Here's my example code that I had to do to get this working:

```
program
  .version('0.0.1')
  .option('s [name]', 'test me')
  .parse(process.argv);

if (process.argv.length == 3 && ! program.s)
{
  program.s = process.argv[2];
}
else if (! program.s)
{
  program.s = 'true';
}
```

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
