### ISSUE TITLE
Conflict with collections module when using "all" parameter

### ISSUE THREAD

**Issue by c-geek** [tj/commander.js#407]
Hi.

I encounter the following problem:

```
$ ./supersoftware reset all
all
execvp(): No such file or directory

  supersoftware-all(1) does not exist, try --help
```

This is due to a conflict with an external module [collections.js](https://github.com/montagejs/collections):

```js
#!/usr/bin/env node
"use strict";
var program = require('commander');
require('collections/set'); // <----- Here is the collision

program
  .version('0.0.1')
  .usage('<command> [options]')
;

program
  .command('reset <what>')
  .description('Reset some parameter')
  .action(function (what) {
    console.log(what);
  });

program.parse(process.argv);
```

Indeed, `collections` define an `all` method on Arrays, which conflicts with the `all` parameter I use in my command.

A turnaround is to lazy initialize `collections` so Commander is not polluted:

```js
#!/usr/bin/env node
"use strict";
var program = require('commander');

program
  .version('0.0.1')
  .usage('<command> [options]')
;

program
  .command('reset <what>')
  .description('Reset some parameter')
  .action(function (what) {
    console.log(what);
    setTimeout(function() {
      require('collections/set');
    }, 10);
  });

program.parse(process.argv);
```

But more deeply, the problem comes from Commander code to me, since the bug is [here](https://github.com/tj/commander.js/blob/master/index.js#L86):

```
function Command(name) {
  this.commands = [];
  this.options = [];
  this._execs = []; // <---- this
  this._args = [];
  this._name = name;
}
```

And then [here](https://github.com/tj/commander.js/blob/master/index.js#L167):
```
if (desc) this._execs[cmd._name] = true;
```

Why using `Array` as an object? Replacing `[]` by `{}` completely solves the problem.

**Comment by zhiyelee** [comment]
Good catch. But I don't think it's a good practice  to add function to `Array.prototype`.
