### ISSUE TITLE
how do I kill subcommands?

### ISSUE THREAD

**Issue by jhoguet** [tj/commander.js#409]
I have a test which effectively does this

```js
var ps = spawn('command', ['sub']);

//... after some time
ps.kill();
```

the command process gets killed but not the child process `command-sub`

at the shell `command sub` and then ctr+c kills both properly. 

How do I kill sub commands from spawn? 

PS - loving commander! excellent work!

**Comment by jhoguet** [comment]
found a solution [here](http://azimi.me/2014/12/31/kill-child_process-node-js.html). 

```js
var ps = spawn('command', ['sub']);
//... after some time
process.kill(-ps.pid);
```

note calling `process.kill` and not `ps.kill` and note `-ps.pid` and not just `ps.pid` which is what gets it to kill the children.

**Comment by zhiyelee** [comment]
Great, thank you for the update @jhoguet

**Comment by tonylukasavage** [comment]
FYI, if you invoke your tests programmatically instead of subprocessing with `spawn()`, you can use the property `runningCommand` to access the child process launched after `parse()`.

**Comment by jhoguet** [comment]
@tonylukasavage that sounds much better, how do I `parse` instead of `spawn`?

**Comment by tonylukasavage** [comment]
You'd have to invoke commander directly to execute you command. This is a wildly impractical example, but let's you know how you can use the `runningCommand` property of commands.

```
var program = require('commander');

program
	.description('runningCommand test')
	.command('foo', 'the foo command to be killed');

program.parse(process.argv);

program.runningCommand.on('exit', function(code) {
	console.log('data from foo: ' + code);
});

// program.runningCommand.kill();
```

**Comment by jhoguet** [comment]
thanks for the example

**Comment by zhiyelee** [comment]
thanks @tonylukasavage ! This should be append to the doc OR README better.

**Comment by tonylukasavage** [comment]
yeah, i agree, dug through the source and just happened upon `runningCommand` at one point
