### ISSUE TITLE
program --help is broken

### ISSUE THREAD

**Issue by jadbox** [tj/commander.js#422]
I'm getting this error when trying to get help for any program on it's base command. For example: "./myapp --help" doesn't work but "./myapp cmd --help" does work.

Error:
../node_modules/commander/index.js:945
    , cmd.description()
          ^
TypeError: Property 'description' of object #<Command> is not a function

**Comment by jadbox** [comment]
I was able to patch the problem by changing this in the source...
Line 936   
 return [
      cmd._name
        + (cmd._alias
          ? '|' + cmd._alias
          : '')
        + (cmd.options.length
          ? ' [options]'
          : '')
        + ' ' + args
    , cmd._description  // WAS cmd.description()
    ];

**Comment by jadbox** [comment]
Any updates on this?

**Comment by SomeKittens** [comment]
This is odd.  Open a PR?

**Comment by jadbox** [comment]
Odd indeed. I don't think I'll have time to open a PR for this one... I've since needed to deviate a bit from head.

**Comment by jadbox** [comment]
node --version
v0.10.38

**Comment by ignacioiglesias** [comment]
@jadbox did your command take a `--description`?

**Comment by SomeKittens** [comment]
Fixed in above PR, thanks @ignacioiglesias !
