### ISSUE TITLE
default command parsing with gulp

### ISSUE THREAD

**Issue by madcapnmckay** [tj/commander.js#428]
I'm trying to use commander with gulp to pass optional params to our task builder like so.

``` javascript
commander.command('build').
            description('builds the UI').
            option('-a, --automated', 'Enables automation capabilities').
            option('-p, --production', 'Build for production environment').
            option('-W, --no-watch', 'Disable watchify functionality').
            action(function(cmdArgs) {
                gulp.task('build', buildUI(props, cmdArgs));
            });
```

The problem is that if 'build' is set as the default gulp command then action callback never fires.

Is there a way to get this scenario to work? In the default scenario the command is empty but I still want the command parser to fire.

**Comment by SomeKittens** [comment]
What command are you passing into the CLI?

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
