### ISSUE TITLE
Multiple options bug

### ISSUE THREAD

**Issue by a-x-** [tj/commander.js#430]
if i set three of option's aliases:
`option('-n, -B, --no-cache', foo)`

then i receive:
```
error: unknown option `--no-cache'
```

What am I doing wrong?

**Comment by zhiyelee** [comment]
should use this pattern `.option('-p, --peppers', 'Add peppers')`   `-x` for short,  `--xxx` for long, split with `[ ,|]`

**Comment by a-x-** [comment]
Can i set more then one alias?

**Comment by zhiyelee** [comment]
Unfortunately not, now we can only set alias for sub command till now.
