### ISSUE TITLE
3.0？

### ISSUE THREAD

**Issue by zhiyelee** [tj/commander.js#431]
Plan to develop 3.0, with break change, will 
- solve name collision issue #404 
- only support Node version above v0.8 or v0.10

Any suggestions?

**Comment by SomeKittens** [comment]
Very much in favor of fixing #404.  We'll need a `legacy` branch to keep track of 2.x fixes.

**Comment by ls12styler** [comment]
Can I vote for fixed sub-commands and #414 & #441

**Comment by ls12styler** [comment]
Also, what about only support node v4?

**Comment by vanesyan** [comment]
close in favor of #666
