### ISSUE TITLE
Can't use --version in custom options

### ISSUE THREAD

**Issue by snaideros** [tj/commander.js#437]
Hi,

When I'm trying to use the feature overloading the **-V, --version** default behavior as I need **-v, --version** somewhere else, I face an issue because it displays the version whatever I do.

I think it comes from the fact the 'version' event is not customized according to the custom version flags chosen (in my case I wanted to reduce it to **-V**). This makes --version in my context emit the 'version' event that displays the version instead of the expected behavior.

Thanks for this awesome module.
BRs
Sébastien

**Comment by abetomo** [comment]
Is this a reference?
https://github.com/tj/commander.js#version-option

**Comment by shadowspawn** [comment]
There have been a couple of improvements in this area, and likely a stale issue now.
