### ISSUE TITLE
Newbie friendly help --help

### ISSUE THREAD

**Issue by AljoschaMeyer** [tj/commander.js#439]
Right now `help --help` only helps people who already know how a typical cli works. Which seems rather pointless.

Wouldn't it be sensible to instead display a more human-readable explanation of the basics of a cli, i.e:
- give instructions via commands, run command by typing it in the console and hitting return
- what are options? why do some have more trailing hyphens? can I combine them?
- what are arguments?
- what do these strange brackets (`<foo>`, `[bar]`) and dots (`<baz...>`) mean?

Also, the last message of the normal `help` function could be an explanation of how to access this information, e.g. `If you are unsure what all this stuff means, type 'help --help' and press enter`.

These changes would make programs more easily accessible for users who might not be as familiar with the command line as the average programmer.

**Comment by yaycmyk** [comment]
+1 Would love to know what the differences are between brackets and angle brackets when interpreting a given option scheme

**Comment by pmbenjamin** [comment]
@yaycmyk, traditionally angled brackets (e.g. <required>) indicates a required option/flag, while square brackets (e.g. [optional]) indicates an optional option/flag.

Here is the source code of the commander.js package:
```
function Option(flags, description) {
  this.flags = flags;
  this.required = ~flags.indexOf('<');
  this.optional = ~flags.indexOf('[');
  this.bool = !~flags.indexOf('-no-');
  flags = flags.split(/[ ,|]+/);
  if (flags.length > 1 && !/^[[<]/.test(flags[1])) this.short = flags.shift();
  this.long = flags.shift();
  this.description = description || '';
}
```

**Comment by zhiyelee** [comment]
Any help on the document is welcome~

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
