### ISSUE TITLE
Mandatory flags

### ISSUE THREAD

**Issue by grahamb** [tj/commander.js#44]
Commander supports required values for flags (`.option('-f --foo <foo>', 'the value of foo)`) but there doesn't appear to be a built-in way of making a flag itself required/mandatory.

Example:

```
var program = require('commander');

program
    .version('0.0.1')
    .option('-f --foo <foo>', 'Foo is required')
    .parse(process.argv);


console.log(program.foo);
```

Output:

```
$ node test.js -f bar
// outputs "bar", good

$ node test.js -f
// outputs "error: option `-f --foo <foo>' argument missing", good

$ node test.js
// outputs "undefined", not good; should output "error: required option `-f -foo <foo>' is missing" or similar
```

**Comment by danse** [comment]
If i get this correctly, there is not a way to have mandatory command line arguments still. This seems pretty important, especially given how devastating `undefined` values can be in a Javascript program

**Comment by mralexgray** [comment]
+1, why was this closed?

**Comment by marcelofarias** [comment]
Submitted https://github.com/tj/commander.js/pull/462. Mentioned here: https://github.com/tj/commander.js/issues/230.

**Comment by axelpale** [comment]
+1

**Comment by bennyn** [comment]
```bash
$ node test.js -f
// outputs "error: option `-f --foo <foo>' argument missing", good
```

How do you make a program fail when a mandatory argument is missing? 

For me it just runs through which I would like to avoid:

```ts
#!/usr/bin/env node

import program from 'commander';

const pkg = require('../package.json');
const appName = Object.keys(pkg.bin)[0];

program
  .description(pkg.description)
  .name(appName)
  .option('-c, --config <path>', 'set path to configuration file')
  .version(pkg.version)
  .parse(process.argv);

console.log('Program does not crash and value is "undefined".', program.config);
```

Tested with `commander` v2.19.0.

**Comment by vedmant** [comment]
This is one of first things I needed from this package and it's still not here?

**Comment by shadowspawn** [comment]
@vedmant Not yet. See #230 for the open issue.

**Comment by shadowspawn** [comment]
See `.requiredOption()`
