### ISSUE TITLE
Explicitly return when an error occurs

### ISSUE THREAD

**Issue by plemarquand** [tj/commander.js#443]
Methods that rely on error methods (such as `unknownOption`, `missingArgument`, etc...) use `process.exit()` to stop execution and exit the program. This is quite inconvenient if you want to use Commander in a context other than a shell.

If a client extends the Command prototype to avoid having these error methods call `process.exit()`, command execution continues and commander blows up.

Personally I am using commander to parse arguments for my Slack bot, extending Command to prevent `process.exit()`s but even still if you input an incorrect command the program will crash.

**Comment by SomeKittens** [comment]
Thanks for this!  Can you write a few tests showing this code works?

**Comment by plemarquand** [comment]
@SomeKittens Hi, I've updated the patch with some relevant tests.

**Comment by shadowspawn** [comment]
Referenced from #945 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
