### ISSUE TITLE
.action vs .on for commands/subcommands

### ISSUE THREAD

**Issue by LestaD** [tj/commander.js#451]
Hello, i need subcommands

First example `demo.js`:

```js
#!/usr/bin/env node

var program = require('commander');

program.version('0.1.12');

program.command('install', 'Install your demo')
  .action(function() {
    console.log('Start install');
    // code of action
  });

program.parse(process.argv);
```

```bash
> ./demo.js install

Start install

  demo-install(1) does not exist, try --help
```

**Comment by LestaD** [comment]
And second question:
How can i make this commands:

```bash
demo glob
demo glob install
demo glob install <name>
demo glob uninstall <name>
demo glob purge
```

**Comment by SomeKittens** [comment]
Hello!  The issue section is for reporting bugs with commander.js, not for technical help.  If you've got a question, your best bet is to ask on StackOverflow.  If you think you've found a bug, we can reopen this.

As to your first question, as said in the docs:

> When `.command()` is invoked with a description argument, no `.action(callback)` should be called to handle sub-commands, otherwise there will be an error.
