### ISSUE TITLE
Problem with `.*`

### ISSUE THREAD

**Issue by tjbenton** [tj/commander.js#452]
I have a option for globs and when I try to select all the dot files `.*` it only returns `.` instead of returning `.*`. I can currently get around it by adding a trailing comma or put it in quotes. It seems to be fine with other instances though.

![commander-screenshot](https://cloud.githubusercontent.com/assets/4776422/10431320/688fd94a-70d2-11e5-8230-40ae19efbd6d.jpg)

**Comment by SomeKittens** [comment]
The correct way to do this would be to put it in single quotes, as in your third example.  Otherwise the command line will think you're trying to pass in the *result* of calling `.*`, instead of literally that.
