### ISSUE TITLE
linter?

### ISSUE THREAD

**Issue by tejasmanohar** [tj/commander.js#459]
thoughts on adding a linter? maybe through [standard](https://github.com/feross/standard) or eslint

i'd be up for pr'ing this

**Comment by tejasmanohar** [comment]
i no longer wanna pr this haha, sorry :\- would recommend opening another issue if you do

**Comment by prometheas** [comment]
I'm just OCD enough to take it on, but I'd definitely want guidance from the maintainer on what rules to go with. I find the [airbnb/javascript](https://github.com/airbnb/javascript) to be great, but it'd ultimately be up to @tj.
