### ISSUE TITLE
Custom command name in --help?

### ISSUE THREAD

**Issue by gocreating** [tj/commander.js#466]
I named my cli `sd` in package.json, but here shows the wrong help message `Usage: index [options] [command]`
now the command name is parsed from file name, is there a way to customize it?

```
$ node cli/index.js -h

  Usage: index [options] [command]


  Commands:

    serve|s   launch exseed app

  Options:

    -h, --help       output usage information
    -V, --version    output the version number
    -e, --env <env>  specify environment (development|test|production)
```

now the way I fix this is replacing process.argv[1] before program.parse:

```
process.argv[1] = 'sd';
program.parse(process.argv);
```

I think there should be another better way

**Comment by martellaj** [comment]
It looks like this has been [discussed, fixed, and then reverted in the past](https://github.com/tj/commander.js/pull/264#issuecomment-56965147). What's the current state of this? The README has examples with custom names, but can't figure how to do it either (other than the solution @gocreating posted). Any guidance?

**Comment by gocreating** [comment]
@martellaj I think we are talking about different things. Let's take `git` for example.
I want to change the main command `git` to another word like `yothisismygit`.
However, what the previously merged PR done is about subcommands like `commit` of `git commit` or `push` of `git push`.
Right?

**Comment by martellaj** [comment]
Well the `Usage: index` line printed for commander help is independent of how you can use your app on the command line. If you want to change how you execute, add the following to your package.json.

```
"bin": {
    "what-you-want-to-execute-with": "./path/to/your/main/file.js"
  }
```

**Comment by GnaspGames** [comment]
@martellaj You comment doesn't seem to be correct. The `usage: name` output doesn't appear to be changed when using bin in the package.json. It still displays the name of the .js file rather than the command name.

**Comment by ZanderBrown** [comment]
Any progress on this?

**Comment by elliotleelewis** [comment]
You can use the `.name` method on your program object. Like so...

```
program
    .name('test')
    .usage('<src>');
```

Then the output would be:

```
Usage: test <src>
```

Hope this helps 😀

**Comment by vanesyan** [comment]
Use appropriated `.name` method, as described above. Close it.

**Comment by vanesyan** [comment]
Feel free to reopen the issue, if still persist.

**Comment by dienluong** [comment]
I was trying to figure this out too. The API documentation didn't help because it was so dated.  I would update it myself (at least the name() part) if I knew how...
