### ISSUE TITLE
How to add an Enum Data for choice

### ISSUE THREAD

**Issue by lichenhao** [tj/commander.js#467]
RT， How can I add a list for Enum with choice action.

**Comment by gabrielcsapo** [comment]
@tj is this a feature that you would be okay with someone creating a PR for?

**Comment by bagage** [comment]
@vanesyan could it be considered? Eg. having a `choice` or equivalent select mode?

**Comment by shadowspawn** [comment]
Closing in favour of #518 which I think is covering similar request with more detail.
