### ISSUE TITLE
Use an option for a subcommand

### ISSUE THREAD

**Issue by marcofranssen** [tj/commander.js#468]
Is it possible to specify an option in your main command in order to reuse it for all your subcommands.
So basically the subcommands all require the same option.

Do I have to specify the option in each subcommand?

This is what I tried.

generate

``` javascript
program
    .version('0.0.1')
    .command('users <inputfile> [otherInputfiles...]', 'generate users based on the input files')
    .option('--hostname, -h', 'hostname')
    .parse(process.argv);
```

generate-users

``` javascript
program
    .arguments('<inputfile> [otherInputfiles...]')
    .action(function (inputfile, otherInputfiles) {
        inputfiles = [inputfile];
        inputfiles = inputfiles.concat(otherInputfiles);
    })
    .parse(process.argv);

console.log(program.hostname);
// here is more code processing the arguments
```

Is it just not possible or do I have to achieve that differently.

**Comment by dcbartlett** [comment]
With the way that the system is calling the sub-commands with this setup, each program is in its own scope/node container.  This means that the reading of the options has to be done in each sub-command. So while its annoying to have to parse the arguments and options in each command that needs them (I.E. all of them for your case), we don't have a better option at this time.

At least this is what i've run into myself.

**Comment by b4dnewz** [comment]
thanks for your explaination @dcbartlett, so is not possible to do something like this? I'm having this issue right now.

_pm.js_
```js
program
  .name('cli')
  .option('-k, --key <apikey>')
```

_pm-foo.js_
```js
program
  .command('list')
  .option('-l, --limit')
  .action(options => {
    console.log(program);
    console.log(options);
    console.log(program.options);
    console.log(program.apikey);
})
```

`cli -k 'ABCD' list `

the apikey from the "root" command?

**Comment by shadowspawn** [comment]
Good explanation of current situation from @dcbartlett 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
