### ISSUE TITLE
A way to override the version and help message

### ISSUE THREAD

**Issue by jeromedecoster** [tj/commander.js#47]
Hello,

It can be nice to have the possibility to modify the default version message 'output the version number'
and the default help message 'output usage information'

Thanks

**Comment by fegemo** [comment]
+1 to this

**Comment by digitalsadhu** [comment]
+1

**Comment by zhiyelee** [comment]
Sound good. PR on this is welcome

**Comment by hb20007** [comment]
It would also be nice to be able to override error messages, e.g., for custom formatting of messages like "error: missing required argument `name'".

**Comment by shadowspawn** [comment]
This issue will be resolved when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
Support for customising the version and help descriptions has shipped in v3 (thanks @idmontie): https://github.com/tj/commander.js/releases/tag/v3.0.0

Closing the oldest open bug. Woop!
