### ISSUE TITLE
'version' is interpreted as '--version'

### ISSUE THREAD

**Issue by fatso83** [tj/commander.js#471]
According to the docs, only "my-cmd --version" should output the version number, but I have found that commander also picks up the string 'version' anywhere in the arguments.

As an example of where this causes problems, you can have a look at a little utility I wrote called [pick_json](https://github.com/fatso83/pick_json/blob/master/pick_json.js#L25). It is used it to extract fields from json on stdin.

```
$ echo '{ "name" : "myapp", "version" : "3.4.5" }' > appinfo.json

$ pick_json name < appinfo.json
myapp

$ pick_json version < appinfo.json  #WTF moment
1.1.2

$ pick_json --version
1.1.2
```

As you can see, instead of picking the version field from the json, it shows the version number of `pick_json`. This is not inline with the docs.

**Comment by SomeKittens** [comment]
Does the bug still happen if you put `version` in quotes?

**Comment by fatso83** [comment]
Yup

```
carl-erik at timbuktu in ~/kode/pick_json  (master)
$ pick_json "version" < appinfo.json
1.1.1

carl-erik at timbuktu in ~/kode/pick_json  (master)
$ pick_json 'version' < appinfo.json
1.1.1
```

But that really does not come as a surprise, as the shell does the unescaping. I can escape the quotes, as in `pick_json '"version"'`, but then you are already way into hack and slash programming to work around the bug.

**Comment by SomeKittens** [comment]
Yup, definitely a bug on our side.

**Comment by fatso83** [comment]
I looked at the source, and it happens due to the logic in parseOptions and parseArgs that does away with the dashes, and subsequently "--version" and "version" both emits the same signal.

Not totally sure how to fix this in a nice way.

**Comment by fatso83** [comment]
Maybe `Option`s should have a [prefixed name](https://github.com/tj/commander.js/blob/master/index.js#L57) to avoid overlapping event names? I understand that this might be troublesome due to the logic involving the "--no-" prefixes.

Whatever the solution might be, "--version" and "version" should result in two different event names.
