### ISSUE TITLE
default option coercion 

### ISSUE THREAD

**Issue by jdavisclark** [tj/commander.js#474]
is there any way to set up a default coercion function for options?

if all my options are strings, and i need to trim/sanitize every one, it would be really  nice to only have to set up a coercion function once.

**Comment by SomeKittens** [comment]
There is not, you'll need to define it each time.

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
