### ISSUE TITLE
Variadic arguments also parse things after `--`

### ISSUE THREAD

**Issue by Unitech** [tj/commander.js#475]
I'm implementing [multi script start into PM2](https://github.com/Unitech/pm2/issues/1825) with the variadic arguments feature. It works well but everything after `--` is also interpreted as an argument

```
$ pm2 start script1.js script2.js    # OK
Start script1.js
Start script2.js

$ pm2 start script1.js -- options1 # NOK
Start script1.js
Start options1  # This should not be there
```

**Comment by Unitech** [comment]
Do literal arguments should be pushed to the argument list [here](https://github.com/tj/commander.js/blob/master/index.js#L677)?

**Comment by zhiyelee** [comment]
Thanks, I will check that. And a PR is also welcome @Unitech

**Comment by Unitech** [comment]
Currently I've just commented out the args.push when litterral is detected

https://github.com/Unitech/commander.js/commit/f0be848d9fb94431a7ff84c7e968b465fbdc7857

Should I send a PR with this?

**Comment by Unitech** [comment]
not related to commander.js, cheers!

**Comment by tizmagik** [comment]
@Unitech why was this closed? I'm having a similar issue and wondering if a fix like that should be PR'd in to commander? Or have you found another solution?
