### ISSUE TITLE
Global Options

### ISSUE THREAD

**Issue by alex-phillips** [tj/commander.js#476]
Is there a way to add global options to a program that is applied to all commands? I'm trying to be able to define a single `verbose` and `quiet` flag that is applied not only to the `program` but to all commands added as well.

I can post sample code if necessary, but I think it's fairly self-explanatory.

**Comment by leesei** [comment]
```sh
Program
  .version(Pkg.version)
  .description(Pkg.description)
  .options('-v, --verbose', 'be verbose')
  .option('-q, --quiet', 'be quiet')


Program
  .command('search <query>')
  .description('do search')
  .option('-r, --regex', 'use regex')
  .action(function search (query, options) {
    // Program.quite
    // options.regex
  });
```

**Comment by donaldpipowitch** [comment]
Can I write a default action for an option? It is quite nice that I can create a "global option" which is passed to every command, but if I have many commands I don't want to call `loggingFramework.setLogLevel(options.quite)` everywhere.

I can't do `commander.parse(process.argv); commander.opts();`, because then the commands action is called _before_ I can do something with `opts`. But it looks I need to call `parse` before I can use options correctly.

**Comment by thetutlage** [comment]
@donaldpipowitch Going through the source code and found this line. https://github.com/tj/commander.js/blob/master/index.js#L393

It seems to be possible as

```js
Program.on('verbose', function () {
  process.env.VERBOSE = this.verbose
})

Program.on('quiet', function () {
  process.env.QUIET = this.quiet
})
```

Also for options has accept values, the value is passed to the callback function. For example

```js
Program.on('env', function (env) {
  process.env.NODE_ENV = env
})
```

```bash
some-command --env=production
```

**Comment by donaldpipowitch** [comment]
Cool, thanks.

**Comment by daldridge-cs** [comment]
So global options work in the scenario above, but they do *not* get propagated to sub-commands.  [This line](https://github.com/tj/commander.js/blob/master/index.js#L551) in `Command.prototype.executeSubCommand` only takes sub-command args.

If that line were changed from
```
args = args.slice(1);
```
to
```
args = argv.slice(2, argv.length - args.length).concat(args.slice(1));
```
then sub-commands would be forwarded those global options.

**Comment by shadowspawn** [comment]
The original question got answered, and I don't think there will be action due to the subsequent comments.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Opened poll on possible enhancements to global options: #1551

**Comment by percenuage** [comment]
Hello, I think it should be a better if the global options are merged with local options in order to access it when we use a different file for commands. See an example: 
```js
program
  .version(version, '-v, --version', 'Output the current version')
  .option('-g, --global', 'Global')

program
  .command('sh')
  .option('-l, --local', 'Local')
  .action(function (args) {
    console.log(args.local) // true
    console.log(program.global) // true
    console.log(args.global) // Should be "true" as well but it's "undefined"
  });
```
I'm using commander v8.2

**Comment by jerrywithaz** [comment]
This is my work around at the moment:

```js
class CustomCommand extends Command {
  constructor(...args) {
    super(...args);
    this.addBucketOption(); // adds the option for all commands created
  }

  createCommand(...args) {
    return new CustomCommand(...args);
  }

  addBucketOption() {
    return this.option(
      '--bucket <name>',
      'The google cloud storage bucket to download backups from.',
      backup_bucket
    );
  }
  }
}

const program = new CustomCommand('my-program');
```

**Comment by shadowspawn** [comment]
Opened a draft PR for `.addCommonOption()` #1670

**Comment by WoZ** [comment]
For everyone who tries to find the right way to access the global options in the action handler...

Here is a working example for version 11+

```javascript
const program = new Command();
program.description('Tool to analyze Feed data');
program.addOption(new Option('--loglevel <loglevel>', 'Logging level').choices(['debug', 'info', 'warn', 'error']).default('error'));

program
    .command('history')
    .description('Generates history')
    .addOption(new Option('--offset <offset>', 'Offset to start from').default(0))
    .action(args => {
        console.log(program.opts());
        console.log(args);
    });

program.parse();
```

The output is

```bash
$ node analyze.js --loglevel info history 
{ loglevel: 'info' }
{ offset: 0 }

```

**Comment by shadowspawn** [comment]
Another approach now available is `.optsWithGlobals()` to combine the global and local options:

```
   .action((options, cmd) => {
      console.log(options);
      console.log(cmd.optsWithGlobals());
}
```

**Comment by teto** [comment]
maybe because I had positional args as well but I had to do: 
```
   .action((options, cmd, toto) => {
      console.log(options);
      console.log(cmd);
      console.log(toto.optsWithGlobals());
    })
```
