### ISSUE TITLE
Support callback for subcommand instead of different binary

### ISSUE THREAD

**Issue by opatut** [tj/commander.js#477]
I'd like to structure my application myself. I'd like to supply a function that is called with the arguments instead of having to supply a binary with the correct name. My subcommands are usually one-liners, this would cut down on small files significantly for me.

In the subcommand I could "recursively" use the supplied args and create sub-subcommands. That'd be fun :)

Also, I'd love to have access to the "parent" parsed arguments when running the subcommand, so in

    ./my-cli --parent-arg 42 subcommand --child-arg 1337

I could fetch the `parent-arg` when the subcommand is invoked. I suggest:

    function subcommandCallback(args) { // ... }

Where `args` contains the special key `_parent` with the parent command's arguments. Also, recursively.

**Comment by hildjj** [comment]
Look at the deploy example: https://github.com/tj/commander.js/blob/master/examples/deploy

It took me a couple of tries to parse through the documentation to understand what that example is doing.  The action for each command gets an `options` parameter that is almost exactly what you want, with a `options.parent` that contains the top-level options.  each call to `command` starts a new chain, where the options set in that chain only apply to that command -- this is why each command definition starts with `program` again.

**Comment by opatut** [comment]
Aahh, nevermind. Within this jungle of command line parsers I skipped most of the README and headed straight for the "git-style subcommand" part -- did not see the normal `.command().action()` chains above. I thought having git-style binaries for handling subcommands was obligatory, not optional. Actually love the `.command().action()` semantics. :+1:
