### ISSUE TITLE
alias for options

### ISSUE THREAD

**Issue by dashmug** [tj/commander.js#479]
Is it possible to use add aliases to options?

e.g.

```
program
  .version('0.0.1')
  .option('-T, --no-tests, --notests', 'ignore test hook')
```

to support both `--no-tests` and `--notests`?

**Comment by zhiyelee** [comment]
Unfortunately, we can't now. Only have alias for command now.

PR is welcome for this. Thanks

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by glensc** [comment]
I was trying to figure out does this work, unfortunately it looks like this is supported (no errors) from help, but really the option does not work

```
➔ ./bin/console.ts push all --help
Usage: console push [options] <worker>

Invoke push for worker

Options:
  -v, --verbose                                Increase verbosity
  --limit <limit>                              Limit to <limit> iterations
  -f, --start-date <date>, --date-from <date>  Specify start date (default: "now")
  -t, --end-date <date>, --date-to <date>      Specify end date (default: "now")
  --id <articleId>                             Submit only these articles (default: [])
  -h, --help                                   display help for command

➔ ./bin/console.ts push all --date-from 'yesterday'
error: unknown option '--date-from'
```

**Comment by shadowspawn** [comment]
Commander supports a short option, a long option, or both. Commander does not support multiple short options or multiple long options. And does not currently have any error checking logic in the Option constructor, so no error message.

Support for a lone short option was added in Commander 6: #1256
