### ISSUE TITLE
Display a hint on how to open the help when entering a unknown switch

### ISSUE THREAD

**Issue by MoritzKn** [tj/commander.js#482]
For example: if I enter the `cp` command with a wrong switch, it displays how to show the help:

```
$ cp -y
cp: invalid option -- 'y'
Try 'cp --help' for more information.
```

If you don't want to hard code this, one option would be to give the programmer the ability to specifies an 'unknown option handler'.

**Comment by hongkongkiwi** [comment]
+1 for this

**Comment by jahbini** [comment]
function `allowUnknownOptions` has no discernable effect.  The default action on unknowns is to eat the next option.  calling `allowUnknownOptions(false)` should abort processing and show help if any funny flags are present.

**Comment by willxy** [comment]
+1 for this.  I want to be able to print out usage help when an unrecognized option is given.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Related: `.showHelpAfterError()` added in prerelease v8.0.0-2 by PR #1534
