### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by rygine** [tj/commander.js#485]
just wondering about the status of the project as i'm evaluating a few options for writing a CLI tool.

nothing major has been committed for at least 6 months. i see what looks like a bunch of abandoned PRs without clear resolution. the `3.0-dev` branch was last committed to over 2 years ago.

is this project in maintenance mode?

**Comment by zhiyelee** [comment]
Yep, @SomeKittens and I are still maintaining this project.
I planned to start v3 #431, but haven't started. 
Really busy on the project of my company recently. Will start that in later January.

**Comment by thethomaseffect** [comment]
That was my branch but my local version was getting a lot more complex than what's currently there and ultimately wasn't worth it, it doesn't mean there isn't active development going on. I've just been really busy with some health issues and other projects.
