### ISSUE TITLE
using same command and alias runs action twice

### ISSUE THREAD

**Issue by deian** [tj/commander.js#490]
Failure program:

``` javascript
'use strict';
const commander = require('commander');

commander.version('0.0.0').description('fun');

commander.command('fail')
         .alias('fail')
         .description('fail twice')
         .action(fail);

commander.parse(process.argv);

function fail() {
  console.log('Should print this once');
}
```

Running `node <program-name> fail` produces:

```
Should print this once
Should print this once
```

The problem is that the alias and command are the same thing (`'fail'`). Arguably this is bad program, but running `fail()` twice is very much unexpected. Throwing an exception if the alias is the same as the command may be more appropriate.

**Comment by SomeKittens** [comment]
Open a PR for the exception case, I think that's our best bet.
