### ISSUE TITLE
Display description and options before subcommands

### ISSUE THREAD

**Issue by leesei** [tj/commander.js#500]
See:
https://github.com/tj/commander.js/blob/master/index.js#L1004-L1008

The global description and options are shown _after_ the subcommands list.

**Comment by e-cloud** [comment]
+1, IMHO, the global description should be display above the subcommands list. But, options below subcommands are acceptable.

**Comment by ValentinTrinque** [comment]
I encountered this issue.

**Comment by jason0x43** [comment]
I agree that the top level description should go before the commands. However, I think the `[options] [command]` order is correct. The `[options]` at the top level are top-level options, not specific to a subcommand, so it's reasonable for them to come before the subcommand. Each subcommand description will also have its own `[options]` if it takes options (and those options would come after the subcommand).

**Comment by ValentinTrinque** [comment]
@jason0x43 :
> However, I think the [options] [command] order is correct.

I totally agree. The PR is ready since a while now though...

**Comment by ValentinTrinque** [comment]
Is there anyone to review this PR ? Any feedback or something ? Is it still maintained ?

It's been 3 months already... I think it's not cool for your maintainer to be so silent when there are willing to improve an open-source tool...
