### ISSUE TITLE
Recursive API

### ISSUE THREAD

**Issue by ccorcos** [tj/commander.js#507]
I like the whole subcommands idea, but I dont like how it reads your filesystem. If you want to create an extensible API, it would be awesome if you use node and `require` to require the commands you want. I'm imagining a recursive api. I'm imagining something like this:

```
const commander = require('commander')
const pizza = commander()
const tacos = commander()
const foods = {pizza, tacos}
const main = commander()

main.command('cook <food>').action(food => foods[food]).parse(process.argv)
```

And as such, you can chain commanders. `cook pizza` will essentially delegate everything on to the pizza commander. Its much like the current api except (1) you have to instantiate the commander program and (2) actions can return new commanders.

I think its quite elegant... just kinda sucks that its a breaking change...

**Comment by ericuldall** [comment]
If you're interested in a recursive solution, I just started a new project to fit my needs better. It allows subroutines which can be included with require.

https://www.npmjs.com/package/termoil

Any feedback is appreciated.

**Comment by ccorcos** [comment]
Nice @ericuldall! I've been working on a similar project myself:

https://github.com/ccorcos/cli

I used it as an opportunity to explore some category theory stuff -- check out the error messages :) -- but your implementation looks nice and lean!

**Comment by ericuldall** [comment]
Looks like some cool features in there @ccorcos :D

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
