### ISSUE TITLE
Provide Array of permitted values for an option.

### ISSUE THREAD

**Issue by joshuapinter** [tj/commander.js#518]
I have an `.option()` that is only allowed to be one of "all", "debug" or "none".

I'd like an easy way to pass an `Array` to an `option()` and have Commander automatically check that the value passed by the user is one of the permitted values. 

Something like this: 

``` js
.option('-t, --target <target>', 'Specifies the target.', ["all", "debug", "none"])
```

Also including the permitted values in the help output could be useful, provided it's not a very large `Array`.

I'd gladly do the PR if I can get a response from @tj or a collaborator that this is useful.

Thanks!!

**Comment by tmiddlet2666** [comment]
I second this, Would be great to be able to do this and validate options.

**Comment by shadowspawn** [comment]
The `.option` call is quite flexible already and it is not easy to add more functionality to the current signature. I am wondering about allowing building options to make it possible to add less common functionality without complicating the existing usage. See https://github.com/tj/commander.js/issues/1106#issuecomment-558379166

I have been wondering if there could be a collection of validators available from Commander to use as custom option processing functions, but my first attempts were a bit clumsy. For a crude example of bring-your-own validator: https://github.com/tj/commander.js/issues/1130#issuecomment-569565495

**Comment by shadowspawn** [comment]
I have been wondering about the syntax and here is one idea, fluent (chaining) calls on Option object like with Command object:

```
program
   .addOption(new Option('-t, --target <target>', 'Specifies the target (all | debug | none).')
      .valueIncludedIn(["all", "debug", "none"])
   )
);
```

**Comment by shadowspawn** [comment]
And another idea, convenience routines for custom option processing with existing api:

```js
program
   .option( '-t, --target <target>', 
      'Specifies the target (all | debug | none).', 
      OptionType.includedIn(["all", "debug", "none"])()
   )
...

(I used `OptionType` here but the other name I considered was `OptionValue`.)

**Comment by shadowspawn** [comment]
Related link from https://github.com/tj/commander.js/issues/215#issuecomment-660456539

Python argparser has `choices` for restricting allowed values: https://docs.python.org/3/library/argparse.html#choices

**Comment by shadowspawn** [comment]
Experimenting with Option approach in #1331:

```js
program
   .addOption(new Option('-s, --size <value>').choices(['big', 'little']));
```

**Comment by shadowspawn** [comment]
Included in v7.0.0 pre-release #1386

**Comment by lydell** [comment]
I might be late to the game, but what if you could return or throw an error in the coercion function? Then you could do any validation you want. commander would automatically generate the error message. `` `--the-flag: ${error.message}` ``

**Comment by shadowspawn** [comment]
Using an exception is actually the approach I took for the choice method, see `commander.optionArgumentRejected` at:

- https://github.com/tj/commander.js/blob/5b98fc8d715c124062469646b752aa4e9b1dfd57/index.js#L432
- https://github.com/tj/commander.js/blob/5b98fc8d715c124062469646b752aa4e9b1dfd57/index.js#L969

But I had not thought of adding the option name in the catch rather than the throw. That would be a solution to #1207

**Comment by shadowspawn** [comment]
Included in Commander 7.0.0.

**Comment by joshuapinter** [comment]
Nice work @shadowspawn! I'll try and make some time to give this a go.

**Comment by fernetmatt** [comment]
@shadowspawn this works very well. The only feature missing right now is to make the newly created  option required. I would suggest something like `setRequired()`

```
new commander.Options("-t, --test <feature>", "test the feature").choices(["feature1", "feature2"]).setRequired()
```

What do you think?

**Comment by lydell** [comment]
@fernetmatt I think that’s `.makeOptionMandatory()`.

**Comment by shadowspawn** [comment]
@lydell is correct. 

Went with `mandatory` as the code already used `required` and `optional` for whether the option-value is required or optional, like `'-r <value>'` and `'-o [value]'`. (I tried some naming variations on whether the "value" was required or the "option" was required, but it was too subtle.)

**Comment by SrBrahma** [comment]
Sorry for commenting here, but couldn't be there also an validator for arguments using addArgument? I also just have an array of possible values

**Comment by shadowspawn** [comment]
Hi @SrBrahma , `.choices()` for arguments is supported in a similar way to options.

From the README:

```js
program
  .addArgument(new commander.Argument('<drink-size>', 'drink cup size').choices(['small', 'medium', 'large']))
  .addArgument(new commander.Argument('[timeout]', 'timeout in seconds').default(60, 'one minute'))
```

**Comment by SrBrahma** [comment]
Many thanks for the quick answer!
