### ISSUE TITLE
option() default value doesn't work with parseInt

### ISSUE THREAD

**Issue by DeoLeung** [tj/commander.js#523]
```js
  commander.option('-I --increment [value]', 'The interval increment', parseInt)
  commander.increment // works if '-I 2'
  commander.option('-I --increment [value]', 'The interval increment', parseInt, 1)
  commander.increment // gives NaN if '-I 2'
```

Seems like a bug or do I get it wrong?

**Comment by DeoLeung** [comment]
```js
  commander.option('-I --increment [value]', 'The interval increment', str => parseInt(str), 1)
```

this works though

**Comment by bfricka** [comment]
Did you try debugging it? My first guess would be that it's passing two params (input and default), which ends up calling `parseInt` with an invalid radix (e.g. `parseInt(2, 1) // NaN`)

**Comment by bfricka** [comment]
BTW this is the behavior across options which allows you to do things like collections:

```js
commander.option('-f, --foo <val>', 'Add values to foo', collect, []);
function collect(val, collection) {
  collection.push(val);
  return collection;
}
```
Which can be invoked: `program --foo=hi --foo=bye` and yields `['hi', 'bye']`

**Comment by DeoLeung** [comment]
@bfricka yes you made a right guess 👍 
would be better to improve the doc :)
