### ISSUE TITLE
Append external commands

### ISSUE THREAD

**Issue by lucaskatayama** [tj/commander.js#526]
Hi

I have a module with a commander options... And I want to append to current commander....

How do I do that?

For instance:

``` javascript
//main.js
var extLib = require('./extlib')
var program = require('commander')

program
  .append(extlib)
  .parse(process.argv)
```

``` javascript
//extlib.js
var program = require('commander')

program
  .option('-o, --option', ...)

module.exports = program
```

**Comment by shadowspawn** [comment]
This issue has not received many reactions or links, and has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
