### ISSUE TITLE
Hiding auto generated help options?

### ISSUE THREAD

**Issue by derek-ellison** [tj/commander.js#542]
Not sure if this is possible, but it would be nice to tell commander to hide the auto-generated help menu. 

So something like, 

**`commander.hideDefaultHelp = true;`**

That way I can customize my own help menu, without having the auto generated version show up as well.

**Comment by dominikwilkowski** [comment]
I got around this issue by capturing the option out of `process.argv` and remove it from `process.argv` and invoking whatever cool thing you wanted to run.

```js
if( process.argv.indexOf( '-x' ) !== -1 || process.argv.indexOf( '--surround-sound' ) !== -1 ) {
	const position = process.argv.indexOf( '-x' ) !== -1 ? process.argv.indexOf( '-x' ) : process.argv.indexOf( '--surround-sound' );

	process.argv.splice( position, 1 );

	doTheThing();
}
```

Hope it helps

**Comment by shadowspawn** [comment]
Commander v6.1 allows allows disabling the built-in help option: #1325
