### ISSUE TITLE
Crappy Benchmark for fun

### ISSUE THREAD

**Issue by rijnhard** [tj/commander.js#543]
So for giggles i put together a bench, running commander and yargs in separate official node:4 docker containers. 

with a basic program containing:
- version
- one command
- one option with default, alias and matched coercion
- 2 required parameters 
- a variadic with an additional 2 inputs

``` bash
# add <a> <b> [params...]
commander-bench add -s 10 1 3 5 7 11
```

I replicated this as exactly as possible in a project with commander and a project with yargs. 
and on 1000 iterations this was the results: 

```
====== commander-bench add -s 10 1 3 5 7 11  with  1000  iterations ======
Total Time:  46 sec,  46648 millis
--------------------------

====== yargs-bench add -s 10 1 3 5 7 11  with  1000  iterations ======
Total Time:  123 sec,  123680 millis
--------------------------
```

and I ran it a couple of times. 

Just a disclaimer: I'm not advocating these results are correct, or that this will always be the case, i jsut thought it was interesting that in a basic application I could replicate these results consistently

**Comment by rijnhard** [comment]
[Link to benchmark for completeness](https://github.com/rijnhard/node-crappy-benchmarks)

**Comment by shadowspawn** [comment]
Thanks @rijnhard
