### ISSUE TITLE
program.args swallowed if no options

### ISSUE THREAD

**Issue by kurtharriger** [tj/commander.js#544]
Seems to work if there are other options: 

```
> program.parse(['--abc', '--', 'def']); program.args
[ 'def' ]
```

But if no options then all args get swallowed: 

```
> program.parse([ '--', 'def']); program.args
[]
```

**Comment by jbcpollak** [comment]
I think I have this problem, please let me know if what I'm describing is something different, or expected behavior.

I have a program defined like this:

```
program
.arguments('[csv]') // [] means optional
.action(csv2sql)
.parse(process.argv);
```

When I execute it:

    ./app foo.csv

Everything works fine.

When I execute:

    ./app

Nothing is called and the program silently terminates.

**Comment by noah-sis** [comment]
+1 for @jbcpollak's issue

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
