### ISSUE TITLE
How to get prompt working...

### ISSUE THREAD

**Issue by mikeerickson** [tj/commander.js#548]
I have been trying to get a simple prompt to work and not having any luck.  The documentation on `prompt` is very thin (no examples so far as I can find)

My code is pretty simple

```
#!/usr/bin/env node

var program = require('commander');

program.prompt('username: ', function(username) {
  console.log('username %s', username);
});
```

which produces the following error

```
program.prompt('username: ', function(username) {
```

**Comment by zhiyelee** [comment]
Nope, `prompt` has been removed since an early version

**Comment by mikeerickson** [comment]
Ahhhh, well that sucks. Guess it needs to be removed from documentation 

What are the options? I can use the co (and co-prompt) libraries I guess?

**Comment by SaintDako** [comment]
Good article about using prompt here: https://developer.atlassian.com/blog/2015/11/scripting-with-node/

**Comment by shadowspawn** [comment]
Answered. Old. Closing.
