### ISSUE TITLE
Cannot pass more than 4 arguments in literal mode

### ISSUE THREAD

**Issue by Unitech** [tj/commander.js#552]
Ref to https://github.com/Unitech/pm2/issues/2064

[This is the main pm2](https://github.com/Unitech/pm2/blob/development/bin/pm2) file on which we use commander.js, but we don't do anything fancy with commander.js

**Comment by ORESoftware** [comment]
+1

**Comment by shadowspawn** [comment]
I was not able to reproduce this issue.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
