### ISSUE TITLE
Is there a way to get the string value rather than bool value without specifying <type>?

### ISSUE THREAD

**Issue by magicmark** [tj/commander.js#555]
Having to do 

`.option('-d, --config-dir <path>', 'specify config directory (defaults to ~/.examplerc')`

does seem nice and fluent, but I would still like to be able to rewrite that without specifying `<path>` in the first arg and still be able to get the string value.

Is this possible?

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
