### ISSUE TITLE
Add support for -v to get the version

### ISSUE THREAD

**Issue by chasenlehara** [tj/commander.js#560]
Please add support for `-v` instead of `-V` to get the `--version` to be consistent with Node and npm (and a lot of other CLIs).

Related to #509

**Comment by chasenlehara** [comment]
@tj, why was [this change](https://github.com/tj/commander.js/commit/9656c377395de79ccafe5d2849c3d09bad6c3c44) made?

**Comment by jrylan** [comment]
I've always been really curious about this as well. I've been using this quick fix near the top of my CLI app to ensure `-v` works:

```js
var vPos = process.argv.indexOf('-v')
if (vPos > -1) {
  process.argv[vPos] = '-V'
}
```

**Comment by sgen** [comment]
Probably because several tools use -v and --verbose for their verbose output flag and -V and --version for their version flag

**Comment by JimmyBoh** [comment]
Thanks @jrylan, that does the trick. But only if you are okay with the auto-generated help not mentioning `-v` specifically.

**Comment by eisbehr-** [comment]
@sgen But the whole environment around `commander` ueses `-v` for the version output. It would be more than usefull to have it the same way.

- `node` uses `-v`
- `npm` uses `-v`
- `gulp` uses `-v`
- `grunt` uses `-v`

It should at least be configurable. Maybe directly on the version command, like:

```JS
cli.version('1.0.0', '-v, --version');
```

**Comment by theoutlander** [comment]
I prefer -V for verbose. Also, is there an easy way to replace -V with -v? If I add a new option, it will show both. Maybe I'm missing something.

**Comment by mojavelinux** [comment]
This is already possible. It's just a customization:

```
.version('1.0.0', '-v, --version')
```

If the flags aren't specified, they just default to `-V, --version`.

One pattern I happen to like is to honor the `-v` when specified as the only argument, but then let it get used as an option when combined with other options and arguments (such as verbose).

**Comment by mojavelinux** [comment]
I think the API docs need to be updated to reflect the fact that flags can be specified as an override.

**Comment by ahmadawais** [comment]
Tried to look for a way to add that doc, couldn't. Thanks @mojavelinux for the tip.

**Comment by ahmadawais** [comment]
Wrote this instead. 
https://gist.github.com/ahmadawais/da08521a51d9093edec46eeedc2065ac

**Comment by mojavelinux** [comment]
As it turns out, the flag can be overridden, but the program continues to respond only to a long name that resolves to "version". But this makes the help inaccurate.

I'll submit a patch to respect the name of the option specified in the method.

**Comment by mojavelinux** [comment]
Patches submitted!

**Comment by ahmadawais** [comment]
Seems to work just fine on my end without the patch? What am I missing?

**Comment by mojavelinux** [comment]
@ahmadawais You are using the default name for the option, which is version. If you wanted to use a different name, like `--revision`, then it wouldn't work. So this fix doesn't apply to your use case, but important nonetheless.

**Comment by ahmadawais** [comment]
Got it.
