### ISSUE TITLE
How do I parse arguments in subcommands?

### ISSUE THREAD

**Issue by morkeleb** [tj/commander.js#565]
I've written a small console app with subcommands.
It's simple enough I have a command with an optional argument.

However in the subcommand I loose all ability to check for the arguments based on the structure given in my index.js file.

My index.js file:

``` javascript
const program = require('commander');
const pjson = require('./package.json');
program
  .version(pjson.version)
  .command('init [config_file]', 'creates a config file template')
  .parse(process.argv);
```

My index-init.js file:

``` javascript
const program = require('commander');
program.parse(process.argv);

const path = require('path');
var file = program.args[0]; // id like to do "var file = program.config_file" here

console.log(file);
```

I would like to be able to do something like `program.config_file` in my index-init.js file, but I can't seem to get the arguments parsed so they'll match my initial setup. I've tried adding `.usage()` and `.arguments()` in the index-init.js file. Nothing gets it to parse the input into named variables on the program object.

**Comment by FDiskas** [comment]
index-init.js file:
```
const program = require('commander');
const path = require('path');

program
  .option('-f, --file [optional]', 'creates a config file template')
  .parse(process.argv);

console.log(program.file);
```

**Comment by shadowspawn** [comment]
Thanks @FDiskas 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
