### ISSUE TITLE
new npm release?

### ISSUE THREAD

**Issue by hedgerh** [tj/commander.js#568]
I've been playing around with commander tonight, and I've run into two issues while using `2.9.0` that have actually been fixed and are merged into `master`.  Would it be possible for a new version to be published to npm with these fixes?  Looks like the last release was 11 months ago.

In the meantime, I'll just get it via `"commander": "git+https://github.com/tj/commander.js.git"`.

Thanks for your time and thank you to everyone who maintains this project!

Here are the issues, for reference:
- Error running sub sub commands: https://github.com/tj/commander.js/issues/527
- Using aliases when executing subcommands: https://github.com/tj/commander.js/issues/402

**Comment by hedgerh** [comment]
@zhiyelee - Hello, it seems that a new version of `commander` hasn't been published to npm for 1 year.  There are a few open issues that are actually resolved, but have not been published.  It seems to be causing problems for a few people.  Are there any plans to publish a new version to npm soon?

**Comment by pciapcib** [comment]
Same question for me.

**Comment by ErBlack** [comment]
@tj, @zhiyelee, @SomeKittens give some response please.

**Comment by shadowspawn** [comment]
Commander has new collaborators, and there are ongoing releases.
