### ISSUE TITLE
Reason about using tilde operator in Option constructor?

### ISSUE THREAD

**Issue by e-cloud** [tj/commander.js#569]
When looking at [source code of Option constructor](https://github.com/tj/commander.js/blob/master/index.js#L41), it's a bit uncommon to see applying tilde operator.

After searching the actual usage of those tilde-operated members of an `Option`, i don't see any benefit of that rather than using logical operator.

@tj, could you explain the original determination of it? Couldn't find any clue from the git history.

**Comment by usmonster** [comment]
Recently fixed in #794.
