### ISSUE TITLE
Defining boolean options via Command#option() defaults to undefined, not false.

### ISSUE THREAD

**Issue by karbica** [tj/commander.js#574]
According to the example http://tj.github.io/commander.js/#Command.prototype.option, when defining an option that does not have a required or optional value, it defaults to `undefined` when it should default to `false`. However, if it's long hand value contains `-no-`, it properly defaults to `true`.

**Comment by louisgv** [comment]
Same issue, the document should be more clear about all flags that contains `-no-`, as these flags are treated differently. E.g:
+ They are stripped off the `no` words
+ They are defaulted to true

Confused me a bit when trying to setup a no flag :p

**Comment by usmonster** [comment]
Tried to clarify this behavior in tests on #795. Please take a look, and feel free to comment!

**Comment by shadowspawn** [comment]
I have proposed a large update to options coverages in README in #953

**Comment by shadowspawn** [comment]
I have rewritten the options description in the README, mentioning the default boolean value being undefined, and covering negatable boolen separately (both with examples). Hopefully this should make it clearer what the current behaviour is.
