### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by tptshepo** [tj/commander.js#580]
Hi there,
First of all great job the on library it's very useful.
I just picked an issue with the documented examples and I spent some time trying to figure out what I was doing wrong. The issue turned to be the following; 

If there is a space between the comma and '--' when setting up an option, `if (program.peppers)` always returns false. Only when I removed the space did the `if` statements work if I did in fact have an argument for `-p`.

**Does not work**
`program
  .option('-p, --peppers', 'Add peppers')`

**Works (no space after comma)**
`program
  .option('-p,--peppers', 'Add peppers')`

**Comment by vanesyan** [comment]
It's seems something is on your side, our integration tests are passed, there a bunch of options registered that way and they are handled correctly.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
