### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by lojzatran** [tj/commander.js#581]
Hi,

when I run my tests, I got into this error

`(node) warning: possible EventEmitter memory leak detected. 11 config listeners added. Use emitter.setMaxListeners() to increase limit.`

I investigated a bit and it seems like this problem is coming from https://github.com/tj/commander.js/blob/master/index.js#L393.

The problem is my tests are sharing the same module of commander. When I run too many tests, they are calling the commander with arguments of the same name (in this case is `config`). For each of these arguments, a new listener is created, causing the above error. Maybe it's good if you can add checking for listener of that name before adding a new one?

Thanks.

**Comment by enriquecaballero** [comment]
+1

**Comment by teddy-gustiaux** [comment]
Try using: `program.removeAllListeners();`

I was having the same error while running my tests in watch mode, but removing all the listeners manually fixes the problem.

**Comment by shadowspawn** [comment]
Thanks for work-around @teddy-gustiaux 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
