### ISSUE TITLE
Literal args have unexpected results when using commands (with args)

### ISSUE THREAD

**Issue by jkamke** [tj/commander.js#582]
try:

```
var program = require('../')
  , should = require('should');

program
  .command('literal [val]')
  .option('-C, --no-color', 'turn off color output')
  .action(function (val, options) {
  });

program.parse(['node', 'test', 'literal', 'val', '-C', '--', 'cmd', '--', '--arg']);

program.args.should.eql(['cmd', '--', '--arg']);
```

`AssertionError:` ... `A has 4 and B has 3`

as well https://github.com/tj/commander.js/blob/v2.9.0/index.js#L296 replaces args[1] with the Command object.

finally if [val] was not supplied it would be fetched from after the '--'.

as in:

```
var program = require('../')
  , should = require('should');

program
  .command('literal [val]')
  .option('-C, --no-color', 'turn off color output')
  .action(function (val, options) {
    should.not.exist(val);
  });

program.parse(['node', 'test', 'literal', '-C', '--', 'cmd', '--', '--arg']);
```

`AssertionError: expected 'cmd' to not exist`

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
