### ISSUE TITLE
customFds option for child_process.spawn is deprecated

### ISSUE THREAD

**Issue by ghost** [tj/commander.js#586]
`customFds` option for `child_process.spawn` is deprecated since https://github.com/nodejs/node/commit/245469587c7a6326d1b55bdf6c6d6650d72bfa22.
Use `stdio` instead.

See https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4

**Comment by shadowspawn** [comment]
We are passing `stdio` too so I suspect were deliberately working with old and new version of node.

https://github.com/nodejs/node/blob/master/doc/api/deprecations.md#dep0006-child_process-optionscustomfds

Assuming minimum version of node is now at least 4, can probably just delete `customFds`.

**Comment by shadowspawn** [comment]
Removed `customFds` on the develop branch for the next release (#1052).

**Comment by shadowspawn** [comment]
v4.0.0-0 prerelease published: #1067

**Comment by shadowspawn** [comment]
v4.0.0 has been released.
