### ISSUE TITLE
sub-command can not found when `ln` link file again

### ISSUE THREAD

**Issue by wfpaopao** [tj/commander.js#588]
If we make a command `c-test`,and `c-test` has a sub-command `c-test init`.after we use `npm/yarn` install `c-test` command, we  excute`ln` which c-test` test` and excute command `test init`, we will get  a `test-init` not found error.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
This has been fixed by #935 released in Commander v2.2.0.0.
