### ISSUE TITLE
An optional argument followed by a required.

### ISSUE THREAD

**Issue by anshulk** [tj/commander.js#589]
Guys i'm trying to have an action which words both for 

>program_name dict apple

and 
 
>program_name apple

This is the code I'm using, but none of the above two are working.

``` js
program
  .command('[dict] <word>')
  .description('Display everything for the word.')
  .action(function(word) {
    console.log("In all");
  });
```

I'm sorry if this is already answered, couldn't find in examples or the web.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
