### ISSUE TITLE
Why doesn't ".arguments('<dir>')" just populate "program.dir"?

### ISSUE THREAD

**Issue by peternann** [tj/commander.js#590]
New to commander. The Options processing is great and succinct.

Why is the method for processing the main **_arguments_** (as opposed to options), so verbose by comparison?

Supply a function, set module globals, and do my own error checking??? Bleh!
Why doesn't commander itself check if the mandatory argument is supplied?
Why doesn't it generate its own error message if it's missing?
And mainly, why doesn't an argument like "\<dir\>" just get set as a 'program.dir'?

Hoping to be educated that there's a good reason. Just seems really weird at first inspection from a noob...

**Comment by angrifel** [comment]
@tj I did not see any contribute guidelines. Is there anything the community can do to help? are you taking any PRs from forks?

**Comment by shadowspawn** [comment]
Bit many questions there. :-)

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
