### ISSUE TITLE
Unexpected action callback arguments

### ISSUE THREAD

**Issue by ccorcos** [tj/commander.js#591]
I have a file, `tmp.js` that looks like this:

```js
'use strict'

const program = require('commander')

program
  .command('hello')
  .option('-n, --name')
  .action((options) => {
    console.log(`hello ${options.name || 'world'}`)
  })

program.parse(process.argv)
```

But when I run it, I get some unexpected results:

```
~/Code ❯❯❯ node tmp.js hello
hello function () {
  return this._name;
}
~/Code ❯❯❯ node tmp.js hello --name="chet"
hello world
```

Am I doing something wrong? It doesnt look like the callback arguments are very well documented...

**Comment by jrylan** [comment]
Had the same problem, you just need to do this:

```js
'use strict'

const program = require('commander')

program
  .command('hello')
  .option('-n, --name [name]')
  .action((options) => {
    console.log(`hello ${options.name || 'world'}`)
  })

program.parse(process.argv)
```

**Comment by ccorcos** [comment]
Check out vorpal. It's much more predictable.

**Comment by shadowspawn** [comment]
You need to specify that the option takes a value, as shown by @jayrylan.

This issue has not had any activity in over six months. 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
