### ISSUE TITLE
Error when option --alias is defined

### ISSUE THREAD

**Issue by zanona** [tj/commander.js#592]
Apparently having the option:

`.option('-a --alias [alias]', 'Version Alias')`

triggers an error at

https://github.com/tj/commander.js/blob/89858e507e0ff60af05e66a6fa3e28f71cc99b15/index.js#L467

```
TypeError: command.alias is not a function
    at /Users/zanona/Desktop/core/node_modules/awsr/node_modules/commander/index.js:467:22
```

**Comment by shadowspawn** [comment]
Closing this as covered by #183 and #933
