### ISSUE TITLE
`--boolean=value` parsed as `--boolean value` (equal sign assign value to boolean should be usage error)

### ISSUE THREAD

**Issue by cspotcode** [tj/commander.js#594]
When passing a value to a flag, this makes sense:

```
# Both mean the same thing
$ myclitool --dir /home/me/foo
$ myclitool --dir=/home/me/foo
```

On the other hand, for a boolean flag which can't take a value, using the equal sign to give it one is wrong and should be reported as a user error.
```
# First is ok; second is a usage error
$ otherclitool --force /home/me/foo
$ otherclitool --force=/home/me/foo
```

However, Commander parses it as if force is true and there's a single positional argument after that.  I think Commander should report the second usage as a user error.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by jpbochi** [comment]
This would still be nice to implement.

**Comment by shadowspawn** [comment]
It does now give an error, of sorts:

```
$ otherclitool --force=/home/me/foo
error: unknown option '--force=/home/me/foo'
```
