### ISSUE TITLE
What's the best practice to do integration testing?

### ISSUE THREAD

**Issue by cggaurav** [tj/commander.js#596]
[Expect Scripts](http://www.admin-magazine.com/Articles/Automating-with-Expect-Scripts) could be an option but I'd love to use the utilities in Javscript like Chai.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
