### ISSUE TITLE
how to delete the mistyped password

### ISSUE THREAD

**Issue by guozheng** [tj/commander.js#6]
Hi, I am trying the password in examples. If I mistyped characters, how to delete these characters? I tried to use backspace/delete, but it just prints out more mask chars for each keystroke and the output seems to be still the incorrect password. Not sure if this is a bug or I am missing something. Thanks!

**Comment by kushwahashiv** [comment]
> Closed because `password` had been removed

is there any way we can mask password?


regards
Shiv
