### ISSUE TITLE
Show help when command is unknown

### ISSUE THREAD

**Issue by 0505gonzalez** [tj/commander.js#603]
Hello,

What would be the best way of printing help output when the command is unknown? E.g. `program unknownCommand`

**Comment by goldcaddy77** [comment]
This should work:

```
    program.on('*', function () {
      console.log('Unknown Command: ' + program.args.join(' '))
      program.help()
    })
```

It would be good to get this documented in the readme.

**Comment by vanesyan** [comment]
Answered

**Comment by lbustelo** [comment]
@goldcaddy77  The issue with this is that the `*` still show in the help output
