### ISSUE TITLE
Option shifting when combining command and options

### ISSUE THREAD

**Issue by Ohadbasan** [tj/commander.js#607]
running this basic code here I encounter an issue when trying to pass options in addition to my commands.

```'use strict'

const program = require('commander')

program
    .command('test <env_id> <action>')
    .option('-e', '--env_vars [envVars]', 'Env vars')
    .action(function(env_id, action, envVars) {
      console.log(env_id)
      console.log(action)
      console.log(envVars)
    })

program.parse(process.argv)
```

for example:
running 
```node cmd.js test aaa setup```
prints "aaa" and "setup" and the Command object.
which is ok, env_id was assigned to the first argument and action was assigned for the second

if I'm running with options
```node cmd.js -e "a=b b=c" test aaa setup```
what happens is that "a=b b=c" and "aaa" are printed. the option (envVar)  is assigned to the first argument and the env_id is assigned to the "action" (second argument). the third argument still contains the Command object and the "action" argument (setup) is "lost"

Can someone please advise? thanks

**Comment by bitstrider** [comment]
Looks like when using `program.command`, parsed options get stored in its own object and passed as the trailing argument to the function passed to `program.action`

So in your case:
```javascript

const program = require('commander')
program
...
    .action(function(env_id, action, options) {
      ...
      console.log(options.envVars) // => "a=b b=c"
    })
...
```

It seems to behave the same even if options are placed in front of the command:
```javascript
// this should work
program.parse(['node', 'my-program.js', '-e', '"a=b b=c"', 'test', 'my-env-id', 'my-action'])
```

**Comment by shadowspawn** [comment]
Explanation provided by @json2d 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
