### ISSUE TITLE
Any way to remove the two-space indent?

### ISSUE THREAD

**Issue by joeyespo** [tj/commander.js#608]
Just a matter of personal preference.

I like the no-indent output style of `git --help`, `npm --help`, `ember --help`, etc. over `yarn --help` and commander's two-space default.

Could be done like:

```js
program
  .usage('<cmd>')
  .version('0.0.1')
  .config({ indent: 0 })
```

which leaves the door open for other config options.

Thoughts?

**Comment by JohnRGee** [comment]
The two space indent has actually been removed now: #853

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
