### ISSUE TITLE
In README, should clarify expected parameters of the function passed to `program.action`

### ISSUE THREAD

**Issue by json2d** [tj/commander.js#613]
There seems to be some confusion here that could use some clearing up in the docs.  

It should explain that when using `program.action(callback)`, the `callback` function will always have `options` as the last parameter...and if `program.command` and `program.arguments` never called,  `options` will be the first and only parameter

#541 
#607

**Comment by shadowspawn** [comment]
This issue will be resolved when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
The README has been updated in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0
