### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by alan-agius4** [tj/commander.js#616]
Hi,

Are you willing to accept TypeScript typings within the repo itself?

This will make it more convenient for typescript users (and [suggested by typescript](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)) to provide typings with the repository itself, rather than another repo (such as [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)).

Are you willing to have a pull request for this?

I will be happy to create typing for this library myself if you agree.

Thanks!

**Comment by vanesyan** [comment]
Yes, it's definitely a good idea. We can support typings. It'll be awesome, if you provide a pull request

**Comment by alan-agius4** [comment]
PR: 646
