### ISSUE TITLE
How to change the value of _name?

### ISSUE THREAD

**Issue by EmpireWorld** [tj/commander.js#617]
I want to make a custom name for my command line app, for example i have a script called `example.js` then when i run it using `node example.js --help` or using `package.json` bin argument `./example.js --help` it outputs command name as `example` but i want to call it `unicorn`.

We have two hacky ways.

First: (not bad)
```javascript
#!/usr/bin/env node

const program = require("commander");

// Set name in the private variable
program._name = "unicorn";

program.parse(process.argv);
```

Second: (very bad idea)
```javascript
#!/usr/bin/env node

const program = require("commander");

// Rename the file in the argv
process.argv[1] = "unicorn";

program.parse(process.argv);
```

We need a public and stable api to do it, like `setName` or `name = "unicorn"` and more.

**Comment by alexbrazier** [comment]
This feature is in PR #605

**Comment by EmpireWorld** [comment]
Nice. so i close this issue. Thanks.
