### ISSUE TITLE
Help default values

### ISSUE THREAD

**Issue by alan-agius4** [tj/commander.js#620]
Is there a way to display the default values as well rather than just the flags and desciption.  When having the --help flag?

**Comment by sntran** [comment]
I think you just have to put it in the option's description, i.e.

`.option('-p, --port [port]', 'The port to listen to. Default: 9999.', parseInt, 9999)`

**Comment by shadowspawn** [comment]
Display of default value was added in:
https://github.com/tj/commander.js/commit/d9abf56c43a93e9584e2e18a9f8fb5af552f738c
