### ISSUE TITLE
'on' event for calling program without arguments?

### ISSUE THREAD

**Issue by awitherow** [tj/commander.js#623]
Currently when I call the program in the terminal without any arguments, it just does a new line with new input.

I was assuming that using the `on('*')` syntax it would be a default if nothing worked, but this does not seem to be the case.

Is it possible to have a catch all to be able to print something without arguments?

I hope this makes sense. My PR that does not do what I want it to do: https://github.com/DanielMSchmidt/flow-bro/pull/8

**Comment by DanielMSchmidt** [comment]
Hey @awitherow, I think `.command('...', '...', {isDefault: true})` may be the thing you are looking for, see the [docs here](https://github.com/tj/commander.js#git-style-sub-commands).

**Comment by awitherow** [comment]
Hmm so with this, it would be necessary to add an `isDefault` catch to every invocation of the program?

**Comment by DanielMSchmidt** [comment]
Only with the command('*', {isDefault: true}) I guess

**Comment by awitherow** [comment]
I did this and am not seeing any result. Maybe simply `command(''), {isDefault: true}`, without the star.

**Comment by mattt416** [comment]
I was just searching how to do this, and found this bug.  I've implemented the following:

```
program
  .command('*', '', {noHelp: true, isDefault: true})
  .action(function(){
    program.outputHelp();
  });
```

Now I can run the program with no arguments or invalid arguments and it'll show display the help.   `{noHelp: true}` is also good because it means it won't add this argument to the help page.

**Comment by awitherow** [comment]
@mattt416 nice thanks for the research! Will check into implementing it.

**Comment by shadowspawn** [comment]
A pattern for displaying a default message is now included in the README.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
