### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by vanesyan** [tj/commander.js#631]
It seems there's no any active contribution since feb...

**Comment by scott-joe** [comment]
Yeah... There are 51 open PRs...

**Comment by timaschew** [comment]
and now almost one month is passed without any reaction from any maintainer

**Comment by abetomo** [comment]
Shall we fork to create a new package?

**Comment by timaschew** [comment]
I would like to know why you want to use commander and not yargs.
I switched to yargs today and I am really happy with its API.
And it's of course maintained.

Tomoaki Abe <notifications@github.com> schrieb am Mi. 14. Juni 2017 um
17:39:

**Comment by vanesyan** [comment]
May be we should to involve @tj into the discussion as his is the very author of the package and I'd think he also should decide want to do with the project.

**Comment by tj** [comment]
happy to add anyone who is interested in maintaining

**Comment by abetomo** [comment]
Please let me cooperate because I am indebted to commander.js.

**Comment by vanesyan** [comment]
I'd also like to help out with maintaining the project. :)

**Comment by tj** [comment]
added you both :D just let me know what your npm usernames are

**Comment by abetomo** [comment]
Thank you. I am the same as github.

**Comment by vanesyan** [comment]
Awesome :) @vanesyan on npm too

**Comment by tj** [comment]
done!

**Comment by vanesyan** [comment]
Awesome!

**Comment by zhiyelee** [comment]
nice

**Comment by vanesyan** [comment]
A bunch of new maintainers been added, so close it for now
