### ISSUE TITLE
Subcommand not registered if no description provided during the setup

### ISSUE THREAD

**Issue by k0pernikus** [tj/commander.js#633]
I wanted to setup a cli with git style subcommands. Hence, created these files:

test.js
test-foo.js
test-bar.js

In my `test.js`, where I define the app, if I set the command description:

```
program
    .version('1.0.0')
    .command('foo', 'foo action')
    .command('bar', 'bar action')
    .parse(process.argv);
```
Everything works as expected:

```
$ node dist/test.js --help

  Usage: test [options] [command]


  Commands:

    foo         foo action
    bar         bar action
    help [cmd]  display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number

```
Yet at first I omitted the description for the test case:

```
program
    .version('1.0.0')
    .command('foo')
    .command('bar')
    .parse(process.argv);
```
and then only the bar command seems added:

```
node dist/test.js --help

  Usage: bar [options]

  Options:

    -h, --help  output usage information
```
As a developer I find that counter-intuitive and would have expected an error to be thrown in my face or for the two commands to be added with or without description.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
(I have this issue noted for future reference, common report of confusion over switching modes based on description.)
