### ISSUE TITLE
Enable tests on Windows CI

### ISSUE THREAD

**Issue by kunagpal** [tj/commander.js#635]
https://www.appveyor.com/docs/

**Comment by vanesyan** [comment]
Probably after #649

**Comment by shadowspawn** [comment]
See #916 for Azure implementation.

**Comment by shadowspawn** [comment]
We are currently trying the GitHub Actions beta, with Windows enabled as a platform. 
#1027

**Comment by shadowspawn** [comment]
v4.0.0 has been released with GitHub Actions including tests running on Windows.
