### ISSUE TITLE
Argument value prefixed with a dash returns version.

### ISSUE THREAD

**Issue by soluml** [tj/commander.js#636]
Using commander 2.9.0, I'm trying to call my node script like so: `node index -e '-KkXJUkBZMYVJXiMo0Pe'`

For some reason, commander is returning the version number instead of calling the script with the e flag set.  If I use a different string that doesn't start with a dash, commander works as expected.

This issue occurs whether I use quotes or not.

**Comment by vanesyan** [comment]
Can you provide part of code, where you configure commander, as it's hard to say which one cause the error, from what you've provided.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
