### ISSUE TITLE
The future

### ISSUE THREAD

**Issue by vanesyan** [tj/commander.js#637]
So let's decide on the future maintaining of the project, it refactoring, etc. Firstly, it's important to note that we should operate very carefully with the future iteration of it, as the package is one of the most popular packages on npm and any regressions will introduce extremely impact on the community. Secondly, IMHO we should keeping it up to date, with iterating of it and dropping unsupported Node.js versions at first as it stucking us from using futures introduced in the most recent stable versions.

**Comment by vanesyan** [comment]
Beside it, I'd also like to split current one big file into chunk files, IMHO it'll help us with future maintaining of the project itself.

**Comment by vanesyan** [comment]
Plus, I'm a huge fan of ECMAScript 2015+ and I'd like to rewrite some parts of the package to use it.

**Comment by vanesyan** [comment]
But, as the first step, we should firstly review most of the issues and PRs and close that a bit outdated, etc.

**Comment by vanesyan** [comment]
Another one good iteration of the project IMHO will be add some tools like linting, etc.

**Comment by vanesyan** [comment]
friendly cc to @zhiyelee @abetomo

**Comment by abetomo** [comment]
@vanesyan 
There is also a difference from the previous release.
Would you like to release it once with the current code?

Check the accumulated PR and let's fix the code.

**Comment by vanesyan** [comment]
Yeah, we can accumulate whole of minor updates, patches and release under minor semver version update. Then starting refactoring and include a bunch of major updates, and finally introduce v3, I think.

**Comment by vanesyan** [comment]
But I'll be a bit busy for the next 2 weeks, summer session, work, etc. you know :)

**Comment by vanesyan** [comment]
close in favor of #666
