### ISSUE TITLE
Run command from another command

### ISSUE THREAD

**Issue by chrisberthe** [tj/commander.js#643]
Is there a way to run one (or more) command from another command?

For instance, you have a main `setup` command that calls 3 other defined commands `lint`, `compile` and `deploy`. Not sure if there's currently a way to do this inside of commander.

**Comment by vanesyan** [comment]
You can register action on setup that execute that 3 actions' handlers, e.g.:
```js
program
  .command('lint')
  .action(() => lint())

  .command('compile')
  .action(() => compile())

  .command('deploy')
  .action(() => deploy())

  .command('setup')
  .action(() => {
    lint()
    compile()
    deploy()
  })
```

**Comment by davidsonsns** [comment]
I'm using this functio that I created
```js
const runCommand = (alias, args = []) => {
  program._events[`command:${alias}`](args)
}
```

running, in action
```js
runCommand('setup', [...args])
```

**Comment by jdmarshall** [comment]
@davidsonsns I'm not seeing the arguments show up in the second command.  Does this still work for you?
