### ISSUE TITLE
Init value of option '--name' is a [Function]

### ISSUE THREAD

**Issue by bySabi** [tj/commander.js#648]
When a option `--name` is not set on CLI, initial value is a [Function]

Example:
```js
var Command = require('commander').Command;
var program = new Command('my-cli');

program
  .version('0.0.1')
  .option('--name <name>', 'Set name')
  .option('--name-prefix <name>', 'Set prefix name')
 .parse(process.argv);
  })
...

console.log('name: ' , program.name)
console.log('namePrefix: ', program.namePrefix)
```

### The ouput of  `$ my-cli --name-prefix=test`  is:
```
name: [Function]
namePrefix: test
```
> Here `name` should be `undefined`

### The ouput of  `$ my-cli --name=test`  is:
```
name: test
namePrefix: undefined
```
> Here is ok!

IMHO a widely use option like '--name' that collide with `[Command.name]` should have a dedicated check and initialization branch in code.

**Comment by bySabi** [comment]
I create a workaround module for this problem: [safe-commander](https://www.npmjs.com/package/safe-commander)

**Comment by elliot-nelson** [comment]
There are a couple flags like this.  `--parent`, for example.

**Comment by bySabi** [comment]
@elliot-nelson you are right, too many options collide. That's for I could not wait for commander 3.x.x release and create [safe-commander.js](https://www.npmjs.com/package/safe-commander). 

Any feedback is welcome

**Comment by shadowspawn** [comment]
Closing this as covered by #183 and #933

**Comment by shadowspawn** [comment]
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102
