### ISSUE TITLE
`program.emit` behavior seems to be broken in 2.11.0

### ISSUE THREAD

**Issue by Flackus** [tj/commander.js#659]
```
-    "commander": "2.10.0",
+    "commander": "2.11.0",
```

Somewhere between those two versions the following case was broken. We have two subcommands, let's name them `start` and `download`. Inside the code for the `start` command we do `program.emit('download');`.

It works for `2.10.0`, but in `2.11.0` `download` subcommand will not be triggered.

**Comment by abetomo** [comment]
Could you give me sample code that does not work as expected so that there is no discrepancy in recognition?

**Comment by Flackus** [comment]
I'll try to make a PR addressing this issue today.
If I won't be able to fix it myself, code snippet will be posted, no worries :)

**Comment by Flackus** [comment]
Discussed issue was introduced in https://github.com/tj/commander.js/pull/494/files

In user code `program.emit('some_command')` now should be changed to `program.emit('command:some_command')`.
This change seems reasonable for me, but it happened in minor release, which is a pitfall.

@abetomo, what do you think?

**Comment by vanesyan** [comment]
Yep, @Flackus you are right, we should merge it in major release, but instead break compatibility in minor release. As things already done, we cannot rollback updates, but instead we can add notice to README.md about the breakage between 2.10 and 2.11 versions.

**Comment by Flackus** [comment]
@vanesyan yeah, you're right, no reason to break things twice.
Thanks!

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
