### ISSUE TITLE
program.on behaviour seems to be broken in v2.11.0

### ISSUE THREAD

**Issue by deepu105** [tj/commander.js#660]
The below snippet which used to work with v2.10.0 seems to be broken in v2.11.0 it doesn't do anything now
```
program.on('*', (name) => {
        console.log(name);
        process.exit(1);
    });
```

Actual usage in JHipster CLI
```
program.on('*', (name) => {
        logger.error(`${chalk.yellow(name)} is not a known command. See '${chalk.white(`${cliName} --help`)}'.`);

        const d = didYouMean(name.toString(), program.commands, '_name');

        if (d) {
            logger.info(`Did you mean: ${chalk.yellow(d)}?`);
        }

        process.exit(1);
    });
```

**Comment by vanesyan** [comment]
Yeah, we break compatibility in v2.11. `*` event renamed to `command:*`. Sorry for that.

**Comment by vanesyan** [comment]
see #659 for more details

**Comment by deepu105** [comment]
Thanks for the update.

**Comment by madjam002** [comment]
This should not be closed. Can this not be fixed for 2.10 and the breaking change be moved to a version 3 release?

**Comment by vanesyan** [comment]
@madjam002 this is a dup of #659.

**Comment by vanesyan** [comment]
Unfortunately we cannot push things back as 2.11 already released, and we cannot delete versions from npm. Plus things already done, no way to re-inverting wheels, sorry for that :)
