### ISSUE TITLE
Can configure option from JSON for more readability

### ISSUE THREAD

**Issue by luatnd** [tj/commander.js#665]
Hi,
I feel that this commander.js is the best cli parser I found. I choose it to develop my small cli app.
But when I start to use it while reading its docs, it take me 2 times to find the `<>` `[]` syntax, but still missing the `-no-` syntax explanation.
So I've made a `configure()` that port to `option()` for an easy work:

JSON config --> configure() --> option()
It look like this, please tell me if you think it's good, I'll submit this code, hope this help:

![image](https://user-images.githubusercontent.com/1859127/28436887-cfeaa162-6dc2-11e7-94b7-f70c2c5809ef.png)

And it still have some issue:
• #601 Adding support for required arguments
• #230 Required arguments for options and commands are not enforced
• #574 Defining boolean options via Command#option() defaults to undefined, not false

----
For further refactoring, In my opinion, I think these features might good:
• Validation value
• Change parseOptions() behavior: It check through the `argv`'s option only, so every option defined but not in `argv` was not be checked for default value.
• Typescript

Thanks.

**Comment by vanesyan** [comment]
Hello there! Really thanks for your interesting in project. While your feature is good, we'd prefer to keep commander's API small and consistent and sure easily to create high-level wrappers on top of it, means we are beside of opinionated decisions like this :-)
