### ISSUE TITLE
Support argument type of regex

### ISSUE THREAD

**Issue by AndersDJohnson** [tj/commander.js#672]
Support defining arguments that accept a string which is converted into a regex (regular expression). Possibly with a mode (opt-in for backwards compatibility) to automatically do this for matching string patterns, e.g., starting and ending with a `/` and optional trailing flags.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
