### ISSUE TITLE
Feature request: support option with multiple values

### ISSUE THREAD

**Issue by lionelvillard** [tj/commander.js#674]
for instance:

```nodejs
option('--entry <key> <value>', 'add an entry', collect)
```

**Comment by beardedpayton** [comment]
@abetomo @tj any update on this? Is there a way to achieve this in Commander currently?

**Comment by edemaine** [comment]
This feature got added by #198, so I think this issue can now be closed.

**Comment by shadowspawn** [comment]
Adding this would complicate parsing too much and be a bit unusual.

However, you can now add custom parsing (as mentioned by @edemaine) and the requested example looks a good candidate for a comma separated pair like:

```
option('--entry <pair>', 'add an entry (key,value)', coercePair)
```

Used like:

```
command --entry alpha,beta
```

**Comment by ricardoekm** [comment]
For anyone coming here from Google, this works: https://github.com/tj/commander.js/blob/master/examples/options-variadic.js
