### ISSUE TITLE
`program.on('*', cb)` broken in 2.11.0

### ISSUE THREAD

**Issue by MiniGod** [tj/commander.js#676]
The use of `program.on('*', cb)` broke in `2.11.0`.

It was suggested here https://github.com/tj/commander.js/issues/219#issuecomment-42626111 as a means of handling unknown commands.

I see that I can use `program.command('*').action(cb)` but then the `*` shows up in the help text. Is that the only way now?

**Comment by vanesyan** [comment]
We accidentally broke compatibility of commander v2 version with the release of `v2.10`, sorry for this.
Try to use `command:*` event name instead.

**Comment by MiniGod** [comment]
I see now that it broke in #494.

Is `command:*` considered an internal event that should not be used externally and might change without bumping major?

**Comment by donaldpipowitch** [comment]
I just stumbled over this. Is using `command:*` a workaround or intended behaviour? It seems to work.

**Comment by vanesyan** [comment]
It's intended behavior, we accidentally broke  compatibility with release of v2.10, as I said before.

**Comment by tkruse** [comment]
In 2.19.0, I cannot find a way to report to the user that an unknown command was given.
I tried

    .on("command:*", cb)
    .command("*").action(cb)

But in both cases cb was called even when another command matched.

**Comment by vanesyan** [comment]
You can maintain an array of known commands and check if one of them, otherwise notify user.
