### ISSUE TITLE
argument started with # is lost

### ISSUE THREAD

**Issue by bladerunner2020** [tj/commander.js#679]
If a required argument is starting with # it's not recognised.
for example, I have the following code:

```
program
    .command('setcolor <color>')
    .action(setColor)
    .description('set color of LED bar lights');
```

If I enter in command line ... setcolor #FF0000 the argument is not recognised and lost.

**Comment by shreeve** [comment]
The '#' is parsed by the shell as a comment and not passed to commander

**Comment by bladerunner2020** [comment]
Thank you for clarification.
