### ISSUE TITLE
There seems to be a bug when having a parameter called "name"

### ISSUE THREAD

**Issue by akayami** [tj/commander.js#681]
Considering following code:
```
const program = require('commander');
program
	.version('0.0.1')
	.option('-n --name [name]', 'Specify name of this vhost')
	.option('-p --port [port]', 'Specify port')

program.parse(process.argv);

console.log(program.name)
console.log(program.port)
```
If I execute:
`node bug2.js -n a -p b`
I get response:
```
a
b
```

However, if I execute:
`node bug2.js`

I get:
```
[Function]
undefined
```

Is there a safe way to check which parameter was provided ? 
This burned me on just checking:
```
if(program.name) {
...
}
```

**Comment by vanesyan** [comment]
Duplication of #284, which is similar to #680, #105.
Closed. Keep your eyes on #105 issue, thx
