### ISSUE TITLE
Support documenting environment variables

### ISSUE THREAD

**Issue by astorije** [tj/commander.js#682]
When running `atom -h` from the command line, I got the following:

```
Atom Editor v1.19.2

Usage: atom [options] [path ...]

One or more paths to files or folders may be specified. If there is an
[...]
window.

Environment Variables:

  ATOM_DEV_RESOURCE_PATH  The path from which Atom loads source code in dev mode.
                          Defaults to `~/github/atom`.

  ATOM_HOME               The root path for all configuration files and folders.
                          Defaults to `~/.atom`.

Options:
  -1, --one                  This option is no longer supported.  [boolean]
  --include-deprecated-apis  This option is not currently supported.  [boolean]
  -d, --dev                  Run in development mode.  [boolean]
  [...]
```

It would be great if `commander` had a way to easily document environment variables like this.

Syntax could be: `program.env('MY_ENV_VAR', 'This is the documentation for this environment variable')`. There would be no enforcement, just for documentation purposes (correctly aligning them with each other, adding a section title "Environment variables" if there is any, etc.), but it would be very helpful.

In fact, in [thelounge/lounge#1416](https://github.com/thelounge/lounge/pull/1416/files#diff-25f700bb76bbf957569bd288fbf7d328), we have deprecated one of our options, `--home`, in favor of an environment variable, `LOUNGE_HOME`.
Documenting this in [thelounge/lounge#1418](https://github.com/thelounge/lounge/pull/1418/files#diff-25f700bb76bbf957569bd288fbf7d328) felt weird and is not ideal as we'll have to correctly document it in a future version, when we remove `--home`.

**Comment by vanesyan** [comment]
You can specify necessary help information using `program.on('--help', () => { ... })` construction.

**Comment by vanesyan** [comment]
Thx for your time, we really appreciate it.
Will close as not interested in add such functionality, commander cannot cover all the userland ideas.
Feel free to reopen, if there's something more here :smile:

**Comment by astorije** [comment]
Well, that's unfortunate. I agree that `--help` can be used to achieve this, but it would feel more natural to have such a capability. In particular, we would not have to deal with padding, or setting up the header, as commander would do it, but I'm sure I'm forgetting advantages.

Using environment variables in a program is not a niche use case, and this would make it easy to document them. After all, they act as options under steroids (can be programmatically set) and it would be nice to document them similarly.

**Comment by astorije** [comment]
BTW, I'm not able to reopen this issue, but wouldn't anyway as you explained your position :)
