### ISSUE TITLE
Use of sub-command adds help command automatically

### ISSUE THREAD

**Issue by RonWang** [tj/commander.js#683]
>Commands:
     .......                     ...........
     subcommand      subcommand description
     help [cmd]           display help for [cmd]

This will automatically be added to the root command help message. Is there a way to remove this help command?

**Comment by RonWang** [comment]
.command('help', null, {noHelp: true}) will solve the problem

**Comment by RonWang** [comment]
no this will remove all the help message! Reopen and wait for response

**Comment by vanesyan** [comment]
As I know, there're no current way to remove help command/option from the output. It added automatically by commander.js.

**Comment by edykim** [comment]
I want to remove this default message as well. I just came with a quick and naughty idea while I read [the code](https://github.com/tj/commander.js/blob/v2.11.0/index.js#L195-L197).

```js
const program = require('commander');
program.addImplicitHelpCommand = () => {};
```

I hope that there is a way to remove the message using an option or something.

**Comment by shadowspawn** [comment]
Answered by @vanesyan 

An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by ZaLiTHkA** [comment]
I know this one is already closed, and also no-all-that-new... but just for anybody else who visits this rabbit hole, you're _most probably_ looking for [the `addHelpCommand` method](https://github.com/tj/commander.js#addhelpcommand):

without this configured at all, my output is as follows:

```powershell
Usage: index [options] [command]

My secret project description...

Options:
  -h, --help                  display help for command

Commands:
  setup                       generate runtime configuration in the current environment, ultimately allowing unattended usage for scheduled runs.
  remove                      remove current runtime configuration, in preparation for program removal.
  extract                     run the core image extraction process, applying custom configuration over internal defaults.
  help [command]              display help for command
PS C:\Users\littl\workspace\projects\my-secret-project-ink> npm start -- --help
```

then after setting the following:

```ts
const program = new Command();
program.addHelpCommand(false);
```

the "Commands" section of my output changed to the following:

```powershell
Usage: index [options] [command]

My secret project description...

Options:
  -h, --help                  display help for command

Commands:
  setup                       generate runtime configuration in the current environment, ultimately allowing unattended usage for scheduled runs.
  remove                      remove current runtime configuration, in preparation for program removal.
  extract                     run the core image extraction process, applying custom configuration over internal defaults.
```

note the missing `help [command]` _command_ at the end, while I still have my expected `--help` _option flag_. 👍🏼  hope that helps..
