### ISSUE TITLE
Conflict between alias and command arguments

### ISSUE THREAD

**Issue by lpezet** [tj/commander.js#684]
I defined a command and an alias for it. I defined another command with arguments which has the same value of the alias I used earlier.
When calling the latter, I get the following (and it seems to exit at once):
`script-[alias](1) does not exist, try --help`

Here's how to reproduce this weird behavior:

```
var program = require('commander');
program
  .version('0.0.1');
program
  .command('setup')
  .alias('configure')
  .description('run setup commands for all envs')
  .action(function(options){
    console.log('setting things up!!!')
  });
program
  .command('exec <cmd>')
  .description('execute the given remote cmd')
  .option("-e, --exec_mode <mode>", "Which exec mode to use")
  .action(function(cmd, options){
    console.log('exec "%s" using %s mode', cmd, options.exec_mode);
  });
program.parse(process.argv);
if (!program.args.length) program.help();
```

Now running the following commands:
`$ node issue.js setup`
`setting things up!!!`

`$ node issue.js exec setup`
`exec "setup" using undefined mode`

`$ node issue.js exec configure`
`exec "configure" using undefined mode`
`issue-setup(1) does not exist, try --help`

I could have sworn it used to work before...or did I mess up here?

**Comment by kiriappeee** [comment]
Can confirm that I reproduced this. It's executing the command as can be seen in :+1: 

`exec "configure" using undefined mode`

but then it's doing something else after that. I'll see if I can dig into this

**Comment by zenoven** [comment]
same issue

**Comment by demonray** [comment]
+1

**Comment by ZhaZhengRefn** [comment]
+1

**Comment by shadowspawn** [comment]
Reproduced.

**Comment by shadowspawn** [comment]
No longer reproducible in v3. The executable lookup got reworked to add support for `executableFile` command option, and perhaps indirectly fixed this particular case.
