### ISSUE TITLE
How can I  run “npm install ”  with  commander.js?

### ISSUE THREAD

**Issue by herozhou** [tj/commander.js#693]
How can I run simple bash commands like  “npm install ” with commander.js?
Install something such as express.Not just console.log(' npm install ')

**Comment by vanesyan** [comment]
It's not about commander at all, it's about Node.js. use `child_process.spawn` method in the command handler. More about `spawn` https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
