### ISSUE TITLE
How to set and persist user defined variable

### ISSUE THREAD

**Issue by KayUOM** [tj/commander.js#694]
Hi, 

Im creating a simple cli to touch a file to specific directory. I want the users to have the ability to set which directory of theirs they want to touch a new file to.. how can i do this. The path variable need to be used for further commands so it needs to persist.

```
const program    = require('commander');
const exec       = require('child_process').exec;
const fs         = require('fs');
var path       = "/";

program.version('0.0.1')
       .description('Command Line Interface (CLI)');

program.option('-p, --path', 'The enviroment path');

program.command('set:path <path>')
       .description('Set project path  <path>')
       .action(function (path) {
           path = path; // ?????
       });

program.command('make:controller <name>')
       .description('Add a new controller called <name>')
       .action(function (name) {
           const command = "touch " + path + name + ".js";
           exec(command);
           });
       });

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
