### ISSUE TITLE
check function not called when the option does not have any value

### ISSUE THREAD

**Issue by Nautigsam** [tj/commander.js#696]
I have this code:
```javascript
...
function checkFileFormat(value) {
    // check value
    console.log('OK')
}
...
program
	.version('1.0.0')
	.option('-F, --file-format [fileFormat]', `A file format`, checkFileFormat)
	.description('A tool to test file format.')
	.parse(process.argv)
```
As you can see, I have an option and I want to check user input with `checkFileFormat` function.

When I call the program like this: `program -F test` the function is called and `OK` is printed. However, when I call the program like this: `program -F` the function is not called and `program.fileFormat` is equal to `true`.

It's not the behaviour I would expect. I specifically marked the option having a value and I want `program.fileFormat` to be undefined if I don't set value for it.

Is it a known bug? I didn't find anything about it.

**Comment by shadowspawn** [comment]
For an option with a required value the syntax is:

```
.option('-F, --file-format <fileFormat>', `A file format`, checkFileFormat)
```

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
