### ISSUE TITLE
Arguments (not options) that start with "-" are discarded

### ISSUE THREAD

**Issue by BenBergman** [tj/commander.js#698]
I am using `osc-cli` which uses `commander.js` in the background. When I try to pass an argument that starts with a `-` the argument is discarded (eg: `osc --host 127.0.0.1:12345 /test "-1"). This occurs even if the argument does not match any of the defined options and even if the argument is surrounded by quotes.

I initially filed a bug in `osc-cli` but then realized the bug was actually in `commander.js`.

https://github.com/nulltask/osc-cli/issues/4

**Comment by lbustelo** [comment]
I think I'm having a similar issue. My tool is really a wrapper of a bunch of other CLI tools that are actually ran within docker containers. They have their own options that I do not want to define using commander, but rather get a hold of them and pass then through. For example:

```
$ my_tool other_tool -optA -optB=foo
```

If `-optA` or `-optB` are not defined using commander, it would be nice to get a hold of them so that I can passed them over to `other_tool`.

My current work around is to define an option in commander, `-o`, and then use that as an escape. That means my users need to write:

```
$ my_tool other_tool -o optA -o optB=foo
```

It works, but the UX is not ideal.

**Comment by plroebuck** [comment]
@lbustelo [untried] but isn't this already possible using `--`, which terminates argument parsing?
Everything remaining should be passed as a positional argument.

```sh
$ my_tool other_tool -- -optA -optB=foo
```

**Comment by lbustelo** [comment]
@plroebuck I have not tried that and if it works, it is a step in a better direction. Ultimately, I think what I'm asking is that if commander does not recognize a certain option... just pass it along.

**Comment by simonbuchan** [comment]
`--` is the current method to do this as a user.

If `.allowUnknownOption()` isn't provided the above should error with something like ``error: unknown option `-1'``, so `osc-cli` shouldn't provide that if they're not going to handle forwarding options themselves.

For now you should be able to use `cmd.parent.rawArgs.slice(3)` / `program.rawArgs.slice(3)`, though it seems a bit flakey to me.

It would be nice to add a "give it to me raw" option for commands like this, where letting it forward git-style is not *quite* what you want.

**Comment by BenBergman** [comment]
The `--` workaround is sufficient for my needs. Allowing the raw, unrecognized options to pass through would be even better, but I can see that is more of a problem with the application using this library than the library itself. Thanks for the help.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months, and original poster satisfied. It isn't likely to get acted on further due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
