### ISSUE TITLE
No longer zero-dependencies. In addition the package size has become 10x.

### ISSUE THREAD

**Issue by abetomo** [tj/commander.js#699]
https://github.com/tj/commander.js/pull/646#issuecomment-329307273

**Comment by vanesyan** [comment]
Yes, we've discussed it before in #646 thread, and the @alan-agius4 said that it's common practice in the way to support TypeScript typing.

**Comment by alan-agius4** [comment]
Quick link for the best practice guide: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md
