### ISSUE TITLE
Show help if no command was executed

### ISSUE THREAD

**Issue by ghost** [tj/commander.js#7]
Hi

I wanted my utility to show help if no command was executed.

This was how I monkey patched my code to solve it.

```
parentAction = commander.Command::action
commander.Command::action = (fn) ->
    newFn = ->
        fn.apply this, arguments
        commander.commandExecuted = this
    parentAction.apply this, [newFn]

# later after parse statement
if !commander.commandExecuted?
    process.stdout.write commander.helpInformation()
```

Is this an acceptable solution, or is there something I'm missing in the API?

Chris

**Comment by foxx** [comment]
PR sent, sorry for the delay

**Comment by mgenereu** [comment]
What if I want the argument missing messages and not the help?

**Comment by mgenereu** [comment]
I should leave an example.  Given this code:
```js
program
  .version('1.0.0')
  .arguments('<abc> <def> <ghi>')
  .parse(process.argv)
```
my experience is:
```
$ program
$ program first
  error: missing required argument `def'
$ program first second
  error: missing required argument `ghi'
```
I was expecting:
```
$ program
  error: missing required argument `abc'
  error: missing required argument `def'
  error: missing required argument `ghi'
$ program
  error: missing required argument `def'
  error: missing required argument `ghi'
$ program first second
  error: missing required argument `ghi'
```

**Comment by pedro93** [comment]
+1 for this

**Comment by lancedolan** [comment]
For posterity wondering specifically about the case where a _wrong_ command is given, such as a case where a user gives a bunch of arguments but forgets the command itself, this still isn't handled in the latest commander and the user will get blank unhelpful output. 

However, the command docs provide a very easy to handle the case explicitly yourself:

```
// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```

**Comment by anantanandgupta** [comment]
here is what i have written

```
program.allowUnknownOption(false);

const parsed = program.parse(process.argv);
if (!(parsed.args && parsed.args.length > 0 && (typeof (parsed.args[0] === 'object')))) {
  program.outputHelp();
}
```

**Comment by antonkulaga** [comment]
It is really annoying that there is not flag to automatically display help after parse errors when it crashes. If it will not be added I will just switch to another CLI lib in my next project

**Comment by shadowspawn** [comment]
Open a new issue with more details if you want visibility on this @antonkulaga

There have been lots of improvements to the error messages and help since this issue was opened and closed in 2011.

**Comment by jcbdev** [comment]
I know this is closed but if anyone finds themselves back here then the best solution is:

```
program
    .exitOverride(err => {
      if (err.code == 'commander.missingArgument') program.help();
      // add other error codes if you have different scenarios (options etc)
    });

  await program.parseAsync(process.argv);
```

**Comment by shadowspawn** [comment]
FYI as recent commenters @jcbdev @antonkulaga  : PR opened #1534

**Comment by shadowspawn** [comment]
Related: `.showHelpAfterError()` added in prerelease v8.0.0-2 by PR #1534
