### ISSUE TITLE
When will the next version be published?

### ISSUE THREAD

**Issue by alan-agius4** [tj/commander.js#701]
When will the next version be published, i noticed that it has been a while since any update was published

**Comment by abetomo** [comment]
@vanesyan Please release at good timing.

**Comment by vanesyan** [comment]
If there's no breaking change in the master since the last release, you can safely release it as I'm a bit busy for the next few months :)

**Comment by fujio0000** [comment]
@vanesyan When will it be released?

**Comment by vanesyan** [comment]
@abetomo
