### ISSUE TITLE
Issue with optional arguments in combination with regex validation

### ISSUE THREAD

**Issue by gerd-k** [tj/commander.js#708]
Taken the folowing example:

```
program
  .usage('[options] <file...>')
  .option('-t --type [type]', 'Type', /^(foo|bar)$/i)

```
I would expect that ``` program.type ``` is either ```foo``` or ```bar``` if a type is given. However, aparently
a value not matching the regex sets ```program.type``` to ```true```, which is not what is expected.
This is especialy bad if there are some argv values left, as in

```cmd -t some_file```

as ```some_file``` will be consumed so after parsing ```program.args``` is empty. 
Actually an option not matching the regex should be pushed back to the ```argv```, and the option itself sould be ```true```.

**Comment by shadowspawn** [comment]
The current regex behaviour is very simple, and sets the default value if the regular expression is not matched by the argument (and consumes the argument). 

You could avoid the surprising "true" by  including a default value (although still weak error handling):

```
.option('-t --type [type]', 'Type', /^(foo|bar)$/i, "foo")
or
.option('-t --type [type]', 'Type', /^(foo|bar)$/i, "unspecified")
```

**Comment by shadowspawn** [comment]
Short version: I have downgraded the regular expression support and removed it from the README (!).

Long version

I had a look at some of the reported issues including this one, and the code. I think the regular expression support is an incomplete feature that is likely to disappoint when the option value does not match the pattern. For now I don't think it is useful enough in general to try and bring up to a fully rounded feature (with help, error handling, et al).

It is not officially deprecated at this time so you can continue using it, but I suggest for new code you are better to handle the validation yourself using custom option processing or post-processing.

There is a somewhat related issue (enhancement) open suggesting a list of allowed values: #518
