### ISSUE TITLE
Incorrect parsing of flags with quotes

### ISSUE THREAD

**Issue by sanex3339** [tj/commander.js#710]
Version: 2.11.0

If i'll add quotes to the flags inside `option` calls, `commander` will incorrectly parse this flags and as result - wrong values will added to the `opts` object. I need quotes to more prettier description of command when `-h` flag is passed.

Example:
```js
.option(
    '--domainLock \'<list>\' (comma separated)',
    'Some description'
)
```

Expected description:
```
--domainLock '<list>' (comma separated)        Some description
```

Command execution
`app --domainLock 'google.com'`

Resulting `opts` object:
```
'\'<list>\'': [ 'google.com' ],
```

**Comment by sanex3339** [comment]
ping

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
