### ISSUE TITLE
autocomplete for subcommands

### ISSUE THREAD

**Issue by khaledosman** [tj/commander.js#716]
Hi,

awesome tool, I have built some kind of cli with two subcommands "deploy" & "undeploy" and was wondering if there's a way to have the terminal autocomplete the subcommands when pressing "tab".. Is this supported via commander? if not any alternatives or ideas to implement this would be appreciated

Thanks

**Comment by JohnRGee** [comment]
Commander does not support command line completion itself.

I use [tabtab](https://github.com/mklabs/node-tabtab#readme), which has an implementation pattern inspired by npm itself.

(Of some interest, [commander-completion](https://github.com/twolfson/commander-completion) is an older project to add commander completions automatically. I didn't get it working with current commander, but did look to the code for inspiration for parsing commander for commands and options. However, for your two subcommands I suggest it is easier to add them explicitly yourself than to generalise.)

**Comment by khaledosman** [comment]
Thanks

**Comment by gutenye** [comment]
For anyone seeking a solution, I’ve developed [@gutenye/commander-completion-carapace](https://github.com/gutenye/commander-completion-carapace) using Carapace. It's fast, works well, and supports numerous shells like Bash, Zsh, Fish, Nushell, and others.
