### ISSUE TITLE
Move @types/node to devDependencies

### ISSUE THREAD

**Issue by timocov** [tj/commander.js#719]
Please move `@types/node` to `devDependencies` section instead of `dependencies` https://github.com/tj/commander.js/blob/master/package.json#L26.

I guess that nobody want to have this types in their web-based project (for example `tslint` have `commander` as deps) (`@types/node` may be installed as cross-deps)

**Comment by timocov** [comment]
Related to #646

**Comment by abetomo** [comment]
It is fixed by #718
