### ISSUE TITLE
How to use the > operator in the command line arguments 

### ISSUE THREAD

**Issue by mregydev** [tj/commander.js#733]
Please I want to make a command that uses the > operator in the command line arguments 
For example I want when the user enter this command in command line 

> name jack > ma   

output will be 

>  jack ma

So I used the commander to create  command by writing this 

`app.command("name <firstName> > <lastName>").parse(process.argv)`

but this not working because > operator is predefined in the command line as it is used for writing in file 

So how to make this ?

**Comment by vicjohnson1213** [comment]
You have a few options:

> name jack \\> ma
> name jack ">" ma
> name jack '>' ma

As far as I know there is no way to prevent these special characters from doing what they do without escaping or quoting.

**Comment by shadowspawn** [comment]
Has an answer. No further responses. No  activity in over six months.

Thank you  for your contributions.
