### ISSUE TITLE
Get the handler funtion, `program.action(handler)`, return value

### ISSUE THREAD

**Issue by aSapien** [tj/commander.js#735]
Commander is writing directly on the process `stdio` streams that currently, cannot be overridden.
I would like to be able to get the resulting outputs as values, so I can then forward it to the invocation source.

In the following example we are receiving a command from a remote user, invoking it, and need to send back the result.

Command handler:

```javascript
/* commandHandler.js */
const program = require('commander')

// We want the value returned from this function
const handler = (word, to) => `${word} ${to}!`

program
  .command('say <word> <to>')
  .description('says <word> to <to>')
  .alias('s')
  .action(handler)
  .usage('say Hi John')

module.exports.handle = (message) => program.parse(['noop', 'noop', message])
```

Client facade:

```javascript
//chatbotFacade.js
const chatbot = require('some-chatbot-eventemitter')
// The command handler defined above
const commandHandler = require('./commandHandler')

chatbot.on('message', ({ sender, message }) => {  
  commandHandler.handle(message) 
  // no access to the result :(
  // returns the context (`Commander`) object
  })
})

const sendMessage = (recepient, msg) => {
	// implementation...
}
```

As you can see, I cannot access the result, nor can I differentiate the `stdout` and `stderr` data that were written by `commmander` from data written by other modules.

One solution may be to add a callback argument to the `program.parse()` function:

```javascript
/* commandHandler.js */ LINE 14
module.exports.handle = (sender, message, callback) => program.parse(['noop', 'noop', message, sender], callback)
//
/* chatbotFacade.js */ LINE 6
chatbot.on('message', ({ sender, message }) => {
  commandHandler.handle(message, (err, result) => {
    if (err) sendMessage(sender, 'An error occurred')
    else sendMessage(sender, result)
  })
})
```

And then manipulate the output, log it, send it, etc...

This is, of course, one of many methods by which the result value can be retrieved.

If the implementation above is acceptable, I can introduce a PR for this.

Thanks

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
