### ISSUE TITLE
Make help indentation configurable

### ISSUE THREAD

**Issue by mojavelinux** [tj/commander.js#741]
commander.js indents all lines in the help output. This is atypical. I don't know many commands that output help with this formatting (if you consider node, npm, lerna, ruby, docker, git, grep, find, vim, rpm). I'd like to make my command look more like the typical command. Please make the indentation size configurable, or provide a switch to disable it outright.

Commands which do use indentation include yarn and gem. Yarn happens to have indentation because it's using this package ;)

**Comment by mojavelinux** [comment]
I'm currently using the following patch as a workaround:

```js
const { Command } = require('commander')
  
const helpInformation = Command.prototype.helpInformation
const indentation = '  '

Command.prototype.helpInformation = function () {
  return helpInformation.call(this).split(/^/m).reduce((accum, line) => {
    if (line === '\n') {
      const lastLine = accum[accum.length - 1]
      if (!lastLine || !(lastLine === '\n' || lastLine.endsWith(':\n'))) {
        accum.push(line)
      }
    } else {
      accum.push(line.substr(indentation.length))
    }
    return accum
  }, []).join('')
}
```

I'd also like to remove the extra blank line between sections.

**Comment by abadraja** [comment]
Try this:
`
const { Command } = require('commander')
const helpInformation = Command.prototype.helpInformation;

  Command.prototype.helpInformation = function () {
      return helpInformation.call(this).split('\n').map(row => {
          return row.replace(/^\s{2}/, '');
      }).join('\n');
  }`

**Comment by mojavelinux** [comment]
That's effectively the same as what I proposed.

**Comment by JohnRGee** [comment]
For interest, the help indentation was removed in commander v2.18.0 via this Pull Request: #853

**Comment by mojavelinux** [comment]
Now that the help output has been standardized, I no longer think that configuration of the indentation is necessary. I had only proposed that as a compromise for changing the default behavior. But now that the default has changed, I think we're good. :+1:

**Comment by ctjlewis** [comment]
> commander.js indents all lines in the help output. This is atypical.

Your comments on this issue have been some of the most particularized and awful busywork-making I have seen in a while. I know it's been a few years since you opened these issues but really, I think it's hilarious that the reason this tool's output makes your eyes bleed is because one guy was adamantly opposed to padding and campaigned to remove it, suggesting it be configurable (!!!) and then dropping it when his particular needs were met.

> Now that the help output has been standardized, I no longer think that configuration of the indentation is necessary. I had only proposed that as a compromise for changing the default behavior. But now that the default has changed, I think we're good. 👍

Yeah, that checks out.

Another library infected by boomer mediocrity. Going on the rewrite list, I suppose.
