### ISSUE TITLE
Add commandFor method to Command

### ISSUE THREAD

**Issue by een250590** [tj/commander.js#746]
your add command

**Comment by mojavelinux** [comment]
The maintainer has decided not to add this method. See https://github.com/tj/commander.js/pull/738.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report. (Good comments in #738.)

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
