### ISSUE TITLE
Auto-Generate Help Documentation (Maybe as a section within a readme document)?

### ISSUE THREAD

**Issue by mofosyne** [tj/commander.js#756]
Is there a way to autogenerate a document from a base command that list out all the commands and command structure in a easily searchable markdown document?

This allows for self documenting cli interfaces.

------------

edit: okay mjavelinux if I get the time, I'll see if I can do it.

Notes:

```
# Help generation
Command.prototype.helpInformation() -- Gen help message string
--> Command.prototype.outputHelp() -- Send to std out
--> Command.prototype.help() -- do all above then exit
--> Command.prototype.addImplicitHelpCommand() -- add help command automagically

# Sub commads like `pm-install` is handled in executeSubCommand()

Command.prototype.executeSubCommand()
---> `var bin = basename(f, '.js') + '-' + args[0];`

```

Objective would be to use the above as a template, but be able to traverse the command() structure and print all commands under it in markdown format.

**Comment by mojavelinux** [comment]
You can take ideas from gli, which as this feature. See https://github.com/davetron5000/gli/blob/gli-2/lib/gli/commands/doc.rb

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report. (But this is an interesting idea.)

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by kuncevic** [comment]
I did this as a quick workaround

```
  program
    .addOption(new Option('-cmd2json')).action(name => {
    console.log(JSON.stringify((program.commands.map((x: any) => ({
      command:`${x.name()} ${x.alias() !== undefined ? x.alias() : ''}`,
      description: x.description()
    })))));
  });
```

Then pasted it [here](https://kdelmonte.github.io/json-to-markdown-table) and copy pasted the result in to my README.md  
You also can use [markdown-table](https://www.npmjs.com/package/markdown-table) to build table locally

**Comment by kuncevic** [comment]
I did this as a quick workaround

```
  program
    .addOption(new Option('-cmd2json').hideHelp());

  program.on('option:-cmd2json', () => {
    stdout(JSON.stringify((program.commands.map((x: any) => ({
      command:`${x.name()} ${x.alias() !== undefined ? x.alias() : ''}`,
      description: x.description()
    })))));
    process.exit();
  });
```

Then pasted it [here](https://kdelmonte.github.io/json-to-markdown-table) and copy pasted the result in to my README.md  
You also can use [markdown-table](https://www.npmjs.com/package/markdown-table) to build table locally

**Comment by mansona** [comment]
If anyone comes across this issue, I created a little helper script that you can use to verify that you have documented all your options: https://github.com/mansona/commander-docs

You can even add it to your CI to fail PRs that add new options but forget to document them https://github.com/mansona/codeowners-commit/blob/main/.github/workflows/ci.yml#L30
