### ISSUE TITLE
program, post option parse, pre action execute function

### ISSUE THREAD

**Issue by arieljake** [tj/commander.js#76]
program
    .version('0.0.1')
    .option('-d, --debug', 'debug mode');
        .prepare(function() {});

program
       .command()
       .action()...

It would be nice to have a "prepare" or init function that runs after the options have been parsed from the command line but before the correct action is executed, for some common initialization common to all actions, like initialization of server connection given provided host and port options. Am I offbase or is this worth writing?

**Comment by abetomo** [comment]
It seems to have been solved, so I will close it.
