### ISSUE TITLE
Handle git-style commands programmatically

### ISSUE THREAD

**Issue by yuhr** [tj/commander.js#767]
I want to do kinds of

```javascript
for (const command in config.commands)
  program.command(`${command}`, config.commands[command])
```

and achieve similar functionality to what npm-scripts does. Is there any way to disable searching executables and make `.action(...)` called?

**Comment by mauriciomelo** [comment]
I was looking for the same thing. This would be awesome.

**Comment by simonbuchan** [comment]
"git-style" means if you provide the description to `command()` it will use the pattern git does where it will call `{prog}-{command}`. Simply don't provide the description or provide it separately to instead use `action`:

```js
program.command(command)
  // .description(description)
  // .option(...)
  .action(action);
```

The docs could be better here, and it could also not use providing the description as a switch, instead falling back to git-style if `action` wasn't provided, which would be much clearer, but that gets confusing with `.on('someCommand', ...)`

**Comment by nwalters512** [comment]
This is a confusing API - I don't see any logical correlation between a command having a description and it being implemented as a git-style command. What if I want to provide a description for a command that is handled programmatically? @tj I'd appreciate any clarification you could make on why the API was designed this way and if there are any alternatives that could be used here.

**Comment by shadowspawn** [comment]
I have added this to a triage list of related items.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
