### ISSUE TITLE
Whitespace in argument

### ISSUE THREAD

**Issue by pandiafwan** [tj/commander.js#768]
i want to use space in my argument, for example:
> command arg1 "this is arg2"

So I used the commander to create command by writing this :

`program.command("command <arg1> <arg2>").description("example argument with space").action(function(arg1, arg2){
        console.log(arg2);
 });`

but the result of `arg2` just "this", and i want arg2 value is "this is arg2"

so how to make this ?

**Comment by JohnRGee** [comment]
This is working fine in a test program for me I wrote using your code:

    $ my-program command arg1 "this is arg2"
    this is arg2

In your example call you do not have the name of the program. Perhaps you have accidentally used `command` as both the program name and the command name?

**Comment by pandiafwan** [comment]
oh i'm sorry, this is my bad. 
i use shell script to run nodejs program, but forgot double quote in arguments

     node $PROGRAM_PATH/myprogram.js "$@"
thank you and sorry :)
