### ISSUE TITLE
Unexplainable error when used with =

### ISSUE THREAD

**Issue by vitaly-t** [tj/commander.js#773]
```js
const program = require('commander');

program
    .option('-i, --input <file>', 'input file')
    .parse(process.argv);
```

Typing in the following:

```
node index.js -i=input-file
```

Outputs:

```
error: unknown option `-p'
```

What option `-p`? The error makes no sense.

**Comment by JohnRGee** [comment]
I don't have a good story for the error message, but the issue is the command is not in an expected form, such as:

    node index.js -i Xxx
    node index.js -iXxx
    node index.js --input Xxx
    node index.js --input=Xxx

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
