### ISSUE TITLE
Installs with date 1st Jan 1970 and breaks ZIP

### ISSUE THREAD

**Issue by FerencH** [tj/commander.js#777]
All of the files installs with this very early date and this prevents uploading to AWS with the message:
ZIP does not support timestamps before 1980

**Comment by AdrieanKhisbe** [comment]
We have the same issue, using commander as a dependency of knex.js

As pointed out by @charsleysa, it's probably because the new version has been published when npm was "broken". 

Maybe a patch publish with an older version of npm (fix has not be released yet) might solve the problem.

**Comment by abetomo** [comment]
v2.15.1 released at npm@5.6.0

**Comment by AdrieanKhisbe** [comment]
@abetomo, awesome!
Thanks a lot!

**Comment by abetomo** [comment]
I think that I solved it, so I will close it.
