### ISSUE TITLE
How to handle errors ?

### ISSUE THREAD

**Issue by ExDomino** [tj/commander.js#782]
I would like to make that my program doesn't crash if there is a command error.
So, how to handle errors from your script please?

**Comment by marcincichocki** [comment]
Above solution didn't work for me. I end up doing something like this:

```typescript
// actions.ts
function actionErrorHanlder(error: Error) {
  console.error(error.message);
}

export function actionRunner(fn: (...args) => Promise<any>) {
  return (...args) => fn(...args).catch(actionErrorHanlder);
}

// main.ts
program
  .command('verify [deps]')
  .option('-s, --skip <deps>', 'skip deps')
  .action(actionRunner((deps, options) => {
    // action
  }));
```

This should work with `try catch` as well if your actions don't return promise.

**Comment by shadowspawn** [comment]
Thanks @marcincichocki 

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by ExDomino** [comment]
The problem was also solved so there is no problem to close this issue.

**Comment by Muhammed-Rahif** [comment]
I did it like this:
```js
program.configureOutput({
  writeErr: (str) => {
    console.error(str);
    console.info("Use --help for usage instructions!");
  },
});
```
