### ISSUE TITLE
Document `Command` class in readme

### ISSUE THREAD

**Issue by nicojs** [tj/commander.js#790]
I've noticed that by using the documented `const program = require('command')` syntax you're actually polluting a global `Command` object. This can be shared by other components resulting in weird issues (like https://github.com/nicojs/node-link-parent-bin/issues/4#issuecomment-378506690)

After inspecting the source code, i see that a `Command` class is exported! Kudo's to you sir! I'll use this from now on. It also helps quite a bit with testability (injecting a mock object for `Command` at test time). Let's promote this way of working a bit by documenting it in the readme

My idea is to update the readme and use `const Command = require('commander').Command; const program = new Command();` everywhere. I would like to place a remark to let people know that they could also use `const program = require('commander');` but that it is not preferred and explain why it is not.

If you agree, I'm willing to create the PR.

I would personally like it if the `const program = require('commander');`-way-of-working would become deprecated and removed in a major release. What are your thoughts on that?

**Comment by shadowspawn** [comment]
We do need to get something into the README about the "new" pattern, thanks for raising.

I don't think we will deprecate the old way as such, but it should be the my-program-is-so-simple-globals-are-ok way of working.

**Comment by shadowspawn** [comment]
I have added the new pattern in a large update to README in #953

**Comment by nicojs** [comment]
Awesome! LGTM

**Comment by shadowspawn** [comment]
Updated README with section right at start showing use of Command class 
https://github.com/tj/commander.js#declaring-program-variable
