### ISSUE TITLE
sub-command not executed if using --version option

### ISSUE THREAD

**Issue by ScandalousMan** [tj/commander.js#797]
Hello,

command : 
```shell
> spm module publish --version 1.0.0
```

expected result:
action requested should be executed passing the value 1.0.0 to option.version for sub-command module

actual result:
program displays current CLI version and exits

Here are the files in question :

```javascript
// file: spm
#!/usr/bin/env node
let Program = require('commander')

Program
.description('CLI for spm')
.version('1.0.0')
.command('module', 'for actions about modules').alias('m')
.parse(process.argv)

if (Program.args.length === 0) {
  Program.help()
}
// EOF

// file: spm-module
#!/usr/bin/env node
let Program = require('commander')

Program
    .command('publish')
    .alias('p')
    .description(`to send your module to spm registry and factory`)
    .arguments('[moduleName]')
    .option('-v, --version <version>', `to specify the module's version`)
    .action((moduleName, options) => {
      console.log('option version works:', options.version)
   })
.parse(process.argv)

if (Program.args.length === 0) {
  Program.help()
}
// EOF
```

I have found many open/closed issues about options in sub-commands, and others for the version option, but I cannot manage to fix this behaviour. Is it a WAI or is there a way to achieve what I'm trying to do ? Thanks a lot in advance !

**Comment by JohnRGee** [comment]
The `.version()` is implicitly adding options for `-V, --version` and triggers before your command fires, which I think is working as intended. To resolve the issue one of the two uses of `--version` needs to change and it can be the global one: 
https://github.com/tj/commander.js#version-option

**Comment by JohnRGee** [comment]
Disclaimer: I am a user not a maintainer. (So comments are IMHO.)

I do not think this feature is handled by commander. I think positional would match what people expect in at least some situations, but treating options globally may be by design. 

It is particularly surprising for --version which makes little sense when used with other arguments and options! But it feels quite natural with --help:
```
spm --help publish
spm publish --help
```

For an external reference, the first program I noticed non-positional global options with was Mercurial:
```
hg --repo custom status
hg status --repo custom

```

**Comment by shadowspawn** [comment]
(I am a maintainer now!)

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Pull Request opened to add `.enablePositionalOptions()` and `.passThroughOptions()`: #1427
