### ISSUE TITLE
hyphen as first char within quotes incorrectly parsed

### ISSUE THREAD

**Issue by twifty** [tj/commander.js#801]
```js
cli
    .arguments('<command> [args...]')
    .option('-h, --host <host>', 'The host on which the server should listen')
    .option('-p, --port <port>', 'The port number on which the server should listen')
    .option('-d, --debug', 'Start both server and client in debug mode')
    .option('-s, --debug-server', 'Start server in debug mode')
    .option('-c, --debug-client', 'Start client in debug mode')
    .action((command) => {
        const idx = cli.rawArgs.indexOf(command)
        const args = -1 !== idx ? cli.rawArgs.slice(idx + 1) : []

        cli.debugServer = cli.debugServer || cli.debug
        cli.debugClient = cli.debugClient || cli.debug

        runCommand(command, args, cli.host, cli.port)
    })
    .parse(process.argv);
```

Calling with `node bin/cli.js "php -dzend_extension=xdebug.so -v"` works correctly, but my script can handle a command without the php prefix. So, calling `node bin/cli.js "-dzend_extension=xdebug.so -v"` fails. The '-d' within the quoted string is interpreted as the --debug option.

**Comment by JohnRGee** [comment]
The quotes do not affect the parsing by commander so it still looks like an option as starts with a dash. What you can use is dash-dash which marks the end of the options for commander. This is a pattern used with other command-line parsing too. I think of it as telling the first command to leave the option for the sub command. 

i.e. try
`node bin/cli.js -- -dzend_extension=xdebug.so -v`

**Comment by twifty** [comment]
For my own usage I don't mind having to add the 'php' prefix. I built the cli as a means to load and test another module. It is not intended for production.

I had earlier tried using the '--' operator, but I couldn't figure out how to get the values.

**Comment by JohnRGee** [comment]
Are you basically always running php? You could do something like:

```
    .action((command, args) => {
        // const idx = cli.rawArgs.indexOf(command)
        // const args = -1 !== idx ? cli.rawArgs.slice(idx + 1) : []
        if (command !== "php") {
          args.unshift(command);
          command = "php";
        }
```

**Comment by twifty** [comment]
Basically yes. But I handle that side of the code within the php server. It's not as simple as unshifting 'php' into the array since it's possible for the php binary to use a different name, `phpx` for example which loads the `xdebug` extension.

Like I said above, I only created the CLI as a development tool. It allows me to load and run the main module outside of the test suite. The actual main module is not intended to be standalone. In reality, the whole string is passed over a tcp socket.

I'll close this since, in my terminal, `php -v` and `php "-v"` produce the same (version) output.
