### ISSUE TITLE
The options on the command seem to be turned into position params

### ISSUE THREAD

**Issue by tgsoverly** [tj/commander.js#805]
```
program
  .command('testCommand')
  .option('-f, --first-option', 'first option')
  .option('-a, --another-option', 'another option.')
  .description('Try to get this to work.')
  .action((firstArg) => {
    console.log(program.anotherOption)
    console.log(first)
  });
```

`testCommand --first-option first --another-option another` will print:

```
undefined
first
```

but 

`testCommand --another-option another --first-option something` will print 

```
undefined
another
```

I am not sure how to actually get the option values on the command.  Is this not working or am I crazy?

**Comment by JohnRGee** [comment]
The options are accessed on the Command object on which you called `.command`. You don't have the variable name visible in your code fragment. I have called it `program` here.

`console.log(program.anotherOne)`

**Comment by JohnRGee** [comment]
(Apologies, my previous answer was for a different situation. Didn't try running the code!)

See [Command specific options](https://github.com/tj/commander.js#command-specific-options) in the README. There is lots of gold in the README. 

Here is your example with an added optional argument just in case, as you mentioned arguments although using options.

```
program
   .command('testCommand [cmd]')
   .option('-f, --first-option <some-value>', 'first option')
   .option('-a, --another-option <some-value>', 'another option.')
   .description('Try to get this to work.')
   .action((theCmd, options) => {
      console.log(`first-option is ${options.firstOption}`);
      console.log(`another-option is ${options.anotherOption}`);
      console.log(`cmd is ${theCmd}`);
   });
```

```
$ node . testCommand --another-option another --first-option something some-command
first-option is something
another-option is another
cmd is some-command
```

**Comment by JohnRGee** [comment]
Oh, looking at your question again, have you set up so that `testCommand` runs node? In that case it does not get specified in the commander setup as it is part of the invocation rather than part of the parsing. (And for extra irony, my first answer might have been close...)

**Comment by tgsoverly** [comment]
You were supper correct, I just didn't see the example with the <param>
value and that is what was throwing it off.

**Comment by abdulhannanali** [comment]
@tgsoverly Does this solve your problem? If yes, maybe close the issue? :smile:
