### ISSUE TITLE
Hidden Options in --help without allowing UnknownOptions

### ISSUE THREAD

**Issue by Ciboulette** [tj/commander.js#811]
Hey everybody, 

I would like to allow passing certain options in a specific command without having it in the CMD --help. It's for admin purpose, how will you manage this? 

Best regards, 

Louis

**Comment by JohnRGee** [comment]
There is not support for hiding options from the help.

Two suggestions:
1) use a hidden command which has the extra admin options, as you can hide a command from the help
2) do not define the admin options for parsing using `commander` and look for it yourself in code.

**Comment by majuric** [comment]
@Ciboulette There's a `.help` callback you should be able to use to post-process help info before it's shown in the console. I guess you should be able to strip anything you don't want to show

https://github.com/tj/commander.js#helpcb

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
