### ISSUE TITLE
Parameter containing ')'

### ISSUE THREAD

**Issue by Simplonium** [tj/commander.js#816]
Whenever a parameter contains a right bracket, the console outputs something strange:

![image](https://user-images.githubusercontent.com/22157621/41304293-0bcadbee-6e70-11e8-8eaf-987aac75c0e5.png)

Is there a way around this without having to escape the character in the command line?

**Comment by JohnRGee** [comment]
This is probably an interaction with with the command-line interpreter (e.g. cmd.exe) rather than anything specific to `commander`. You may be able to confirm this by trying the same parameter with a different program.

**Comment by vanesyan** [comment]
Hello there I'm closing it as resolved, as there is no feedback by the author for long periods of time. Feel free to reopen it if problem still persists
