### ISSUE TITLE
Value inside angle brackets

### ISSUE THREAD

**Issue by dland512** [tj/commander.js#817]
I get that the angle brackets indicate a required value but what is the significance of the value inside them? So if I have

```
var program = require('commander');
program.option('-c, --config <path>', 'set config path. defaults to ./deploy.conf')
```

what does `path` do or mean?

**Comment by dland512** [comment]
Okay, I think I see how it works now. The value in angle brackets is like a placeholder for that option's value, i.e. the place where you would type it on the command line. The string inside the angle brackets doesn't really seem to matter.

So if it's in angle brackets and you don't supply the value, you get an error:

```
node test.js -c
error: option `-c, --config <path>' argument missing
```

Whereas if you use square brackets like this:
```
program.option('-c, --config [path], 'set config path. defaults to ./deploy.conf')
```
you can either specify a value like this

`node test.js -c /some/path`

in which case `program.config` will be `/some/path`. Or you can leave it off like this:

`node test.js -c`

in which case `program.config` will simply be `true`.

**Comment by JohnRGee** [comment]
Yes, the option name is used in the code but the `<value>` is a placeholder and potentially useful documentation.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. 

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
