### ISSUE TITLE
program.on('--help', function(){}) is not working

### ISSUE THREAD

**Issue by davidgatti** [tj/commander.js#818]
I'm following the documentation from here https://www.npmjs.com/package/commander#custom-help, and it seams not to be working. I did a bunch of combinations but without luck. 

If the doc is outdated could someone update it with a working example?

**Comment by JohnRGee** [comment]
The documentation is up to date. I checked by copying and pasting the whole example, and worked as advertised. The custom help is added on the end of the automatically generated help. 

Is your problem with adding to the help, or running your command?

**Comment by davidgatti** [comment]
Hmm.. adding the help. I have this:

```
//
//	React when the user needs help
//
program.on('--help', function() {

	//
	//	Just add an empty line at the end of the help to make the text more
	//	clear to the user
	//
	console.log("test");

});

//
//	Pass the user input to the module
//
program.parse(process.argv);
```

And nothing happens. This a project where I have it [L26](https://github.com/0x4447/0x4447-cli-node-cucumber/blob/master/index.js#L26). I remember it working. And when I updated the modules and was testing something else, I realized that this listener is not getting triggered.

And ida of what I'm missing?

**Comment by JohnRGee** [comment]
You have an extra (unwanted) call to `.parse` just before that code. Remove that and should start working more as expected.

**Comment by davidgatti** [comment]
The blindness is strong with this one 😅. Thank you and sorry.
