### ISSUE TITLE
Backslash with apostrophe in argument causes parsing error

### ISSUE THREAD

**Issue by ShaunLWM** [tj/commander.js#831]
I'm not sure if this was raised before but I can't find any related questions.

Apparently, when passing in the value to arguments with backslash + apostrophe, the command will continue parsing the rest of the arguments.

My usage of using this backslash + apostrophe was to allow users to input directory in the command line.
``` node test.js -i "C:\New Folder\" -o "D:\New Folder 2\"```

-----------------
**My test for this issue**

Example:

```
var program = require('commander');

program
    .version('0.1.0')
    .option('-p, --peppers', 'Add peppers')
    .option('-P, --pineapple', 'Add pineapple')
    .option('-b, --bbq-sauce', 'Add bbq sauce')
    .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
    .option('-m, --meat [type]', 'Add the specified type of meet [chicken]', 'chicken')
    .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineapple) console.log('  - pineapple');
if (program.bbqSauce) console.log('  - bbq');
console.log('  - %s cheese', program.cheese);
console.log('  - %s meat', program.meat);
```
-----------------
Input:
```
node test.js -c "Special Cheese" -m "chicken"
```
Result: 
```
you ordered a pizza with:
  - Special Cheese cheese
  - chicken meat
```
--------------------
Input:
```
node test.js -c "Special Cheese" -m "chicken"
```
Result:
```
you ordered a pizza with:
  - Special Cheese cheese
  - chicken meat
```
--------------------
Input:
```
node test.js -c Special Cheese\ -m chicken
```
Result:
```
you ordered a pizza with:
  - Special cheese
  - chicken meat
```
--------------------
Input:
```
node test.js -c "Special Cheese\" -m "chicken"
```
Result:
```
you ordered a pizza with:
  - Special Cheese" -m chicken cheese
  - chicken meat
```

Only the final input with the backslash+apostrophe combo caused the output to include the remaining command line. I'm not sure if it's supposed to work this way but feel free to close this if it is!

Thank you!

**Comment by shadowspawn** [comment]
I expect this was a parsing issue in the shell rather than an issue with commander.

This issue has not had any activity in over six months. Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
