### ISSUE TITLE
Options without values are always marked as required

### ISSUE THREAD

**Issue by HayDegha0917** [tj/commander.js#835]
Commander identifies whether an option is required or optional based on whether the value is [] or <>. Many times, however, an option does not need a value. For example, the `-v` (verbose) option does not need a value; either the option is present or it is not. In the past, commander would treat this as an optional argument. Now, it treats it as mandatory.

That's a breaking change and completely counter-intuitive. Using the UNIX `ls` command as an example, `-l`, `-s`, `-R` are all optional. Commander should restore backward compatibility, as well as compatibility with UNIX.

**Comment by ericnewton76** [comment]
What version did you notice this? 2.12.2 doesnt seem to do this.

**Comment by HayDegha0917** [comment]
Definitely with the latest version (2.19). If I switch to `commander 2.11`, it behaves as expected. If I switch to 2.19, I have a problem.

**Comment by HayDegha0917** [comment]
Try your test with a single-hyphen option (such as `-q`).

**Comment by vanesyan** [comment]
Hello there, I'll look into it soon

**Comment by JohnRGee** [comment]
I am using commander 2.19.0 and have not had this problem. There would seem to be some extra steps or context to trigger the issue.

I also tried using this code fragment:

````javascript
program.option('-o --optional', 'An optional option');
program.parse(process.argv);
console.log(program.optional);
````

which produced: 

````bash
$ node .
undefined
$ node . --optional
true
$ node . -o
true
````

(I am running macOS Mojave and using node v8.12.0.)

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
