### ISSUE TITLE
Enhancement request: Handle consecutive `-` options

### ISSUE THREAD

**Issue by HayDegha0917** [tj/commander.js#836]
In UNIX, it is possible to provide multiple flags as one "word". For example, `ls -ltr`. If you try that in commander, however, you get an error.

It would be nice if Commander handled that use case.

**Comment by JohnRGee** [comment]
The documentation says this is already supported.

https://github.com/tj/commander.js#option-parsing

> Short flags may be passed as a single arg, for example -abc is equivalent to -a -b -c. 

Can you provide some detail on what you tried?

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
