### ISSUE TITLE
Inconsistent use of ` vs '

### ISSUE THREAD

**Issue by campionfellin** [tj/commander.js#840]
See here:

https://github.com/tj/commander.js/blob/25b06ee12b6f14afa0b4b7b6f028a66a7c4faf5e/index.js#L792

https://github.com/tj/commander.js/blob/25b06ee12b6f14afa0b4b7b6f028a66a7c4faf5e/index.js#L808

https://github.com/tj/commander.js/blob/25b06ee12b6f14afa0b4b7b6f028a66a7c4faf5e/index.js#L810

for a few examples.

This causes the response to look like:
```
error: missing required argument `argument'
```

**Comment by vanesyan** [comment]
If you talk about usage of <code>`</code> as starting quote mark and then <code>'</code> as closing quote mark, then it was made intentionally by the author of library.
