### ISSUE TITLE
Breaking change in 2.17.0

### ISSUE THREAD

**Issue by BrandonOCasey** [tj/commander.js#850]
Here is our code https://github.com/videojs/standard/blob/9362b9ea57cd22a6f6e92edad93c9c62e80d5ef5/cli.js#L19-L28
Before version `2.17.0`  the action for `[targets...]` is not run. This means `commander.targets` would be `null`/`undefined`. 

After version `2.17.0` the action is run and `commander.targets` becomes `[]`. This causes the default that we have set with `!commander.targets` to not be set, which breaks things for us. 

This is the [fix we had to employ](https://github.com/videojs/standard/pull/32), but I still think this is a breaking change.

**Comment by abetomo** [comment]
Thanks for the report.
This is because we solved the issue (#729).
