### ISSUE TITLE
Standardize help output

### ISSUE THREAD

**Issue by jaredpetersen** [tj/commander.js#852]
The standard for command line interface help outputs is to print the help message without any newlines before or after the message. Currently, Commander does both.

Commander should better adhere to the standards set by other command line interfaces like `node`, `git`, `bash`,  `grep`, etc.

Changes Needed
- [x] Remove newline before help output
- [x] Remove newline after help output
- [x] Update documentation (particularly the "Custom help" section)
- [x] Update help output tests

Related to #832.

**Comment by jaredpetersen** [comment]
Working on this on my [fork](https://github.com/jaredpetersen/commander.js/tree/clean-up-help-output).

**Comment by jaredpetersen** [comment]
@vanesyan @abetomo @mojavelinux What are your thoughts on un-indenting the help output as well?

**No Indentation (Proposed)**
```
$ ./cli.js
Usage: my-app [options] [command]

Options:

  -v, --version    output the version number
  -h, --help       output usage information

Commands:

  start [options]  start the app
$ 
```

**Indentation (Current)**
```
$ ./cli.js
  Usage: my-app [options] [command]

  Options:

    -v, --version    output the version number
    -h, --help       output usage information

  Commands:

    start [options]  start the app
$ 
```

**Comment by jaredpetersen** [comment]
No indentation seems to be more standard across CLI tools.

**Comment by michael-brade** [comment]
This is great, thank you! Now only the error messages are still wrapped in newlines. This should be fixed as well, so I'll open a new issue.

**Comment by mojavelinux** [comment]
> What are your thoughts on un-indenting the help output as well?

I'm strongly in favor. In fact, I use a patch on top of commander.js to do exactly that.
