### ISSUE TITLE
Custom Sub Command Implementation Should Work

### ISSUE THREAD

**Issue by weasnerb** [tj/commander.js#857]
Hello tj and maintainers!

I have been using commander.js for a cli project that I have been writing and I did not like how sub commands are loaded into the program.

I have modified an existing command loader from [commander-starter](https://github.com/tsantef/commander-starter/blob/master/commands/index.js) so that it will load in commands based on folder structure. 

Here is the code for my loader:

```javascript
'use strict';

const fs = require('fs');
const path = require('path');

/**
 * Loads all commands within the commands folder
 * @param {*} program 
 */
module.exports = function(program) {

	class CommandLoader {
		
		constructor() {
			this._getAllCommands();
		}

		_loadCommandsInDir(loadPath, parentProgram) {
			let self = this;
			
			if (fs.existsSync(loadPath)) {
				// Loop though command files
				fs.readdirSync(loadPath).filter(function (filename) {
					return (/\.js$/.test(filename) && filename !== 'index.js');
				}).forEach(function (filename) {
					let name = filename.substr(0, filename.lastIndexOf('.'));
					
					// Load command into parentProgram
					require(path.join(loadPath, filename))(parentProgram);
					
					let loadedCommand = parentProgram.commands.find((cmd => cmd._name === name))
					
					let possibleSubCommandDir = path.join(loadPath, name);
					// Use self, because forEach overwrites 'this'
					self._loadCommandsInDir(possibleSubCommandDir, loadedCommand);
				});
			}
		}

		_getAllCommands() {
			const loadPath = path.dirname(__filename);
			this._loadCommandsInDir(loadPath, program);
		}

	}

	new CommandLoader();
};
```

My current folder structure is:

```text
/.index.js -- this has require('./commands')(program)
/commands/index.js -- This is the command loader
/commands/bridge.js -- bridge command 
/commands/bridge/setup.js -- bridge setup command
```

Loads in as:

```text
hue
hue bridge
hue bridge setup
```

The loader creates (what I believe to be) the correct command structure by adding setup to bridge.commands and adding bridge to setup.parent.

When calling hue bridge -h, the generated help shows setup as an available command, however when hue bridge setup -h is run,  it outputs the generated help for hue bridge -h.

[Here is a link to the branch in my repo in case you wish to take a look at it in more depth.](https://github.com/Weasnerb/hue-cli-extended/tree/bridgeAndRoom)

Thanks!
-Brian

**Comment by shadowspawn** [comment]
Interesting, thanks.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
