### ISSUE TITLE
Remove newline after "Options" in help output

### ISSUE THREAD

**Issue by jaredpetersen** [tj/commander.js#863]
From @mojavelinux in PR #853:

Another thing I've noticed is that commander.js adds a blank line after the category (such as options and commands). Most commands I use don't include this extra line.

commander.js:
```
Options:

  -v, --version                  output the version number
```

other commands
```
Options:
  -v, --version                  output the version number
```

**Comment by jaredpetersen** [comment]
Also extending this to "Commands:".

**Comment by mojavelinux** [comment]
For reference, here are the commands where I observe the described behavior:

grep, sed, awk, docker, firefox, wget, vim, gulp, mvn, node, ruby, zsh

**Comment by mojavelinux** [comment]
I'm actually having a hard time finding a command which uses a blank line that otherwise has fairly clean usage text. (There are a lot of commands which have completely disorganized usage text, so I'm ignoring those commands).

**Comment by mojavelinux** [comment]
Thanks for fixing this @jaredpetersen and @vanesyan for merging. Nice work!
