### ISSUE TITLE
Plurality Support for option/command/alias

### ISSUE THREAD

**Issue by gtzilla** [tj/commander.js#871]
This project is really useful. Simple enough to be comprehensible and still useful. Solid support. Mention because this request might cause too much complexity to be worth any trouble.

Really like the `.alias()` method and find myself using it for a lot of different common scenarios. One of those cases is plurality. For example `.command("locations")` vs `.alias("location")`  Would it be possible to support plurality as an alias directly? `locations?` for instance.  I didn't see anything in the code but I could have easily over looked.

**Comment by shadowspawn** [comment]
I don't think we would add this, not least because English is so inconsistent. Have you got examples of other CLI tools or packages doing this?

**Comment by shadowspawn** [comment]
As for doing it manually, there is not current support for multiple aliases, and that was raised in #531
