### ISSUE TITLE
empty argument list does not result in help showing

### ISSUE THREAD

**Issue by TrentonAdams** [tj/commander.js#878]
I did not pass any "description" for my `program.command('mycommand')` calls.  Since commander checks for the existence of a "desc", before settings `this.executables`, and implicit help is only set if `this.executables` is true, help is never shown.

Shouldn't `this.executables` always be set if `program.command()` is called?  See line 178.

Here is a real example of how I'm calling command, you'll see no description passed.
```
        program
            .command('show-cab <cab_number>')
```

**Comment by JohnRGee** [comment]
I expect this is the intended behaviour, as in general the program may do something useful when executed without options or parameters. As a simple example, consider the `ls` command.

An example of displaying help by default is included in the README example for 
[outputHelp](https://github.com/tj/commander.js#outputhelpcb)

**Comment by shadowspawn** [comment]
This issue has not had any activity in five months, and an explanation was offered. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
