### ISSUE TITLE
Provide info about default values on the main github page

### ISSUE THREAD

**Issue by mprinc** [tj/commander.js#884]

**Comment by JohnRGee** [comment]
What sort of info about default values are you looking for?

There are a coupe of examples of default values for options that are covered without additional explanation in the README:

      .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')

      .option('-s --size <size>', 'Pizza size', /^(large|medium|small)$/i, 'medium')

**Comment by mprinc** [comment]
Thanks. Yes I discovered them eventually, but at the moment I was interested to provide a default value in my app, I couldn't search for any explicitly mentioned default use case, but rather hitting:

`  .command('list', 'list packages installed', {isDefault: true})`

or

`If you want to display help by default ..`

It would be nice to have more clear directions

**Comment by Stogoh** [comment]
And how can i set a option on by default. For example I have an option `--databaseHost` which should have a default value. How can I do this? This is without an enum.

**Comment by ozbillwang** [comment]
I am looking similar to set default value for the parameters.

I used package `argparse` before, and it is easy to set the default value, how can I do the same with `commander`?

```
bar.addArgument(
  [ '-f', '--foo' ],
  {
    action: 'store',
    defaultValue: "test.txt",
    help: 'foo3 bar3'
  }
);
```

**Comment by shadowspawn** [comment]
@ozbillwang 

```
  .option('-f, --foo <value>', 'foo3 bar3', 'test.txt')
```

**Comment by shadowspawn** [comment]
I have proposed a large update to options coverages in README in #953

**Comment by shadowspawn** [comment]
Updated README to clarify option types, including section for default option value
https://github.com/tj/commander.js#default-option-value
