### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bgm5d** [tj/commander.js#885]
Can you confirm that all versions (including 2.6.0) are subject to the MIT License?  I am very grateful for any guidance you can give!!

Thank you!
Bridget

**Comment by JohnRGee** [comment]
A little digging shows the MIT license was in the initial commit of README.md in 2011, moved to a separate license file in 2015, and has not been modified since then.

https://github.com/tj/commander.js/commit/672c7d01d8382257226d67c39c6e1002c881d95f
https://github.com/tj/commander.js/commit/ef0a54ff10166bdfadf7c7e554221b723a8a2248#diff-9879d6db96fd29134fc802214163b95a
https://github.com/tj/commander.js/commits/master/LICENSE

**Comment by bgm5d** [comment]
Thank you!!

On Tue, Oct 30, 2018 at 6:02 AM John Gee <notifications@github.com> wrote:

> A little digging shows the MIT license was in the initial commit of
> README.md in 2011, moved to a separate license file in 2015, and has not
> been modified since then.
>
> 672c7d0
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tj_commander.js_commit_672c7d01d8382257226d67c39c6e1002c881d95f&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=sXL1Y3L63sBCDZ2JmNsYjqH28WHOxjKyFZ2jT2AywnM&s=CkG4C9XkxftAqKGHmWyX5GaKQM6MaAuz-QY4C0RlOW8&e=>
> ef0a54f#diff-9879d6db96fd29134fc802214163b95a
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tj_commander.js_commit_ef0a54ff10166bdfadf7c7e554221b723a8a2248-23diff-2D9879d6db96fd29134fc802214163b95a&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=sXL1Y3L63sBCDZ2JmNsYjqH28WHOxjKyFZ2jT2AywnM&s=JGeBX5Vfr57raHINRkK14tmPxaS7WSU6doicY8p8gAA&e=>
> https://github.com/tj/commander.js/commits/master/LICENSE
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tj_commander.js_commits_master_LICENSE&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=sXL1Y3L63sBCDZ2JmNsYjqH28WHOxjKyFZ2jT2AywnM&s=mD3M0bBkN1wciClqiFGu_6Sd3S6AaglFxRLYW_RmA38&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tj_commander.js_issues_885-23issuecomment-2D434240129&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=sXL1Y3L63sBCDZ2JmNsYjqH28WHOxjKyFZ2jT2AywnM&s=zp-_MpSXEipGvW5k6886j0Kf9X4MKLrq5Z_MI46og4o&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AqcSol8IvKByGO7-5FOswFJSxRikASCTnPks5uqCO-5FgaJpZM4X-5FWjF&d=DwMFaQ&c=pLULRYW__RtkwsQUPxJVDGboCTdgji3AcHNJU0BpTJE&r=53ETeLIrYy3xQSeY0QdYzBZDCVzlhcvQ3XYg7yAIKxc&m=sXL1Y3L63sBCDZ2JmNsYjqH28WHOxjKyFZ2jT2AywnM&s=8oXnbgn4FX5e7DVSbcu3lNrGsxjMjHeMLPQalVprW88&e=>
> .
>


-- 

*Bridget Morris*

Manager, Counsel
804-512-2273
bridget.morris@capitalone.com
________________________________________________________

The information contained in this e-mail is confidential and/or proprietary to Capital One and/or its affiliates and may only be used solely in performance of work or services for Capital One. The information transmitted herewith is intended only for use by the individual or entity to which it is addressed. If the reader of this message is not the intended recipient, you are hereby notified that any review, retransmission, dissemination, distribution, copying or other use of, or taking of any action in reliance upon this information is strictly prohibited. If you have received this communication in error, please contact the sender and delete the material from your computer.
