### ISSUE TITLE
.action is not triggered

### ISSUE THREAD

**Issue by SpaceboyRoss01** [tj/commander.js#887]
Code:
```js
#!/usr/bin/env node

const Client = require("../client.js");
const blessed = require("blessed");
const fs = require("fs");
const os = require("os");
const path = require("path");

if(!fs.existsSync(path.join(os.homedir(),".cluster-mon"))) fs.mkdirSync(path.join(os.homedir(),".cluster-mon"));
if(!fs.existsSync(path.join(os.homedir(),".cluster-mon","client.json"))) fs.writeFileSync(path.join(os.homedir(),".cluster-mon","client.json"),fs.readFileSync(__dirname+"/../client-defaults.json"));

var action;

const program = require("commander")
	.version("1.0.0")
	.command("<command>")
	.action(cmdAction => {
		action = cmdAction;
	})
	.parse(process.argv);

switch(action) {
	case "monitor":
		var cfg = JSON.parse(fs.readFileSync(path.join(os.homedir(),".cluster-mon","client.json")).toString());
		var clients = [];
		if(Array.isArray(cfg)) {
			for(var cc of cfg) clients.push(new Client(cc));
		} else clients[0] = new Client(cfg);
		
		var screen = blessed.screen({ smartCSR: true });
		screen.title = "Cluster Monitor";
		
		screen.key(["escape","q","C-c"],(ch,key) => { process.exit(0); });
		
		screen.render();
		break;
	default:
		throw new Error("Invalid action: "+action);
}
```

Output:
```
/home/spaceboyross/cluster-mon/bin/cmcli.js:38
		throw new Error("Invalid action: "+action);
		^

Error: Invalid action: undefined
    at Object.<anonymous> (/home/spaceboyross/cluster-mon/bin/cmcli.js:38:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by Bamii** [comment]
So i tested your code, and it seems that adding a description to the command fixes it. 
Like so, `.command('<command>', 'Some description')` Try it and see.

**Comment by JohnRGee** [comment]
You could define `monitor` as a command, like:

```
program.command("monitor")
   .action(() => {
      var cfg = JSON.parse(fs.readFileSync(path.join(os.homedir(),".cluster-mon","client.json")).toString());
      // etc
   });
```

Or you can use `.arguments` rather than `.command` (since you aren't defining a command as such). See [specify-the-argument-syntax](
https://github.com/tj/commander.js#specify-the-argument-syntax) in the README, like:
```
program.arguments("command")
   .action((cmdAction) => {
      action = cmdAction;
   });
```

**Comment by SpaceboyRoss01** [comment]
I tried that and it didn’t work.--Sent from Yandex.Mail for mobile21.11.2018, 02:14, "John Gee" <notifications@github.com>:You could define monitor as a command, like:
program.command("monitor")
   .action(() => {
      var cfg = JSON.parse(fs.readFileSync(path.join(os.homedir(),".cluster-mon","client.json")).toString());
      // etc
   });

Or you can use .arguments rather than .command (since you aren't defining a command as such). See specify-the-argument-syntax in the README, like:
program.arguments("command")
   .action((cmdAction) => {
      action = cmdAction;
   });

**Comment by JohnRGee** [comment]
Please give an example of a command line call to your program? (If your program is called `monitor` then that does not get parsed in the commander code.)

I took shortcut with my example program and called it directly without setting up bin, like:

```
node . monitor
```

**Comment by SpaceboyRoss01** [comment]
`node cmd.js monitor`21.11.2018, 10:05, "John Gee" <notifications@github.com>:Please give an example of a command line call to your program? (If your program is called monitor then that does not get parsed in the commander code.)
I took shortcut with my example program and called it directly without setting up bin, like:
node . monitor

**Comment by JohnRGee** [comment]
Which approach would you like a longer example for, `.command("monitor")` or `.arguments' ?

**Comment by SpaceboyRoss01** [comment]
.command21.11.2018, 10:13, "John Gee" <notifications@github.com>:Which approach would you like a longer example for, .command("monitor") or `.arguments' ?

**Comment by JohnRGee** [comment]
Two example actions, and error handling for unrecognised actions:

```
#!/usr/bin/env node

const program = require("commander")
    .version("1.0.0");

program
    .command("monitor")
    .action(() => {
        console.log("recognised monitor");
    });

program
    .command("log")
    .action(() => {
        console.log("recognised log");
    });

program.on('command:*', () => {
    console.error(`Invalid action: ${program.args.join()}`);
});

program.parse(process.argv);
```

```
$ node cmd.js monitor
recognised monitor
$ node cmd.js log
recognised log
$ node cmd.js missing
Invalid action: missing
$ node cmd.js 
$ 
```

**Comment by JohnRGee** [comment]
Did you sort out your problem? (Can this issue be closed?)

**Comment by SpaceboyRoss01** [comment]
Yes
