### ISSUE TITLE
Disable validation for a specific command

### ISSUE THREAD

**Issue by mikeerickson** [tj/commander.js#888]
I am looking for a way to disable option validation on a per command basis?

```javascript
program
  .command("up")
  .action((env, options) => {
});
```

Then, when calling command, I dont want commander to throw error with invalid options

```bash
$ cli up -dl --flags --logs ...
```

When calling `up` I receive message

```bash
error: unknown option `-l'
error: unknown option `--flags'
...

**Comment by JohnRGee** [comment]
You can use `allowUnknownOption()` which does just what you want, but be warned there is not a convenient way to get the unrecognised options. See example and discussion in #802.

An alternative pattern which might make sense if the options are for another command is to use `--` to stop the option processing (which effectively turns the remaining options into arguments). I use this pattern a bit, like when passing options to an npm run script which are intended for the script and not for npm.

e.g.
```
program
.command("up [args...]")
.action((args) => {
    console.log(args);
});
```

Called like: 
```
$ cli up -- -dl --flags --logs ...
```

**Comment by JohnRGee** [comment]
Did you sort out your problem? (Can this issue be closed?)

**Comment by shadowspawn** [comment]
Question hopefully answered. No further questions. Closing.
