### ISSUE TITLE
how to use `help [cmd]`/way to opt out of this behaviour

### ISSUE THREAD

**Issue by jakebolam** [tj/commander.js#892]
Could we have some docs on how to add commands that support the recently introduced command
`    help [cmd]                display help for [cmd]`

Alternatively could we have a way to opt out of help for sub commands.
e.g. just
`    help               display help`

And possibly a way to opt out of `-h`/`--help` as well (if using the command)
```
  Options:

    -h, --help                output usage information
```

**Comment by shadowspawn** [comment]
In answer to your first question, the current behaviour is when using a git-style (sub)command, these two are equivalent, and call the (sub)command with --help to display its help:

```
my-command help foo
my-command foo --help
```

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
