### ISSUE TITLE
Override --help?

### ISSUE THREAD

**Issue by Simplonium** [tj/commander.js#893]
I haven't found any topic on this online, but how do I override --help? I know I can listen to the event, but the default help output still appears. I'd like to override it both globally and per-command without the default help output appearing.

Edit: Just checked the source code. It seems --help is hardcoded and not configurable?

**Comment by JohnRGee** [comment]
Correct, there isn't currently support for overriding the default help output for `--help`.

It has come up before: #47 #242

**Comment by Tbhesswebber** [comment]
@shadowspawn - I would make a new issue, but it seems as though it would just be closed as a duplicate - is this something that is considered out of scope for commander?

**Comment by shadowspawn** [comment]
@Tbhesswebber 
Go ahead and open a new issue with details about your situation.

#242 was still open when this got closed as a duplicate., and this issue was a question which was "answered". It didn't get enough upvotes to consider it an implicit enhancement request.

**Comment by shadowspawn** [comment]
My standard line when closing old bugs due to inactivity, rather than as a duplicate is:

> Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by shadowspawn** [comment]
Commander v6.1 allows allows disabling the built-in help option: #1325
