### ISSUE TITLE
Variadic not recognized if only a single argument is supplied to it when using a non-argument option

### ISSUE THREAD

**Issue by tcf909** [tj/commander.js#894]
With the following commander command:
```
cli.command('push [files...]')
	.description('Push new versions of classes.')
	.option('--class-repo [classRepo]', "Required.")
	.option('--create', 'Optional. Create the class if it does not already exist.')
	.action(async (...args) => await apiInterface['classes/push'](...args));
```

I am not able to successfully run:
```
prog push --create ./file1.js
```
I am however able to run:
```
prog push --create ./file1.js ./file2.js
```
I have even tried using .command('push <file> [files...]') and combining the data, but I get the same result. Shouldn't the variadic be 1 OR more? not more than 1?

It should be noted that I can also run the prog without the --create option and a single variadic successfully:
```
prog push ./file1.js
```
Also works fine if I do:
```
prog push --create --class-repo someValue ./file1.js
```

**Comment by JohnRGee** [comment]
Did you sort out your problem? (Can this issue be closed?)

**Comment by tcf909** [comment]
> I think your problem might be using the `...` with the action callback parameter, making it a `rest parameter` collecting all the arguments. `commander` will pass an array of files as the first parameter, and an options object as the second parameter. You are combining them all into one variable, which is probably not what you intended.
> 
> I suggest try something like this and see what objects you are getting passed:
> 
> ```js
> .action(async (fileArgs, options)
> ```


Unfortunately, that isn't the issue. The issue is commander won't even validate the input enough to hand the parameters to my application.

The program instead outputs the "Usage:" dialog.

This is definitely a bug. I'm surprised more people don't run in to it.

**Comment by tcf909** [comment]
@shadowspawn bump

**Comment by tcf909** [comment]
Update:

It seems to only run in to the validation issue when <files...> (vs [files...]) is used and a single file is provided.

**Comment by tcf909** [comment]
I'm working around the issue by using [files...] then validating the files array is not empty in the application code.

**Comment by tcf909** [comment]
Example action handler:

```
async method(files, {create, confirm} = {}){
  
  let files = ['a', 'b'];

  let fileContents = await Promise.all(_.map(files, async (file) => return await fs.readFile(file)))

  console.log('We never make it here')

}

**Comment by tcf909** [comment]
Looks like it was my fault. Sorry for wasting your time. 

I was handling a weird condition where a sub command with no arguments will not display help:

```
command sub-command
```
Just exits with no output and exit code 0

So I had:
```
cli.parse(process.argv);
cli.args.length === 0 && cli.help();
```
But because of the way the args are cleared out for this particular command (different than others for some reason) the cli.help() condition was being hit even for valid commands.

switched to using ```cli.rawArgs.length === 2 && cli.help()```
