### ISSUE TITLE
Unexpected behavior when options passed before command, but fine if passed after

### ISSUE THREAD

**Issue by philsturgeon** [tj/commander.js#895]
I maintain [Speccy](http://speccy.io/) and we've got a [confusing bug](https://github.com/wework/speccy/issues/217).

Our commander.js usage is all [here](https://github.com/wework/speccy/blob/master/speccy.js) and as far as I can tell im following documented usage. But, our options are not working as expected. 

All commands suffer the same issue, butt an example:

``` js
program
    .command('lint <file-or-url>')
    .description('ensure specs are not just valid OpenAPI, but lint against specified rules')
    .option('-q, --quiet', 'reduce verbosity')
    .option('-r, --rules [ruleFile]', 'provide multiple rules files', collect, [])
    .option('-s, --skip [ruleName]', 'provide multiple rules to skip', collect, [])
    .option('-j, --json-schema', 'treat $ref like JSON Schema and convert to OpenAPI Schema Objects (default: false)')
    .option('-v, --verbose', 'increase verbosity')
.action(lint.command);
```

I would expect the command `speccy lint -j foo.yaml` to work the same way that I would expect `speccy lint foo.yaml -j` to work, but the first command gives this output:

```
 node speccy lint --json-schema test/samples/json-schema/openapi.yaml
Usage: speccy <command> [options]

Options:
  -V, --version                    output the version number
  -c, --config [configFile]        config file (containing JSON/YAML). See README for potential values.
  -h, --help                       output usage information

Commands:
  lint [options] <file-or-url>     Ensure specs are not just valid OpenAPI, but lint against quality control rules
  resolve [options] <file-or-url>  Pull in external $ref files to create one mega-file
  serve [options] <file-or-url>    Display specifications in beautiful human readable documentation
```

Any ideas here?

**Comment by JohnRGee** [comment]
You are getting a false positive from this line in [speccy.js](https://github.com/wework/speccy/blob/master/speccy.js):

```javascript
if (!program.args.length) program.help();
```

`program.args` has what is left-over from `commander` parsing, whereas for displaying help you want to check the original arguments passed to your program. (I am a bit surprised by the difference in behaviour you are seeing, but not relevant to fix.)

The [Output Help](https://github.com/tj/commander.js#outputhelpcb) example code is:

```javascript
if (!process.argv.slice(2).length) {
  ...
}
```

**Comment by philsturgeon** [comment]
Thank you, that was it!
