### ISSUE TITLE
Display help message in blue

### ISSUE THREAD

**Issue by cmouze** [tj/commander.js#901]
Hi,

I would like to display help in blue.
I try to use : on function like this
```javascript
const { Command } = require('commander')
const helpInformation = Command.prototype.helpInformation
program.on('--help', function() { 
    console.log(make_blue(helpInformation.call(this)));
    console.log('');
});
function make_blue(txt) {
    return colors.blue(txt); //display the help text in blue on the console
}
```
but I got help message twice. once in white and the second in blue.

Could you give what I miss, please ?

**Comment by shadowspawn** [comment]
I assume this has been answered.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
