### ISSUE TITLE
`.usage` is not documented

### ISSUE THREAD

**Issue by toymachiner62** [tj/commander.js#902]
I see this example of `.usage`, but it's not documented anywhere on the README file.

This should be documented in the README so we know how to use it.

![image](https://user-images.githubusercontent.com/485782/50652754-b75c8f00-0f44-11e9-9180-22efbe5e4547.png)

**Comment by tahayk** [comment]
+1

**Comment by baruchvlz** [comment]
If you read the code [here](https://github.com/tj/commander.js/blob/master/index.js#L913-L926), seems pretty straight forward to me. It logs the commands and flag options you have added through `.option`....

**Comment by shadowspawn** [comment]
(Note to self: unrelated other than also undocumented and might cover in same section of less common routines, `.name()` and `.opts()`.)

**Comment by shadowspawn** [comment]
Added `.name` and `.usage` to README in v3.0.1
