### ISSUE TITLE
Provide access to the allowUnknownOption complaints

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [tj/commander.js#903]
There's no way I can find to find _which_ args are unsupported. In this 

```typescript
program..allowUnknownOption();

// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```

The function receives no arguments and `command.args` is empty in my usage. Can there be a `command.unknownOptions` added to store the ones added?

**Comment by shadowspawn** [comment]
Closing in favour of #802

Thank you  for your contributions.
