### ISSUE TITLE
Help text for subcommand options

### ISSUE THREAD

**Issue by jwheare** [tj/commander.js#905]
A subcommand can have options with descriptions defined but I can't see how to make them show up in the help text. It just shows:
`subcommand [options]`

Is it possible to expand this just as the global options are at the top of the help text?

**Comment by JohnRGee** [comment]
To see the options for the subcommand:

    command subcommand --help

You can also install a [Custom help](
https://github.com/tj/commander.js#custom-help) listener for the subcommand to supply additional information about the subcommand to display when its help is requested.

**Comment by jwheare** [comment]
Ah, thanks, would be good to get this documented. Also is there a way to programmatically trigger it? Thinking of a subcommand like:

`command help <subcommand>`

Would be useful for people familiar with git's help system.

**Comment by jwheare** [comment]
Looks like this is already stubbed but doesn't seem to do anything:

https://github.com/tj/commander.js/blob/82d0d0ae6d66163f5c97ce56031b796621bef4ce/index.js#L210-L212

**Comment by shadowspawn** [comment]
The current behaviour is when using a git-style (sub)command, these two are equivalent, and call the (sub)command with --help to display its help:

```
my-command help foo
my-command foo --help
```

**Comment by claytongulick** [comment]
I'm running into this as well. Not sure what the correct approach is.

My structure looks like this:
Top command: reporting (this is npm linked)
Sub commands: reporting-datapump, reporting-scheduler (these are all also npm linked bins)
Sub Sub commands: reporting-datapump clean [options] - this has an action handler, and does the work.

So, from what I can tell, there's no way to get what the [options] are from top level help. These combinations fail:

```reporting help datapump```
```reporting datapump --help```
```reporting help datapump drop```
```reporting-datapump help```
```reporting-datapump help drop``` -- this shows nothing ?!?

This works:
```reporting-datapump drop --help```
and this:
```reporting datapump drop --help```

Perhaps this could all be solved by some sort of recursive help option? I.e. optionally navigate all sub commands recursively and aggregate their helps?

It's not a great user interface for the user to have to guess that specific command in order to see the options for the sub-sub-command help.

My expectation, as a user, would be that when I do:
```reporting help datapump``` or ```reporting datapump --help``` I would be able to see all of the sub commands and their options.

**Comment by shadowspawn** [comment]
Interesting example of `npm -l` given in https://github.com/tj/commander.js/issues/521#issuecomment-565115407

**Comment by benjaminadk** [comment]
I am running into a similar issue. I am using git style subscommands. I wanted to add some customization to the help message. I used `.help(cb)` as per docs. This was great for the top level command but overwrote all subcommand help messages. The `command help subcommand` now just outputs the custom help message.

I tried to add `.help(cb)` to subcommands thinking maybe I could overwrite them all, but that didnt work. 

Anyways, I might just use this to create an all inclusive help menu by manually inserting subcommand options. The downside is that this is more work and defeats the cool features already present in this tool. 

I made a branch for the version of my code I am referring to [Custom Help Issue](https://github.com/benjaminadk/la-design-concepts/tree/custom-help/javascript/cli)

**Comment by shadowspawn** [comment]
@benjaminadk 
Some quick feedback based on first read of your code, not actually running it.

1) `.help(cb)` is a call to actually display the help, with an optional callback to process the text. It does not provide a callback to be used when the help is displayed later, which I think is how you are trying to use it.

2) For an all inclusive help, a possible approach might be to add a help command which displays the top level built-in help and runs over the subcommands displaying their built-in help too.

**Comment by shadowspawn** [comment]
For original poster, there are related changes in the published pre-release of Commander v5.0.0 (#1163)

- there is an implicit help command added when there are subcommands
- the README now includes a short section under "Automated help" covering getting help for a subcommand

**Comment by shadowspawn** [comment]
Commander v5.0.0 has been released with improvements to the help command, and to the README. 

https://github.com/tj/commander.js/releases/tag/v5.0.0

**Comment by shadowspawn** [comment]
Opened poll on possible enhancements to global options: #1551
