### ISSUE TITLE
List values, shorthand flag with more than 1 character values

### ISSUE THREAD

**Issue by flyfishMT** [tj/commander.js#908]
I am having some issues, I may just not understand how this works.  This is on windows 10.

Lists 
```
program
.option('-c, --components <components>', 'List of components to create')
.parse(process.argv);
```

Test
`index.js --components dir\one dir\two`

Expected results: 
`program.components = ["dir\\one", "dir\\two"]`
Actual:
`program.components = "dir\\one";`

Shorthand flag, more than one character:

```
program
  .option('-tf, --testfolder [testfolder]', 'Description')
  .parse(process.argv);
```

`index.js --testfolder somefolder`
Results
`program.testfolder = "somefolder"`

`index.js -tf somefolder`
Results
`program.testfolder = undefined`

However, with a single char:

```
program
  .option('-x, --testfolder [testfolder]', 'Description')
  .parse(process.argv);
```

`index.js -x somefolder`
Results
`program.testfolder = "somefolder"`

**Comment by JohnRGee** [comment]
1) List: I think this may take a coercion to declare, and I assume is comma separated when calling. The example from the README is:

      .option('-l, --list <items>', 'A list', list)

and I assume call like:

    my_command --list dir\one,dir\two

2) Short flags are a single character, with single leading dash. Multiple flags may be combined as mentioned in the README:

> Short flags may be passed as a single arg, for example -abc is equivalent to -a -b -c.

3) You asked about options, but on a related note about arguments, the last argument may be a [variadic argument](https://github.com/tj/commander.js#variadic-arguments)

**Comment by JohnRGee** [comment]
See also #913 for some other approaches to options taking lists.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by flyfishMT** [comment]
Thank you, this was great help. Sorry for not posting back and closing.

**Comment by shadowspawn** [comment]
FYI, there is a recent issue asking to allow multiple character short options: #2307
