### ISSUE TITLE
Require an option

### ISSUE THREAD

**Issue by dzek69** [tj/commander.js#909]
Can I define option as required?
I want to create ffmpeg-like cli experience and want person to always include `-i` option with a value. I can manually detect that `-i` wasn't given, but I want commander to do it for me.
Is it possible?

If yes - then I think README and API Docs need some examples, if not - I'd like make this a feature request.

Example
```javascript
program .option("-i <path>", "source file")
```

This fails on:
`app -i`

but continues on:
`app`

**Comment by shadowspawn** [comment]
Answer provided, and enhancement covered by existing issue. Closing in favour of #230 

Duplicate of #230
