### ISSUE TITLE
Add option to alphabetize help output

### ISSUE THREAD

**Issue by NickHeiner** [tj/commander.js#910]
The auto-generated `--help` output is a neat feature of this module. What if the flags were listed in alphabetical order? This could particularly help for programs with many flags.

```
Options
  -a A explanation
  -b B explanation
  -c C explanation
```

**Comment by shadowspawn** [comment]
#625 is the same request, but for commands

**Comment by shadowspawn** [comment]
I think having options sorted is a good default, but am concerned how many users over the years have carefully created custom orders for their help and would be disappointed by an enforced change.

Do we need to provide an opt-out for sorting?

**Comment by shadowspawn** [comment]
For interest, the POSIX specifications for [Utility Conventions](https://pubs.opengroup.org/onlinepubs/9699919799/) say:

> Options are usually listed in alphabetical order unless this would make the utility description more confusing.

However, the utility conventions only include single character options (aka flags) so is describing a simpler situation.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report (although it is a reasonable suggestion).

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Commander 7 allows:

```js
program.configureHelp({
   sortOptions: true
})
```
