### ISSUE TITLE
Commander not testable

### ISSUE THREAD

**Issue by F1LT3R** [tj/commander.js#917]
Commander does not allow me to test with a custom `process.argv` array.

script.js:

```js
#!/usr/bin/env node
var program = require('commander');

const run = (args) => {
	program
	.option('--no-sauce', 'Remove sauce')
	.parse(args);
	
	console.log('you ordered a pizza');
	if (program.sauce) console.log('  with sauce');
	else console.log(' without sauce');
}

const cli = !module.parent

if (cli) {
	run(process.argv)
} else {
	module.exports = {run}
}
```

No run...

```shell
node script.js --no-sauce
```

I get...

```shell
you ordered a pizza
 without sauce
```

Now lets try that under test...

test.js:

```js
const lib = require('./script')
lib.run(process.argv)
```

Commander does not separate the real `process.argv` from the process.argv argument it is passed, making it impossible to get full test coverage for code using commander.

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at basename (path.js:1289:5)
    at Command.parse
```

**Comment by JohnRGee** [comment]
Your example code worked for me when I ran `test.js`, and I suspect the issue is in your real code.

```sh
$ node test.js --no-sauce
you ordered a pizza
 without sauce
```

There are a couple of things to be aware of for running tests, and the first one might be your current problem.

1) You need a couple of extra parameters when you construct the arguments array yourself to match the usual pattern of running program as `arg[0]`and script name or command name as `argv[1]`. e.g.

```js
lib.run(["node", "test.js", "--no-sauce"])
```

2) To allow you to run multiple tests you will want to create a fresh `program` to parse each run.

```js
#!/usr/bin/env node
var commander = require('commander');

const run = (args) => {
	program = new commander.Command();
	program
	.option('--no-sauce', 'Remove sauce')
	.parse(args);
...
```

**Comment by F1LT3R** [comment]
The only way it works for me is if I pass `['', '', '--no-sauce']`.

The error I was getting you can see here: https://github.com/F1LT3R/commander-untestable/

The following error was super confusing to me... because Commander gave such a generic Node error message... this made me jump to the conclusion that Commander was getting it's path overridden by the test runner.

```bash
TypeError [ERR_INVALID_ARG_TYPE] (NodeError) {
    message: 'The "path" argument must be of type string. Received type object',
}
```
