### ISSUE TITLE
How to display help when someone types an invalid option?

### ISSUE THREAD

**Issue by toymachiner62** [tj/commander.js#919]
If someone types in an option that doesn't exist, i want to display the `--help` text similarly to using `program.help()`.

Where can i listen for errors such as this:

```sh
$ ./createUser -V
 error: unknown option `-V'
```

So that I can call `program.help()`?

**Comment by willxy** [comment]
This came up previously also in #482.

**Comment by Tarabass** [comment]
Does this help?

```
// Assert that a VALID command is provided 
if (!process.argv.slice(2).length || !/[arudl]/.test(process.argv.slice(2))) {
    program.outputHelp()
    process.exit()
}
```

**Comment by shadowspawn** [comment]
@toymachiner62 
If you have commands, are you attaching actions to your commands, or using git-style executables?

In my program I have actions attached to the commands and get an error displayed automatically.

```bash
$ fab --silly
error: unknown option `--silly'
$ fab -X
error: unknown option `-X'
```

However, note that your example of `-V` is special as that is the default short option to display the program version:

```bash
$ fab -V
4.1.4-0
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.

**Comment by trusktr** [comment]
In case someone stumbles here, this is how to show help when an invalid option was passed:

```js
const cli = new commander.Command()

cli
	.description('...')
	.option(...)
	// ...
	.exitOverride(err => {
		// If an unknown option was passed, show help.
		if (err.code === 'commander.unknownOption') cli.help();
	});

cli.parse()
```

**Comment by shadowspawn** [comment]
FYI as a recent commenter @trusktr : PR opened #1534

**Comment by shadowspawn** [comment]
Related: `.showHelpAfterError()` added in prerelease v8.0.0-2 by PR #1534
