### ISSUE TITLE
How to escape parameters with "--" on it?

### ISSUE THREAD

**Issue by fernandojsg** [tj/commander.js#922]
Currently I have a command line tool and I need an option to support additional parameters to launch a web browser. These attributes could contain `--` on it, so commander.js is detecting them as parameters to the actual program and not just simple values.

eg:
```
.option("-l, --launchparams [additional parameters]", "Additional parameters to launch the browser")
```

```
➜  tests git:(master) ✗ tests run --launchparams "--ez e10s true"
error: unknown option `--ez e10s true'
```

Is there any way to bypass that?

**Comment by JohnRGee** [comment]
Try explicitly assigning the parameter like:

```
tests run --launchparams="--ez e10s true"
```

**Comment by fernandojsg** [comment]
@JohnRGee thanks for your answer, but, sadly, it doesn't seem to solve the issue :\
```
➜  tests git:(master) test run misc_fps --adb --browser fxr --launchparams="--ez e10s true"
error: unknown option `--ez e10s true'
```

**Comment by fernandojsg** [comment]
Although if I add an space inside the brackets it works:
```
tests run --launchparams " --ez e10s true"
```

**Comment by JohnRGee** [comment]
Tested the actual code this time! Note the change in brackets around `<additional parameters>` making a value required if the option is specified.

```
var program = require("commander");

program
.option("-l, --launchparams <additional parameters>", "Additional parameters to launch the browser")
.action((options) => {
    console.log(`Launch parameters: ${options.launchparams}`);
});

program.parse(process.argv);
```

```
$ node index.js 
Launch parameters: undefined
$ node index.js --launchparams --one
Launch parameters: --one
$ node index.js --launchparams --one --two
error: unknown option `--two'
$ node index.js --launchparams "--one --two"
Launch parameters: --one --two
$ node index.js --launchparams "--ez e10s true"
Launch parameters: --ez e10s true

```

**Comment by fernandojsg** [comment]
@JohnRGee that works!! thank you very much!! 👍

**Comment by seawatts** [comment]
I am still running into this issue even when changing the brackets. However, adding a space like https://github.com/tj/commander.js/issues/922#issuecomment-468357182 works
