### ISSUE TITLE
Add a new collaborator to the project 

### ISSUE THREAD

**Issue by vanesyan** [tj/commander.js#925]
I have seen high activity of @JohnRGee recently in responds to the open issues. I think we can add him to the project collaboration team. Would you like to join the team, @JohnRGee? Sorry, I have no your email, so cannot ask about this in private first.

**Comment by vanesyan** [comment]
@abetomo
What do you think about it?

**Comment by JohnRGee** [comment]
Hi! I am interested. Thanks. I won't be offended if I am not added, or if does not work out.

To be clear, I am not currently expert in the internal commander code. I have worked mostly with the interface.

I am passionate about good clean consistent CLI.

**Comment by abetomo** [comment]
I think that it is a good idea.

**Comment by vanesyan** [comment]
@tj, can you, please, add @JohnRGee to the list of project collaborators. He shows high activity answering/resolving open issues

**Comment by JohnRGee** [comment]
Link to [my comments](https://github.com/tj/commander.js/issues?utf8=%E2%9C%93&q=is%3Aissue+commenter%3AJohnRGee) on Commander

(In case you want npm, on npmjs.com I have different username, there I am [shadowspawn](https://www.npmjs.com/~shadowspawn) )

**Comment by vanesyan** [comment]
Friendly reminder @tj

**Comment by JohnRGee** [comment]
(After I have access.)

I thought I would start by reviewing the open Issues, closing stale and duplicate entries, and get a better feeling for some of the most common problem areas (like confusion over action vs git-style commands).

On a more minor note, the Labels are a bit inconsistent in style and some are stale. They are not getting used a lot currently and mostly cosmetic. I thought I would modify those to follow the naming style in new GitHub repos: https://help.github.com/en/articles/about-labels . I am thinking it would be useful to add a `docs` label for issues that might be resolved by improving the README et al. (so a bit like `bug` but not planning code changes).

**Comment by shadowspawn** [comment]
NB: My main account is now named @shadowspawn on both GitHub and npmjs.com. (Formerly known as JohnRGee on GitHub.)

I apologise for the name churn. I had set a name change in motion the day before this issue got opened, and it has just come through, so unfortunate timing.

**Comment by vanesyan** [comment]
@tj we are still waiting for you ;)

**Comment by vanesyan** [comment]
Seems TJ is too busy right now. I've sent an email to him, still waiting.

**Comment by tj** [comment]
added :D

**Comment by shadowspawn** [comment]
Accepted. I am looking forward to helping project as a collaborator. Thanks @tj and team.

**Comment by shadowspawn** [comment]
I have made a start on reviewing open Issues. Updated labels and closed 18 issues tonight. I will refine messaging I am using when closing if I receive any feedback, as closing issues is a sensitive topic! Have not started collating common themes but as expected already seeing some. :-)

**Comment by vanesyan** [comment]
Congrats, @shadowspawn 🎊 🎉

**Comment by vanesyan** [comment]
So we add @shadowspawn to the team of collaborators, closing.
