### ISSUE TITLE
What's the meaning of 'true' here?

### ISSUE THREAD

**Issue by ozbillwang** [tj/commander.js#926]
I follow the sample and give a wrong drink
```
$ cat a.js
var program = require('commander');

program
  .version('0.1.0')
  .option('-s --size <size>', 'Pizza size', /^(large|medium|small)$/i, 'medium')
  .option('-d --drink [drink]', 'Drink', /^(coke|pepsi|izze)$/i)
  .parse(process.argv);

console.log(' size: %j', program.size);
console.log(' drink: %j', program.drink);

$ node a.js
 size: "medium"
 drink: undefined

$ node a.js -d abc
 size: "medium"
 drink: true

```

What's the meaning of `true` here?

How do I write code to identify, if drink's value is not `coke|pepsi|izze`, exit(-1).

**Comment by shadowspawn** [comment]
The `true` means `drink` was specified as an option, but with no (valid) value. Like calling:

```
node a.js -d
```

> How do I write code to identify, if drink's value is not coke|pepsi|izze, exit(-1). 

I suggest you don't use the pattern in the `.option` call and check the option value yourself after calling parse. I also suggest putting the allowed values in the description so it appears in the help.

**Comment by ozbillwang** [comment]
should we change `true` to something else? It really confused me. `True` makes the feeling, something happen and it is correct.

I would prefer to exist directly, if this drink is not in the list.

**Comment by shadowspawn** [comment]
If any users of regular expression option read this thread, I am interested in what your code looks like.

**Comment by kira1928** [comment]
@ozbillwang 
> How do I write code to identify, if drink's value is not coke|pepsi|izze, exit(-1).

How about this one:
```
var program = require('commander');

const parseDrink = (function() {
  var regex = /^(coke|pepsi|izze)$/i;
  return function(value) {
    if (regex.test(value)) {
      return value;
    } else {
      console.error(`invalid param ${value}`);
      process.exit(-1);
    }
  };
})();

program
  .version("0.1.0")
  .option("-s --size <size>", "Pizza size", /^(large|medium|small)$/i, "medium")
  .option("-d --drink [drink]", "Drink", parseDrink)
  .parse(process.argv);

console.log(" size: %j", program.size);
console.log(" drink: %j", program.drink);
```

```
$ node a.js
size: "medium"
drink: undefined
```

```
$ node a.js -d abc
invalid param abc
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ node a.js -d
size: "medium"
drink: true
```

```
$ node a.js -d coke
size: "medium"
drink: "coke"
```

**Comment by ozbillwang** [comment]
Thanks, @kira1928 👍 

I never think to write a function (`parseDrink`) in the part of `program.option` . I currently add the test to `program.drink`

**Comment by shadowspawn** [comment]
Found another related issue: #708

**Comment by shadowspawn** [comment]
Closing this in favour of #708

Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Short version: I have downgraded the regular expression support and removed it from the README (!).

See: https://github.com/tj/commander.js/issues/708#issuecomment-496123000
