### ISSUE TITLE
Jasmine Mocha Support

### ISSUE THREAD

**Issue by vlikin** [tj/commander.js#927]
Convert tests to a more standard way. It is very hard to add new features to for external developers. Your library provides enough functionality. But it is not so well maintainable.

**Comment by shadowspawn** [comment]
Thanks for the feedback. I was actually doing some research on this just yesterday, and can refer you to #649

**Comment by shadowspawn** [comment]
@mojavelinux converted a couple of the test files to ava in #755 to show what it looks like, which I thought was a useful way of seeing real code for a modest time investment. If someone is interested in showing what it would look like using mocha, you could do a draft Pull Request with the same two files and a mocha setup.

**Comment by shadowspawn** [comment]
Closing this in favour of #649
