### ISSUE TITLE
Triage: Namespace pollution

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#933]
The current code uses the same namespace for user specified options, user specified arguments, and command.Command internals. Opened this issue to collect the related issues found during triage.

Issues:
- #19 Cannot name options/subcommands after commander public methods or JavaScript built-ins
- #105 '--domain' option may cause problem
- #183 Option values should not be added to the command instance.
- #284 "name" option is broken as of 2.4.0
- #370 Breaks when using "domain" as an option
- #377 Command name "inspect" causes weird behaviour
- #404 argument 'once' (and probably others) cause naming collision
- #483 It causes unexpected result if arguments are the same as option name
- #514 Move parsed options into a data object
- #516 Using .name and .description has unexpected results.
- #584 program.opts() can be overridden by an option
- #592 Error when option --alias is defined
- #629 Error when argument has same name as a flag
- #644 Options object is not strictly the user input
- #648 Init value of option '--name' is a [Function]
- #1020 Can not use action as option name

Pull Requests:
- #515 Data overload
- #673 Fix options key name conflict with commander object's' key

Fixing this will be a major breaking change. To manage the disruption perhaps we can make a new approach opt-in (non-breaking), then make the new behaviour default (breaking), before finally deprecating the old behaviour.

**Comment by vanesyan** [comment]
Should we open an issue to collect all wanted breaking changes and finally decide on v3?

**Comment by shadowspawn** [comment]
(Started v3 conversations in #666)

**Comment by shadowspawn** [comment]
Draft code for options refactor in #951

**Comment by shadowspawn** [comment]
My biggest stumbling block at the moment is what to pass into the action handler. Currently the command is passed in, but most people probably assume it is just the options. I did at first. 

Should it be the command, with properties for access to clean options? Or an option object. Or an option map. Or configurable... Still thinking...

One a somewhat related note, there is an existing `.opts()` method that grabbed the nicest short name! I have been wondering about optsM and opsO for map and object, somewhat in style of argV and argC, but probably better to be more readable. We should not be afraid of a few extra characters...

**Comment by shadowspawn** [comment]
Current plan:
- legacy default behaviour is options stored as properties on program/command, action handler gets passed program/command.
- modern default behaviour is options separate from program/command, action handler gets passed options
- allow override to get command passed in modern for advanced uses
- offer options as object (not map) as familiar and fairly backwards compatible code for action handler

**Comment by shadowspawn** [comment]
I have opened a Pull Request which allows storing option values separately rather than as command properties (access using `.opts()`), and passes the options (rather than the command) to the action handler. Opt-in using

```
program.configureCommand({ modern: true });
```

See #1102

**Comment by shadowspawn** [comment]
Added `. storeOptionsAsProperties()` and `. passCommandToAction()` in Commander 4.1. 

See: https://github.com/tj/commander.js#avoiding-option-name-clashes

**Comment by shadowspawn** [comment]
Adding new issues for reference, encouragement for changing the default behaviour:

- #1020 Can not use action as option name
- #1160 requiredOption doesn't work for option named 'action'
- #1212 Cannot have option named parent
- #1226 TypeError: this.name is not a function
- #1237 Adding `--no-emit` option results in error
- #1252 Handling of "--version" program option is buggy
