### ISSUE TITLE
Run action for all commands

### ISSUE THREAD

**Issue by dland512** [tj/commander.js#936]
Is there a way to have an action that always runs, no matter what command you are running? I tried this but it's not running the top level action attached to `program`:

```
var program = require('commander');

program
  .option('-c, --chdir <path>', 'change the working directory')
  .action(x => {
    // always run this
    console.log('chdir:', x.chdir);
  });

program.command('go')
  .option('-o --opt <whatev>', 'some option')
  .action(o => {
    console.log('opt:', o.opt);
  });

program.parse(process.argv);
```

**Comment by shadowspawn** [comment]
I don't think is quite what you are asking, but these things came to mind:
- can use an option and [custom event listeners](https://github.com/tj/commander.js#custom-event-listeners)
- there can be a default action for [git-style sub-commands](https://github.com/tj/commander.js#git-style-sub-commands)

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
