### ISSUE TITLE
Throw an error when the short flag for an option for longer than one character

### ISSUE THREAD

**Issue by HopefulLlama** [tj/commander.js#937]
In the `.option(...)` method, it takes a string flag which is comma separated, and describes a short and a long flag for passing arguments, such as:

```
  .option('-v, --version', 'Version information');
```

However, when given a short flag which is longer than one character, the program will still parse and execute, but cannot be accessed by its short flag. 

For example:

```
  .option('-nv, --next-version', 'The next version');
```

It is impossible to use `-nv` on the command-line, as commander interprets this as two short flags concatenated together: `-n` and `-v`. 

It would be better to throw an error to avoid the misleading set up of commander options.

**Comment by shadowspawn** [comment]
The documentation does mention the cli behaviour:

> Short flags may be passed as a single arg, for example -abc is equivalent to -a -b -c.

but I agree it would be nice if commander warned you about the setup problem.

**Comment by HopefulLlama** [comment]
It does mention that, but it took me a long time to put two and two together.

I.e.: It does take some thinking to realise that a two character flag **cannot** work due to the short flag feature. It doesn't _explicitly_ say so in the documentation.

I think an addition to the documentation, and an error or warning given when the misleading setup is actioned would be suitable.

**Comment by shadowspawn** [comment]
It now _explicitly_ says single character in the documentation. (But still no warning about coding error, so feel free to keep this issue open.)

**Comment by shadowspawn** [comment]
Some more errors or warnings for coders (rather than users) is something we can improve in future. Closing this as have made _an_ improvement with the addition to the README.
