### ISSUE TITLE
Triage: Problems with negating boolean options

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#939]
People have a variety of problems with boolean options and negating.  Opened this issue to collect the related issues found during triage.

NB: there is an open pull request and I have not yet looked at how well it addresses the issues, but likely to be some documentation work even if functionally solid.

Issues:
- #108 On and off switches are not working
- #238 when specifying options, the "--no" version of a flag must appear after the flag
- #574 Defining boolean options via Command#option() defaults to undefined, not false.
- #626 Command.opts() values are always undefined
- #630 No way to know if parameter is set with --no- options
- #928 Support defaults for boolean options (including --no-*), for env var set defaults
- #979 Adding negative option makes Commander.js to return "true" when option is not specified

Pull Requests:
- #795 fixes behavior of --no-* options

**Comment by usmonster** [comment]
Thanks for the triage work here, especially concerning the readme & examples updates in #953! FYI, I've updated my open PR (#795) to include your changes.

Regarding this:
> NB: there is an open pull request and I have not yet looked at how well it addresses the issues, but likely to be some documentation work even if functionally solid.

Once you get around to finishing your review, please let me know if there's anything related to [my comment on Custom Events](https://github.com/tj/commander.js/pull/795/files#r185717938) that you think might require further functional or documentation updates. Thanks again!

**Comment by shadowspawn** [comment]
This issue will be resolved when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
Support for combined `--foo` and `--no-foo` has shipped in v3 (thanks @usmonster): https://github.com/tj/commander.js/releases/tag/v3.0.0
