### ISSUE TITLE
Throw error when no sub-command specified

### ISSUE THREAD

**Issue by dland512** [tj/commander.js#942]
My app always requires a sub command, e.g.

`node main.js sub1`
or
`node main.js -x sub1`

It's not valid to do

`node main.js`
or
`node main.js -x`

How can I catch this scenario? Is there a way to introspect the `program` object to tell if a sub command was used?

I was going to use `process.argv.length` but that doesn't really work because a user could still pass in options without a sub-command (`node main.js -x -y -z`). I can get around that by parsing `porcess.argv` more carefully but I was hoping there was a more supported way.

**Comment by shadowspawn** [comment]
After calling `program.parse`, `program.args` hold the arguments not consumed by options. So you could do this:

```
const program = require("commander");

program
    .option("-x")
    .command("sub1")

program.parse(process.argv);

if (program.args.length === 0) {
    console.log("Subcommand not specified");
}
```

```
$ node index.js 
Subcommand not specified
$ node index.js -x
Subcommand not specified
$ node index.js sub1
$
```

**Comment by dland512** [comment]
I think that will do it, thank you!
