### ISSUE TITLE
Pass multiple flags seperately is parsed incorrectly?

### ISSUE THREAD

**Issue by shaharx** [tj/commander.js#947]
When running a terminal command with multiple flags and values, passing a <required> flag without its value, will take the next flag as the value:

example script:

program
    .option('-n, --number <number>', 'the number or name of a case environment')
    .option('-v, --artVersion <artVersion>', 'the Artifactory version to deploy')

console.log(program.number)

executing

command: foo -n
output: error: option `-n, --number <number>' argument missing

command: foo -n -v 4.4.5
output: -v

Is this behaviour expected?

**Comment by shadowspawn** [comment]
I don't think your example script matches your example output, but can offer some tips which will hopefully answer your question.

There are boolean options:

```
.option('-p, --peppers', 'Add peppers')
```

and options that always have a value:

```
.option('-f, --float <n>', 'A float argument')
```

and lastly and less common in my experience, an option that _may_ have a value (so sort of a hybrid of a boolean option and an option with value):

```
.option('-o, --optional [value]', 'An optional value')
```

An option that always has a value will take the next argument as its value whether or not it starts with a dash.

**Comment by shaharx** [comment]
Hello shadowspawn, thank you for your answer.
What i meant is this:
If you pass in to the command a flag with a required parameter i.e. <value>, but you don't pass into that flag any parameter, you will get a missing argument exception which is ok and expected.
But if you run a command again with the same flag as above, with no value, but with another flag that follows it i.e.: " -n -v ", the commander will take the second flag '-v' as an argument and no exception will be raised. all the following flags and their values will just get a false assignments.

**Comment by shadowspawn** [comment]
Yes, the option takes the next argument as its value whether or not it starts with a dash.

```
const program = require("commander");

program
.option('-n, --number <n>', 'the number or name of a case environment')
.option('-v, --artVersion <v> ', 'the Artifactory version to deploy');

program.parse(process.argv);

console.log(`number is ${program.number}`);
console.log(`artVersion is ${program.artVersion}`);
console.log("other arguments are:");
console.log(program.args);
```

```
$ node index.js
number is undefined
artVersion is undefined
other arguments are:
[]
$ node index.js -n 123
number is 123
artVersion is undefined
other arguments are:
[]
$ node index.js -n -456
number is -456
artVersion is undefined
other arguments are:
[]
$ node index.js -n --dash-dash--
number is --dash-dash--
artVersion is undefined
other arguments are:
[]
$ node index.js -n 123 -v 7.8.9 hello
number is 123
artVersion is 7.8.9
other arguments are:
[ 'hello' ]
$ node index.js -n -v oops hello
number is -v
artVersion is undefined
other arguments are:
[ 'oops', 'hello' ]

```

**Comment by shaharx** [comment]
Thank you shadowspan, i didn't know this is an expected behavior.
I tried running with docker for a reference and i see the same result when passing the -p flag with no ports:
$ docker run --name ngx -p -d nginx
docker: Invalid containerPort: -d.

Thanks for the support.

**Comment by shadowspawn** [comment]
Thanks for docker example @shaharx
