### ISSUE TITLE
Option with space in value cannot be passed

### ISSUE THREAD

**Issue by freelock** [tj/commander.js#957]
Hi,

I've defined an option as 
```
.option('-S, --subject <subject>', 'Subject to use')
```
... and this works fine for a single word, but I cannot find any way to escape spaces to send a phrase or sentence.

Have tried quoting the phrase with single or double quotes, or using backslashes/other typical shell escape characters -- whatever I do, program.subject ends up getting assigned the first word of the option, and the rest get accumulated into args.

**Comment by shadowspawn** [comment]
My guess is the problem is extra shell interpretation due to how you are calling your program. Try logging out `process.argv` to see if the arguments have been split before they get into the program.

```
const program = require("commander");

program
.option('-S, --subject <subject>', 'Subject to use');

console.log(process.argv);
program.parse(process.argv);
console.log(program.subject);
```

```
$ node index.js --subject "one two three"
[ '/usr/local/bin/node',
  '/Users/[redacted]/commander/issues/957/index.js',
  '--subject',
  'one two three' ]
one two three

```

**Comment by freelock** [comment]
Hmm yes, you're right! process.argv is showing these split no matter what I pass in -- but this does look affected by the shebang line.

I've been using:
```
#!/usr/bin/env node
```
but when I switched it to 
```
#!/usr/bin/node
```
... it now seems to pass the quoted parameters as a single parameter, instead of breaking on each space no matter what...

Any idea why?

**Comment by freelock** [comment]
ok weird... thanks for your help, looks like I had some strange wrapper bash script in ~/.composer/vendor/bin/node, which was in my $PATH... this did resolve to the same node binary eventually, but I guess the extra bash script somehow mangled the arguments... Removing that makes all work as expected! Thanks for your help.
