### ISSUE TITLE
component search json == component search --json

### ISSUE THREAD

**Issue by timoxley** [tj/commander.js#97]
You are given json output if you do a search for `json`
i.e.

```
$ component search json
[
{
  "name": "superagent",
  "repo": "visionmedia/superagent",
  "description": "awesome http requests",
...
```

is the same output as using the --json flag:

```
$ component search --json
[
{
  "name": "superagent",
  "repo": "visionmedia/superagent",
  "description": "awesome http requests",
...
```

I had a quick look into this and the issue may actually be in commander.js; there doesn't seem to be a good way to determine the difference between defined --args and subsequent args that are passed in.

e.g.

``` js
// $ component-search json
program.json // => []

// $ component-search --json
program.json // => true

// $ component-search --json json
program.json // => []
```

Possibly related issue: https://github.com/visionmedia/commander.js/pull/35

**Comment by vanesyan** [comment]
@tj can we close this one?

**Comment by abetomo** [comment]
Closed because there is no update for a long time. Feel free to comment in case the issue persisted.
