### ISSUE TITLE
Command not exiting after execution on windows.

### ISSUE THREAD

**Issue by arbazsiddiqui** [tj/commander.js#972]
This is my cli.js :
```
#!/usr/bin/env node

const program = require('commander');

program
	.command('test')
	.alias('t')
	.description('random')
	.action(() => {
		console.log("print something")
		return
	});

program.parse(process.argv);
```

When running using `utility t` (utility being the name of program) it prints `print something` but the cursor after that keeps blinking. Further cmd goes into powershell mode (title bar changes).
To exit after this command you have to press Ctrl^C. This prompt appears after that:
`Terminate batch job (Y/N)?`

This issue is irrespective of using `return` to return from action function. Tried both ways.
After pressing Y you exit the program.

Same code works on perfectly on OSX.

**Comment by shadowspawn** [comment]
Do you see the same behaviour if you run your program directly?

```
node cli.js t
```

**Comment by shadowspawn** [comment]
This issue has not had a response in a month. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by Slava-stack** [comment]
got the same issue D:

**Comment by Slava-stack** [comment]
I've added:
process.exit();
at the end of my command and it works. Not sure if it's gonna for your code but better than nothing.

**Comment by kingaptos** [comment]
Is the recommendation to actually manually call `process.exit()`, seems a bit odd 🤷‍♂️

**Comment by kingaptos** [comment]
So if you run with node-ts, the process won't automatically terminate; running via node actually does. So I would run with node and avoid adding process.exit().

**Comment by shadowspawn** [comment]
There isn't a recommendation, as the underlying cause has not been identified. Feel free to open a new issue if you want to investigate what you are seeing.

See: https://github.com/tj/commander.js/issues/972#issuecomment-1149149073
