### ISSUE TITLE
Tidelift Funding

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#975]
A company called [Tidelift](https://tidelift.com) offer subscriptions to companies to support their use of open source software, and Tidelift share  the money they receive with the software maintainers.

Tidelift has some funds available for Commander, but not a big amount:

- <https://tidelift.com/lifter/search/npm/commander>

The way to get the funding is to sign up as a "lifter" to perform various support tasks with Tidelift for the package. We do not give away any control over the project or the code or the development direction.

- <https://tidelift.com/docs/lifting/what-is-lifting>
- <https://blog.tidelift.com/how-to-start-earning-money-for-your-open-source-project-with-tidelift>

Part of the arrangement is saying Commander is part of Tidelift on the home page. I am thinking plain text, not a fancy banner:

- <https://tidelift.com/docs/lifting/marketing>
- <https://drive.google.com/drive/folders/1e-87z2k3CHWyQNlQ8z4AZoG6ElRiekZf>

We can have more than one lifter too, and we tell Tidelift how to share the funding.

I am keen to signup and give it a go. The agreement can be cancelled with 30 days notice by either party, so I am not locked in.

You ok with me signing up to Tidelift @abetomo? Are you interested in being a Lifter too?

(I didn't include you @vanesyan as not active at the moment, but if you come back then it is relevant.)

**Comment by shadowspawn** [comment]
Bump: you ok with me signing up to Tidelift @abetomo?

**Comment by abetomo** [comment]
Signed up for Tidelift.
Is there anything else to do?

**Comment by phated** [comment]
@abetomo I just reached out via email to finish our signup process. You and @shadowspawn should also agree on the % split for the funding.

**Comment by phated** [comment]
@abetomo did you receive my email?

**Comment by abetomo** [comment]
Sorry for replying so late.
I replied.

**Comment by shadowspawn** [comment]
We are now officially "Lifters". Thanks for split @abetomo !!

I'll start looking at lifting tasks in weekend, but will be spending time on v3 too.
