### ISSUE TITLE
It looks not way to know has action is run?

### ISSUE THREAD

**Issue by andares** [tj/commander.js#977]
```javascript
var program = require('commander');

program.version('0.1.0');

program
  .command('pat <dir>')
  .option('-o, --output', 'Output dir')
  .action((dir, command) => {
    console.log('POINT A')
  });

program
  .on('command:*', () => {
    console.log('POINT B')
  });

program.parse(process.argv)

console.log('POINT C')
```

in `POINT A`, I know command pat action is run. in `POINT B`, I know user send a error command. in `POINT C`, it means may be a action is run, or none command was be sent.

but I can not find a way to know just none command was be sent, unless I add callback after signal each action, there could be hundreds..

I think program object should provide some api to get there has action be called, and which action be called?

**Comment by shadowspawn** [comment]
A simple way to check for no arguments:

```
if (process.argv.length <= 2)
  console.log("No command specified");
```

**Comment by andares** [comment]
I see, I will try it first, thanks.
