### ISSUE TITLE
What is the best practice for organising large commander tool?

### ISSUE THREAD

**Issue by hixus** [tj/commander.js#983]
My commander based tool is getting quite large and I was thinking about splitting it to separate files but couldn't find an example. I would still like to have single executable but import different commands from their own files. Only thing what came to mind was:

``` javascript
// file ./commands/a.js
const addTo = (program) => program.command('command-a')
module.exports = {addTo}

// file ./commands/b.js
const addTo = (program) => program.command('command-b')
module.exports = {addTo}


// file ./cli.js
const program = require('commander')
const a = require('./commands/a')
const b = require('./commands/b')

a.addTo(program)
b.addTo(program)

program.parse(process.argv)
```

Is there some other way?

**Comment by shadowspawn** [comment]
That is simple and effective. 

In my project, I decided to keep the Commander setup in a single file and import the modules to call from the action handler. I like having the CLI in a single file to help keep the style of the commands and custom help consistent. I don't think this is better than  what you suggested, just sharing an alternative. 

e.g. TypeScript
```
import * as commander from "commander";
import * as coreFor from "./core-for";

  program
    .command("for-each")
    .description("run specified command on each repo in the forest, e.g. \"fab for-each -- ls -al\"")
    .arguments("<command> [args...]")
    .option("-k, --keepgoing", "ignore intermediate errors and process all the repos")
    .action((command, args, options) => {
      coreFor.doForEach(command, args, options);
    });
```

**Comment by shadowspawn** [comment]
A reply was provided, and no further activity in a month. Closing.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
