### ISSUE TITLE
Drop API link from README?

### ISSUE THREAD

**Issue by shadowspawn** [tj/commander.js#985]
There is a link in the README to the [API documentation](http://tj.github.com/commander.js/)

In the early days this may have been the most authoritative documentation. We now have a more comprehensive README, IDEs with built-in support for JSDoc, and TypeScript. In particular I suggest the primary use of the JSDoc is now for built-in editor support in the IDE.

I think the documentation is updated by merging to the `gh-pages` branch and running `make`, and then doing "something" to update GitHib Pages. Looks like last updated four years ago. #182 #171 #299

I suggest we delete the link from the README and focus on the other forms of documentation now.

**Comment by abetomo** [comment]
I like it!

**Comment by rap2hpoutre** [comment]
Should we close this issue since #988 is merged?

**Comment by shadowspawn** [comment]
The changes have been merged to branch `release/3.0.0` but not to `master` (yet). I am currently leaving issues open until the changes land on `master`. Partly just in case, partly so they are still visible for discussion.

**Comment by shadowspawn** [comment]
This issue will be resolved when v3.0.0 is released. Available now as a prerelease. See #1001

**Comment by shadowspawn** [comment]
Shipped in v3: https://github.com/tj/commander.js/releases/tag/v3.0.0
