### ISSUE TITLE
How to check if option(flag) is set?

### ISSUE THREAD

**Issue by weilinzung** [tj/commander.js#994]
I have multiple options in one command, how do I check if the option(flag) is set while using the terminal?  If there are no any options(flags) then exit.

```
const setup = options => {
  if ???  { -> not sure the condition 
   return process.exit(1);
  }
}

program
  .command('setup')
  .option("-m, --mode", "Which setup mode to use")
  .option("-t, --test", "test mode")
  .option("-g, --go", "go to mode folder")
  ...
  .action(setup);
```

// normal command line
```
npm setup --xxx
```
// wrong command line that missing flag would return to exit
```
npm setup
```

Thanks!

**Comment by shadowspawn** [comment]
If you had a lot of options you could loop over `options.opts()` properties looking for any that were defined (not counting `version`), but for three options I would just list them, keep it simple:

```
if (!options.mode && !options.test && !options.go)
   console.log("No options defined");
```

**Comment by weilinzung** [comment]
@shadowspawn 

I was almost there because asking it, but just miss the `!`.

thanks!
