### ISSUE TITLE
Could have error() output to stderr?

### ISSUE THREAD

**Issue by crystalfp** [tj/commander.js#997]
I have a command line application with the output redirected to a file.
```
node app.js mandatory-argument > output.dat
```
If `mandatory-argument` is not present, commander `help()` function is called. Unfortunately the help text goes to the output file due to the redirection. In the commander source file, the help output is hardcoded to go to stdout (line 1147).

A workaround is to call `help()` this way:
```
	const cb = (hlpText: string): string => {
		process.stderr.write(hlpText);
		return "";
	};
	program.help(cb);
```
But should be simpler if all commander messages go to stderr and not to stdout.
Thanks for looking!
mario

**Comment by shadowspawn** [comment]
I saw a related article tonight: https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by cengizhanbasak** [comment]
If you like me to do, I'll change the stdout to stderr.

**Comment by crystalfp** [comment]
Yes, please.

**Comment by shadowspawn** [comment]
@crystalfp Are you displaying the help yourself? Or is Commander displaying the help when you call `.parse`?

**Comment by crystalfp** [comment]
It is commander that displays the help.
I had to add the following code to display help when the program is called without arguments:
```

	// To send the help text to stderr
	const cb = (hlpText: string): string => {
		process.stderr.write(hlpText);
		return "";
	};
	program.help(cb);
```

**Comment by shadowspawn** [comment]
That isn't a bad work-around. 

When using git-style executable subcommands, the help gets displayed automatically when there are no arguments (unless there is a default command). I was wondering if this was the behaviour you had encountered.

I don't think it is appropriate for all Commander messages to go to `stderr` though. When the help is explicitly requested, the caller is likely to expect the output to be on `stdout`, e.g.:

```
my-command --help | grep port
```

**Comment by crystalfp** [comment]
This was the only way to have the help text visible when stdout is routed to a file. Anyway, for my specific program, this workaround solved the problem. Ah, and I don't use subcommands. 

I understand your points. I will continue with my workaround any time I have to redirect stdout.
Thanks!
mario

**Comment by shadowspawn** [comment]
An idea for future is is to have the optional parameter to the help calls be the `logger`, and this could be passed through to the help event listeners too. But listener might want to detect it it is a tty to turn on/off colour, so tradeoffs with function vs stream...

e.g. `program.help(console.error);` or `program.help(process.stdout)`

**Comment by shadowspawn** [comment]
I am currently thinking of making `.helpInformation()' public as a simple change that lets caller do what they want with the text.

Related PR:#992

**Comment by shadowspawn** [comment]
`.helpInformation()` is public in the published pre-release of Commander v5.0.0 (#1163), so a bit more direct to write the help built-in information to `stderr`:

```
process.stderr.write(program.helpInformation());
```

**Comment by shadowspawn** [comment]
This issue has not had activity in over six months (part from my updates). It isn't likely to get acted on due to this report.

I do agree the help-displayed-as-an-error should go to stderr, but it is not a high priority based on feedback for this item.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
If the help is displayed due to a usage error then it is displayed on stderr from Commander 7.0.0.

**Comment by hibes** [comment]
Just to echo the sentiment presented here https://github.com/tj/commander.js/pull/1069, it would be really nice if I could control the output of explicit help requests also.

**Comment by shadowspawn** [comment]
@hibes 

That is now supported:
```
program.help(); // stdout
program.help({ error: true }); // stderr
```

**Comment by hibes** [comment]
From the readme:
```
.help(): display help information and exit immediately. You can optionally pass { error: true } to display on stderr and exit with an error status.
```

I meant that I would like to be able to configure a program such that `./program --help` would send help text to `stderr`.

**Comment by shadowspawn** [comment]
Ah, ok. There is not direct support for that. You could achieve it with a Command subclass and an override.

If you have an interesting use case perhaps open a new issue, as you are asking about something different than the original poster in this issue, and not the usual behaviour for utilities:

- https://github.com/tj/commander.js/issues/997#issuecomment-538611969

**Comment by crystalfp** [comment]
Thanks, but I solved in a different way. What I was outputting to stdout now goes to a file. Thanks again for the useful package!
